### ISSUE TITLE
[Résumé reg] Ajouter un bandeau dans le résumé reg quand la reg. n'est plus valide ou supprimée

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#1012]
Diane dit : 
> J'avais indiqué une date de fin de validité au 01/01/2022 pour la zone "Cantonnement_Filets-calés_Adour" cf capture d'écran ci-dessous. Or la zone est toujours visible sur monitor. [au 16/02/2022]

![image](https://user-images.githubusercontent.com/71878648/154275279-44086665-ab7a-40bf-9815-3ce39f56232e.png)

**Comment by louptheron** [comment]
C'est quoi la règle ?
- On n'affiche plus la zone ?
- On spécifie que celle-ci n'est plus valide (ce que je propose)

**Comment by AdelineCelier** [comment]
Pour moi on n'affiche plus la zone. Il me semble bien qu'on avait dit comme règle que ce qui s'affiche dans MF est ce qui est valide à un instant T, on n'historise pas les reg.

**Comment by louptheron** [comment]
C'est vrai, du coup faut gérer deux cas :
-  Quand il y a déjà la zone dans "Mes Zones", on doit afficher qu'elle n'est plus valide non ?
- Ne pas remonter la zone quand on fait une recherche REG

**Comment by AdelineCelier** [comment]
Ah oui zut je n'avais pas pensé au cas de la zone présente dans "Mes zones"...on peut effectivement prévoir un bandeau jaune disant "attention, cette règle n'est plus en vigueur".

+ après discussion avec toi puis Diane, on peut prévoir un moyen pour le service reg de valider la suppression de reg arrivées à échéance, plutôt que de le faire pour eux. Par exemple, une modale qui s'affiche à l'arrivée sur le backoffice disant "telle reg est arrivée à échéance, validez-vous leur suppression ?"
Je dessine ça et te dis quand c'est prêt.

**Comment by AdelineCelier** [comment]
@louptheron voilà pour le bandeau (dernier écran du XD " Carte_Zones et fonds de carte_OK" : 
![image](https://user-images.githubusercontent.com/71878648/154470072-1ddb0c87-5b02-4563-9b24-2d9190a5a391.png)

**Comment by louptheron** [comment]
![Screenshot from 2022-02-22 11-13-33](https://user-images.githubusercontent.com/14853556/155111195-2722f3f1-6b27-4cad-864d-affdb4fefdb0.png)

**Comment by louptheron** [comment]
- [ ] à valider en PROD
