### ISSUE TITLE
[Backoffice] L'espèce "corail rouge" n'apparaît pas dans la liste des espèces.

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#1020]

**Comment by VincentAntoine** [comment]
Il s'appelle "Corail Sardaigne", bizarrement. Code: COL.

Dans le référentiel des espèces de la FAO, il y a plusieurs colonnes pour le nom de chaque espèce: nom scientifique, nom anglais, nom français, espagnol, arabe, ... Toutes les espèces ont un nom scientifique, mais le nom dans les autres langues n'est pas toujours donné. Dans Monitorfish, le nom qui est utilisé en priorité est le nom français, s'il est donné, et s'il n'est pas donné, on prend le nom scientifique. Exemples :
![image](https://user-images.githubusercontent.com/27647971/156588449-c47d23a4-7bfa-41be-8065-93f9402b2470.png)
Pour l'espèce de code AZN, le nom dans Monitorfish sera le nom scientifique _Anthoatecatae_, alors que pour l'espèce de code COL, ce sera _Corail Sardaigne_. 

J'ai fait le choix de mettre le nom français en priorité car la réglementation donne les noms d'espèce en français et non les noms scientifiques, donc ça m'a semblé plus utile pour le pole reg d'avoir les noms d'espèce en français que les noms scientifiques. Il se trouve que pour le "corail rouge" ([Corallium rubrum](https://fr.wikipedia.org/wiki/Corail_rouge)), le nom français donné par la FAO est "Corail Sardaigne", ce qui est curieux et ne permet pas de trouver l'espèce facilement depuis le backoffice. Mais ce cas est a priori minoritaire.

Si ce genre de cas reste exceptionnel, je pense qu'on peut le gérer en renvoyant au référentiel FAO pour faire une recherche sur le nom scientifique ou anglais. Ce référentiel est disponible sous une version pas très sympathique [sur le site de la FAO](http://www.fao.org/fishery/static/ASFIS), ou dans une version [plus sympathique](https://www.data.gouv.fr/fr/datasets/liste-des-especes-a-but-detudes-statistiques-sur-la-peche/) sur data.gouv.fr, exporté par nos soins.

Si ce cas se produit régulièrement, on peut envisager de mettre les deux noms, français et scientifique, dans Monitorfish, et faire une recherche sur les deux, mais comme d'habitude, question de priorité :)

**Comment by AdelineCelier** [comment]
Après discussion, on a convenu qu'il faut ajouter le corail rouge dans la liste "catégorie d'espèces", car cela semble un peu étrange de modifier l'intitulé de la liste FAO. 
Cette solution convient tant que l'on ne souhaite pas lever d'alerte sur le corail rouge.
