### ISSUE TITLE
[Résumé reg] Revoir l'affichage de "tous les engins" dans le résumé réglementaire

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#1021]
Aujourd'hui, quand la case "tous les engins" a été cochée dans la section "engins" du formulaire reg. dans le backoffice, cela affiche la liste de toutes les catégories d'engins. 
Il faudrait plutôt afficher "tous les engins".

**Comment by louptheron** [comment]
J'ai coché tous les engins, ça m'affiche bien le texte : 
![Screenshot from 2022-02-22 08-39-46](https://user-images.githubusercontent.com/14853556/155084943-42c65353-1f6e-4836-8044-f9ccccd582d1.png)

**Comment by AdelineCelier** [comment]
@louptheron je crois que mon dernier commentaire ci-dessus est passé entre les mailles du filet. Côté résumé reg, cela s'affiche bien, en revanche faudrait juste rebosser un peu l'affichage côté formulaire (cf. commentaire).

**Comment by louptheron** [comment]
@AdelineCelier Ah bon ? Chez moi ça semble OK

![Uploading Screenshot from 2022-03-23 10-06-32.png…]()

**Comment by AdelineCelier** [comment]
Oups mea culpa, c'est effectivement pour l'ordre des engins !
En revanche j'ai un problème avec la checkbox de "tous les engins" : elle n'apparaît pas comme cochée quand je clique dessus, bien que cela affiche la liste de tous les engins. Et je ne peux pas la désélectionner non plus, quand je reclique dessus il ne se passe rien.

**Comment by louptheron** [comment]
@AdelineCelier C'est déployé en INT!

**Comment by AdelineCelier** [comment]
@louptheron on est presque bons, il y a juste un petit couac encore : la checkbox de "tous les engins" est cochée par défaut quand tu l'affiches pour la première fois (sans que pour autant les engins soient affichés) : 
![image](https://user-images.githubusercontent.com/71878648/161560748-600c03d2-02e9-47bc-b9a5-fc26419f2256.png)
