### ISSUE TITLE
[Backoffice] Supprimer la fonctionnalité "réglementation à venir" 

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#1030]
@AdelineCelier On ne gère pas le passage d'une REG à venir à une REG en cours aujourd'hui, ?

-> J'ai remarqué qu'on n'affiche pas la réglementation à venir dans le résumé réglementaire

**Comment by AdelineCelier** [comment]
**Après discussion avec Loup et Diane le 23/02/2022**
On décide de supprimer la fonctionnalité "ajouter une réglementation à venir". 
En effet, on l'avait imaginée pour lui permettre de rentrer des textes réglementaires qui tombent en amont de leur validité. Mais cela implique qu'elle sache toute seule quel texte est dans MF et quel texte n'y est pas. Or ce n'est pas évident de s'en rappeler par soi-même, c'est pour cette raison que Vincent a créé le mail automatique indiquant les liens morts de Légipêche dans MF.
On a donc convenu que même lorsque des textes reg. tombaient en avance de phase, le service reg. attendait de voir que le texte précédent n'était plus en vigueur via le mail pour aller le remplacer dans MF.
