### ISSUE TITLE
Faut-il historiser les définitions de segments de flotte?

### ISSUE THREAD

**Issue by VincentAntoine** [MTES-MCT/monitorfish#1034]
Deux options :
- soit on historise les définitions de segments de flotte (en ajoutant une colonne de date de début de validité et une colonne de date de fin de validité, qui sera NULL si la définition est actuellement valable)
- soit on n'historise pas et on garde en base uniquement les définitions actuelle

L'impact est essentiellement sur les contrôles : veut-on attribuer les contrôles aux segments de flotte en cours de validité à la date du contrôle, ou à la date actuelle?

@AdelineCelier @louptheron

**Comment by AdelineCelier** [comment]
Cela me semble assez indispensable d'attribuer les contrôles aux segments de flotte à la date du contrôle non ? Sinon cela va fausser le suivi des objectifs.

**Comment by VincentAntoine** [comment]
Comme discuté ce soir :
- A proiri on n'historise pas les définitions de segments, par contre on inclut dans le CR de contrôle le / les segments du contrôle (avec suggestion sur la base des données JPE à l'instant du contrôle + sur la base des engins / espèces / zones du contrôle saisies dans le CR)
- A valider avec CNSP / OPS

Cf #1039
