### ISSUE TITLE
Problème de disparition des pistes quand on fait faire 360° au fond de carte

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#1046]
**Remarqué aujourd'hui par Jérémie**

_Comportement observé_
Il navigue sur la carte de façon à faire un tour complet de la Terre en partant de la France, et lorsqu'il revient sur l'Europe, les pistes ont "disparu". Elles n'ont en fait pas suivi le fond de carte, et sont "restées" sur la première représentation de la France. Quand on revient en arrière ou qu'on recherche une piste avec la barre de recherche, la carte se recentre bien sur la "première" France. 

_Comportement attendu_ 
Que la planisphère soit bien ronde et qu'on retrouve ses pistes même après un tour du monde ;)

**Comment by louptheron** [comment]
Il n'est pas possible d'avoir ce comportement avec WebGL (j'ai regardé sur ANAIS, c'est pareil chez eux).
Du coup pour enlever toute ambiguité, j'ai également masqué toutes les couches quand on fait un tour complet, car jusqu'à maintenant toutes les autres couches étaient affichées sauf les dernière positions des navires.

**Comment by AdelineCelier** [comment]
Ah bon ? C'est bizarre qu'ils n'aient pas pris ça en compte, je ne vois pas dans quel cas d'usage l'utilisateur n'aimerait pas retrouver ses infos en faisant le tour de la Terre... 
Mais du coup quand tu parles des autres couches c'est quoi ? Les zones admin et les zones reg ? Je ne sais pas si ça enlève vraiment l'ambigüité mais bon...ça reste un cas assez à la marge donc on ne va pas y passer trop de temps. Faut juste prévenir les équipes que ce n'est pas possible du coup.

**Comment by AdelineCelier** [comment]
Je trouve que ça peut quand même prêter à confusion, et que l'utilisateur risque de se perdre. Peut-être serait-il plus clair de contraindre la carte, et d'empêcher de faire le tour du globe ? L'utilisateur devrait faire "demi-tour" mais au moins il ne risquerait pas d'avancer vers une carte vierge en ayant perdu ses pistes. 
Je rebascule le ticket dans le backlog pour réflexion ultérieure.
