### ISSUE TITLE
Ajouter l'OP/le groupement de navire à la fiche navire

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#107]
Data : où récupérer cette info ? Est-ce qu'elle doit être très fraîche ? Demander à la DPMA.
Design : à mettre dans l'onglet identité ou dans l'onglet pêche ?

**Comment by VincentAntoine** [comment]
Point du 30/08 avec Céline : pas du tout prioritaire car pas dans les attributions du CNSP de vérifier les fermetures de quota régionales, uniquement les fermetures nationales.
