### ISSUE TITLE
Faire une 1ère version de TritonFish pour les PAMs

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#1079]
Suite au découpage de POSEIDON à venir, il est opportun de supprimer les vues de TRITON (qui peuvent limiter la modif. de ce premier).

Etapes :
- [ ] Rajouter un login/mdp en dur dans l'application (avec l'écran de login d'Adeline)
- [ ] Rajouter un bouton d'export de zone, qui créé une "vue" de la carto partageable par une URL
  - Qu'affiche-t-on dans cette vue : les zones admin/REG ? On cache la note de risque et les avaries ?

**Comment by AdelineCelier** [comment]
Cela me semble très bien comme première version ! 
Les deux points qu'on peut améliorer dans la foulée : 
- supprimer l'espace entre la barre de recherche et les menus à gauche
- rediriger les messages du chat vers un canal de feedback spécifiques "ext"
