### ISSUE TITLE
Récupérer dans Poséidon le champ "équipé ESACAPT"

### ISSUE THREAD

**Issue by VincentAntoine** [MTES-MCT/monitorfish#1087]
Demande de Séverine, qui doit permettre de savoir si un navire est équipé de la solution de secours, et s'il tombe en panne (24h sans FAR ou signalement par le navire qui appelle le CNSP), de savoir quoi lui dire : s'il est équipé, il utilise la solution de secours, sinon, il doit rentrer à quai.

**Comment by louptheron** [comment]
@VincentAntoine ça reste dans POSEIDON ? Ou alors one shot qui initialise notre table
