### ISSUE TITLE
Ajouts de fonctionnalités dans le formulaire du Backoffice

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#1112]
- [x] 1. Impossible de désélectionner "mesures dérogatoires". Pour rappel même constat pour périodes, espèces et engins, impossible de désélectionner ces rubriques.

- [x] 2. Ajouter un commentaire sur la période de pêche autorisée sans ajouter de période précise ; et permettre l'affichage dans le résumé REG

- [x] 3. Intégrer diverses possibilités de maillage. Pour être exhaustive: supérieur à / supérieur ou égal à / inférieur à / inférieur ou égal à / égal à / entre

- [ ] 4. Intégrer la possibilité de définir des engins interdits et des engins autorisés (ex je suis tombée sur un AP (58/2007) pour la pêche du lançon en filet remorqué en MEMN où on a une réglementation relative aux chaluts mais en parallèle les TBB sont interdits pour pêcher cette espèce). La même chose serait éventuellement à faire pour les espèces, il y a moins de cas mais c'est possible d'avoir une zone relative à la pêche des praires et dans cette zone interdiction d'avoir de la CSJ à bord. Il me semble avoir un autre cas avec de la sole et de la plie mais je n'ai pas encore réussi à retrouver le texte. 

- [x] 5. Ajouter un champ libre sous chaque espèce et chaque engin (avec possibilité de retour à la ligne). ça ne me servira pas à décrire toute la rég de l'arrêté mais parfois j'en aurais besoin pour préciser certains points. Ex: j'ai une zone interdite aux casiers sans trappe d'échappement. Si je mets uniquement engins interdits : "casiers" ça porte à confusion. Il faudrait que je puisse spécifier sous l'engin casier que seuls ceux sans trappe sont interdits. S'il y a plusieurs engins concernés ce serait bien que j'ai ce type de champ libre sous chaque engin pour qu'ensuite visuellement dans le résumé rég ce soit plus clair. Même chose pour les espèces =) (au lieu de taille min ou quantités)

- [x] 6. **[Ajout Adeline, après discussion avec Diane]** Garder les champs libres globaux pour chaque section (période, engin, espèce). Les renommer "remarques générales" dans le backoffice, mais ne pas faire apparaître le titre de ce champ dans le résumé reg. Seul le commentaire apparaîtra, en fin de section.

- [x] 7. J'aimerais avoir dans les champs libres textuels la possibilité de revenir à la ligne. Si je reprends l'ex ci-dessus ça donne pour le moment ça visuellement sur MF:
![gmbilncokiopldpc](https://user-images.githubusercontent.com/14853556/162449885-89304036-4bac-453a-9ae6-69f9ad6ce885.png)
L'idée ce serait au moins de pouvoir faire des retours à la ligne pour différencier les 3 cas...

- [x] 8. Le champ libre sous la rubrique période, lorsqu'il est rempli ne s'affiche pas dans le résumé rég. A noter: généralement je le remplis lorsque la période est un peu complexe donc je ne coche que "récurrence annuelle" sans remplir toute la rubrique période. C'est peut être ça qui fait que le champ libre ne s'affiche pas.

- [x] 9. Revoir la manière d'afficher la liste des engins et catégories d'engins dans le résumé reg. Aujourd'hui ce n'est pas bien regroupé et nuit à la lisibilité de la rubrique quand il y a une liste importante (cf. nourriceries soles). 
-> dans le cas des sub-catégories "engins traînants" et "engins dormants" : si elles ont été cochées dans le backoffice, mentionner juste "engins trainants" / "engins dormants", et rajouter une infobulle mentionnant les catégories d'engins concernées (cf. infobulle existante dans le backoffice).
-> dans le cas des catégories, 1/ les ranger dans le même ordre que dans le menu déroulant du backoffice, 2/ faire le même principe d'infobulle, en spécifiant les engins en toutes lettres + le code FAO. A noter qu'il faudrait passer à la ligne après chaque engin dans l'infobulle, cf. ci-dessous : 
![image](https://user-images.githubusercontent.com/71878648/163977933-b1b4a602-e375-4a4c-975f-ee1a67eab5f0.png)

- [ ] 10. Une fonctionnalité qui nous gêne Alexis et moi c'est le remplissage des dates pour la période. Je ne sais plus ce que tu nous avais dit Adeline dessus mais si on pouvait les remplir à la main ce serait l'idéal ^^ (par ailleurs il y a un souci d'affichage quand on clique sur la date et qu'on a un calendrier année/mois qui s'affiche)
--> Pour l'instant ça ne sera pas possible de les rentrer à la main car ça demande de changer le composant des dates, mais c'est noté pour une passe un peu plus tard.

- [x] 11. Quand on clique sur un engin dans les différents listings proposés, cela ne le sélectionne pas. Il faut cliquer sur la case à cocher pour sélectionner vraiment l'engin. A voir si pour les espèces il n'y a pas le même problème (je ne crois pas).

- [ ] 12. J'ai noté avoir eu un problème avec l'espèce pétoncle blanc et praire (venus verrucosa), je crois que ce sont des espèces que je n'ai pas réussi à retrouver dans la liste FAO. Après la liste transmise par Vincent devrait bien m'aider!
--> Du coup c'est OK pour toi ?

- [ ] 13. Les cases à cocher relatives au références réglementaires (création de zone/ réglementation de zone / jusqu'à nouvel ordre) se décochent parfois. Cela dépend des textes, je n'ai pas observé de raison particulière mais parfois quand on veut modifier une zone dans le back office, ces éléments ne sont plus cochés et il faut les recocher. Bon absolument rien de grave ou de prioritaire mais je ne sais pas pourquoi ça se produit.
--> Tu as encore eu le cas ? C'est possible de m'appeler (Loup) quand tu retombes dessus ?

- [ ] 14. J'ai eu un cas étrange où en ajoutant en engin 1 "casier" et en voulant ajouter un engin 2, ça m'a mit cette engin en catégorie 1 au lieu de engin 2.
--> Tu as encore eu le cas ? C'est possible de m'appeler (Loup) quand tu retombes dessus ?

- [x] 15. Réorganiser le listing d'espèces FAO par ordre alphabétique si possible

- [x]  16. Renommer la catégorie Pièges en "Pièges et casiers" et renommer "Nasses (casiers)" en "Casiers (nasses)", en effet le terme nasses est vraiment rare dans les textes rég, c'est systématiquement le terme casier qui est utilisé.

- [x] 17. Je dois à chaque fois relancer geoserver très régulièrement et notamment dans les cas suivants: dès que je me connecte au backoffice et dès que je modifie le nom d'une thématique (je ne peux d'ailleurs plus afficher ensuite les zones de la thématique dans la carto). Pour régler ce dernier souci je dois soit refaire la manip geoserver soit rafraichir la page.
--> ça devrait être OK, dis moi si tu as encore le cas.

- [x] 18. Lors de la modification du contenu textuel lié à une zone, dans les rubriques période de pêche/espèces/engins il n'y a pas de possibilité une fois qu'on a sélectionné "autorisé(es)" ou "interdit(es)" de pouvoir désélectionner notre choix afin d'éviter de faire apparaître ladite rubrique dans le résumé rég. Sur le screen ci-dessous, typiquement impossible d'enlever "période de pêche autorisée".
![pjpceagepiflblbm](https://user-images.githubusercontent.com/14853556/162449774-2adf990c-eace-4b6f-a5cd-34cff62eec73.png)

- [x] 19. Je pense que ce serait bien que le titre de la zone  s'affiche dans le résumé rég. On a "ensemble rég" - "thématique" - "région" qui s'affichent mais pas le titre de la zone alors qu'il peut parfois être tronqué dans le menu de recherche.
**NB Adeline : je pense qu'on peut aussi supprimer le nom de la thématique dans le bandeau du résumé reg., pour ne laisser que le nom de la zone**

- [x] 20. Je rencontre un problème avec le bulot. Dans les faits le bulot commun est le Buccinum undatum sauf qu'il n'apparaît pas dans le listing des espèces FAO. J'ai le choix entre pas mal d'espèces de buccins dont Buccin (WHE) et buccinum spp (BEX). J'ai choisi de sélectionner ces 2 là mais bon sur le résumé rég ça apparaît sous le nom buccin et pas bulot (qui est quand même plus utilisé et parlant) et puis j'ai 2 codes FAO pour la même espèce.
Après je n'ai pas vraiment la connaissance dans les faits des codes utilisés par les pêcheurs pour ce type d'espèce, ce qui complique aussi mes choix...
Par contre quand on a plusieurs codes FAO pour une même espèce (c'est le cas ici mais aussi pour la baudroie : ANF ou MNZ, il faudrait que je puisse associer plusieurs codes à l'espèce 1 car sinon cela m'oblige à sélectionner une espèce 2...)
ex du bulot: 
![ljlbnodcobbfmcai](https://user-images.githubusercontent.com/14853556/162449976-a7ab7042-1925-4c1e-ac5d-dd8ce5c32aaa.png)
pour le moment dans le back office j'ai ça:
Or j'ai aussi le code WHE pour lequel les mêmes mesures techniques s'appliquent... ce serait lourd de créer une espèce 2 buccin WHE alors que c'est la même espèce que l'espèce 1.
--> A gérer dans "Remarques générales" ?

- [x] 21. Il y a un problème d'affichage des listes d'espèces quand on est trop haut sur la page (ahha difficile à expliquer comme ça je vais tâcher de le faire via des screens)
Cas où on accède à toute la liste:
![nlbgllnnncbjkbmp](https://user-images.githubusercontent.com/14853556/162450010-27f8a8c9-a3c1-4ca1-bdcc-1bd4ecaf0c24.png)
Cas où ça buggue:
![elbmapdonpielgdf](https://user-images.githubusercontent.com/14853556/162450041-c3ce1328-0d76-4e71-ad69-6545b24230c9.png)
La liste reste bloquée à gastéropodes, on ne peut plus la descendre.
--> C'est mieux comme ça ?

**Comment by AdelineCelier** [comment]
## Retours UI (de ce que j'ai pu vérifier)

- Revoir la marge entre les libellés et les valeurs des champs espèce et engin : 20 px entre le libellé le plus long et sa valeur 
![image](https://user-images.githubusercontent.com/71878648/165105921-356d5ed2-462f-4ea1-a7f6-7b903afeacd4.png)

- Aligner le libellé "remarques générales" avec le haut du champ, ne pas le centrer
![image](https://user-images.githubusercontent.com/71878648/165106252-a5bffcc0-0f16-408b-ab88-b27a105909e9.png)

- Dans le menu déroulant, trier les engins par ordre alphabétique – attention, pas les catégories d'engins mais juste les engins au sein des catégories. Là j'ai l'impression qu'ils sont un peu en vrac. 
- Dans le résumé reg, trier les listes d'engins et d'espèces de manière à refléter l'ordre du menu déroulant du formulaire : les trier par catégories dans le même ordre que le menu, et au sein des catégories les trier par ordre alphabétique. Tester avec un saut de ligne entre chaque catégorie pour aérer la liste (à voir si ça ne rallonge pas trop la liste, et si ça ne fait pas bizarre sur des listes plus courtes). 
- Sur le point 15, la liste des espèces FAO semble bien rangée par ordre alphabétique, sauf bizarrement le 1er poisson, qui commence par un S...je sais pas si c'est très gênant mais c'est intrigant !

**Comment by louptheron** [comment]
@AdelineCelier C'est ok pour toi ?

**Comment by AdelineCelier** [comment]
@louptheron Hihi ya toujours le Stolephorus holodon qui est en haut de la liste des espèces, alors qu'il commence par un S...

![image](https://user-images.githubusercontent.com/71878648/176400501-cda5d6ae-933d-4936-9fe0-59098ffcbd22.png)

**Comment by AdelineCelier** [comment]
Bon je repasse ce ticket dans le backlog, il n'est pas très urgent, avouons-le.
