### ISSUE TITLE
Les heures ne s'affichent pas toujours correctement dans le front

### ISSUE THREAD

**Issue by VincentAntoine** [MTES-MCT/monitorfish#1193]
Exemple sur une heure de DEP :
![image](https://user-images.githubusercontent.com/27647971/170267940-e50baedc-0a9c-49a2-892d-ef7d2577b39c.png)

`04h00` ne correspond pas à ce qui est dans le message xml :

![image](https://user-images.githubusercontent.com/27647971/170268064-4be8cc6e-d27d-493e-bd63-d5cc75cbfd61.png)

où l'heure est 04:24 et qui est bien renvoyé par l'API :

![image](https://user-images.githubusercontent.com/27647971/170268174-0365f18a-655f-44bb-83bf-5d389de62a11.png)

**Comment by VincentAntoine** [comment]
Exemple sur une heure de DEP :
![image](https://user-images.githubusercontent.com/27647971/170267940-e50baedc-0a9c-49a2-892d-ef7d2577b39c.png)

`04h00` ne correspond pas à ce qui est dans le message xml :

![image](https://user-images.githubusercontent.com/27647971/170268064-4be8cc6e-d27d-493e-bd63-d5cc75cbfd61.png)

où l'heure est 04:24 et qui est bien renvoyé par l'API :

![image](https://user-images.githubusercontent.com/27647971/170268174-0365f18a-655f-44bb-83bf-5d389de62a11.png)

**Comment by louptheron** [comment]
Nice catch!
