### ISSUE TITLE
Alerte message FAR - réduire le nombre d'alertes remontées

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#1209]
Deux pistes d'amélioration pour cette alerte :
- retirer de l'alerte les navires qui sont sous Visiocapture (Visiocapture étant aujourd'hui utilisé par France Agrimer pour saisir les données des fiches de pêche papier, les données sont toujours en retard)
- retirer de l'alerte les navires qui sont partis du port entre 20h et minuit, car elles ont moins d'intérêt opérationnel : à faire valider par Céline ou Elsa.

**Comment by VincentAntoine** [comment]
- Visiocapture : j'ai regardé ce qu'on a reçu comment données ERS en VisioCapture depuis le mois de janvier :

vessel_length | number_of_vessels_with_visiocapture
| -- | -- |
| Unknown | 4 |
| <12m | 2667 |
| >=12m | 29 |

-> Visiocapture ne concerne que les <12 (à 29 exceptions près
-> après vérification, ces navires >12m utilisant VisioCapture sont les mêmes que les navires exemptés de JPE (champ dans Poséidon)
-> On avait déjà décidé que pour ces navires exemptés, ce serait aux utilisateurs de désactiver les alertes pour un an, donc si toujours OK, il n'y a rien à changer de notre côté sur ce point

- Alertes entre 20h et minuit : OK je modifie ça!
