### ISSUE TITLE
Importer un fichier de tracé par Drag&Drop et le stocker dans "Mes zones importées"

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#1211]
https://openlayers.org/en/latest/examples/drag-and-drop-custom-kmz.html

**Comment by AdelineCelier** [comment]
Formats de fichier "tracés" :
- KML à faire
- Shape ou GPX : voir les besoins auprès des utilisateurs + la faisabilité technique

**Comment by AdelineCelier** [comment]
## Revue zones importées

**Revue UI**

- [ ] Est-ce que c'est possible de mettre la phrase "glissez et déposez..." sur 3 lignes seulement ?

- [ ] Retirer le scroll qui apparaît quand il n'y a pas de zones encore importée
![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/00cdbc75-f1cd-4c61-8aee-83bb82172297)

- [ ] Les chevrons des différentes sections de zones sont à l'envers
![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/a380cf02-21a2-405e-9a6c-9b586f99b3f5)

**Comment by AdelineCelier** [comment]
@louptheron pour les chevrons et la phrase sur 3 lignes, c'est bon.
En revanche je vois toujours un scroll de mon côté...tu crois que ça peut être lié à la résolution de mon écran ? 
Et il y a un petit point gris qui est apparu à gauche de la fenêtre (cf. capture)

![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/d6e37f2e-5107-4d60-b622-39b938b4d620)

**Comment by louptheron** [comment]
Fixé & testé sur une VM Windows
