### ISSUE TITLE
Recherche avancée dans les navires de la carte

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#124]
Filtrer par différents critères :  
- nationalité
- seg. de flotte
- engin à bord (JPE)
- espèce pêchée (JPE)
- zone de la marée (JPE ou VMS ?)
- émission VMS ( oui/non, plage temporelle), sachant que pour les navires de -12m le filtrage sera limité

Pouvoir filtrer
- soit tous les navire, en partant de la recherche globale dans navpro
- soit les navires d'une (ou plusieurs) zones, en traçant ou sélectionnant la/les zone(s) sur la carte
=> pouvoir enregistrer des zones personnalisées pour les réutiliser lors de filtrages/recherches ultérieurs ?

Scénario : 
1. Paramétrer le filtre : critères + plage temporelle
2. Modifier l'apparence des navires filtrés 
3. Enregistrer le filtre (ou non)
4. Supprimer le filtre s'il a été enregistré

Travail sur l'affichage des résultats de la recherche : juste sur la carto, ou aussi une liste de navires ?

**Comment by AdelineCelier** [comment]
*NB1 : La recherche avancée seulement pour les bateaux avec VMS*
dans un premier temps, je pense qu'il faut se concentrer sur les navires visibles + ou - en temps réel, et donc spécifier que cette recherche avancée ne concerne que les bateaux avec VMS. 
On pourra réfléchir à une recherche avancée incluant les -12m sans VMS, une fois qu'on saura un peu mieux les infos qu'on peut récupérer sur eux. 

*NB2 : Navires avec VMS et sans JPE*
Ces bateaux seront de fait écartés de la recherche à partir du moment où l'un des critères de recherche concernant le JPE est rempli.

**Comment by AdelineCelier** [comment]
Ecrans terminés, tests utilisateurs faits. 
Je te passe la main @louptheron

**Comment by AdelineCelier** [comment]
**Petits ajustements UI, s'ils sont faisables sans perdre trop de temps :** 
- est-ce que c'est possible de garder nos propres icônes de chevron et de croix dans les menus déroulants ? + bien justifier à droite les icônes dans la box du menu déroulant
- idem, si je peux te donner l'icône que j'ai dessiné pour la checkbox, je préfère 
- tout pareil pour les icônes de tri dans le tableau...ou alors au minimum les passer en gris
- dans le champ "zone", ajuster l'intitulé : "Filtrer avec une zone existante"
- petit problème d'affichage du menu déroulant, une fois qu'il est plein : 
![image](https://user-images.githubusercontent.com/71878648/112868585-8421ef80-90bc-11eb-9965-fbeb31e70843.png)

**Autres points :** 
- comment faire pour faciliter la recherche dans le menu déroulant (pouvoir rechercher dans les catégories) + pouvoir par défaut replier les tiroirs (le tiroir des rectangles stat est archi long) ? Est-ce qu'on met ça de côté pour l'instant, et on demande au développeur qui viendra nous prêter main-forte de s'occuper de ça (sachant qu'il ou elle devra faire plein de menus déroulants pour le formulaire) ? 
- est-ce qu'on n'ajusterait pas la taille de la fenêtre en attendant d'avoir les colonnes manquantes ?

**Comment by AdelineCelier** [comment]
Trois points identifiés : 
- problème NaN dans le champ "Priorités", quand tu effaces un chiffre
- revoir les espacements de la ligne avec les filtres
- marge interne gauche/droite des boutons : 12px, et ce pour tous les boutons de MF ;)

![image](https://user-images.githubusercontent.com/71878648/114160656-7162b280-9927-11eb-9f17-ff470d585592.png)

**Comment by louptheron** [comment]
Fixes :
- Barre de scroll à l'intérieur du tableau
- Tout sélectionner -> tout désélectioner
- Zone custom : bouger la croix dans son carré
