### ISSUE TITLE
[Signalements] Liste des signalements en cours

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#1262]

**Comment by AdelineCelier** [comment]
Ce serait possible de rajouter le tri sur toutes les colonnes ? ça semble plus cohérent de pouvoir trier toutes les colonnes d'un tableau sans distinction. 
Ou si c'est trop long, a minima sur la colonne "Titre" ? 

Si je me souviens bien, on avait dit qu'on faisait le déploiement de la ligne au clic pour voir le détail dans un 2nd temps. 
- est-ce qu'un ticket a été créé sur le sujet ? 
- en attendant, il me semble qu'on avait dit qu'on mettait les infos au survol (notamment pour le NATINF, et la description au survol du titre)
