### ISSUE TITLE
Vérifier l'alerte "Message FAR manquant" pour le navire LAURA

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#1303]
Pour la marée `20220078` du LAURA (FRA000726559), le dernier FAR date du `21/08/22` mais un LAN est émis le `22/08/22`.
Une alerte de FAR manquant est émise (le `Tue Aug 23 2022 08:45:06 GMT+0200 CET`) alors que le navire est à quai depuis le `2022-08-22T08:19:00Z`.

Cf.
![Screenshot from 2022-08-23 13-51-31](https://user-images.githubusercontent.com/14853556/186151285-84cc49c0-e57d-4864-ada3-dc7519b2e83f.png)
![Screenshot from 2022-08-23 13-48-14](https://user-images.githubusercontent.com/14853556/186151301-8cadc667-d0a9-496d-9a41-b29295e2030c.png)

**Comment by VincentAntoine** [comment]
Le navire était donc en mer le 22/08 de 00:00 à 08:10, période pour laquelle il aurait dû émettre un FAR et n'en a pas émis. Il est donc remonté en alerte le lendemain, au prochain run du flow `missing_far_alert`.

A noter qu'il était uniquement en transit le 22/08 entre 00:00 et 08:10, donc depuis #1295, ce genre de cas ne remonte plus d'alerte.
