### ISSUE TITLE
[Avaries VMS] Des avaries multiples sont créées si des vieilles positions d'un navire sont en doublons dans `last_positions`

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#1313]
cf. boite email

**Comment by VincentAntoine** [comment]
Si les identifiants (cfr et/ou ircs et/ou marquage extérieur) d'un navire sont modifiés dans Poséidon / Navpro, une ligne avec les anciens identifiants reste indéfiniement dans `last_positionse`, en plus de la vraie dernière position du navire avec les nouveaux identifiants. Cette ancienne `last_position` va générer une avarie à chaque run de `update_beacon_malfunctions`.

Il faut donc modifier `last_positions` pour s'assurer qu'elle ne contient pas de doublons.
