### ISSUE TITLE
Ajouter l'info de la DML concernée dans les alertes

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#1318]
Pour préparer l'envoi de signalement aux DML à partir d'un navire

**Comment by VincentAntoine** [comment]
@louptheron J'ai élargi l'issue, c'est bien ça le but ? On fait une branche pour gérer l'ajout de la DML à tous les niveaux : 
-  tables vessels, pending_alerts, reportings
- front depuis un signalement
?

**Comment by VincentAntoine** [comment]
Pour mémoire : on a la correspondance quartier <-> DDTM dans Navpro, j'ai demandé à CG si c'est suffisant ou s'il faut préciser la DML. En fonction de ça, soit on prendra la DDTM dans Navpro soit on intégrera un fichier csv avec la correspondance quartier - DML.

**Comment by louptheron** [comment]
> @louptheron J'ai élargi l'issue, c'est bien ça le but ? On fait une branche pour gérer l'ajout de la DML à tous les niveaux ?
> 
>     * dans les tables vessels, pending_alerts, reportings
> 
>     * dans le front, que ce soit visible depuis un signalement (je ne sais pas s'il y a déjà des écrans pour ça)


@VincentAntoine C'est déjà le cas pour les signalements (en base et dans le front) : https://github.com/MTES-MCT/monitorfish/blob/master/backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/reporting/InfractionSuspicion.kt#L11

Il manque les alertes (dans le champ `value JSONB`) et l'ajout dans la table `vessels` (nécessite une migration)

**Comment by VincentAntoine** [comment]
Cf discussion avec Adeline et Loup : 
Pour l'instant la DML d'un signalement  de type suspicion d'infraction est renseignée manuellement, mais il n'y a pas de DML dans les signalements issus d'une alerte. Or on veut pouvoir transmettre des signalements de type alerte, pas uniquement des signalements de type suspicion d'infraction. Donc il faut ajouter la DML du quartier du navire au moment de la création de l'alerte.

**Comment by VincentAntoine** [comment]
- [ ] Ajouter une table `dml`
- [ ] Ajouter un champ `dml` dans le `value` des `pending_alerts`
- [ ] Ajouter un champ `dml` dans le `value` des `reportings` de type `ALERT`

**Comment by VincentAntoine** [comment]
> @VincentAntoine C'est déjà le cas pour les signalements (en base et dans le front) : https://github.com/MTES-MCT/monitorfish/blob/master/backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/reporting/InfractionSuspicion.kt#L11
> 
> Il manque les alertes (dans le champ `value JSONB`) et l'ajout dans la table `vessels` (nécessite une migration)

@louptheron Après nouvelle discussion avec @AdelineCelier, on a décidé que cette histoire de DML devenait inutilement complexe et qu'il vallait mieux TOUT CASSER. Plus sérieurement :

- le choix manuel de la DML concernée par un signalement risque d'être peu consistant d'un signalement à l'autre pour un même navire (dans le temps, d'un utilisateur à l'autre en changeant de quart / de bordée...), et les signalements d'un même navire pourraient se retrouver dispatchés entre plusieurs DML, de façon pas forcément voulue
- la combinaison de DML ajoutées automatiquement (depuis les alertes) et manuellement (depuis le formulaire de signalement) augmenterait ce risque de non consistance
- le seul vrai besoin est de pouvoir grouper les signalements par DML : or on peut le faire à partir du quartier des navires (`reportings.vessel_id > vessels.district_code > districts.dml`), donc il n'y a pas besoin de stocker d'info de DML ni dans les signalements ni dans les alertes
- il faut donc virer le champ `dml` du formulaire de signalement et du champ `value` de la table `reportings`
- dans la vue des signalements par DML, il faut aller chercher la DML concernée par chaque signalement via `reportings.vessel_id > vessels.district_code > districts.dml`


Todo actualisée :

- [x] Ajouter une table `districts` avec la DML correspondant à chaque quartier
- [ ] Dans le formulaire de signalement, supprimer champ `dml`
- [ ] Dans le formulaire d'édition de signalement, supprimer champ `dml`
- [ ] Faire une migration pour supprimer le champ `value->>'dml'` dans les signalements existants
- [ ] Dans la vue des signalements par DML, aller chercher la DML concernée par un signalement via `reportings.vessel_id > vessels.district_code > districts.dml`

**Comment by AdelineCelier** [comment]
De ce que je peux vérifier sur ce ticket en intégration :
- le champ "DML" a bien été retiré du formulaire de création et d'édition d'un signalement
- en revanche, je ne vois pas de DML assignée aux signalements existants : est-ce parce que ce n'est pas rétro-actif ? J'ai essayé de tester en créant un nouveau sur le Jean-Louis Vincent en MED, mais je ne le vois pas apparaître le signalement dans la liste.

**Comment by louptheron** [comment]
Pour le deuxième point, il y avait en effet un souci côté data & frontend (le navire n'était pas trouvé et donc on ne pouvait pas lui rattacher une DML ni une façade), maintenant ça devrait bien fonctionner pour les nouveaux signalements.
