### ISSUE TITLE
Afficher dans la colonne "ARCHIVAGE", les avaries des 5 derniers jours

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#1343]
Modifier `findLastThirtyEndOfFollowUp`->`findLastThirtyArchived` pour remonter `150` avaries au lieu de `30`
Modifier le test correspondant

**Comment by AdelineCelier** [comment]
Il n'y a aucune avarie dans l'environnement de dev, c'est à vérifier en prod ?

**Comment by AdelineCelier** [comment]
@louptheron  Si l'on affiche maintenant les avaries des 5 derniers jours, il faut modifier la phrase de description de la colonne "Archivage" : 
"Avaries clôturées. NB : seules les avaries des 5 derniers jours restent dans le tableau." 
[remplacer "kanban" par "tableau", c'est peut-être plus compréhensible].

**Comment by louptheron** [comment]
Vérifié. On affiche finalement les 60 dernières avaries.
