### ISSUE TITLE
[Avarie VMS] Afficher le statut et non la cause de fin d'avarie sur le ticket du kanban

### ISSUE THREAD

**Issue by VincentAntoine** [MTES-MCT/monitorfish#1348]

**Comment by AdelineCelier** [comment]
Il faut que les tags de cause de fin d'avarie soient aussi visibles dans la colonne "archivage"

**Comment by VincentAntoine** [comment]
> Il faut que les tags de cause de fin d'avarie soient aussi visibles dans la colonne "archivage"

Je viens de check en prod, c'est bien le cas.

**Comment by AdelineCelier** [comment]
Ok dans ce cas on peut fermer le ticket !
