### ISSUE TITLE
Exemptions pour les alertes "Absence de message FAR" et "Pêche par un navire tiers en ZEE française"

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#1370]
Après discussion avec Céline et Xavier G., il en est ressorti que cette logique d'exemption ne concernait que ces deux alertes, et qu'il n'était donc pas nécessaire de l'implémenter dans les paramètres de toutes les alertes. 

Pour rester le plus simple possible dans un premier temps, il a été convenu que les deux listes seraient éditées via des tableaux dans le backoffice, un peu sur le même modèle que les segments de flotte. Le SIP pourrait se charger des exemptions JPE, et la reg ou l'ops des vénézueliens autorisés à venir pêcher en eaux françaises. 

A noter que pour Céline ce point n'était plus vraiment une priorité, puisque les navires concernés ont vu leurs alertes suspendues, au moins jusqu'au 31/12. Il faudrait donc que les tableaux soient prêts pour début 2023.

A faire : dessiner rapidement les tableaux pour gérer les exemptions

**Comment by louptheron** [comment]
Je rattache l'exemption des navires à l'ajout de l'alerte de FAR manquant de 48h (et la validation automatique des FAR manquants).

Nous avons convenu que ces exemptions seraient des suspensions d'alertes (objet déjà existant dans MonitorFish) ; ça simplifie l'architecture et le développement back + data de garder cette structure générique plutôt que de créer un nouvel objet `exemptions`.
Par contre, se pose la question de la façade et l'affichage des exemptions dans les onglets de façades :
- Une exemption est-elle bien multi-façade ?
- On affiche les exemptions dans les listes de suspensions d'alertes par façade ou alors seulement dans un autre tableau ?

**Comment by louptheron** [comment]
## Bug

Lorsque je rajoute un navire exempté, son `flagState` est en minuscule alors qu'il devrait être en majuscule, ce qui fait planter l'API.
