### ISSUE TITLE
Signalements - Ajouter le tri sur toutes les colonnes de la liste de signalements

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#1377]

**Comment by AdelineCelier** [comment]
Problème : quand je clique sur le titre d'une colonne, il y a bien des flèches de tri qui apparaissent, mais quand je clique sur les flèches, cela ne trie pas les colonnes (à part les colonnes "ouvert il y a" et "navire").

D'autre part, je me demande s'il ne faut pas laisser affichées les flèches tout le temps pour plus de visibilité ? Je ne suis pas sure que les utilisateurs aient le réflexe de cliquer sur le titre de colonne pour la trier s'ils ne voient pas de flèches...surtout que jusqu'ici cela ne fonctionnait pas pour toutes les colonnes.

**Comment by louptheron** [comment]
Le tri est maintenant sur toutes les colonnes
