### ISSUE TITLE
Retouches UI

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#1379]
- [x] Problème de taille de police qui crée des décalages.
![image](https://user-images.githubusercontent.com/71878648/190652437-8105e020-b793-479b-bac0-66a5ca92afb0.png)
![image](https://user-images.githubusercontent.com/71878648/190652490-a42f2b74-4e77-4369-a381-48df90e6b95f.png)
![image](https://user-images.githubusercontent.com/71878648/190652612-c484d70e-bcfc-4da0-98ca-a6829a9897f9.png)
![Screenshot from 2022-09-16 14-51-17](https://user-images.githubusercontent.com/71878648/190655250-c27bb096-6d2f-4d37-9a09-6a9980fa4dba.png)
![Screenshot from 2022-09-16 14-50-59](https://user-images.githubusercontent.com/71878648/190655270-6985b1ed-9223-4012-a74f-7a921af2bb92.png)

- [x] Problèmes de scrolls horizontaux dans des menus déroulants 
![image](https://user-images.githubusercontent.com/71878648/190652045-2799d18c-cd4c-4ae2-8e93-bb7e4dcef2c4.png)
![image](https://user-images.githubusercontent.com/71878648/190652121-040796d7-6083-4814-8372-1ef5eeed3028.png)
![image](https://user-images.githubusercontent.com/71878648/190652303-9bcf5f1f-a444-4d2d-a50b-1a4d14ae60f1.png)

- [x] Divers problèmes de marge
![image](https://user-images.githubusercontent.com/71878648/190654246-daf7645a-fd12-454f-affc-e1b776afee9d.png)
![image](https://user-images.githubusercontent.com/71878648/190654274-3e1afde7-900b-4c13-ba92-cf8d47fea6ff.png)
![image](https://user-images.githubusercontent.com/71878648/190654325-603951bd-7e98-4df3-abc7-3bb8a4a71614.png)
![image](https://user-images.githubusercontent.com/71878648/190655021-1684dc44-84e0-4ec8-b4f1-ad81365f39ea.png)
![image](https://user-images.githubusercontent.com/71878648/190669259-ebe0b5eb-3d0d-4e7c-81ac-274f738cd940.png)
![image](https://user-images.githubusercontent.com/71878648/190670170-ede3b536-00fa-40b5-961b-4e888e3b5d1b.png)

- [x] Problème improbable de décalage du bouton "exporter la piste" quand on clique sur l'étiquette d'un message JPE sur la piste d'un navire
![Screenshot from 2022-09-16 14-52-47](https://user-images.githubusercontent.com/71878648/190655607-499ce910-ffa8-4efb-91cf-0457831b487c.png)

- [ ] Retirer l'icône fantôme qui apparaît sous l'icône du navire quand on le sélectionne (en mer comme à quai)
![image](https://user-images.githubusercontent.com/71878648/190664652-19d13fb4-0d2c-4532-9293-206a6532c956.png)

**Comment by louptheron** [comment]
- [ ] Rajouter quelques pixels à la taille de la box pour le résumé JPE du préavis
- [ ] 
![Screenshot from 2022-09-19 14-37-29](https://user-images.githubusercontent.com/14853556/191018975-d7c07155-55a6-4a51-9130-240f6645851a.png)
- [ ] Bouton close décalé de la modale :
![Screenshot from 2022-09-19 14-45-11](https://user-images.githubusercontent.com/14853556/191020267-6fbd527d-0468-4adf-8e5e-a34c900c83d1.png)

**Comment by ivangabriele** [comment]
@AdelineCelier Je clos cette issue et déplace la tâche restante là: #1829.
