### ISSUE TITLE
Signalements - Traiter les signalements par lots

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#1381]
A ajuster pour un usage optimal : 
- [ ] Rajouter une case à cocher dans l'en-tête du tableau afin de pouvoir cocher toutes les lignes d'un coup
- [x] Les boutons "archiver" et "supprimer" sont tout le temps visibles, mais ils sont inactifs (cf. library) tant qu'aucune case n'est cochée
- [x] Bien aligner les boutons sur le bout du tableau (cf. capture)
![image](https://user-images.githubusercontent.com/71878648/191029597-78487f88-54cf-4ac6-87a5-adaa52da0c76.png)

**Comment by AdelineCelier** [comment]
@ivangabriele quand je teste, j'ai l'impression que tu es resté sur le fonctionnement "une case reste cochée même lorsque je filtre la vue liste". J'opterais pour un fonctionnement plus simple qui serait moins source d'erreur (tu sais, comme on en avait discuté à Etel) : si je filtre la vue liste et que ça masque des lignes cochées, ça les décoche.

**Comment by louptheron** [comment]
@ivangabriele @AdelineCelier Je repasse le ticket en TODO

**Comment by ivangabriele** [comment]
@AdelineCelier On est d'accord que ca ne décoche que les cases qui ne font plus partie de la sélection filtrée mais que ça conserve cochées celles qui font encore partie de la sélection ?

**Comment by AdelineCelier** [comment]
@ivangabriele oui on est d'accord ! le filtre ne décoche pas toutes les cases, seulement celles qui ne font plus partie de la sélection.

**Comment by AdelineCelier** [comment]
ça me semble bon aussi !
