### ISSUE TITLE
Refonte de la gestion des avaries VMS

### ISSUE THREAD

**Issue by VincentAntoine** [MTES-MCT/monitorfish#1398]
- [x] La pipeline doit générer des avaries sur toutes les balises (pas uniquement les balises avec le statut `ACTIVEES`)
- [x] Redéfinition du flag "prioritaire" : 
  - [x] La pipeline doit générer des avaries non prioritaires pour les balises avec le statut `NON SURVEILLEE` et des avaries prioritaires pour les balises avec le statut `ACTIVEE` dans Poséidon
  - [x] La pipeline ne doit pas envoyer de notifications pour les avaries non prioritaires
  - [x] Le back ne doit envoyer au front que les avaries prioritaires
  - [x] Le flag peut être supprimé dans le front (puisque seuls les prioritaires seront affichés)
- [x] Suppression de la gestion des <12 m par liste dans la pipeline
- [x] Mise à jour des raisons de fin d'avarie : remplacement des interruptions de suivi temporaire / définitive par `BEACON_DEACTIVATED_OR_UNEQUIPPED`

**Comment by VincentAntoine** [comment]
- [ ] La pipeline doit générer des avaries sur toutes les balises (pas uniquement les balises avec le statut `ACTIVEES`)
- [ ] Redéfiintion du flag "prioritaire" : 
  - [ ] La pipeline doit générer des avaries non prioritaires pour les balises avec le statut `NON SURVEILLEE` et des avaries prioritaires pour les balises avec le statut `ACTIVEE` dans Poséidon
  - [ ] La pipeline ne doit pas envoyer de notifications pour les avaries non prioritaires
  - [ ] Le back ne doit envoyer au front que les avaries prioritaires
- [ ] Suppression de la gestion des <12 m par liste dans la pipeline

**Comment by louptheron** [comment]
@AdelineCelier Faut-il changer l'en-tête du mail d'avarie ? On est passé au SG Mer maintenant...

**Comment by AdelineCelier** [comment]
Aujourd'hui il n'y a que le logo du CNSP dans les mails. On pourrait effectivement rajouter le cartouche du SG Mer, mais ce n'est pas urgent je pense. On se dit qu'on voit ça plus tard ? 😇
