### ISSUE TITLE
[BUG] Lorsqu'il y a deux messages `RET` pour un message JPE, prendre en compte le dernier reçu

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#1407]
La méthode `findAllMessagesByTripNumberBetweenDates` ne prend pas en compte qu'il peut y avoir plusieurs messages `RET` pour un message `DAT`.

La requête avec les messages RET du message FAR manquant :
```
select * from logbook_reports where referenced_report_id = 'OOE20220928027601';
```

![Screenshot from 2022-09-28 15-46-05](https://user-images.githubusercontent.com/14853556/192795838-f8dba1ba-c679-4e86-8a51-e331e850178c.png)

------

## Email du service SIP

Nous avons détecté une anomalie dans MF concernant les remontées d'info ERS  pour la marée 20220058 du navire DOLOMIEU.

CONSTAT.

Comme vous pouvez le constater ci-dessous, des messages du 25 au 28/09 remontent en non acquittés.
![ofpadihpeamacgei](https://user-images.githubusercontent.com/14853556/192796051-cbda7946-005c-41e6-a1b4-138ea5a35410.png)

Dans le même temps sur PAGODE "déclarations", ces messages sont acquittés.
![onemplkjhjaifbaj](https://user-images.githubusercontent.com/14853556/192796068-862b61c7-aabb-4924-9b1d-ace6291cd4f9.png)

EXPLICATIONS.
Dans premier temps, ces messages étaient en effet non-acquittés sur PAGODE. Suite à la suppression de 2 messages bloquants émis depuis eSACAPT, ces messages ont été acquittés par le serveur.
Il serait donc nécessaire de "rafraichir" MF en conséquence de ces modifications.

**Comment by VincentAntoine** [comment]
En regardant de plus près je crois pas qu'il faille prendre le dernier RET reçu.

Sur une année (2023), on trouve 38121 messages JPE ayant au moins 2 RET qui pointent vers eux (via `referenced_report_id`), dont :
- 32234 (84.6%) messages JPE pour lesquels tous les RET qui pointent vers eux ont la même valeur de `return_status` --> pour ceux-là peu importe quel RET on prend (le premier, le dernier, un autre...) puisqu'ils ils sont tous identiques
- 5887 (15.4%) pour lesquels les différents RET ont des `return_status` différents --> pour ceux-là le choix du RET retenu importe. Or, sur ces 5887 cas, il s'en trouve plus de 4700, soit plus de 80%, pour lesquels on trouve à la fois des RET d'acceptation (`return_status` 000) et des codes de refus (`return_status` 002) avec pour motif de refus l'erreur `MOPS05 Message incorrect : la déclaration DAT n°<masqué> envoyée le <date heure> fait référence à un message portant le même numéro (ON) mais dont le contenu est différent. Veuillez contacter votre opérateur.` ce qui semble indiquer un double envoi du même message, probablement pour cause de mauvaise réception satellite ou autre merdouille de télécommunication qui force la balise à faire plusieurs essais, mais le message a toutes les raisons d'être considéré comme acquitté si au moins une de ses instances a été acquittée. De plus, les éventuels doublons qu'on recevrait en entrée (plusieurs xml avec le même  operation_number (ON)) sont éliminés en entrée de DB car on n'insère pas les données d'un fichier XML ayant un ON déjà en base.

Je pense donc que dès qu'il y a une acceptation (code 000), qu'elle arrive en premier, en dernier ou au mileu d'autres RET avec des valeurs de refus, c'est l'acceptation (code 000) qui prévaut.

J'en parle au SIP et je mettrai leur réponse ici !

**Comment by VincentAntoine** [comment]
Point fait ce matin avec le pôle SIP.
Confirmatin qu'on peut garder le principe qu'un message peut être considéré comme acquitté dès lors d'au moins un message RET avec code 000 le concernant existe, même si d'autres messages avec code 002 existent aussi.

Création aussi du ticket #3089 qui est lié.
