### ISSUE TITLE
La marée `20220154` du navire `BEOTHUK` ne s'affiche pas dans l'onglet Pêche

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#1418]

**Comment by VincentAntoine** [comment]
En fait elle s'affiche bien mais le chargement est très lent car il y a dans cette marée des messages erronés avec 2 FAR en 1983...
Je dirais qu'il faut prévoir que ce genre de cas peut arriver en

- mettant des `LIMIT` dans la requête de positions
- affichant un warning du genre "attention, piste tronquée en raison d'un nombre de positions trop élevé - Veuillez choisir une période moins longue" quand le nombre de positions remontées atteint la limite fixée
