### ISSUE TITLE
Ajout des rectangles stat Crozet & Kerguelen

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#1419]

**Comment by AdelineCelier** [comment]
@louptheron Je ne les vois pas en intégration...c'est normal ?

**Comment by louptheron** [comment]
@AdelineCelier Ils sont rajoutés dans rectangles statistiques :
 
![Screenshot from 2022-10-14 16-59-27](https://user-images.githubusercontent.com/14853556/195878741-9631fbd3-41ce-4515-8717-510b0b04e13d.png)

**Comment by AdelineCelier** [comment]
Ah bah chelou, j'avais bien affiché les rectangles statistiques pourtant (cf. ma capture d'écran). Mais là je viens de ré-essayer et ça marche bien.
