### ISSUE TITLE
Changement des couleurs des couches REG et affichage des périodes non autorisées

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#1420]
Beaucoup de zones avec engins n'ont pas de couleur correspondante. Et les couleurs des zones ne sont pas reportées dans la vue liste (petit carré à gauche du nom de la zone toujours de la couleur par défaut).

**Comment by louptheron** [comment]
@AdelineCelier Je fix cette issue ou alors on change la façon de coloriser ces couches ?

**Comment by AdelineCelier** [comment]
**Décisions prises suite à ma discussion avec Diane et Léa hier**
- le système actuel d'attribution des couleurs selon la famille d'engins n'est pas pertinent, près d'un tiers des zones n'ayant pas d'engin renseigné
- selon les retours de l'ops, la seule couleur signifiante qui leur serait utile est une couleur rouge pour les zones en période de pêche fermée. Les règles à appliquer pour qu'une zone soit en rouge 
  - on ne se concentre que sur les dates de période pas les horaires
  - une période interdite est renseignée : la zone est rouge pendant cette période, et reprend une couleur "normale" en-dehors
  - une période autorisée est renseignée : la zone est "normale" pendant cette période, et devient rouge en-dehors

**Comment by AdelineCelier** [comment]
Hello @louptheron, j'ai fait une gamme colorée de 15 couleurs "neutres" (dans les bleus et verts) pour les zones reg en période ouverte ou sans période + 1 nuance rouge pour les zones en période fermée. 
Elles sont dans la librairie, ici : https://xd.adobe.com/view/b6d4c472-3fbe-4dec-9f14-38fe03872a3e-e387/screen/b9bdc1ba-5f07-4c4f-bd44-2d38b2c6f663/specs/

**Comment by louptheron** [comment]
![Screenshot from 2022-10-19 18-19-59](https://user-images.githubusercontent.com/14853556/196748604-c8a3d2fb-aa5a-4ded-9c8f-d103866bcb85.png)
![Screenshot from 2022-10-19 18-19-49](https://user-images.githubusercontent.com/14853556/196748610-c98e53eb-84ba-470b-9689-b8183ef07362.png)
![Screenshot from 2022-10-19 18-19-35](https://user-images.githubusercontent.com/14853556/196748615-b3d113e2-1822-429f-a915-77536f6ce271.png)

**Comment by AdelineCelier** [comment]
Merci pour les captures ! Bon le point positif déjà c'est que le rouge des alertes ressort bien sur le rouge de la zone fermée. 
Est-ce que les zones sont en opacité 75% ? Elles me semblent un peu opaques... on était à combien d'opacité sur les anciennes couleurs de zone ?

**Comment by AdelineCelier** [comment]
Alors, après revue avec Loup, petit ajustement des couleurs : 

**On retire les teintes vertes suivantes, qui tranchent trop avec le bleu, et qui ne sont pas toutes utilisées**
- Light Cyan - #C7EAE5
- Middle Blue Green - #91CFC9
- Verdigris - #56B3AB
- Viridian Green - #01A29D
- Paolo Veronese Green - #21977F
- Skobeloff - #01686B
- Blue Sapphire - #01536A
- Indigo Dye - #033E54

**On ajoute les teintes de bleu suivantes**
- Light Blue - #B9DDE5
- Sky Blue - #77C1DE
- French Blue - #2E75AB
- Prussian Blue - #003454

On se retrouve donc avec une palette plus réduite de 12 bleus différents, et 1 rouge qui tranche bien avec les bleus.

**Comment by AdelineCelier** [comment]
@louptheron 
Oups en revanche il semble y avoir un bug encore sur les zones fermées : la zone sélectionnée sur la capture d'écran ne devrait pas être rouge, si ?
![image](https://user-images.githubusercontent.com/71878648/203324179-f0bb9f81-d38e-4921-80a9-575e51d068c6.png)

**Comment by louptheron** [comment]
@AdelineCelier 
- C'est fix pour le bug normalement
- Je ne peux pas avoir ce type d'algo pour le groupe de zones, par contre il y a une répartition uniforme (grosso modo) des couleurs sur toutes les couches dans MF, donc c'est plutôt une histoire de malchance pour Bretagne Palangres...
J'ai fait lee test pour avoir la répartition des 12 couleurs REG sur toutes les couches :
           0: 13%
           1: 9%
           2: 7%
           3: 7%
           4: 6%
           5: 7%
           6: 9%
           7: 7%
           8: 8%
           9: 7%
           10: 9%
           11: 6%

**Comment by AdelineCelier** [comment]
@louptheron pour le fix des zones rouges j'ai l'impression qu'il y a encore des problèmes : le polygone B du groupe "Vendée Chaluts" n'apparaît bien plus en rouge (pêche autorisée du 15 septembre au 19 avril), en revanche le polygone C n'est plus rouge alors qu'il devrait l'être (pêche autorisée du 15 septembre au 15 novembre). 

Ah tiens c'est marrant que les couleurs soient toutes autour de 7-9%, et que la 1ère soit à 13% ! 
Bon ok si c'est trop chronophage tant pis, ce n'est pas prioritaire, restons comme ça pour l'instant.

**Comment by louptheron** [comment]
@AdelineCelier ça devrait être bon là

PS. J'ai noté que quand on fait le preview de la zone depuis la recherche, la couleur rouge n'est pas affichée, je fais un ticket
