### ISSUE TITLE
Notifications d'avaries aux FMC étrangers

### ISSUE THREAD

**Issue by VincentAntoine** [MTES-MCT/monitorfish#1423]
cf discussion avec FF : une fonctionnalité existe dans Poséidon pour envoyer une notification à un FMC étranger quand un navire français est en avarie dans ses eaux, ce qui n'existe actuellement pas dans MF et qu'il faudrait développer.

De mémoire l'envoi de ces notifications par le FMC de l'Etat du pavillon au FMC de l'Etat côtier est une obligation réglementaire. 

A court terme le SIP peut toujours utiliser Poséidon pour faire ça, donc ce n'est pas forcément bloquant pour passer à MF pour la gestion des avaries, surtout que le volume est très faible - quelques avaries par an.

Dans Poséidon :
- l'envoi est déclenché manuellement par l'agent, ainsi que le choix du pays à qui envoyer la notification (menu déroulant pour choisir le pays)
- c'est le logiciel qui crée et envoie les messages de notification. Il y a donc une liste de diffusion avec le contact FMC de chaque pays dans Poséidon.

Dans MF :
- il faudrait récupérer les listes de diffusion dans Poséidon
- il faudrait aussi créer un template de message (en anglais quel que soit le pays j'imagine ?)
- pour le déclenchement de l'envoi :
  - soit ça reste manuel comme dans Poséidon - ce qui n'est peut-être pas plus mal pour éviter le boulettes, et pas très gênant vu le volume très faible
  - soit on automatise en fonction de le position de la dernière émission VMS croisée avec les ZEE
- pour le choix du pays à qui envoyer la notif : 
  - soit on fait comme Poséidon et on laisse l'agent choisir le pays d'envoi, et dans ce cas il faut créer un menu de sélection du pays d'envoi
  -  soit on envoie automatiquement au pays dont la ZEE contient la dernière position émise par le navire

Ecrans :
- https://xd.adobe.com/view/86c9b418-202b-43b7-b13f-403532f501d9-d39a/screen/27eaed65-fde0-4e8b-839c-8f140870909d/specs/
- https://xd.adobe.com/view/86c9b418-202b-43b7-b13f-403532f501d9-d39a/screen/db22381d-4062-418e-8580-d223acb2bf35/specs/

**Comment by AdelineCelier** [comment]
- Le message qui s'affiche quand on envoie un mail au FMC étranger n'est pas bon : le détail mentionne un capitaine et un fax, au lieu d'un FMC et d'un mail. Dans l'idéal il faudrait mettre "FMC [Pays]", ex. "FMC Portugal". C'est possible ?
- Autre point, le menu déroulant pour le choix du pays n'est pas aligné avec le reste à gauche

![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/e9613bab-27d3-461d-be48-a4545667ad7d)

**Comment by louptheron** [comment]
Testé en PROD par le pôle SIP.
