### ISSUE TITLE
Signalements - Télécharger la liste des signalements au format .csv

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#1445]
Maintenant que l'on a les DML dans les signalements, l'utilisateur pourrait filtrer la liste par DML, puis télécharger un tableau des signalements à envoyer directement à la DML concernée. 

@louptheron  avec Vincent on s'est dit que ce serait potentiellement un quick win, qu'en penses-tu ? ça demanderait beaucoup de travail ? Je peux facilement rajouter un bouton en haut à droite du tableau pour le téléchargement.

**Comment by louptheron** [comment]
@ivangabriele Deux retours en intégration :
- Le champ `DML concernée` du CSV est vide alors qu'il y a une DML
- Il y a un champ en trop : `reportingTitle`
- Il manque le champ `description`

**Comment by AdelineCelier** [comment]
Hello ici,

Sur le .csv, l'ordre des colonnes ne me semble pas tout à fait logique. Je propose : 
- Ouvert le
- DML concernée
- Origine de l'alerte
- Titre de l'alerte
- NATINF
- Pavillon du navire
- Nom du navire
- CFR
- CS
- Marquage extérieur

**Comment by AdelineCelier** [comment]
C'est bon pour moi !
