### ISSUE TITLE
Améliorations bandeau jaune de dysfonctionnement VMS ou JPE

### ISSUE THREAD

**Issue by VincentAntoine** [MTES-MCT/monitorfish#1450]
Le SIP m'a informé que le bandeau jaune posait parfait problème en cas de dysfonctionnement partiel des chaînes de données :
- sur le JPE : en cas de panne du système français uniquement, le bandeau n'apparait pas car on reçoit des données d'autres pays
- sur le VMS : en cas de panne sur un seul des opérateurs voire sur un seul type de balise, le bandeau n'apparait pas non plus

Une piste à creuser : faire des checks plus fins (par opérateur, par pays, par logiciel JPE...) pour mieux détecter les pannes, et mettre dans le bandeau jaune un messge générique "panne VMS en cours" ou "panne JPE en cours" avec un lien vers un dashboard Metabase qui montre en détail l'état des flux JPE et VMS par pays, opérateur, type de balise etc

**Comment by louptheron** [comment]
@AdelineCelier Ok pour toi ?
Pour récap, on afficherait le bandeau si :
- Un opérateur VMS est DOWN
- On ne reçoit pas assez de messages JPS d'un pays (liste des pays à définir)

**Comment by AdelineCelier** [comment]
Yes ça me semble bien d'être un peu plus fin ! Et top si on peut rajouter un lien vers un Metabase, ça permettrait sûrement un diagnostic plus rapide. Est-ce qu'on essaye de spécifier un peu plus le message dès le bandeau : "Panne VMS en cours ([nom de l'opérateur])" par ex ? Ou bien ce serait rapidement lisible sur le Metabase ?

**Comment by VincentAntoine** [comment]
J'ai un peu peur qu'il y ait trop de cas possibles pour arriver à faire une phrase qui résume la situation à chaque fois, voire que ça fausse le diagnostic. Par exemple si les données ne sont pas à jour dans MF parce qu'on a une panne de notre côté, on risque d'afficher "panne sur l'opérateur bidule" alors que le problème vient de chez nous et pas de l'opérateur. Sur le dashboard on affiche juste quelles sont les données à jour sans interpréter, et c'est à l'utilisateur de comprendre ce qui se passe. Donc ça mâche moins le travail mais au moins ça n'induit pas en erreur je trouve.

**Comment by AdelineCelier** [comment]
Ok je comprends, restons générique dans le bandeau dans ce cas.

**Comment by louptheron** [comment]
Ecran : ![image(2)](https://github.com/MTES-MCT/monitorfish/assets/14853556/bce4e2f5-66de-4ccc-9976-38c21af65117)
