### ISSUE TITLE
Quand on rentre un remarque dans le champ Période du Backoffice (sans période), le champ ne s'affiche pas dans le résumé réglementaire

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#1466]
Ex: Manche Est - Pétoncle blanc - Secteur Est Baie de Seine

**Comment by AdelineCelier** [comment]
@louptheron Je ne peux pas vérifier ce ticket, car il y a un bug sur la récupération des tracés dans le back (donc je ne peux pas créer de zone pour vérifier).

**Comment by louptheron** [comment]
@AdelineCelier C'est bon la récupération des tracés est fix!

**Comment by AdelineCelier** [comment]
Aloooors ça ne marche pas pour la zone "Secteur large Baie de Somme", seule zone de la thématique pour laquelle Diane n'a pas coché un des deux radio buttons "pêche autorisée" ou "pêche interdite". Et selon moi, il faudrait que ça s'affiche quand bien même on n'a rien coché
