### ISSUE TITLE
Alertes JPE

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#149]
# Alertes relatives au JPE

## Technique

- Stockage dans la table `alerts` avec un structure variable en JSONB.
- Remontée des alertes dans l'API `/ers`
- Affichage des alertes sur la piste navire (au point le plus près de la date où l'alerte a été detectée)
- Stockage des types d'alertes dans le code (type `SIMILAR_PNO_AND_LAN_WEIGHT`) mais instanciation des alertes sauvegardées (condition `IS_EQUAL`) en base de donnée (car des alertes existantes peuvent être modifiées ou de nouvelles alertes peuvent être crées)

### 1. **Tolérance 10% non respectée**
  - **Condition** : pour chaque espèce, si le poids du LAN est 10% supérieur au poids du préavis (PNO)
  - **Exécution** : toutes les 10 minutes
  - Exception pour les thoniers tropicaux

### 3. **Message FAR manquant**
  - **Condition** : Un message FAR n'a pas été envoyé depuis >24h alors que le navire est en marée (il a émis un message DEP de FSH (Fishing) non terminé par un EOF et/ou RTP)
  - **Exécution** : toutes les 10 minutes

### 2. **Poids du PNO et poids du LAN similaires**
  - **Condition** : sur le total des poids, si le poids du PNO et le poids du LAN sont égaux
  - **Exécution** : à la réception du message LAN

### 4. **Rejet d'une espèce interdite au rejet**
  - **Condition** : Une espèce contenue dans la liste des espèces interdites au rejet est présente dans un message de rejet (DIS)
  - **Exécution** : à la réception du message DIS

**Comment by VincentAntoine** [comment]
Cf test fait à l'instant pour la liste des navires en mer à un instant t.

```SQL
WITH last_dep AS (
    SELECT 
        cfr,
        MAX(TO_TIMESTAMP(value->>'departure_datetime_utc', 'YYYY-MM-DD HH24:MI')) as last_departure_datetime_utc
    FROM processed.ers_json
    WHERE operation_datetime_utc > date '2020-8-1'
    AND log_type = 'DEP'
    GROUP BY cfr),
    
last_rtp AS (
    SELECT 
        cfr,
        MAX(TO_TIMESTAMP(value->>'return_datetime_utc', 'YYYY-MM-DD HH24:MI')) as last_return_datetime_utc
    FROM processed.ers_json
    WHERE operation_datetime_utc > date '2020-8-1'
    AND log_type = 'RTP'
    GROUP BY cfr)

SELECT 
    last_dep.cfr as cfr,
    last_dep.last_departure_datetime_utc,
    last_rtp.last_return_datetime_utc,
    (last_dep.last_departure_datetime_utc > last_rtp.last_return_datetime_utc) OR last_rtp.last_return_datetime_utc IS NULL AS is_at_sea
FROM last_dep
LEFT JOIN last_rtp
ON last_dep.cfr = last_rtp.cfr
```
