### ISSUE TITLE
La colonne `facade` est inutile dans `regulations`

### ISSUE THREAD

**Issue by VincentAntoine** [MTES-MCT/monitorfish#1520]
@louptheron : sauf erreur de notre part, avec @AdelineCelier on a remarqué qu'il y a une colonne `facade` désormais inutilisée dans `regulations`. Elle n'est pas dans geoserver donc a priori pas utilisée par l'app. Si tu confirmes, on peut faire :

**BDD CROSS**
- [x] Exclure `facade` de la trigger function qui calcule le hash
- [ ] Supprimer la colonne `facade` de la table

**BDD Monitorfish**
- [x] Supprimer la colonne `facade` de la table

**Pipeline**
- [x] Supprimer la colonne `facade` de la requête de synchronisation

**Comment by louptheron** [comment]
En effet elle a été remplacée par "Ensemble REG", i.e `Reg. NAMO`
