### ISSUE TITLE
[Avaries] Ajouter les statuts navire

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#1532]
**Statuts navire**
Ajouter :
- En arrêt technique
- En vente
- Suspendu cause impayé
- Navire en ZEE étrangère
Supprimer :
- N'a jamais émis

**Comment by AdelineCelier** [comment]
Couleur des statuts : 
- _en arrêt technique_ : même couleur que _à quai_ (Wheat)
- _en vente_ : idem, même s'il faudrait demander au SIP si en vente = forcément à quai
- _suspendu cause impayé_ : même couleur que _activité détectée_ (Maximum Red), mais pareil faudrait demander au SIP si ce statut a toujours valeur d'alerte ou non
- _en ZEE étrangère_ : même couleur que _navire en mer_ (Powder blue)
