### ISSUE TITLE
La recherche reg par zone sélectionnée sur la carte est cassée

### ISSUE THREAD

**Issue by VincentAntoine** [MTES-MCT/monitorfish#1560]

**Comment by AdelineCelier** [comment]
@louptheron Cela m'a l'air bon. En revanche j'ai l'impression que le style de la zone de recherche est différent d'avant...est-ce qu'il serait possible de changer le style du contour de la zone tracée ? L'affiner (2 px) et le mettre en pointillés ? Si cela ne prend pas trop de temps à faire...
