### ISSUE TITLE
Rajouter le cadencement du VMS dans la fiche navire

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#174]
@Vincent pourrais-tu regarder si on a accès à cette info (bateau émettant soit à l'heure, soit au quart d'heure, soit selon une cadence personnalisée, demandée par le CNSP aux opérateurs) ? 

Si on peut récupérer l'info, elle pourrait s'afficher dans la fiche résumé du navire, à la suite de "VMS" dans "type de signal" : "VMS (1position/heure)" ou "VMS (1position/15 min)", etc. : 

![Capture2](https://user-images.githubusercontent.com/71878648/108729972-5e3c8480-752b-11eb-9044-cf3460f4bfb6.PNG)

**Comment by AdelineCelier** [comment]
Dans un premier temps, on reste sur qqch de simple : moyenne sur les 4 derniers points VMS

**Comment by AdelineCelier** [comment]
En revoyant l'écran, je me dis que ça n'a pas grand intérêt pour l'instant de mettre un champ "type de signal", vu qu'on n'a pas encore l'AIS et que quand on le rajoutera, il faudra probablement refaire une passe sur tous les écrans et composants liés aux infos de piste des navires.
Du coup je propose les modifications suivantes : 

![image](https://user-images.githubusercontent.com/71878648/109676587-2233a000-7b79-11eb-9920-054d2e4d51e7.png)
![image](https://user-images.githubusercontent.com/71878648/109676853-632bb480-7b79-11eb-827d-546c935f286d.png)

**Comment by VincentAntoine** [comment]
@louptheron on peut simplement faire une vue SQL `vms_period` qui calcule cette valeur pour chaque navire avec 2 colonnes
* id (PK, FK vessels)
* cadencement
Ca te semble bien ? Si OK pour toi je peux faire une migration pour créer la vue.

**Comment by CNSP-Etel** [comment]
Remplacer "type de signal" par "cadencement" aussi dans le survol sur le navire
