### ISSUE TITLE
Mettre en valeur un ou plusieurs navires sur la carte

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#175]
### **Besoins** 
**Marquage sur le picto du navire**
Pouvoir faire ressortir des navires sur la carte, de façon temporaire. 
Ex. navires prioritaires du ciblage
Ex. navires en cours de contrôle
Autre ? A clarifier lorsqu'on se penchera sur le ciblage plus avant

**Liste de navires favoris**
Pouvoir sauvegarder des navires dans une liste. Les superviseurs veulent pouvoir faire leurs propres listes de navires, en les regroupant de façon thématique (ex. ces 5 navires belges qui pêchent la sole dans telle zone, ces deux navires bretons que je soupçonne de chaluter en bœufs sans le signaler, ce navire qui va tout le temps pêcher dans les 3 milles...) 
=> attention à ne pas être redondant avec les filtres

### **Outils** 
- rentrer des marquages préparamétrés ? Ex. clic droit sur le navire / annoter le navire / navire prioritaire / 1, 2, 3, 4 ou 5 // ou : navire en cours de contrôle / marquage spécifique "CTRL"...autre ?
- annotation libre, notamment avec note textuelle accrochée au bateau ?

**Comment by louptheron** [comment]
- La mise à jour de la profondeur par défaut des pistes (onglet "Paramétrer la longueur par défaut des pistes") doit mettre à jour les pistes affichées
- On peut centrer sur la piste du navire pour ne pas le perdre

**Comment by louptheron** [comment]
- Refacto des fetch dans chaque fichier métier
- Utilisation d'un seul web worker wrappé (permet de ne pas avoir 5 fichiers requis par le front au chargement de l'appli)

**Comment by louptheron** [comment]
:Tester
- L'ajout de navires dans la liste
- La suppression de navires
- L'affiche des positions et de la fiche navire
- Le changement de la profondeur de piste par défaut et les changments des piste sque ça effectue (avec screenshot)

**Comment by AdelineCelier** [comment]
>Laisser affiché la piste quand on ferme la fiche navire
Ce n'est pas le cas aujourd'hui ;)

Et d'autre part, je me demandais si on ne pouvait pas griser le bouton "masquer les navires non sélectionnés" tant qu'il n'y avait aucun navire sélectionné. Cela me semble plus juste, en termes d'action décrite, et ça évite de masquer tous les navires. Qu'en penses-tu ?

**Comment by louptheron** [comment]
> Tu avais noté dans tes specs "Laisser la piste affichée quand on ferme la fiche navire", ce n'est pas le cas aujourd'hui ;)

En effet, ça me semble plus intuitif si on la ferme finalement, ok pour toi ?

**Comment by louptheron** [comment]
J'ai l'impression qu'il y a deux cas :
- Quand on affiche la fiche mais que sa piste n'est pas déjà affichée, on veut sûrement pas garder sa piste d'affichée quand on ferme la fiche, non ?
- Quand on affiche la fiche et que sa piste était déjà affichée, en effet le fait de fermer la fiche devrait laisser la piste affichée

Pour le côté intuitif, je n'avais pensé qu'au 1er cas

**Comment by AdelineCelier** [comment]
Yes, il y a ces deux cas, et si on voulait être vraiment cohérent, il faudrait dans le 1er cas n'afficher que la fiche navire, sans la piste. Mais bon, c'est peut-être un peu chelou ? 
Si tu penses que oui, on dit qu'on laisse comme ça le 1er cas, et qu'en plus on traite le 2è comme tu le décris.

**Comment by louptheron** [comment]
Oui ça fait pas de mal d'afficher la piste avec la fiche je pense

**Comment by louptheron** [comment]
à faire :
- Quand on a affiché une piste par clic droit et qu'ensuite on affiche la fiche navire, on reporte la configuration d'affichage de la piste sur la fiche navire
- Quand on ferme une fiche navire et qu'on a au préalable affiché sa piste par clic droit, on laisse sa piste affichée
