### ISSUE TITLE
Contrôles – Générer automatiquement les act-rep depuis MonitorFish

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#1750]
## Critères pour l'export

- Le contrôle contient au moins une espèce spécifiée dans les listes de espèces "liste espèces JDP NS-01", "LISTE_ESPECES_JDP WW" et "Liste Espèces_JDP MED") située dans la bonne zone FAO:
  - Si c'est un contrôle en mer, prendre la zone FAO du contrôle
  - Si c'est un contrôle à la débarque, prendre la zone FAO du PNO
- Si c'est un contrôle en mer, la mission doit être JDP
- Si on a une engin de pêche double (chalut jumeaux, chaluts à perche, ...), on rentre seulement le maillage le plus petit.

Liste des espèces : 
[Liste Espèces_JDP MED.pdf](https://github.com/MTES-MCT/monitorfish/files/12927967/Liste.Especes_JDP.MED.pdf)
[liste espèces JDP NS-01.odt](https://github.com/MTES-MCT/monitorfish/files/12927969/liste.especes.JDP.NS-01.odt)
[LISTE_ESPECES_JDP WW.odt](https://github.com/MTES-MCT/monitorfish/files/12927972/LISTE_ESPECES_JDP.WW.odt)

---

_Explications de Xavier sur les act-rep (je n'ai pas joint les fichiers au ticket pour des questions de confidentialité, mais ils sont bien dans mes mails) :_ 

Comme évoqué hier, je t'envoie les 2 formats ACTREP que l'ont doit remplir.

**FRA_ACTREP_WW-01_JDP_2023_MODELE**
On transmet ce fichier quotidiennement.
Il ne concerne que les contrôles au débarquement, ou à la mer dans le cas d'un moyen sous JDP, et dans lesquelles on retrouve au moins une espèce concerné par ce JDP (liste des espèces en PJ).

Tu trouveras dans le tableur excel plusieurs onglets (la liste des infractions avec code propre à l'ACTREP, une instruction de remplissage des champs).

J'ai laissé, à titre d'exemple un contrôle - j'ai grisé les champs qui ne sont jamais remplis par nous!

On ne peut mettre qu'une seule infraction dans ce tableau; en cas d'infraction multiples, on créé manuellement des colonnes supplémentaires - même cas pour les espèces (=>manière de faire validée par l'AECP).

Si on a une engin de pêche double (chalut jumeaux, chaluts à perche, ...), on rentre seulement le maillage le plus petit.

**ACTREP-MED-2023-01**
On transmet ce fichier mensuellement.
Il ne concerne que les contrôles au débarquement, ou à la mer dans le cas d'un moyen sous JDP, dans lesquelles on retrouve au moins une espèce concerné par ce JDP (liste des espèces en PJ).

Le format est différent de l'ACTREP WW.

N'hésitez pas à revenir vers nous si vous avez des questions (et vous en aurez surement...)

---

_Explication de Matthieu (mail du 15/10/2023 - "ACTREP")_

Nous **remplissons autant d'ACTREP que de JDP auxquels nous participons (Nord Sea, Western Waters, Med Atlant)**. Je te mets en PJ les différents modèles d'ACTREP (ils différent d'un JDP à l'autre). Les navires contrôlés au débarquement avec au moins une des espèces concernés par le JDP (liste espèces par JDP en PJ également) doivent apparaitre ainsi que tous les navires contrôlés en mer par une unité placée sous JDP.

 Nous les remplissons de manière quotidienne (plutôt en fin de journée), notamment pour le WW et la NS, l'ACTREP Med quant à lui est mensuel, mais son remplissage nous prendrait trop de temps c'est pourquoi nous le remplissons quotidiennement également. Pourrait-on envisager une extraction d'ACTREP à la demande (où l'on pourrait au choix définir des dates d'extraction)?

 Il restera le remplissage des colonnes "infractions" et "comment"(INFR1_CLASS, INFR1_CODE, INFR1_DESCRIPTION, COMMENT)  en bout de tableau. Je ne pense pas que cela puisse être automatiser car ils sont exprimés avec d'autres codes infractions que nos codes NATINF, je propose donc que cela reste au remplissage manuel du superviseur pour ces colonnes mais que si possible une croix "X" y soit intégrer lorsqu'il y a une infraction. Cela permettrait en un coup d'œil de faire ressortir les navires sur lesquels le superviseur doit apporter une modification manuelle.

**Comment by louptheron** [comment]
@AdelineCelier Je propose de me mettre sur cette feature, elle est assez demandée en salle.
Cela peut être un bouton "Export" en dessous du bouton des avaries (sur la gauche de la carto) qui ouvre une modale de choix des dates. wdyt ?

**Comment by AdelineCelier** [comment]
Hello,
J'aurais plutôt mis ce bouton dans la vue liste des missions, étant donné que ce sont les données des missions qu'on va extraire. 
Qui ouvre en effet une modale, un peu sur le modèle de l'extraction de situs VMS. Je peux essayer de regarder cette semaine où placer le bouton. 
Dans la modale, il faudrait pouvoir choisir les dates, mais peut-être aussi le modèle -> cf. la description du ticket, il semblerait qu'il y ait plusieurs formats d'act-rep.

**Comment by louptheron** [comment]
Testé sur la mission (contrôle en mer) : 
```
24 sept. 23, 16:00
25 sept. 23, 00:00
Mer
CNSP
ULAM 34/30 (DDTM)
BUCKIE
```

**Comment by louptheron** [comment]
Après vérification en production, lorsqu'une mission est introuvable (cas qui peut se présenter quand un contrôle est lié à une mission `deleted`), il n'y a aucun contrôle de renvoyé.
Il faut donc permettre de seulement logger ce souci, sans casser l'export.
