### ISSUE TITLE
Missions – Ajout des points de contrôle (coordonnées et ports)

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#1780]
**Pour les contrôles en mer et les contrôles aériens**
- [x] Ajout des points de contrôle en tapant des coordonnées ou en cliquant sur la carte. Comme vu ensemble j'ai un peu retravaillé la tête du composant "coordonnées" (+ long et avec l'unité dans la barre) et l'organisation de la petite fenêtre.
Ecrans [20](https://xd.adobe.com/view/0eacf501-00f4-496b-bf08-4e9ca7985909-5bff/screen/84770002-6772-47d5-b9c9-d328260a1223) et [21](https://xd.adobe.com/view/0eacf501-00f4-496b-bf08-4e9ca7985909-5bff/screen/4ebaaf22-e431-4ec3-b498-9d14be4ca3f7).

**Pour les contrôles à la débarque**
- [x] Choix d'un port dans un menu déroulant. Trier les ports par ordre alphabétique. Il faut pouvoir rechercher les ports au clavier. 
Ecrans [31](https://xd.adobe.com/view/0eacf501-00f4-496b-bf08-4e9ca7985909-5bff/screen/4fc40696-4eaf-40c6-8dbd-d9c14701176c) et [32](https://xd.adobe.com/view/0eacf501-00f4-496b-bf08-4e9ca7985909-5bff/screen/d6eb9647-8e11-4430-8bf4-8314f9a314a6)

**BONUS UI**
Harmoniser les dimensions de la petite fenêtre pour l'ajout des zones de missions avec celle pour l'ajout des points de contrôle :  j'ai juste revu la taille du bandeau Charcoal pour l'aligner sur le système des multiples de 8, elle fait 48 px de haut maintenant. Et le bouton "quitter" est un small icon button donc il fait 24 px de haut. (les écrans sont à jour normalement)

**Reste à faire**

- [x] Ajouter un point de contrôle en cliquant sur la carte
- [x] Ajouter un point de contrôle en rentrant les coordonnées dans l'input (`CoordinatesInput`)
- [x] Modifier la position du contrôle quand on change la valeur du `CoordinatesInput` dans le formulaire du contrôle
- [x] #2352
    - Nécessite de changer l'input dans `monitor-ui`, il semblerait que la `defaultValue` ne change pas bien sa valeur interne.
    - Attention, il faut bien `transform()` les coordonnées dans le bon référentiel avant de rentrer les valeurs dans `defaultValue`, voir ci-dessous.
- [x] Lors de la modification d'un point de contrôle, remplacer le point précédent avec le nouveau point
   - Nécessite de changer le fonctionnement du hook `useGetMissionsWithActions` pour mettre à jour le cache avec la nouvelle valeur)
- [ ] Ajouter des test Cypress
  - Non prioritaire 

----

Code pour récupérer et injecter les coordonnées dans la `defaultValue` (non-prioritaire) :
```
const coordinates = useMemo(() => {
    if (feature?.getGeometry()?.getType() !== OpenLayersGeometryType.POINT) {
      return undefined
    }

    const featureCoordinates = (feature?.getGeometry() as Point).getCoordinates()

    return transform(featureCoordinates, OPENLAYERS_PROJECTION, WSG84_PROJECTION) as Coordinates
  }, [feature])
```

**Comment by louptheron** [comment]
@ivangabriele L'API pour les ports est disponible ici : `/bff/v1/ports`

**Comment by AdelineCelier** [comment]
**Reste à faire**

- [x] Ajouter un point de contrôle en cliquant sur la carte
- [x] Ajouter un point de contrôle en rentrant les coordonnées dans l'input (`CoordinatesInput`)
- [ ] Afficher les coordonnées du contrôle dans l'input (`CoordinatesInput`) après un clic (non-prioritaire)
    - Nécessite de changer l'input dans `monitor-ui`, il semblerait que la `defaultValue` ne change pas bien sa valeur interne.
    - Attention, il faut bien `transform()` les coordonnées dans le bon référentiel avant de rentrer les valeurs dans `defaultValue`, voir ci-dessous.
- [ ] Lors de la modification d'un point de contrôle, remplacer le point précédent avec le nouveau point
   - Nécessite de changer le fonctionnement du hook `useGetMissionsWithActions` pour mettre à jour le cache avec la nouvelle valeur)
- [ ] Ajouter des test Cypress



----

Code pour récupérer et injecter les coordonnées dans la `defaultValue` (non-prioritaire) :
```
const coordinates = useMemo(() => {
    if (feature?.getGeometry()?.getType() !== OpenLayersGeometryType.POINT) {
      return undefined
    }

    const featureCoordinates = (feature?.getGeometry() as Point).getCoordinates()

    return transform(featureCoordinates, OPENLAYERS_PROJECTION, WSG84_PROJECTION) as Coordinates
  }, [feature])
```
