### ISSUE TITLE
Missions – Revue du formulaire (champs mission - colonne 1)

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#1782]
**RETOURS UX**

- [x] Le menu déroulant "ressource 1" doit s'appeler "moyen 1" 👍🏻 
- [x] Permettre de rechercher au clavier dans les menus déroulants des administrations et unités 👍🏻 
- [x] Dégriser le champ "unité" : on doit pouvoir saisir indifféremment l'administration ou l'unité en premier – c'est un retour d'xp côté CACEM, parfois les utilisateurs ne connaissent pas l'admin. de l'unité, donc veulent pouvoir chercher direct dans le menu unité. 👍🏻 
- [x] Il faut que le champ "contact" se dégrise à partir du moment où on a saisi une unité, pas besoin d'avoir saisi un moyen 👍🏻 
- [x] Retirer les champs "objectifs du vol" et "segment ciblé" de la colonne 1 dans le cas d'une mission air => on les a basculé dans l'action de surveillance aérienne (dans la colonne 3) 👍🏻 
- [x] Il y a un "undefined" à retirer dans le bouton "valider" lors de la création/l'édition d'une zone de mission sur la carte 👍🏻 

**RETOURS UI**

- [x] Le bandeau en haut de la fenêtre me semble trop grand. J'ai retouché les écrans, il fait 80 px de haut. 👍🏻 
- [x] Ne pas ancrer "Informations générales", cela doit défiler au scroll avec le reste de la colonne 👍🏻 
- [x] La marge gauche au sein de la colonne doit faire 40 px. 👍🏻 
- [x] Concernant la longueur des champs, j'ai étudié ta proposition Ivan, et je crois que je resterais sur mes écrans ;) je trouve ça plus aéré avec des champs plus courts, qui ne font pas toute la largeur de la colonne. Je les mettrais donc en 384 px de long (ils font 380 sur mes maquettes, mais 384 est un multiple de 8). 👍🏻 
- [x] Dans la même logique que ci-dessus, le bouton "ajouter une zone de mission" doit s'adapter à la longueur des champs (384 px donc), et non aux icônes "éditer" et "supprimer" de la zone de mission 👍🏻 
- [x] Ne pas mettre d'icône de suppression face au champ "administration" de la première unité 👍🏻 
- [ ] Le bouton "ajouter une autre unité" est un small button (il doit donc faire 24 px de haut) et doit faire 161px de long ; il ne s'adapte pas à la longueur des autres champs. **=> ok pour le fait qu'il ne s'adapte pas à la longueur des autres champs**
- [x] Le bouton "centrer sur la carte" du polygone de la zone de mission doit être par défaut en Slate Gray 👍🏻 
- [ ] [Ce point vaut pour tous les boutons du formulaire] Il y a un pb de centrage du texte dans les secondary buttons, le texte apparaît trop haut (cf. capture ci-dessous). Je mets ce point ici et pas dans Monitor UI parce que je n'ai pas l'impression que ça le fasse dans le Storybook. 

![image](https://user-images.githubusercontent.com/71878648/222222687-602a8f0f-0f3d-4ae1-9bd8-4ccead3f5085.png)

**Comment by AdelineCelier** [comment]
@ivangabriele tout ce que tu as coché est bon pour moi ! 
Est-ce que les deux qui restent sont des tickets à ouvrir dans Monitor UI ?

**Comment by ivangabriele** [comment]
@AdelineCelier Je note ici ce qu'on s'est dit :

- Le centrage du texte en hauteur est un sujet global monitor-ui/env/fish sur les conflits CSS à avoir (devs) ensemble. On a djà abordé le sujet durant notre journée technique.
- Il faudra qu'on fasse une passe globale sur monitor-ui avec toi Adeline pour revoir tous les composants de base ensemble, leurs variations, leurs états dans monitor-ui. C'est à mon avis majoritairement live-codable.

**Comment by ivangabriele** [comment]
@AdelineCelier Editer une nouvelle mission (à partir de la map) alors que le formulaire est déjà ouvert > Load infini

**Comment by AdelineCelier** [comment]
@ivangabriele les admin et unités historiques apparaissent toujours dans les menus déroulants des admin et unités.

**Comment by ivangabriele** [comment]
@AdelineCelier @louptheron Je prends ce ticket.

**Comment by ivangabriele** [comment]
@AdelineCelier On peut passer les deux derniers points CSS dans un autre ticket plus global sur lequel on parlera de la passe sur monitor-ui (boutons, inputs & icones) ? On a eu un sujet similaire avec @claire2212 hier aussi.

**Comment by AdelineCelier** [comment]
@ivangabriele oui on peut faire ça ! On pourra voir ce ticket une fois que les retours sur les missions seront bouclés. 
Je passe ce ticket, les unités historiques ont bien été retirées.
