### ISSUE TITLE
Missions – Revue du formulaire (actions de contrôle - colonne 2)

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#1783]
### **RETOURS UX**

- [x] Les cartes ne se mettent pas à jour quand un navire est renseigné dans le formulaire, ou quand le nb de pistes est renseigné dans les surveillances aériennes. NB : pour la typo, le nom du navire et le nb de pistes survolées doit être en Bold, le reste en Medium (cf. écrans)
- [x] Tags appréhension sur les cartes d'actions de contrôle : lorsque sont cochés dans le formulaire les champs "appréhension engin", "appréhension espèce" ou "appréhension navire", il faut afficher les tags correspondants sur la carte, avec une pastille rouge. Cette info étant importante, on peut mettre ces tags en 1er dans la carte. 👍🏻 
- [x] Tags NATINF sur les cartes d'actions de contrôle : j'ai rectifié les écrans, je pense que c'est plus judicieux de regrouper les n° de NATINF dans un seul tag s'il y en a plusieurs. Cela évite de répéter "NATINF" ce qui prend de la place pour rien. Cf. écrans [27](https://xd.adobe.com/view/0eacf501-00f4-496b-bf08-4e9ca7985909-5bff/screen/0df79652-90da-4d4b-95c2-cbf94dfcfc82) et [28](https://xd.adobe.com/view/0eacf501-00f4-496b-bf08-4e9ca7985909-5bff/screen/2670af42-0209-4624-ac3d-7b00ed514ae3). 👍🏻 

### **RETOURS UI**

- [x] Les cartes des actions doivent faire par défaut 52 px de haut, avant que des tags n'y soient rajoutés selon le contenu des formulaires remplis dans la colonne 3 👍🏻 
- [x] Fonds colorés des cartes : les actions de contrôle doivent être sur fond blanc, les actions de surveillance sur fond Gainsboro et les notes libres sur fond Blue Yonder 25% 👍🏻

**Comment by ivangabriele** [comment]
@AdelineCelier 

> Les cartes ne se mettent pas à jour quand un navire est renseigné dans le formulaire, ou quand le nb de pistes est renseigné dans les surveillances aériennes. NB : pour la typo, le nom du navire et le nb de pistes survolées doit être en Bold, le reste en Medium (cf. écrans)

J'ai corrigé le bold mais je n'arrive pas à reproduire le bug qui ne mettrait pas à jour le titre de la carte lorsqu'on met à jour le nombre de pistes ou le nom du navire.

**Comment by AdelineCelier** [comment]
Hey @ivangabriele  ! 
Ah étrange pour le premier point...il faudra qu'on reteste en intégration. Tu es encore en local pour l'instant n'est-ce pas ?

Haha oui go pour 56 ;)

**Comment by AdelineCelier** [comment]
@ivangabriele 
- c'est bon pour le Bold, faut juste mettre les infos "Contrôle en mer – [Nom du navire]" en GunMetal une fois que le navire est renseigné ou que le nb de pistes est indiqué (pardon je crois que je ne l'avais pas spécifié la 1ère fois)
- En ce qui concerne la mise à jour du titre de la carte, ça fonctionne pour les contrôles en mer (nom du navire) et pour la surveillance aérienne (nb de pistes survolées), mais pas pour les contrôles débarque et pour les contrôles aériens : quand je renseigne un navire dans la colonne 3, son nom n'apparaît pas dans la carte

![image](https://user-images.githubusercontent.com/71878648/230593903-2a1e340b-457c-4d2a-954a-c40a066bce11.png)

**Comment by AdelineCelier** [comment]
Ok pour moi
