### ISSUE TITLE
Missions – Revue du formulaire (contrôles mer & débarque - colonne 3)

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#1784]
### **CONTRÔLES EN MER**

**Retours UX**

- [x] Coche "navire inconnu" : si cette case est cochée, il faut griser la barre de recherche (on ne peut pas avoir à la fois un navire dans la barre de recherche et la case cochée).
- [x] Coche "maillage non mesuré" : idem, si cette case est cochée, cela doit effacer et griser le champ "maillage mesuré"
- [x] Encart infraction : il manque le champ "engin contrôlé : oui / non". Les radio buttons doivent être désélectionnés par défaut. Ils contrôlent les champs suivants "maillage déclaré/mesuré/non mesuré" : si rien rempli ou si "non" coché, les champs sont grisés. Si "oui" coché, les champs s'activent. Cf. écran [18](https://xd.adobe.com/view/0eacf501-00f4-496b-bf08-4e9ca7985909-5bff/screen/dca24cda-1765-4339-9b91-1fda7ea748be)
- [x] Sur les cartes d'infraction, les tags "appréhension" doivent apparaître si les cases "appréhension engin" ou appréhension espèce" sont cochées dans l'infraction. 👍🏻 
- [x] Encart "Espèces à bord" : les champs "Poids des espèces vérifié", "Taille des espèces vérifié" et "Arrimage séparé..." ne sont pas conditionnés à l'ajout d'espèces. Dans le déroulé du CR de contrôle, il faut que l'utilisateur au CNSP puisse cocher ces cases avant d'ajouter les espèces 👍🏻 
- [x] Il manque le nom des espèces sélectionnées dans le tag, à la place le trigramme est répété 2 fois. 👍🏻 
- [ ] Si possible, il ne faudrait pas prendre en compte les accents dans la recherche des NATINF : aujourd'hui, si je tape "débarquement" et "debarquement", cela ne remonte pas les mêmes résultats. 

**Retours UI**

- [x] Les cartes d'infraction me semblent trop hautes. Cf. marges sur Xd et sur capture ci-dessous **[CAPTURE]** 👍🏻 
- [ ] Les champs libres d'observations doivent faire 48 px par défaut de haut (mea culpa si ce n'est pas partout le cas sur les écrans). Ils s'adaptent aux commentaires saisis (bien que je doute qu'ils écrivent souvent des romans).
- [ ] Idem pour les champs libres "[Engin] Autres mesures et dispositifs", 48 px de haut par défaut. 
- [x] Les champs "maillage déclaré" et "maillage mesuré" sont trop longs, ils doivent faire 112 px de long. 👍🏻 
- [x] Idem pour les champs "Quantité estimée" et "Quantité déclarée", 112 px de long. 👍🏻 
- [ ] Encart "Espèces à bord" : ne pas faire de sections comme pour les engins. Il y a potentiellement beaucoup d'espèces à renseigner, cela ferait un formulaire trop long. Reprendre l'espacement des écrans XD. 
- [ ] Le filet qui sépare "autres observations" de "segments de flotte" doit faire 2 px (il me semble n'en faire qu'1) et être en Slate Gray (j'ai l'impression qu'il est plus foncé, mais peut-être me trompe-je)
- [ ] La phrase d'explication sur l'ajout des segments de flotte doit être en Slate Gray
- [ ] Zones de la marée pour les segments de flotte : si le navire n'a pas fait de FAR, les zones de marée seront déterminées par la position du contrôle => le libellé doit être "Zones de la marée (issues du lieu de contrôle). Cela fonctionne autant quand le calcul du segment est automatique que quand l'ajout du segment se fait manuellement via le menu déroulant : dans les deux cas il faut récupérer la zone de marée depuis la position du contrôle.
- [ ] Le champ "Saisi par" à la fin du formulaire doit faire 120 px de long. 

### **CONTRÔLES À LA DÉBARQUE**

**Retours UX**

- [x] Dans l'encart sur les espèces, il faut remplacer le libellé du champ "Quantités estimées" par "Quantités pesées" 👍🏻 
- [x] Pour les contrôles débarque, l'encart "Appréhension et déroutement du navire" doit s'appeler juste "Appréhension du navire" 👍🏻

**Comment by ivangabriele** [comment]
@AdelineCelier 

> Encart infraction : il manque le champ "engin contrôlé : oui / non". Les radio buttons doivent être désélectionnés par défaut. Ils contrôlent les champs suivants "maillage déclaré/mesuré/non mesuré" : si rien rempli ou si "non" coché, les champs sont grisés. Si "oui" coché, les champs s'activent. Cf. écran [18](https://xd.adobe.com/view/0eacf501-00f4-496b-bf08-4e9ca7985909-5bff/screen/dca24cda-1765-4339-9b91-1fda7ea748be)

Pour l'instant j'ai ajouté le champ manquant mais je me pose la question pour les champs de type booléen qui seraient indéfinis par défaut (sachant que normalement ils sont soit "TRUE" soit "FALSE" au final).

**Comment by AdelineCelier** [comment]
Tu parles des radio buttons c'est ça ?
C'est vrai que ce n'est pas tout à fait le comportement d'un radio, tu mettrais quoi toi ? 
Ca ne peut pas être des cases à cocher, et à mon sens pré-remplir un des deux radio buttons peut être source d'erreur dans le remplissage, dans le sens où l'utilisateur peut oublier de le changer. Et aussi si c'est pré-rempli tu ne peux pas mettre de check de validation (type "champ bloquant")...preneuse de tes retours sur ce point, sachant qu'on a le même cas de figure dans Env !

**Comment by AdelineCelier** [comment]
> Coche "navire inconnu" : si cette case est cochée, il faut griser la barre de recherche (on ne peut pas avoir à la fois un navire dans la barre de recherche et la case cochée).

- Dans le cas des contrôles en mer, cela fonctionne dans la colonne 3, ça efface bien le nom du navire et ça grise le champ de recherche
- Dans le cas des contrôles aériens, ça grise bien le champ de recherche mais ça n'efface pas le nom qu'on a pu saisir avant
- Dans le cas des contrôles débarque, il y a deux cases à cocher "navire inconnu", donc 1 de trop ;) Et son comportement doit être le même que dans le cas du contrôle en mer
- Dans tous les cas, la carte dans la colonne 2 doit être mise à jour non pas en disant que le contrôle est à renseigner, mais en mettant à la place du nom du navire la mention "navire inconnu".

**Comment by AdelineCelier** [comment]
Ticket #1886 qui reprend les retours UI d'ici.
