### ISSUE TITLE
L'en-tête des contrôles est parfois tronqué quand le nom de port est long

### ISSUE THREAD

**Issue by VincentAntoine** [MTES-MCT/monitorfish#1788]
Retour utilisateur suite à la MEP du redesign des contrôles dans la VesselSidebar, un utilisateur s'est plaint qu'on ne voit pas la date du contrôle dans ce genre de cas (le nom du port est long) :

![image](https://user-images.githubusercontent.com/27647971/222216394-03c19e93-35d8-488b-9dcc-e281a53f5233.png)

@AdelineCelier j'ai dit que c'était visible en entier au survol, mais si c'est fréquent il faut peut-être le repenser, à creuser.

**Comment by AdelineCelier** [comment]
Ah c'est un retour intéressant, je pense en effet qu'ils ont besoin de voir la date du contrôle rapidement (vu que j'ai l'impression que c'est le seul check qu'ils font systématiquement sur les navires à contrôler 😬).
Je n'avais pas compris que cette partie-là était déjà en prod, je ne l'ai absolument pas revue avant...je vais aller regarder du coup, et chercher s'il arrive souvent que le nom du port soit long. 

@VincentAntoine est-ce que c'est normal pour toi que le nom du port soit plus ou moins répété entre parenthèses ? Est-ce qu'il y a un potentiel de "nettoyabilité" du référentiel des ports ou ce n'est pas tant le problème ?

**Comment by VincentAntoine** [comment]
> @VincentAntoine est-ce que c'est normal pour toi que le nom du port soit plus ou moins répété entre parenthèses ? Est-ce qu'il y a un potentiel de "nettoyabilité" du référentiel des ports ou ce n'est pas tant le problème ?

Hello, je pense que tu as vu dans la liste que je t'ai envoyée que parfois il y a un deuxième nom entre parenthèse, qui peut être une traduction ou un nom alternatif pour faciliter la recherche. Je ne pense pas qu'on puisse vraiment nettoyer.

**Comment by louptheron** [comment]
Aussi, on nous demande de remettre les codes ports, car ils l'utilisent pour remplir les ACTREP.

**Comment by AdelineCelier** [comment]
Ok donc il faut plus de place pour le nom du port et son code. 
Je propose du coup qu'on mette le titre sur 2 lignes, comme ci-dessous : 
![image](https://user-images.githubusercontent.com/71878648/223362541-51640b87-8dc3-4a21-a174-b9f69f52af1f.png)

**Comment by AdelineCelier** [comment]
C'est bon pour moi ça
