### ISSUE TITLE
UI // Onglet Pêche // Résumé JPE

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#180]
### **Titres des sections**
- mettre les titres en graisse medium 👍🏻 
- centrer le texte dans le bandeau d'en-tête (cf. capture) 👍🏻 
- revoir la taille des bandeaux : 36 px quand il n'y a qu'une seule ligne, 46 px quand il y en a 2 (cf. capture) 👍🏻 

![Taille titres onglet JPE](https://user-images.githubusercontent.com/71878648/109143260-1e121780-7760-11eb-96d8-74a792ed9220.PNG)

### **Messages résumés**
- Message DEP : 
  - "captures à bord" n'est pas à la ligne (cf. capture) 👍🏻 
  - plutôt qu'un tiret, mettre "aucune" lorsqu'il n'y a pas de capture à bord
  **=> le mettre dans le même style de police que le contenu des autres champs (Marianne 13px gris foncé #515151)** 👍🏻 
  - ~~bug sur capture à bord (pê un bug côté JPE) (cf. capture du Charles Gilberte II)~~
  **=> les espèces sont dans le XML, c'est probablement un bug côté JPE**
  - mettre des espaces entre les couples engins/maillage (regarder la maquette XD) 👍🏻 
  - refaire un point ensemble sur les dimensions des engins
- Problème de marge en bas des messages résumés (cf. capture)
**=> J'en vois encore, cf. capture mise en commentaire ci-dessous**
- Problème de virgules dans le poids des captures + dans les poids du LAN (cf. JPE du bateau "Ultime épreuve")
**=> encore des problèmes avec les virgules (toujours sur l'Ultime Epreuve, dans le LAN, cf. capture dans le commentaire ci-dessous)** 👍🏻 
- Décimales : afficher un chiffre rond, sans ",00". 👍🏻 
- Scroll : éviter l'effet "double-scroll" ? Y a-t-il besoin de mettre une barre de scroll d'ailleurs ?
**=> encore des double-scrolls présents dans plusieurs cas**
- Titre du message LAN : rajouter une virgule entre le nom du port et "prévu le..." 👍🏻 

![Espacement_message_DEP](https://user-images.githubusercontent.com/71878648/109143171-02a70c80-7760-11eb-9242-e7356773c24e.PNG)
![Message DEP](https://user-images.githubusercontent.com/71878648/109144166-2028a600-7761-11eb-8894-6baf35edf626.PNG)
![Pb virgules captures](https://user-images.githubusercontent.com/71878648/109144378-64b44180-7761-11eb-8032-acd49adff02a.PNG)
![image](https://user-images.githubusercontent.com/71878648/109156438-232b9280-7771-11eb-9f33-6c15ee217c9c.png)

### **Autres remarques**
- Si possible, rendre le refresh du JPE "transparent" pour l'utilisateur. Aujourd'hui, la fiche navire reload (apparition du loader une seconde) et se réaffiche mais en fermant les tiroirs et en remontant en haut de la fiche.  
**=> ticket #201 ouvert pour dessiner un bouton "nouvelles infos"**
- Est-ce qu'il serait possible de faire un bandeau de scroll qui n'apparaît qu'au survol/quand tu l'actives à la molette ? Et qui se juxtaposerait à l'élément à scroller, sans décaler le contenu ? A discuter ensemble 👍🏻 
- Retravail sur les contrastes : j'ai légèrement modifié les deux gris les plus clairs. Le gris moyen 2 #E0E0E0 devient #D6D6D6, et le gris clair #F0F0F0 devient #EDEDED. Ok pour le changer partout ? 👍🏻

**Comment by louptheron** [comment]
Si possible, rendre le refresh du JPE "transparent" pour l'utilisateur. Aujourd'hui, la fiche navire reload (apparition du loader une seconde) et se réaffiche mais en fermant les tiroirs et en remontant en haut de la fiche.
-> C'est compliqué de le rendre transparent (car il faut enregistrer les volets ouverts et a position du scroll). On peut peut-être rafraichir le JPE à la main ? (avec une icône du style en haut https://cdn4.iconfinder.com/data/icons/geomicons/32/672406-refresh-512.png)

Est-ce qu'il serait possible de faire un bandeau de scroll qui n'apparaît qu'au survol/quand tu l'actives à la molette ? Et qui se juxtaposerait à l'élément à scroller, sans décaler le contenu ? A discuter ensemble
-> Ce type de scroll transparent et avisible au survol est géré par MacOS, mais pas par Windows. C'est assez compliqué à faire au niveau applicatif. à discuter !

**Comment by AdelineCelier** [comment]
![image](https://user-images.githubusercontent.com/71878648/110626733-64746700-81a1-11eb-8176-b30959da003e.png)

**Comment by AdelineCelier** [comment]
Problème sur certaines listes de messages : le contenu est coupé 

![Capture](https://user-images.githubusercontent.com/71878648/110626938-a7363f00-81a1-11eb-8435-c09406dabf09.PNG)

**Comment by AdelineCelier** [comment]
Problème de "baby scroll" lorsque le contenu d'un champ n'est pas assez raccourci 

![image](https://user-images.githubusercontent.com/71878648/110628940-ea91ad00-81a3-11eb-8c7d-379f7285b55e.png)

**Comment by AdelineCelier** [comment]
Lorsque le message de capture indique "0 kg", ne pas mettre de chevron (aujourd'hui cela n'ouvre sur rien)

![image](https://user-images.githubusercontent.com/71878648/110630844-2fb6de80-81a6-11eb-857c-611ef7e40d3a.png)

**Comment by AdelineCelier** [comment]
Pb de mise en forme sur le maillage : 

![image](https://user-images.githubusercontent.com/71878648/110630973-58d76f00-81a6-11eb-8fcc-80447431de1b.png)

**Comment by AdelineCelier** [comment]
Retirer le séparateur sous le dernier tiroir "débarquement"

![image](https://user-images.githubusercontent.com/71878648/110634110-e10b4380-81a9-11eb-8c6f-16749864ffb6.png)

**Comment by AdelineCelier** [comment]
Autres détails à régler : 
- mettre le "aucune" en face du champ "captures à bord" dans le même style de police que le contenu des autres champs (Marianne 13px gris foncé #515151). Globalement je pense que tu pourrais mettre cette règle pour le contenu de tous les champs, ça sera plus clair je pense. 

- il y a encore des problèmes de marge au début et/ou à la fin d'un tiroir, ici dans un résumé de préavis ou de débarquement : 
![image](https://user-images.githubusercontent.com/71878648/112860857-81bb9780-90b4-11eb-8c94-651bce9955c5.png)
![image](https://user-images.githubusercontent.com/71878648/112860995-ab74be80-90b4-11eb-8790-c6e2f1c32f93.png)
![image](https://user-images.githubusercontent.com/71878648/112861255-ee369680-90b4-11eb-8a9f-c967ca161768.png)

- problème de décalage du titre du tiroir (ici débarquement) : 
![image](https://user-images.githubusercontent.com/71878648/112861568-32299b80-90b5-11eb-9dd5-f0b08099409e.png)

**Comment by AdelineCelier** [comment]
- mettre le "aucune" en face du champ "captures à bord" dans le même style de police que le contenu des autres champs (Marianne 13px gris foncé #515151). Globalement je pense que tu pourrais mettre cette règle pour le contenu de tous les champs, ça sera plus clair je pense.
**=> pas encore fait**
