### ISSUE TITLE
Analyse comparatif FAR/PNO/LAN avec des présentations différentes : les poids sont-ils comparables ?

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#184]

**Comment by VincentAntoine** [comment]
Hello @AdelineCelier 
J'ai fait une étude sur les données historiques, je n'ai trouvé aucun cas où la présentation est diffèrente dans les FAR et dans les PNO / LAN. Donc je ne peux pas répondre à la question "est-ce que les poids sont affichés vifs ou processés ?" sur la base des données JPE.
