### ISSUE TITLE
Fiche résumé reg : lorsqu'un champ n'est pas rempli, il disparaît systématiquement (cf. discussion avec Diane lors de la réunion nommage de la reg.)

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#186]

**Comment by AdelineCelier** [comment]
Revoir la mise en page du volet "résumé reg" lorsque tous les champs ne remontent pas (filets à supprimer + ajuster les marges) : 
![image](https://user-images.githubusercontent.com/71878648/114162531-79235680-9929-11eb-810d-e14a7873ecda.png)

**Comment by louptheron** [comment]
Réduire la hauteur mini  de la box
