### ISSUE TITLE
Missions – Retouches après revue par Céline et Célia

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#1860]
Céline et Célia ont revu les écrans pour écrire la procédure sur la saisie des missions et contrôles. 
J'ai sélectionné les points suivants qui me semblent importants à intégrer dans la V1 des missions, à discuter pour priorisation si besoin : 

- [x] Retrait des champs "intentions principales de mission : env / pêche /autre", qui ne sont finalement pas très clairs, et qui seront remplacés par le tag "ouverte par le CACEM" ou "ouverte par le CNSP" (cf. ticket #1830) @louptheron
- [x] Le champ "Mission sous JDP" est conservé et placé dans le champ "type de mission", un peu plus à l'écart (48 px) car pas tout à fait de même nature que "mer / terre /air". Il n'est plus lié au fait de cocher la case "pêche" (puisqu'on enlève cette case) et reste tout le temps cliquable.  @louptheron
- [x] Le champ "ordre de mission" serait mieux placé juste après les types de mission plutôt qu'après la localisation. Idem, il n'est plus lié au fait de cocher la case "pêche" et reste tout le temps cliquable.  @louptheron
- [ ] Concernant la localisation d'une mission pêche à terre : ce sera forcément dans un port, aussi il serait finalement plus logique que les utilisateurs puissent sélectionner un port dans une liste déroulante plutôt que de tracer une zone autour du port (mea culpa, j'aurais dû y penser plus tôt). Ce que j'imagine 
  - si le type de mission est "terre", légère modification du champ "localisation" : changement du libellé, mettre en premier le menu déroulant avec les ports, et au cas où en option garder le bouton "ajouter une zone de mission". 
  - dans la 3è colonne, dans le formulaire d'un contrôle débarque : je propose que pour l'instant on laisse visuellement tel quel, simplement que tous les contrôles débarque de la mission aient le port rempli avec celui indiqué dans la colonne 1. 

@ivangabriele je te laisse prendre connaissance de ces différents points et me dire si c'est clair, et si cela te semble envisageable à faire pour la V1. Je pense notamment à cette question des ports, cela implique peut-être de générer automatiquement une zone autour du port, afin de permettre un affichage correct dans Env comme dans Fish. Peut-être faire un point tous les 3 avec Thomas sur le sujet ?

**Comment by AdelineCelier** [comment]
@ivangabriele c'est bon pour moi côté UX.

**Comment by louptheron** [comment]
@VincentAntoine KDO

**Comment by louptheron** [comment]
Finalement, le port ne passe PLUS sur la colonne de gauche pour la V1, il reste sur la colonne de droite.

**Comment by AdelineCelier** [comment]
@louptheron @ivangabriele vu avec Céline, elle est d'accord pour reporter la question des ports dans la mission à plus tard, une fois que les différents scénarios possibles seront mieux identifiés. 
Cette question sera donc à traiter en V2.
On peut donc fermer ce ticket ? Les points restants sur les champs mission sous JDP et ordre de mission sont mentionnés dans le ticket #1782

**Comment by AdelineCelier** [comment]
@louptheron Le champ "ordre de mission" ne s'enregistre pas.

**Comment by AdelineCelier** [comment]
C'est bon pour l'enregistrement des ordres de mission.
