### ISSUE TITLE
Calcul automatique du segment de flotte dans le CR de contrôle

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#1879]
## Dans le cas d'un navire de pêche sans JPE
- L'utilisateur saisit les engins contrôlés, les espèces contrôlées et le point de contrôle (soit une lat/long, soit un port)
- Les zones de la marée sont déduites du point de contrôle (on part du principe que c'est un petit navire, et que les possibilités d'erreurs sont faibles).  Dans le cas d'un contrôle à la débarque, les zones de marée sont prises dans la colonne `fao_areas` de la table `ports` pour le port concerné.
- Le segment de flotte est calculé sur la base du tryptique engin/espèce/zone de la marée issue du point de contrôle
- Le segment n'est pas directement éditable par l'utilisateur

## Dans le cas d'un navire de pêche avec JPE
- Les engins et les espèces sont tirées du JPE pour pré-remplir le CR de contrôle
- L'utilisateur peut les éditer (en rajouter/en retirer en fonction de ce que lui dit l'unité). 
- Les zones de marées sont tirées également du JPE
- Le segment de flotte est calculé sur la base des engins/espèces saisies dans le CR + des zones de la marée issues du JPE
- Le segment n'est pas directement éditable par l'utilisateur

## Dans le cas d'un ajout manuel de segment par le CNSP
- Si l'utilisateur (plutôt Stéphane Horel) souhaite ajouter une espèce-cible, quand bien même le navire ne l'a pas (encore) pêché, il peut ajouter l'espèce en question dans le CR et indiquer "0 kg" dans la quantité déclarée. Cela ajoutera cette espèce au calcul automatique du segment.
- Cas où l'utilisateur souhaiterait ajouter une zone de marée : cela peut-il arriver ? A demander pendant les tests et à voir avec Stéphane Horel

### Notes sur les phases de développement
- Pour la mep prévue le 14 avril, les segments ne seront pas encore calculés de façon dynamique (les segments correspondants aux zones FAOs du navire contrôlé sont récupérés lors de l'ajout du navire, on a donc beaucoup de segments si une zone FAO correspond à plusieurs segments)
- Le calcul dynamique (espèce/engins/zones FAOs) sera à développer pendant que les équipes testent le module
- Dans l'idéal, il serait très pratique pour les équipes que le calcul auto. des segments s'accompagne du pré-remplissage auto. du CR avec les infos du JPE

----

### Tâches techniques
- Utiliser la colonne `fao_areas` de la table `mission_actions` (manquante dans l'entité) pour stocker les zones FAOs au lieu de les stocker dans la colonne `segments`.
- Faire une API pour chercher le segment d'un flotte à partir de la localisation, engins et espèces

**Comment by AdelineCelier** [comment]
@VincentAntoine Est-ce que tu crois que tu pourrais vérifier ce ticket en production steuplé ? J'ai peur de passer à côté de bugs que je n'aurai pas vu parce que je ne connais pas bien les segments. Par exemple est-ce que c'est normal qu'un navire ait rapidement 3 segments indiqués ?

**Comment by VincentAntoine** [comment]
Je n'ai pas pu le faire en prod à cause du problème de focus, mais en intégration ça semble bien, avec juste une différence dans le mode de calcul par rapport à ce qui est fait par la pipeline pour l'attribution des segments en live sur la carto et qui est utilisé dans la note de risques : la pipeline considère les espèces "captures accessoires" des segments, alors qu'elles ne sont pas prises en compte pour l'attribution de segments dans le CR de contrôle. Il faudrait sans doute harmoniser, dans un sens ou dans l'autre, sachant que l'EFCA n'est pas explicite sur ce point.

**Comment by VincentAntoine** [comment]
@louptheron @AdelineCelier

**Comment by AdelineCelier** [comment]
@VincentAntoine comme vu au tel ensemble, on peut dire que pour l'instant on aligne le calcul dans les CR de contrôles avec la manière dont c'est fait dans la pipeline, à savoir prendre en compte les captures accessoires. 
Qu'est-ce que tu préfères, je repasse ce ticket en todo pour cette dernière tâche, ou bien on ouvre un nouveau ticket ?
