### ISSUE TITLE
Historique de contrôle – Problème de marges dans les cartes de résumé des contrôles

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#1880]
Il y a un problème de marge droite pour les textes dans les cartes de résumé des contrôles : les textes vont jusqu'au bout alors qu'il devrait y avoir une marge de 24px. A noter que ça n'a pas l'air de le faire sur tous les navires (regarder l'Oceane III où ça le fait).

![image](https://user-images.githubusercontent.com/71878648/230336759-0db6ca01-3379-4215-89cc-c60046f998ab.png)

**Comment by Uriell29** [comment]
Hello @AdelineCelier, j'ai une petite question concernant la marge de 24px à appliquer. C'est bien 24px par rapport au composent Contrôle ? (je ne sais pas si c'est très clair, mais je parle de la zone en jaune sur la capture d'écran).

Merci :)

<img src="https://github.com/MTES-MCT/monitorfish/assets/32679370/c808adbb-4385-414f-b38c-dc6b62a72a4d" width="500">
