### ISSUE TITLE
Crash de l'application en intégration

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#1881]
FrontendErrorBoundary > Unhandled Error main.1adba3a9.js:260282:204
error TypeError: vesselProperties is undefined
    VesselCard http://monitorfish-test.csam.e2.rie.gouv.fr/static/js/main.1adba3a9.js:242239
    Xh http://monitorfish-test.csam.e2.rie.gouv.fr/static/js/main.1adba3a9.js:53625
    Wk http://monitorfish-test.csam.e2.rie.gouv.fr/static/js/main.1adba3a9.js:56718
    Vk http://monitorfish-test.csam.e2.rie.gouv.fr/static/js/main.1adba3a9.js:56412
    Uk http://monitorfish-test.csam.e2.rie.gouv.fr/static/js/main.1adba3a9.js:56406
    Jk http://monitorfish-test.csam.e2.rie.gouv.fr/static/js/main.1adba3a9.js:56392
    Ok http://monitorfish-test.csam.e2.rie.gouv.fr/static/js/main.1adba3a9.js:56115
    Hk http://monitorfish-test.csam.e2.rie.gouv.fr/static/js/main.1adba3a9.js:56052
    J http://monitorfish-test.csam.e2.rie.gouv.fr/static/js/main.1adba3a9.js:63148
    R http://monitorfish-test.csam.e2.rie.gouv.fr/static/js/main.1adba3a9.js:63179
    3095 http://monitorfish-test.csam.e2.rie.gouv.fr/static/js/main.1adba3a9.js:63191
    __webpack_require__ http://monitorfish-test.csam.e2.rie.gouv.fr/static/js/main.1adba3a9.js:67059
    2224 http://monitorfish-test.csam.e2.rie.gouv.fr/static/js/main.1adba3a9.js:63321
    __webpack_require__ http://monitorfish-test.csam.e2.rie.gouv.fr/static/js/main.1adba3a9.js:67059
    534 http://monitorfish-test.csam.e2.rie.gouv.fr/static/js/main.1adba3a9.js:50301
    __webpack_require__ http://monitorfish-test.csam.e2.rie.gouv.fr/static/js/main.1adba3a9.js:67059
    1168 http://monitorfish-test.csam.e2.rie.gouv.fr/static/js/main.1adba3a9.js:57467
    __webpack_require__ http://monitorfish-test.csam.e2.rie.gouv.fr/static/js/main.1adba3a9.js:67059
    1739 http://monitorfish-test.csam.e2.rie.gouv.fr/static/js/main.1adba3a9.js:57434
    __webpack_require__ http://monitorfish-test.csam.e2.rie.gouv.fr/static/js/main.1adba3a9.js:67059
    <anonymous> http://monitorfish-test.csam.e2.rie.gouv.fr/static/js/main.1adba3a9.js:74039
    <anonymous> http://monitorfish-test.csam.e2.rie.gouv.fr/static/js/main.1adba3a9.js:281141
    <anonymous> http://monitorfish-test.csam.e2.rie.gouv.fr/static/js/main.1adba3a9.js:281142

**Comment by AdelineCelier** [comment]
J'ai passé 3 minutes à cliquer sur tous les navires de la carte, l'écran blanc n'est pas revenu. Cela me semble bon.
