### ISSUE TITLE
Missions – Revue UI de la colonne 3

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#1886]
**_[ticket en cours de rédaction]_**

## Reprise des retours du ticket 1784

- [x] Les champs libres d'observations doivent faire 48 px par défaut de haut (mea culpa si ce n'est pas partout le cas sur les écrans). Dans l'idéal, il faudrait qu'ils s'adaptent aux commentaires saisis (bien que je doute qu'ils écrivent souvent des romans). On peut en rediscuter si le côté adaptatif des champs est relou à mettre en place.
- [x] Idem pour les champs libres "[Engin] Autres mesures et dispositifs", 48 px de haut par défaut. 
- [x] Encart "Espèces à bord" : ne pas faire de sections comme pour les engins. Il y a potentiellement beaucoup d'espèces à renseigner, cela ferait un formulaire trop long. Reprendre l'espacement des écrans XD. 
- [x] Le filet qui sépare "autres observations" de "segments de flotte" doit être en Slate Gray (j'ai l'impression qu'il est plus foncé, mais peut-être me trompe-je)
- [x] La phrase d'explication sur l'ajout des segments de flotte doit être en Slate Gray
- [ ] Zones de la marée pour les segments de flotte : si le navire n'a pas fait de FAR, les zones de marée seront déterminées par la position du contrôle => le libellé doit être "Zones de la marée (issues du lieu de contrôle). Cela fonctionne autant quand le calcul du segment est automatique que quand l'ajout du segment se fait manuellement via le menu déroulant : dans les deux cas il faut récupérer la zone de marée depuis la position du contrôle.
- [x] Je ne mettrais pas directement les champs de la section infraction en rouge, c'est un peu vénère ^^ Il faudrait que seuls les champs manquants apparaissent en rouge, au clic sur le bouton "valider l'infraction". Et pour moi la mention "[tel champ] est un champ obligatoire" n'est pas vraiment nécessaire, si on met le libellé du champ + son contour en rouge cela me semble assez explicite. 
![image](https://user-images.githubusercontent.com/71878648/231103056-4bd0e4b1-3e7e-466c-afd6-4120d0120f6b.png)
- [x] Le champ "Saisi par" à la fin du formulaire doit faire 120 px de long. 

## Nouveaux retours

- [x] Problèmes de marges entre les items de la section obligations déclaratives et engins
![image](https://user-images.githubusercontent.com/71878648/231102181-59ab68af-7d44-433a-aebd-551067e0657c.png)
![image](https://user-images.githubusercontent.com/71878648/231101078-2bb3daad-8299-4ac6-9900-13dbaaa3fa8c.png)

- [x] Problèmes de marges entre les items de la section espèces
![image](https://user-images.githubusercontent.com/71878648/231102211-7e39b9d7-c0d6-4548-8d5b-8caeb5da08cb.png)

- [x] Problèmes de marges entre les items de toutes les sections "infraction" (sachant que pour moi les commentaires en rouge sous les champs pourraient sauter, cf. mon commentaire ci-dessus).
![image](https://user-images.githubusercontent.com/71878648/231103991-a128f883-ef9b-4999-b9a3-d921ced2860d.png)

**Comment by AdelineCelier** [comment]
On y est presque ! Il me reste deux petits points : 

- [ ] l'agrandissement des champs libre se fait de façon horizontale et non verticale
![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/1bfa49b8-003e-46ca-b4fe-13b629e0f0a8)

- [ ] les petits traits dans le coin en bas à droite du champ libre sont pour moi en Light Gray et non Slate Gray

- [ ] dans une surveillance aérienne, il manque un espace de 8px dans la section "qualité du contrôle"
![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/a3e45c7f-c670-42cf-9d0b-881fa2e01fb4)

**Comment by ivangabriele** [comment]
>     * [ ]  les petits traits dans le coin en bas à droite du champ libre sont pour moi en Light Gray et non Slate Gray

@AdelineCelier Si tu parles bien de changer la couleur des 4 petits traits de l'icône de "resize" du champ de texte, ce n'est pas si facile que ça à modifier. Il y a peut-être moyen de faire ça en créant une icône qui remplace celle du navigateur.

**Comment by AdelineCelier** [comment]
@ivangabriele mmh je ne crois pas que ce soit fait côté Env. Si c'est compliqué aucun pb on laisse comme ça ! Ca a le mérite d'être plus lisible qu'en Light Gray ;)
