### ISSUE TITLE
Rajouter les fonds de carte

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#190]
- Fonds de carte Mapbox : 👍🏻 
  - light (customisé) 👍🏻 
  - dark 👍🏻 
  - satellite 👍🏻 
- Fonds de carte SHOM 
  - fonds marins 👍🏻 
  - isobathes

**Comment by louptheron** [comment]
@AdelineCelier Je t'assigne à ce ticket avant que j'y passe, non ?

**Comment by AdelineCelier** [comment]
Pour ce qui est du dessin des écrans, c'est fait (cf. ci-dessous). Et pour le fond de carte custom je pense que je le ferai quand je ferai la refonte UI non ? Pour l'instant je n'ai pas encore fixé les couleurs de l'interface... Peut-être peux-tu ajouter les fonds de carte "standard" de Mapbox aujourd'hui, et on verra pour le custom plus tard ?
D'ailleurs, est-ce qu'on remplacerait OSM par le fond light de Mapbox ?

![image](https://user-images.githubusercontent.com/71878648/109640426-c1906d00-7b50-11eb-99c6-206683483e97.png)

**Comment by AdelineCelier** [comment]
Il manque encore les couches de bathymétrie, j'ai créé un nouveau ticket (#400).
Pour le nom de la couche SHOM, on pourrait plutôt mettre : Carte marine (SHOM)
