### ISSUE TITLE
Zones admin – Certaines zones ne se masquent pas

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#1908]
Au démarrage de l'app, certaines zones admin sont affichées (ici les FAO et les rectangles stats), et impossible de les masquer. 
Les autres zones admin. fonctionnent correctement.

![image](https://user-images.githubusercontent.com/71878648/231987348-6d932166-1f09-4aa0-ba12-0967e5d25f20.png)

**Comment by louptheron** [comment]
Je ferme, le bug n'apparait plus
