### ISSUE TITLE
BUG: Quand il n'y a pas de DEP de trouvé, remonter les positions depuis X heures

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#191]

**Comment by AdelineCelier** [comment]
@louptheron à combien de temps remontes-tu du coup quand il n'y a pas de DEP ?

**Comment by louptheron** [comment]
@AdelineCelier Je remonte de 24h

**Comment by AdelineCelier** [comment]
Rajouter une alerte jaune qui dit : "Nous n'avons pas trouvé de message DEP pour ce navire, sa piste est affichée sur les dernières 24h"

**Comment by AdelineCelier** [comment]
Rajouter 1/2 secondes dans le timing des alertes et autres messages temporaires
