### ISSUE TITLE
Missions – Bug lorsqu'on veut éditer une mission à partir de la carto et qu'une autre mission est déjà ouverte dans la side window

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#1924]
...quand on fait ça, il y a un load infini sur le formulaire et la mission qui a perdu son nom ("mission undefined")

**Comment by louptheron** [comment]
Je propose de suivre le même principe sur sur Env : https://github.com/MTES-MCT/monitorenv/pull/412

Cela nous permettrad'éviter également les soucis :
- https://github.com/MTES-MCT/monitorenv/issues/178
- https://github.com/MTES-MCT/monitorenv/issues/347

**Comment by AdelineCelier** [comment]
@louptheron Oui ça me semble bien d'appliquer la même logique aux deux apps.
