### ISSUE TITLE
[Missions] La recherche et les filtres des missions sont beugés

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#1943]
Plusieurs soucis :
- Elle n'affiche pas ce qui est recherché
- Quand on enlève les termes de la barre de recherche, toutes mes missions ne sont pas affichées
- Si il y a des filtres d'activé (ex. Administration à "DDTM"), la recherche outrepasse les filtres

**Comment by AdelineCelier** [comment]
Les problèmes sont résolus !
