### ISSUE TITLE
[Missions] pour filtrer les facades dans la liste des missions, utiliser les facade non-groupées

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#1948]
Car Env utilise celles-ci dans le back
i.e utiliser `Guadeloupe` plutôt que `OUTREMEROA`

**Comment by AdelineCelier** [comment]
@louptheron et donc vous les regroupez ensuite dans le front pour les faire rentrer dans les onglets du menu des façades "outre-mer OA" et "outre-mer OI", ou bien il faudrait changer le menu ?

**Comment by louptheron** [comment]
On regroupe ensuite dans le front oui !
