### ISSUE TITLE
[Missions] Filtrer les unités quand on sélectionne une administration

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#1960]

**Comment by AdelineCelier** [comment]
Petit problème encore sur le lien entre le filtre administration et le filtre unité : quand on supprimer un filtre d'administration, il faut que cela supprime aussi les filtres unités liés à cette administration (cf. ce que je t'ai montré en live pendant notre visio).

**Comment by AdelineCelier** [comment]
@ivangabriele comme vu ensemble au tel, on part sur le comportement de filtre identique à Env : quand on retire une administration (en la décochant ou en supprimant son tag), cela retire aussi les unités de cette administration qui étaient cochées. On n'attend pas l'ajout d'une nouvelle administration.

**Comment by AdelineCelier** [comment]
good pour moi !
