### ISSUE TITLE
[Missions] Saisie de contrôles sur un navire inconnu

### ISSUE THREAD

**Issue by VincentAntoine** [MTES-MCT/monitorfish#1964]
- [x] Data : créer un navire "Navire inconnu" dans `vessels` -> par exemple avec `id=-1`
- [x] Front : remettre la checkbox "navire inconnu" et attribuer le contrôle au navire inconnu de `vessels`

**Comment by AdelineCelier** [comment]
Trois points visibles : 
- si un navire a été renseigné avant de cocher "navire inconnu", il faudrait que son nom s'efface
- le statut d'erreur ne disparaît plus quand on on renseigne un navire ou qu'on coche la case, il faut faire une autre action sur le formulaire pour qu'il disparaisse
- la phrase d'erreur n'est pas au bon endroit, il faut la mettre sous la barre de recherche, avec 8px de marge
