### ISSUE TITLE
Missions – Il y a toujours des unités historiques dans le formulaire de mission

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#2003]
Cf. dans les unités de l'admin "DDTM", il y a des unités avec un "(historique)". Mais surtout il y a des unités qui ne sont pas marquées comme "historique" dans la liste, et pourtant elles ne sont pas censées être dans le nouveau référentiel (ex. Ecureil [sic]).

**Comment by ivangabriele** [comment]
Vu ensemble, ce qui devrait être fixé en staging est l'affichage des "... (historique)" dans les unités qui ne devrait plus apparaître.

Par contre, concernant les unités qui ne devraient pas être dans le nouveau référentiel comme "Ecureil", le problème vient des données côté Env qui n'indique pas ces unités comme `isArchived`.

**Comment by AdelineCelier** [comment]
Ok merci. @claire2212 ou @thoomasbro il semblerait en effet que d'anciennes unités apparaissent encore dans la liste, alors qu'elles ne font pas partie de la liste que Roxane avait établi. Vous avez une idée d'où ça peut venir ?

**Comment by AdelineCelier** [comment]
@claire2212 @thoomasbro @ivangabriele 
Alors mea culpa sur ce ticket, il semblerait que je n'aie pas regardé une version assez récente de la liste des unités de Roxane. En ouvrant une version plus récente, j'ai retrouvé notre Ecureil à qui on a volé un u. 

J'ai fait une vérification plus approfondie, et au final il semble n'y avoir qu'un petit problème de nommage de quelques unités de la Gendarmerie nationale, qui n'ont pas des noms très clairs. C'est donc plus une question d'hygiène de référentiel, à discuter directement avec le CACEM et le CNSP. Je me note d'aller en parler à Roxane. 

Conclusion : pas besoin de changements sur ce ticket, tout ça pourra être réglé au moment où l'on abordera le backoffice des unités. Sorry pour la fausse alerte !
