### ISSUE TITLE
Missions – Revue UI du tableau des missions

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#2020]
## Points repris du ticket #1777

- [x] quand il y a le daterange affiché pour la période spécifique, il faut que les tags des autres filtres se rangent à sa droite (cf. [écran 49](https://xd.adobe.com/view/0eacf501-00f4-496b-bf08-4e9ca7985909-5bff/screen/18574dfb-6e3d-43fc-9e23-f17eca62c8f0/)). Sinon je trouve que ça mange trop d'espace en hauteur pour des petits items.

- [x] icône à gauche du nom des statuts dans la liste : l'icône "clôturée" est un petit tick, et non une pastille. A modifier. 

- [x] Barre de recherche pour rechercher un navire dans la liste : reprendre le visuel du composant, avec le fond blanc, la loupe et le placeholder à 8 px du bord gauche du champ

**Comment by AdelineCelier** [comment]
Les points précédents sont bons ! 
J'ai juste deux petites remarques UI concernant les menus multi-select : 
- quand on sélectionne un item dans un multi-select, le champ s'agrandit en hauteur (je sais que ça fait ça sur le composant React de base), c'est très très moche haha. Côté Env j'ai l'impression que Claire a réussi à régler le pb, si ya moyen de reproduire ce serait cool 
- le menu "Type de mission" a la typo un peu tronquée, la queue du "y" est coupée ça me perturbe depuis le début 😅 s'il y a moyen d'y remédier très rapidement je suis preneuse, sinon clairement pas un point prioritaire comme vous vous en doutez. 

![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/3303b04d-23e6-452f-a8d1-74e32ee9cf9e)

**Comment by ivangabriele** [comment]
Ce n'est pas compliqué à corriger je pense. Par contre ça vaudrait le coup de passer ça dans monitor-ui, c'est dommage que ces composant n'aient pas été créés directement dans monitor-ui plutôt que dans Env, ça nous aurait permis d'éviter de dupliquer le travail.

**Comment by AdelineCelier** [comment]
D'acc. Dans ce cas on peut en effet le passer dans Monitor UI une fois qu'on aura fini les derniers points bloquants ou importants pour la bascule de Poséidon vers Fish.

**Comment by AdelineCelier** [comment]
Ticket créé sur le sujet
