### ISSUE TITLE
Missions - Rajouter les espèces `by_catch` pour le calcul des segments de flottes avec `fleet_segments/compute`

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#2024]
Cf. https://github.com/MTES-MCT/monitorfish/issues/1879

**Comment by AdelineCelier** [comment]
@VincentAntoine ce ticket est passé en prod, si tu as un petit moment dans la semaine pour vérifier que tout te semble bon à ce  niveau, ce serait top ! Merci :)

**Comment by VincentAntoine** [comment]
@AdelineCelier @louptheron C'est bon!
