### ISSUE TITLE
Missions - Bug au remplissage des espèces

### ISSUE THREAD

**Issue by CNSP-Etel** [MTES-MCT/monitorfish#2035]
Après avoir rentré les 15 espèces d'un contrôle, le formulaire a freezé, et le bandeau "MonitorFish rlantit Firefox" est apparu. On est obligés de tout resaisir...
![image](https://github.com/MTES-MCT/monitorfish/assets/81374588/259bb2dd-cf6f-46ff-8fdd-5e5a9a179250)

**Comment by AdelineCelier** [comment]
C'est normalement lié au ticket #2023 , on l'a priorisé et on espère pouvoir le régler pour début de semaine prochaine.

**Comment by CNSP-Etel** [comment]
![mf bug](https://github.com/MTES-MCT/monitorfish/assets/81374588/0074293e-14dc-4d2a-b24a-f0a147bc820c)
ci-joint le bug de saisie des espèce intervenu à 14h36 le 23/05
