### ISSUE TITLE
Missions – Le tableau des missions ne s'affiche plus sur toute la largeur de la fenêtre

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#2040]
- Agrandir la colonne unités

**Comment by AdelineCelier** [comment]
C'est bon de mon côté, en revanche je teste sur un 13 pouces. 
@louptheron tu crois que tu pourrais juste aller jeter un œil en salle pour voir comment ça s'affiche de leur côté ?

**Comment by AdelineCelier** [comment]
Vu par Loup en salle : il semblerait que la largeur du tableau des missions soit plus grande maintenant en intégration, mais elle dépasse de l'écran des superviseurs et on ne peut plus cliquer sur les boutons d'édition (la dernière colonne affichée est "Contrôles")

**Comment by louptheron** [comment]
C'est bon pour la largeur, avec la petite marge qui va bien !
