### ISSUE TITLE
Missions – Ajustements sur le pré-remplissage du formulaire avec le JPE

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#2042]
En testant de façon plus approfondie la fonctionnalité, on s'est rendu compte qu'il n'y avait pas de bug (quand ça ne remonte pas c'est généralement parce que ce sont des navires de -12m, et que leurs messages sont du Visiocapture). 

En revanche j'ai noté plusieurs points gênants ou à améliorer : 
- [x] pré-remplir le maillage déclaré quand il est renseigné, cela permet de différencier deux engins identiques utilisés dans la même marée (ex. un OTB de 80 et un OTB de 100mm)
  - [x] Dans un 1er temps, récupérer le maillage déclaré dans la table `risk_factors` 
- [x] sommer les captures par espèces : aujourd'hui si un navire a fait un trait de 800kg de HKE puis un autre trait de 1000kg de HKE, l'espèce est renseignée deux fois dans le formulaire
- [x] ce serait pas mal de trier les espèces par poids décroissant dans le formulaire (comme dans le résumé du JPE), ça permettrait de voir tout de suite quelles sont les plus grosses captures de la marée

**Comment by louptheron** [comment]
Dans un 1er temps :
- Récupérer le maillage déclaré dans la table `risk_factors`

**Comment by AdelineCelier** [comment]
@louptheron est-ce que ce ticket est testable en intégration ? j'ai essayé de renseigner des navires de +12 m qui avaient des messages JPE en intégration, mais ça n'a pas prérempli le formulaire. Après peut-être que les messages JPE sont trop vieux ?

**Comment by louptheron** [comment]
Oui les messages étaient trop vieux en effet !

**Comment by AdelineCelier** [comment]
D'acc ! tu as pu voir en prod si tes fixs ont bien tous été pris en compte ?
