### ISSUE TITLE
Missions - Contrôle apparaîssant en doublon dans MF

### ISSUE THREAD

**Issue by CNSP-Etel** [MTES-MCT/monitorfish#2058]
![MF bug 2](https://github.com/MTES-MCT/monitorfish/assets/81374588/f5d786e8-376e-4786-8435-9ca8fa062ad5)
Nouveau Pb: 2 contrôles créés suite au bug de saisie des espèces

**Comment by AdelineCelier** [comment]
Bon j'ai testé de cliquer plein de fois sur le bouton "enregistrer", et ça n'a pas recréé de doublon. Je ne sais pas s'il y avait d'autres cas pouvant engendrer des doublons, donc je passe ce ticket et on le ressortira si on observe à nouveau le pb.
