### ISSUE TITLE
Missions - Prendre les engins dans les FAR plutôt que dans le DEP

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#2061]
Pour éviter les engins "parasites" et n'avoir que le ou les engins de la marée

**Comment by VincentAntoine** [comment]
Relance de MEMN car cela fausse les stats de contrôle, si les agents ne suppriment pas les engins pré-remplis dans le CR de contrôle qui n'étaient en fait pas à bord. En effet, les CR de contrôle semblent être pré-remplis avec les `gear_onboard` de `last_positions` (tu confirmes @louptheron ?), qui comportent les engins du DEP et non ceux des FAR de la marée.
