### ISSUE TITLE
Missions – Revoir la manière de renseigner les appréhensions

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#2070]
Vu avec les équipes CNSP : il peut arriver qu'une infraction **engins** entraîne une appréhension des **espèces**. Or aujourd'hui on ne peut pas indiquer une appréhension des espèces dans l'encart d'infractions engins. 

Deux solutions possibles : 
- dans chaque encart d'infraction, on doublonne et on met les deux cases "appréhension engin" et "appréhension espèces". Dans ce cas-là, il ne faut pas compter en double les appréhensions. => à voir avec Vincent si ok
- on sort la notion d'appréhension engin ou espèce de l'encart d'infraction, et on la met à côté de l'appréhension du navire. Défaut pour moi de cette solution, c'est que ça casse la linéarité de saisie des conséquences de l'infraction.

**Comment by AdelineCelier** [comment]
J'ai finalement opté pour la solution 2 : regrouper les cases d'appréhension à part, dans la même section que l'appréhension du navire, afin d'éviter les doublons qui peuvent prêter à confusion. Même si ça casse un peu le fil du rapportage, ce sera probablement plus clair comme ça. 
Il faut donc retirer les cases "appréhension engin" et "appréhension espèce" de leurs encarts d'infraction respectifs, et les redescendre dans la section dédiée. 

J'ai màj les écrans XD, attention il reste une petite différence de nommage entre [contrôle en mer](https://xd.adobe.com/view/0eacf501-00f4-496b-bf08-4e9ca7985909-5bff/screen/eb662dee-267a-4a3c-9da5-3d656246abd2/) et [contrôle à la débarque](https://xd.adobe.com/view/0eacf501-00f4-496b-bf08-4e9ca7985909-5bff/screen/4fc40696-4eaf-40c6-8dbd-d9c14701176c/).

**Comment by AdelineCelier** [comment]
Le fonctionnement me semble bon, simplement un problème UI d'espacement entre les cases : 
![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/baad30db-98f9-428d-ab92-a1b756664edf)

**Comment by ivangabriele** [comment]
> Le fonctionnement me semble bon, simplement un problème UI d'espacement entre les cases (il faut 8px entre les textes) :

Déjà fixé dans #2265 ^^.
