### ISSUE TITLE
Missions – Ergonomie : revoir l'affichage de la liste des espèces

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#2071]
Liste pas assez condensée, pas assez lisible quand il y a beaucoup d'espèces.

Proposition de remaniement de la mise en page faite par l'équipe CNSP

![Capture liste espèce](https://github.com/MTES-MCT/monitorfish/assets/71878648/3e591b17-5794-4f37-8c70-176b3d2d8c7c)

**Comment by louptheron** [comment]
Done
