### ISSUE TITLE
Missions – Le message "Une erreur est survenue" apparaît parfois dans les contrôles

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#2077]
Idem il y a eu un moment où je ne sais pas pourquoi le formulaire de contrôle ne s'affichait plus, il y avait marqué "une erreur est survenue". C'est Romain qui était à la manœuvre, il avait juste saisi des trucs dans un contrôle, je ne peux malheureusement pas te donner un contexte plus précis. On pouvait enregistrer la mission, ouvrir d'autres actions, mais quand on revenait sur ce contrôle, cela affichait toujours "une erreur est survenue".

**Comment by louptheron** [comment]
Saisie du navire + ajout du trigrame

**Comment by AdelineCelier** [comment]
J'avoue que je ne sais pas trop comment vérifier ce ticket en intégration. @louptheron @ivangabriele vous aviez réussi à reproduire ?

**Comment by AdelineCelier** [comment]
L'erreur est à nouveau apparue en intégration ce matin. 
Pour le contexte, c'était une mission déjà créée que j'étais en train d'éditer. J'ai ajouté un contrôle à la mer, renseigné le nom d'un navire, commencé à remplir le formulaire et j'étais en train de remplir je ne sais plus quel champ (plutôt en fin de formulaire), le message est apparu.

![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/d69173ff-9c12-4911-bc75-dc2926cc5d0c)
![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/6cef0a45-5f6e-47eb-ad03-7d92bb629c77)
![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/f5dfefbb-d561-47fd-bdbb-8fcaab68b949)

**Comment by AdelineCelier** [comment]
EDIT : ça m'a refait l'erreur sur le même contrôle, quand j'ai voulu valider une infraction. 

Message de la console : 
> errorInfo 
Object { componentStack: "\nInfraction@http://monitorfish-test.csam.e2.rie.gouv.fr/static/js/main.22fab621.js:276495:66\ndiv\nP@http://monitorfish-test.csam.e2.rie.gouv.fr/static/js/main.22fab621.js:64067:8\ndiv\nP@http://monitorfish-test.csam.e2.rie.gouv.fr/static/js/main.22fab621.js:64067:8\nfieldset\nP@http://monitorfish-test.csam.e2.rie.gouv.fr/static/js/main.22fab621.js:64067:8\nFieldset@http://monitorfish-test.csam.e2.rie.gouv.fr/static/js/main.22fab621.js:122840:18\nP@http://monitorfish-test.csam.e2.rie.gouv.fr/static/js/main.22fab621.js:64067:8\nFormikMultiInfractionPicker@http://monitorfish-test.csam.e2.rie.gouv.fr/static/js/main.22fab621.js:276510:154\nSpeciesField@http://monitorfish-test.csam.e2.rie.gouv.fr/static/js/main.22fab621.js:276593:241\ndiv\nP@http://monitorfish-test.csam.e2.rie.gouv.fr/static/js/main.22fab621.js:64067:8\nFormik@http://monitorfish-test.csam.e2.rie.gouv.fr/static/js/main.22fab621.js:116301:28\nSeaControlForm@http://monitorfish-test.csam.e2.rie.gouv.fr/static/js/main.22fab621.js:276616:49\nFrontendErrorBoundary@http://monitorfish-test.csam.e2.rie.gouv.fr/static/js/main.22fab621.js:276619:246\ndiv\nP@http://monitorfish-test.csam.e2.rie.gouv.fr/static/js/main.22fab621.js:64067:8\nUnmemoizedActionForm@http://monitorfish-test.csam.e2.rie.gouv.fr/static/js/main.22fab621.js:276624:88\nFrontendErrorBoundary@http://monitorfish-test.csam.e2.rie.gouv.fr/static/js/main.22fab621.js:276619:246\ndiv\nP@http://monitorfish-test.csam.e2.rie.gouv.fr/static/js/main.22fab621.js:64067:8\ndiv\nP@http://monitorfish-test.csam.e2.rie.gouv.fr/static/js/main.22fab621.js:64067:8\nMissionForm@http://monitorfish-test.csam.e2.rie.gouv.fr/static/js/main.22fab621.js:276772:265\ndiv\nP@http://monitorfish-test.csam.e2.rie.gouv.fr/static/js/main.22fab621.js:64067:8\ndiv\nP@http://monitorfish-test.csam.e2.rie.gouv.fr/static/js/main.22fab621.js:64067:8\nSideWindowWithRef@http://monitorfish-test.csam.e2.rie.gouv.fr/static/js/main.22fab621.js:276819:217\nNewWindow@http://monitorfish-test.csam.e2.rie.gouv.fr/static/js/main.22fab621.js:119422:20\nme@http://monitorfish-test.csam.e2.rie.gouv.fr/static/js/main.22fab621.js:63865:14\nSideWindowLauncher@http://monitorfish-test.csam.e2.rie.gouv.fr/static/js/main.22fab621.js:276826:64\ndiv\nP@http://monitorfish-test.csam.e2.rie.gouv.fr/static/js/main.22fab621.js:64067:8\nRoute@http://monitorfish-test.csam.e2.rie.gouv.fr/static/js/main.22fab621.js:161340:29\nSwitch@http://monitorfish-test.csam.e2.rie.gouv.fr/static/js/main.22fab621.js:161476:29\nHomePage@http://monitorfish-test.csam.e2.rie.gouv.fr/static/js/main.22fab621.js:298301:1719\nPersistGate@http://monitorfish-test.csam.e2.rie.gouv.fr/static/js/main.22fab621.js:161868:25\nProvider_Provider@http://monitorfish-test.csam.e2.rie.gouv.fr/static/js/main.22fab621.js:159804:15\nRoute@http://monitorfish-test.csam.e2.rie.gouv.fr/static/js/main.22fab621.js:161340:29\nSwitch@http://monitorfish-test.csam.e2.rie.gouv.fr/static/js/main.22fab621.js:161476:29\nRouter@http://monitorfish-test.csam.e2.rie.gouv.fr/static/js/main.22fab621.js:161053:30\nBrowserRouter@http://monitorfish-test.csam.e2.rie.gouv.fr/static/js/main.22fab621.js:161575:35\nCustomProvider@http://monitorfish-test.csam.e2.rie.gouv.fr/static/js/main.22fab621.js:84683:18\nFrontendErrorBoundary@http://monitorfish-test.csam.e2.rie.gouv.fr/static/js/main.22fab621.js:276619:246\nLe@http://monitorfish-test.csam.e2.rie.gouv.fr/static/js/main.22fab621.js:63988:31\nThemeProvider@http://monitorfish-test.csam.e2.rie.gouv.fr/static/js/main.22fab621.js:119224:18\nApp" }
[main.22fab621.js:76582:33](http://monitorfish-test.csam.e2.rie.gouv.fr/static/js/main.22fab621.js)

​

**Comment by AdelineCelier** [comment]
@ivangabriele on est d'accord qu'au final cette erreur ne concernait a priori que les NATINF, pb pour lequel tu as ouvert le ticket #2124 ?

**Comment by ivangabriele** [comment]
@AdelineCelier Oui c'est `data.comments` donc ça doit être fixé maintenant par #2124 sur le staging.

**Comment by AdelineCelier** [comment]
Ok, je passe ce ticket en done alors
