### ISSUE TITLE
Missions – Il manque le NATINF 22182

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#2083]
@VincentAntoine comment procède-t-on côté MonitorFish pour les NATINF pour l'instant ?

**Comment by louptheron** [comment]
@VincentAntoine ça ne vient pas de Poseidon ?

**Comment by AdelineCelier** [comment]
C'est Romain qui l'avait remonté sur le chat de Slack la semaine dernière. Quand on tape "22182" dans le menu déroulant des NATINF dans Fish, il n'y a rien qui remonte.

**Comment by louptheron** [comment]
Ok c'est dû au fait qu'on ne récupère seulement les natinfs de type Pêche (125 natinfs) au lieu de tous (Sécurité, Environnement et Pêche) (750 natinfs). Je peux rajouter les natinfs Sécurité, ce qui rajoute 62 natinfs.
Ok pour vous ?

**Comment by AdelineCelier** [comment]
Yes ça me semble pas mal !

**Comment by AdelineCelier** [comment]
Le NATINF 22182 est bien là.
