### ISSUE TITLE
Rechercher les JPEs par numéro de marée

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#2112]
Demande de :
- l'ULAM 14 (cf.mail E.P)
- Pôle Brexit (qui recherche dans les marée des navires)

**Comment by louptheron** [comment]
Ecran : ![Image collée à 2023-6-1 15-58](https://github.com/MTES-MCT/monitorfish/assets/14853556/a44f4d16-e0b2-4fc9-a230-5a7e83e33f85)

**Comment by louptheron** [comment]
Note: Essayer avec des navires sous FLUX (i.e BEL030912021).

**Comment by AdelineCelier** [comment]
@louptheron à première vue cela semble fonctionner sur les données de tests. Je te laisse refaire une passe un peu plus approfondie.
