### ISSUE TITLE
Missions – Coquille dans le libellé des infractions autres

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#2113]
On peut juste mettre "Autre infraction 1", "Autre infraction 2"... 
![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/745167af-ac12-410a-af3a-eece7d76cac4)

**Comment by AdelineCelier** [comment]
De mon côté je vois toujours le même titre d'infraction...ce ticket est bien passé en INT ?

![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/d9a0b7aa-c1fc-40fc-aa9c-1dde5dc73fd3)

**Comment by ivangabriele** [comment]
Ah ce n'est pas normal ça en effet, je regarderai demain matin.

**Comment by AdelineCelier** [comment]
c'est bon cette fois !
