### ISSUE TITLE
[Missions] Revoir les erreurs sur les formulaires

### ISSUE THREAD

**Issue by ivangabriele** [MTES-MCT/monitorfish#2117]
Ping @AdelineCelier 

- Afficher les erreurs de validation pour les unités de contrôle
- Corriger l'alignement visuel et l'erreur qui s'affiche même avec un navire inconnu
- Afficher un micro-bandeau en bas pour afficher la dernière erreur s'il y en a pour facilement savoir ce qui empêche d'enregistrer ?

**Comment by AdelineCelier** [comment]
@ivangabriele 
Je vais décliner un écran dans le XD pour les unités de contrôle et le navire. 
Mais grosso modo l'UI pour moi c'est ça : 
- pour les unités, juste mettre le composant en statut d'erreur (libellé rouge + encadré rouge) me semble suffisant. 
- pour le nom du navire, j'ai spécifié l'UI dans le ticket #1964 
- pour le micro-bandeau en bas, je ne sais pas s'il est nécessaire...pour moi soit tu vois direct le champ en question dans le formulaire, soit tu mets une phrase dans la colonne 2, au niveau de l'action qui a un problème (cf. [cet écran](https://xd.adobe.com/view/973ae2b4-ecd1-419f-b092-8545e0d8ce57-c269/screen/4152c4b8-c623-4e64-b191-0ae6fe117996/) que j'ai fait pour Env, en attendant que je décline côté Fish).
- en revanche on peut mettre une phrase près des boutons d'enregistrement dans le cas où il y a eu une erreur à l'enregistrement !

**Comment by AdelineCelier** [comment]
@ivangabriele 

- pour la validation sur les unités : maintenant quand on ouvre une nouvelle mission, ils sont direct en rouge. Il faudrait qu'ils ne le soient que quand on clique sur les boutons d'enregistrement
- pour la question du micro-bandeau : mea culpa, après discussion avec Thomas hier, je reviens un peu sur ce que j'ai dit, ça peut être pas mal de garder une phrase en rouge à côté des boutons d'enregistrement disant "veuillez corriger les éléments en rouge", dans le cas où les champs en erreur sont en-dessous de la ligne de flottaison...pardon pour le revirement ! 
Ex. ici, la phrase peut apparaître juste à gauche des boutons, avec 24 px de marge, toujours en Regular Italique 13 px
![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/4afa9bb7-aa05-417a-b5a6-b56d6b37aaf1)

- pour les erreurs "toast", c'est bien noté. Je pense que c'est ok pour l'instant. On pourra refaire une passe UI en effet, mais pas prio pour l'instant.

**Comment by ivangabriele** [comment]
@AdelineCelier Noté pour le passage des erreurs dans le bandeau du bas.

Normalement tu ne peux pas tester les erreurs toasts car elles n'arrivent que s'il y a soit un bug 😅 soit un problème réseau (Env est down par exemple). Il y a moyen de simuler l'erreur réseau en refusant des connections dans les outils de développement du navigateur mais c'est pas une manip facile à faire.

**Comment by ivangabriele** [comment]
Je le remets en To do pour faire un petit point sur ce ticket quand tu pourras @AdelineCelier.

**Comment by AdelineCelier** [comment]
J'ai testé en bloquant les requêtes "missions" dans l'inspecteur, j'ai bien un toast qui est apparu. 
Après je sais pas si ça couvre tous les cas mais bon, on passe le ticket non @ivangabriele ?

**Comment by AdelineCelier** [comment]
Vu avec Ivan hier : 
- on rajoute bien la petite phrase en rouge dans le bandeau du bas, dans le cas où les erreurs seraient sous la ligne de flottaison
- en ce qui concerne le choix entre une validation à la volée (qui implique d'avoir direct des champs en rouge quand on ouvre un formulaire) et une validation au clic sur "enregistrer et quitter", on laisse un peu les utilisateurs prendre en main l'outil et nous faire des retours. Une harmonisation de fonctionnement entre Fish et Env serait souhaitable à terme, à voir ensemble si techniquement aussi une solution a plus de sens que l'autre. 
=> on attend un peu de voir avant de trancher, j'ouvre donc un ticket sur le sujet que je mets dans le backlog (ticket #2324)

**Comment by ivangabriele** [comment]
Vu avec @AdelineCelier : seul le champ "Engin contrôlé : Oui / Non" est obligatoire maintenant dans les engins (en plus de l'obligation d'ajouter au moins un engin).

**Comment by AdelineCelier** [comment]
Ok pour l'ajout de la phrase en rouge dans le bandeau 
Ok pour le fait que seul le champ "engin contrôlé oui/non" est obligatoire à la clôture.
