### ISSUE TITLE
Affichage des zones reg en 3 niveaux de classification : type de reg / facade / layer_name

### ISSUE THREAD

**Issue by VincentAntoine** [MTES-MCT/monitorfish#212]

**Comment by VincentAntoine** [comment]
Rappel de la demande d' @AdelineCelier :

---
@VincentAntoine J'aurais aimé tester de rajouter un 3è niveau de classification de la reg, afin de ranger les thématiques par paquets dans la recherche reg : 
![image](https://user-images.githubusercontent.com/71878648/110635275-31cf6c00-81ab-11eb-900f-7c78fe11fdf2.png)

L'idée est tout simplement de spécifier de quelle reg on parle : 
- Reg locale (découpée par façade) : Reg locale / MEMN, Reg locale / NAMO, Reg locale / MED, etc. 
- R(UE) 1241
- R(UE) 1380 / Droits historiques
- R(UE) 494 / Merlu

Aujourd'hui il n'y a "que" ces reg-là, mais on pourra en rajouter au fur et à mesure. 
Je pense que ça pourrait aider à structurer les résultats de la recherche reg, mais c'est difficile de se projeter sans les vraies données. Et si on rajoute un champ, il faut que ça vaille le coup ! Bref, à discuter ensemble

---

@louptheron J'ai ajouté la colonne "law_type" pour le premier niveau de hiérarchie, il reste donc le front à faire.

**Comment by VincentAntoine** [comment]
@AdelineCelier est-ce que c'est normal que ce ticket soit fermé ?

**Comment by AdelineCelier** [comment]
@VincentAntoine je pense que je l'avais fermé, me disant que ces modifications faisaient partie du gros chantier sur la recherche reg n°2, pour lequel j'ai bien fait les écrans incluant cette évolution de l'affichage (cf. capture d'écran ci-dessus).
Après on peut décider d'en faire un ticket à part pour l'inclure dès maintenant.
