### ISSUE TITLE
Missions – Erreur à l'enregistrement après l'ajout d'un contrôle et d'une infraction

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#2133]
![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/1df6033f-2e6b-4e4a-8cc1-e2b109a0130c)

**Comment by ivangabriele** [comment]
Déplacé dans `Done` car l'erreur n'est pas ré-apparue en production.
