### ISSUE TITLE
Missions – Problème avec le filtre "période spécifique"

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#2154]
Le filtre ne fonctionne plus : quand on saisit des dates dans le daterange, elles ne s'affichent pas et le tableau ne se filtre pas.

**Comment by ivangabriele** [comment]
Normalement fixé par df9673a.

**Comment by AdelineCelier** [comment]
C'est bon, ça a l'air de bien fonctionner à nouveau.

**Comment by ivangabriele** [comment]
@louptheron On a besoin de re-review ça ? Tu as vu un nouveau bug ?

**Comment by louptheron** [comment]
> @louptheron On a besoin de re-review ça ? Tu as vu un nouveau bug ?

Ah non c'est bon, erreur du bot Github ^^
