### ISSUE TITLE
Erreur lors de la création d'une mission

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#2169]
a l'ouverture d'une mission depuis la carte, juste après avoir ouvert l'appli :
![Image collée à 2023-6-12 17-36](https://github.com/MTES-MCT/monitorfish/assets/14853556/624e8cb1-62a9-4745-9ad6-4806df24245d)

https://sentry.incubateur.net/organizations/betagouv/issues/44437/?query=&referrer=issue-stream&statsPeriod=14d :
```
`mainFormValues` is undefined.
```

**Comment by AdelineCelier** [comment]
Je ne vois plus d'erreur quand j'ouvre l'application, je passe ce ticket.
