### ISSUE TITLE
Navigation – La fermeture de l'onglet Monitor doit entraîner la fermeture de sa side window

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#2187]
Si c'est possible, cela éviterait des side windows "orphelines" qui peuvent être source d'erreurs.

**Comment by louptheron** [comment]
Ce n'est pas possible de ferme la side window lorsqu'on ferme l'onglet, soit :
- 1) on laisse comme maintenant (confirmation de la fermeture de l'onglet côté carto mais pas de fermeture automatique de la side window par l'application).
  - Il peut donc rester une side window "orpheline", qui n'est plus utilisable ; mais l'utilisateur a été prévenu lors de la fermeture de l'onglet.
- 2) on ferme la side window quand on ferme l'onglet carto mais on ne prévient pas l'utilisateur qu'une édition est en cours

## Raison techniques
il faut démonter tous les composants avec `unmount()` sur l'application globale pour que le composant `NewWindow` se ferme (avec la props `closeOnUnmount`).

Dans `src/index.ts` :
```
window.addEventListener("beforeunload", event => {
  root.unmount()
})
```

Conclusion : Nous optons pour la solution 1).
