### ISSUE TITLE
Augmenter le délai de déclenchement de l'alerte `FAR`

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#2189]
Il y a trop d'alertes sur la carto, sans but opérationel

Passer à 48h pour réduire le nombre d'alertes ?

**Comment by AdelineCelier** [comment]
On vient de faire un point sur le sujet avec Céline et Carole. 
Ce qui a été décidé : 
- Pour tous les cas où un seul FAR n'a pas été émis (donc sur 24h), on n'en fait plus une alerte, mais directement un signalement archivé.
  -  D'un point de vue OPS : il n'apparaîtra donc plus sur la carto, mais dans le cas où on veut prioriser entre plusieurs navires à contrôler qui n'ont pas d'éléments saillants, on pourra consulter leur historique de signalement et repérer celui qui régulièrement oublie de faire ses FAR à l'heure
  - D'un point de vue STAT : on garde la donnée, qui pourra être affichée dans Metabase et traitée par le pôle reg/planif sous la forme d'un envoi récap mensuel aux DML
- Pour les cas où 2 FAR de suite ont été oubliés (sur 48h), cela reste une alerte à traiter comme les autres alertes. A voir si c'est suffisant pour alléger la carto et permettre une meilleure vision de ce qui est "prioritaire" en temps réel.

**Comment by VincentAntoine** [comment]
Suite discussion ce jour, il faudrait aussi implémenter la liste des navires exemptés JPE dans le backoffice en même temps, sinon on risque d'archiver des signalements de `MISSING_FAR` sur des navires exemptés, chose que la validation manuelle des signalements est censée éviter.
