### ISSUE TITLE
Créer une table de catégories espèces & une colonne de tag sur les espèces

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#219]
Le plus important sont les bivalves, mais aussi si possibles les crustacés, les céphalopodes + espèces pélagiques / espèces démersales

**Comment by AdelineCelier** [comment]
Après discussion avec Diane, celle-ci pointe du doigt le fait qu'il y a peu de contrôles sur les espèces comme les bivalves et autres coquillages. Il faudrait demander confirmation aux ops, mais si c'est le cas, on pourrait imaginer ne pas renseigner de codes FAO, et laisser un champ libre dans lequel le service reg indiquerait : "bivalves fouisseurs", ou "bivalves autres que pectinidés".

**Comment by louptheron** [comment]
Rajouter une colonne espèce champ libre dans lequel le service reg indiquerait : "bivalves fouisseurs", ou "bivalves autres que pectinidés".
