### ISSUE TITLE
Zone des situation VMS

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#222]

**Comment by AdelineCelier** [comment]
Voilà la séquence d'écrans :
![image](https://user-images.githubusercontent.com/71878648/111784291-8ebdd700-88bb-11eb-9e59-8e578675bc98.png)
![image](https://user-images.githubusercontent.com/71878648/111784328-98473f00-88bb-11eb-8d65-094102989747.png)
![image](https://user-images.githubusercontent.com/71878648/111784361-a006e380-88bb-11eb-9289-b740532affd0.png)
![image](https://user-images.githubusercontent.com/71878648/111784387-a72df180-88bb-11eb-9d62-ad80ef6fa1e6.png)

@louptheron qu'en penses-tu ? cf. notamment le commentaire en vert sur le dernier écran.

**Comment by AdelineCelier** [comment]
Après discussion : 
- aller voir les ops pour clarifier les usages des différents types de zones tracées par le CNSP : lesquelles sont permanentes, lesquelles sont temporaires, qui utilise quoi ?
- redessiner le tracé libre, afin que juste le nom de la zone s'affiche sur la carto.
   - après avoir tracé la zone, l'utilisateur la nomme, directement sur la carto
   - il valide, et la zone s'enregistre dans le tiroir "Zones CNSP (tracé libre)
   - il peut supprimer quand il veut la zone depuis ce tiroir

**Comment by AdelineCelier** [comment]
**Outil pour tracer une zone avec des coordonnées**
- une troisième icône dans les filtres du tableau
- une petite fenêtre sur la carte pour rentrer des coordonnées

![image](https://user-images.githubusercontent.com/71878648/114200100-295a8480-9955-11eb-96e2-cef3405b3123.png)
![image](https://user-images.githubusercontent.com/71878648/114200190-3e371800-9955-11eb-8596-ddd3e35bc35a.png)

**Comment by louptheron** [comment]
Situ poly:
[165.23333333, 0.05000000]
-130.91666667, 2.71666667
-165.81666667, -27.30000000
-124.45000000, -25.38333333

**Comment by AdelineCelier** [comment]
Tout est ok, il reste juste ces petits points : 
- Marge à gauche des intitulés de zones : 20 px (aujourd'hui je crois que ce n'est que 10 px)
- Ordre des zones
- Pour ce volet, j'ai mis le chevron qui ouvre les zones ORGP, 1241 et situ VMS plutôt au bout à droite, pour qu'ils s'alignent avec les icônes "œil".

**Comment by louptheron** [comment]
Je ne peux que trier les zones par un ordre (alphabétique par ex) mais j'ai une liste de zone, je ne les places pas à la main...
