### ISSUE TITLE
Missions – Ajouter un trigramme de clôture du contrôle + indiquer dans la colonne 2 les contrôles clôturés

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#2247]
Retour du CNSP : 
> Avoir la possibilité de clôturer les contrôles, et avoir une icone ou un visuel indiquant que le contrôle est clos lors de l'aperçu de mission. Indication que le contrôle est complet.

Suggestion de Matthieu : rajouter un trigramme "clôturé par" en fin de formulaire, qui une fois rempli indiquerait que le contrôle est complété => ajouter un tag dans la colonne 2 (et/ou en haut de contrôle).
Ou à l'inverse montrer qu'un contrôle est en cours. 
Dans un sens ou dans l'autre, l'idée est de voir rapidement en arrivant sur une mission sur quels contrôles il manque encore des infos.

**Comment by louptheron** [comment]
Suggestion de Romain & Adrien :
Sauvegarder les modifications de trigrammes lors de la mise à jour d'un contrôle, pour savoir qui à ouvert puis modifié le contrôle (on pourra afficher seulement la 1ère saisie et la dernière).
Solution court-terme : Effacer le champ trigramme quand on modifie le contrôle pour obliger la saisie d'un trigramme.

**Comment by AdelineCelier** [comment]
Yes, mais au final pour moi il semble y avoir deux questions différentes : 
1. comment est-ce qu'on sait si un contrôle est en cpurs ou s'il est complété
2. comment est-ce qu'on sait qui est la dernière personne qui a modifié le contrôle et à quelle heure.
Les deux problèmes peuvent être traités séparément.

**Comment by AdelineCelier** [comment]
Deux choses ajoutées dans les écrans : 
- en fin de contrôle, le champ "saisi par" est remplacé par deux champs : "ouvert par" et "clôturé par", comme pour la mission. 

![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/d968c9b5-1c01-49e0-be64-84b83c7bbc50)

- tant que le champ "clôturé par" n'est pas rempli, une petite barre bleue s'affiche à gauche de la carte du contrôle dans la colonne 2. Au survol sur la barre, une infobulle "contrôle en cours" s'affiche. 

![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/297eb7ac-2227-4d00-b89f-d06b5c018655)

**Comment by AdelineCelier** [comment]
ça me semble nickel, il manque juste l'infobulle au survol de la barre disant "contrôle en cours".
