### ISSUE TITLE
Réglementation –  Problèmes dans la barre de recherche de la réglementation sur la carto

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#2251]
Il semblerait que la recherche ne tape plus sur les noms de zones ou sur ls métadonnées type "référence réglementaire". 
Il en résulte que la recherche par mots-clés est grandement diminuée. Peut-être intéressant d'identifier ce qui a provoqué cette régression, afin qu'elle ne se reproduise plus ?

**Comment by louptheron** [comment]
Pour info, la recherche ne cherchait plus dans la colonne "Références réglementaires"

**Comment by louptheron** [comment]
La recherche n'est pas trop peu restrictive ? à voir avec D.F.
(ex : 2013-7266 pour retrouver l'AP correspondant)
