### ISSUE TITLE
Missions - Ajouter automatiquement le polygone du port dans la mission quand on ajoute le port d'un contrôle à la débarque

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#2271]
Pour l'instant, il ne faut pas oublier de rajouter cette zone à la main.
Etant donné que la façade d'une mission est définie par cette zone, si le superviseur oublie de rentrer la zone du port, la mission n'est pas affichée dans l'onglet de sa façade.

**Comment by AdelineCelier** [comment]
Je dirais plutôt qu'il faudrait pouvoir sélectionner des ports en guise de zone de mission en cas de mission terre, puis que dans les contrôles, ce soient le ou les ports sélectionné(s) qui soient disponibles à la sélection comme lieux de contrôle.

**Comment by AdelineCelier** [comment]
C'est top, ça a l'air de bien marcher ! Et le toast pour confirmer la création est une bonne idée, en revanche il a des comportements un peu étranges : 
- quand j'édite la mission avec déjà un contrôle saisi, il réapparait
- quand je saisis un nouveau contrôle avec le même port, il apparait à nouveau, et en double...j'imagine que c'est parce que tu mets la zone à jour systématiquement, au cas où l'utilisateur rentre un nouveau port ? @louptheron A voir ensemble comment on peut mieux réguler son apparition ?

![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/aa566af4-e590-4a0f-8ccb-a0b0ea6b4921)

Autre questionnement (même si cela ne correspond pas à un cas d'usage vraiment identifié, c'est plus pour pousser les limites du système) : quand on décoche la case "zone de la mission calculée à partir des contrôles", cela laisse le dernier polygone saisi, est-ce qu'il ne faudrait pas que ça le supprime automatiquement ? Je n'ai pas un avis hyper tranché, mais je me suis posée la question en testant.

**Comment by louptheron** [comment]
Pour les deux premiers points, c'est normalement fixé dans https://github.com/MTES-MCT/monitorfish/pull/2381
