### ISSUE TITLE
Ouvrir le formulaire de contrôle depuis l'onglet "Contrôles" de la fiche navire pour un contrôle existant

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#2276]
- Pour voir en détail les informations du contrôles ou de la mission
- Pour modifier le contrôle depuis la fiche navire

cf. écran : https://xd.adobe.com/view/43ab72bf-f891-43f4-b51c-ca4704cb13ce-16f8/screen/8930f31f-f73b-4664-8338-b08a480e361e/specs/

**Comment by AdelineCelier** [comment]
Cela fonctionne bien, après je me pose la question de la justesse du wording qu'on avait fait à l'époque sur le bouton. Est-ce qu'il ne faudrait pas plutôt dire "ouvrir la mission du contrôle" ou bien "ouvrir le contrôle" ? Puisqu'à priori ils vont parfois juste le consulter, sans le modifier ?
@louptheron qu'en penses-tu ?

**Comment by louptheron** [comment]
On renomme en "Ouvrir le contrôle"
