### ISSUE TITLE
Affichage des contrôles dans Monitorfish

### ISSUE THREAD

**Issue by VincentAntoine** [MTES-MCT/monitorfish#233]

**Comment by VincentAntoine** [comment]
Vu avec JB, actuellement la saisie d'un contrôle demande que l'agent saisisse : 

- la façade
- l'administration (Gend. Mar., Aff. Mar., ...)
- l'unité de contrôle (menu déroulant pré-filtré avec uniquement les unités de l'administration saisie ci-dessus)
- le type de contrôle (air / mer / terre)
- ordre de mission : oui / non
- navire ciblé : oui / non
- le CNSP a été prévenu avant le contrôle : oui / non
- c'est le CNSP qui a appelé l'unité : oui / non
- la position : 
    - s'il s'agit d'un contrôle au débarquement, le port de contrôle
    - s'il s'agit d'un contrôle en mer ou aérien, latitude / longitude de la position du contrôle

-> à revoir pour éliminer / automatiser la saisie de ce qui peut l'être

**Comment by VincentAntoine** [comment]
@Adeline la liste des champs disponibles : 


    controller -> "ULAM xxx"
    controller_type -> "Maritime" ou "Terrestre" ou "Aérien"
    administration -> -> "Gendarmerie", ...
    control_type -> "Contrôle à la mer", "Contrôle à la débarque" ou "Contrôle aérien"
    control_datetime_utc -> Date et heure de contrôle
    input_start_datetime_utc -> Date et heure de création du contrôle
    input_end_datetime_utc -> Date et heure de saisie du résultat du contrôle
    facade -> "Atlantique - Manche Ouest"...
    longitude -> 45.56 (position, dans le cas d'un contrôle en mer)
    latitude -> -7.96 (position, dans le cas d'un contrôle en mer)
    port_locode -> "FRLRT" ou "Lorient" (dans le cas d'un contrôle à la débarque)
    mission_order -> oui / non : était-ce un contrôle sur ordre de mission ?
    vessel_targeted -> oui / non : le navire était-il ciblé ?
    cnsp_called_unit -> oui / non : le CNSP a-t-il appelé l'unité ?
    cooperative -> oui / non : le contrôle s'est-il passé de façon coopérative ?
    pre_control_comments -> Commentaires avant contrôle
    post_control_comments -> commentaires post contrôle
    infraction -> oui / non : le navire était-il en infraction ?

    infraction_ids -> liste des infractions constatées (voir champs suivants)
          natinf_code -> codes NATINF des infractions constatées
          regulation -> référence(s) du/des texte(s) de loi définissant les infractions constatées
          infraction_category -> "Pêche" / "Sécurité"
          infraction -> Description texte des infractions constatées

    diversion -> oui / non : y a-t-iul eu déroutement ?
    escort_to_quay -> oui / non : y a-t-il eu reconduite à quai du navire ?
    seizure -> oui / non : y a-t-il eu saisie de la pêche ?
    seizure_comments -> description texte de la saisie
    

    gear_controls -> listes des engins à bord et des contrôles d'engins (voir champs suivants)
           gear -> engin à bord
           declared_mesh -> maillage déclaré
           gear_controlled -> oui / non
           controlled_mesh -> maillage mesuré

**Comment by AdelineCelier** [comment]
@VincentAntoine sur les infos concernant les engins : 
- le champ "engin à bord", c'est bien les engins que les contrôleurs notent quand ils sont à bord ?
- "maillage déclaré" c'est quoi ? c'est le maillage qu'ils relèvent dans le JPE à bord ?
- le champ "maillage mesuré" n'est bien présent que s'il a été répondu "oui" à "gear controlled" ?

**Comment by VincentAntoine** [comment]
> @VincentAntoine sur les infos concernant les engins :
> 
> * le champ "engin à bord", c'est bien les engins que les contrôleurs notent quand ils sont à bord ?

Ce sont les engins que l'agent du CNSP renseigne dans Poséidon quand il saisit le résultat du contrôle. Je suppose que ça doit correspondre à ce qui a été noté sur le navire oui, mais à vérifier peut-être.

> * "maillage déclaré" c'est quoi ? c'est le maillage qu'ils relèvent dans le JPE à bord ?

Idem c'est renseigné manuellement par l'agent du CNSP, et je suppose que ça doit être celui déclaré dans le JPE mais à vérififier également.

> * le champ "maillage mesuré" n'est bien présent que s'il a été répondu "oui" à "gear controlled" ?

Eh bien... non. Il ya 10% de contrôles avec un maillage mesuré mais "gear_controlled" est "non". Ca n'a pas trop de sens... Par contre dans l'autre sens il doit être possible d'avoir un engin qui a été contrôlé mais sans  "maillage mesuré", pour les engins qui n'ont pas de maillage (dragues, lignes...)

> D'autre part, est-ce qu'il y a des contrôles qui étaient sur ordre de mission et pour lesquels les navires n'étaient pas ciblés ? Ou bien est-ce que l'OM entraîne systématiquement un ciblage du navire ?

| mission_order    |   Vessel not targeted |   Vessel targeted |
|:-----------------|----------------------:|------------------:|
| No mission order |                  6273 |               567 |
| Mission order    |                   664 |              1071 |

**Comment by AdelineCelier** [comment]
Les écrans sont faits, ajoutés au XD (écrans 62 à 65) : https://xd.adobe.com/view/7fb378f2-2d2b-437d-a0ef-3b7001d56c62-2ae0/

**Comment by louptheron** [comment]
Sur la chiffre déroutement etc : line-height: 14px;
Entre admin et unité : flex: 0 1 0px;
1 infractionS -> 1 infraction dans le texte du contrôle
