### ISSUE TITLE
Missions - Ajouter automatiquement la zone de la mission quand on ajoute un contrôle en mer

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#2331]

**Comment by AdelineCelier** [comment]
C'est top, ça a l'air de bien marcher ! Et le toast pour confirmer la création est une bonne idée, en revanche il a des comportements un peu étranges : 
- quand j'édite la mission avec déjà un contrôle saisi, il réapparait
- quand je saisis un nouveau contrôle avec le même port, il apparait à nouveau, et en double...j'imagine que c'est parce que tu mets la zone à jour systématiquement, au cas où l'utilisateur rentre un nouveau port ? @louptheron A voir ensemble comment on peut mieux réguler son apparition ?

Autre questionnement (même si cela ne correspond pas à un cas d'usage vraiment identifié, c'est plus pour pousser les limites du système) : quand on décoche la case "zone de la mission calculée à partir des contrôles", cela laisse le dernier polygone saisi, est-ce qu'il ne faudrait pas que ça le supprime automatiquement ? Je n'ai pas un avis hyper tranché, mais je me suis posée la question en testant. 

![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/aa566af4-e590-4a0f-8ccb-a0b0ea6b4921)
