### ISSUE TITLE
Missions – Matérialiser dans la vue liste des missions les contrôles en cours /clôturés

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#2332]
A dessiner

**Comment by AdelineCelier** [comment]
Comme vu ensemble, on fait un rappel de la barre bleue du formulaire au sein du tableau. 4px de marge à gauche, en haut et en bas de la barre au sein de la cellule du tableau + 8 px de marge entre la barre et le nombre de contrôles. 

![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/b9942f6b-494c-401d-ab98-ed9be3a142af)

**Comment by AdelineCelier** [comment]
Mmh c'est pas tout à fait les dimensions et les marges des maquettes...si c'est compliqué à faire comme sur les maquettes on ne fait pas, si c'est simple je veux bien une petite retouche 😇 
Et idem, ajouter l'infobulle "contrôle en cours" au survol sur la barre bleue (pour qu'on comprenne d'où elle sort).

**Comment by louptheron** [comment]
C'est fait comme sur les maquettes maintenant normalement (sauf qu'une ligne du tableau est plus haut que sur les maquettes j'ai l'impression).
