### ISSUE TITLE
Le maillage déclaré/mesuré pour les engins LHP lignes à main et FPO et casiers est un point bloquant lors de la clôture.

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#2337]
il faudrait rendre  le champ non bloquant.

Message de Matthieu :
"Il faudrait adapter les champs à remplir aux engins saisis, exemple:
filet: maillage déclaré/contrôlé, longueur, hauteur, emploi de pingers. etc..."

**Comment by louptheron** [comment]
@AdelineCelier En effet quand on sélectionne une Palangre, on ne devrait pas rendre le champ "maillage déclaré" obligatoire.

**Comment by AdelineCelier** [comment]
Oui le problème du champ bloquant de maillage est effectivement à retirer pour éviter d'être bloqué pour des engins sans maillage. 
Après il était effectivement prévu qu'on retravaille un peu la section "engins" pour l'adapter en fonction des engins. Mais je serais pour déjà avancer sur le brief avant de se lancer dans le détail des mesures techniques pour chaque engin dans le formulaire.
