### ISSUE TITLE
Le filtre des missions par dates ne s'applique qu'à la date de début de mission

### ISSUE THREAD

**Issue by VincentAntoine** [MTES-MCT/monitorfish#2382]
Comportement attendu : si une mission va du 1er au 15 juillet, utiliser le filtre par dates en sélectionnant la période du 10 au 20 juillet fait apparaître la mission.

Comportement observé : dans ce cas la mission n'apparaît pas. Il faut que la période sélectionnée contiennent la date de début de mission.

**Comment by AdelineCelier** [comment]
Comme c'est à faire côté Env, j'ai ouvert le ticket [680](https://github.com/MTES-MCT/monitorenv/issues/680) dans le kanban Env. Je ferme ce ticket.
