### ISSUE TITLE
Missions – Deux nouveaux champs bloquants à l'enregistrement d'une mission : contact et fin de mission

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#2400]
Vu aujourd'hui avec Céline, Matthieu, Mick et Jérem.

Champ date "fin de mission" bloquant : pour éviter les missions qui restent éternellement "en cours" sur la carto. 

Champ "contact" bloquant : pour éviter les cas où l'on a besoin de rappeler une unité qui est en mission, qu'on n'a pas leur num et qu'on doit refaire tous les numéros de l'unité.

**Comment by louptheron** [comment]
En stand-by : en attente de la conclusion de la synchronisation des missions

**Comment by louptheron** [comment]
On a réduit les champs bloquants pour la synchro des missions.
