### ISSUE TITLE
[Avaries VMS] Changement des champs de loggage des balises VMS dans Poséidon

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#2403]
En septembre 2023, il va y avoir une modification des champs relatifs aux balises VMS dans POSEIDON (voir avec Fabien F.).
Il faudrait voir avec le pôle SIP les champs à inclure ou à modifier et surtout éviter qu'une nouvelle version de POSEIDON écrase les fonctionnement actuel de gestion des Avaries VMS dans MonitorFish.

---

Ce document retrace les changements (voir les commentaires de Jérome L. pour avoir les infos techniques d'ajouts de tables/colonnes) :
[REDMINE - modification des champs du menu loggage balise-4_CNSP v5(3).odt](https://github.com/MTES-MCT/monitorfish/files/12180947/REDMINE.-.modification.des.champs.du.menu.loggage.balise-4_CNSP.v5.3.odt)

POSEIDON actuel : 
![POSEIDON LOGGAGE](https://github.com/MTES-MCT/monitorfish/assets/14853556/e598f32e-2303-4234-b053-b3e8cb1fc93e)

POSEIDON à venir :
![POSEIDON LOGGAGE NEW](https://github.com/MTES-MCT/monitorfish/assets/14853556/b772cf45-bc5c-4f4d-8ca9-71482ee802d6)

Résumé des changements par le pôle SIP :
![resum changement loggage balise](https://github.com/MTES-MCT/monitorfish/assets/14853556/94a354d4-b965-4fdd-9065-3a09aba74851)

**Comment by VincentAntoine** [comment]
Après investigation il n'y a rien à faire dans Monitorfish, les changements en base dans Poséidon n'impactent pas les flows qui récupèrent les données de balises.
