### ISSUE TITLE
Affichage résumé JPE : retirer mentions PNO dans le LAN quand il n'y a pas de PNO

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#248]
**DANS LE LAN**
- Retirer la mention "sur les -kg annoncés dans le PNO" (dans le champ "poids débarqué")
- Retirer les champs "poids PNO", et ne laisser que "Poids FAR" et "Poids LAN"

 **NB : lorsque nous aurons les espèces soumises à PNO, il faudra faire une alerte dans le JPE si le préavis est manquant**

**Comment by louptheron** [comment]
Enlever pointillés
Re-init le nom pour l'animation la longueru pour le PNO (Débarquement)
Limande sole commune trop long dans le débarquement
