### ISSUE TITLE
[Missions] Afficher un message d'avertissement quand une mission est déjà ouverte sur une unité

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#2480]
Pour éviter le doublage des missions CNSP/CACEM :
Lorsqu'on sélectionne une unité dans une nouvelle mission, afficher le message "Attention : une mission est en cours avec cette unité" quand une unité est déjà dans une mission en cours.

Pré-requis technique : Il faut connaître à l'instant T toutes les unités mobilisées (cf. https://github.com/MTES-MCT/monitorenv/issues/801).

**Comment by AdelineCelier** [comment]
Ecran [5](https://xd.adobe.com/view/0eacf501-00f4-496b-bf08-4e9ca7985909-5bff/screen/598f834e-eb2f-4155-bb63-0ab11c28655d) du XD pour l'alerte

**Comment by AdelineCelier** [comment]
## Revue en cours

**Problèmes de fonctionnement de l'avertissement**

- [ ] Il s'affiche quand on édite la mission et que la mission éditée est en cours
- [ ] Il s'affiche quand on édite la mission et que la mission éditée est terminée
- [ ] Il s'affiche quand on édite la mission et qu'une autre mission avec la même unité est terminée

**Améliorations de fonctionnement**

- Pour éviter à l'utilisateur de devoir checker à chaque fois qu'il rouvre la mission, deux options : 
   - [ ] soit permettre une fermeture manuelle (genre une croix) sur l'avertissement, que l'utilisateur peut ainsi masquer s'il a bien vérifié et qu'il n'y a pas de doublon
   - [ ] soit n'afficher le message qu'à la création de mission, mais plus aux éditions suivantes...peut-être plus facile dans un 1er temps, @louptheron qu'en penses-tu ?
- [ ] Ajouter la source (CNSP ou CACEM) de la mission déjà ouverte dans le message d'avertissement, pour que l'utilisateur sache direct si c'est un doublon inter-centre ou infra-centre : "Cette unité est actuellement sélectionnée dans une autre mission en cours ouverte par le [CACEM].". Dans le cas de plusieurs missions ouvertes, de sources différentes : "Cette unité est actuellement sélectionnée dans plusieurs autres missions en cours, ouvertes par le CACEM et le CNSP."

**Comment by louptheron** [comment]
à faire sur Fish
