### ISSUE TITLE
Préavis – Récupérer données manquantes

### ISSUE THREAD

**Issue by VincentAntoine** [MTES-MCT/monitorfish#2484]

**Comment by AdelineCelier** [comment]
@VincentAntoine je suis en train de me pencher sur cette question du poids total VS poids débarqué en reprenant le chantier préavis. 
Est-ce que tu as ouvert ce ticket suite à une demande ou remarque de la part des équipes ? Sais-tu dans quels cas ils ont besoin de différencier poids total / poids débarqué ?

**Comment by VincentAntoine** [comment]
Autre point à récupérer : les zones CGPM. Ne fait pas partie du standard ERS, mais parfois ajouté dans une balise `ERAS`

**Comment by VincentAntoine** [comment]
Créé #3012 pour les histoires d'espèces à bord VS à débarquer sur lesquelles il reste des questions non tranchées.
Ce ticket reste donc pour les autres points : 
- heure prévue d'arrivée du PNO
- engins de la marée du PNO pour les segments et les types

**Comment by AdelineCelier** [comment]
@VincentAntoine où en est-on de ce ticket ? c'est reviewable ?

**Comment by AdelineCelier** [comment]
Vu avec Vincent, les dates de préavis et les engins de la marée pour le calcul des segments ont bien été récupérés, je ferme ce ticket.
