### ISSUE TITLE
Supprimer les zones "Prudhomies" des zones reg

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#249]
Demander en salle si c'est utile ? C'est pas utile

**Comment by louptheron** [comment]
Voir avec Marine si on peut les supprimer

**Comment by VincentAntoine** [comment]
@AdelineCelier tu avais refait le point là-dessus ? Je peux refaire un tour en salle et voir avec Charlotte s'il y a un doute avant de supprimer.

**Comment by AdelineCelier** [comment]
@VincentAntoine Normalement c'est bon, mais tu peux t'assurer une dernière fois avec Charlotte qu'elle les a bien rangées quelque part au cas où on voudrait les remettre (ce qui est peu probable).
