### ISSUE TITLE
Missions -  Migration des champs d'infractions en bas du formulaire de contrôle

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#2507]
Pour éviter de faire des A/R dans le formulaire quand l'unité dicte les PVs.

- Ajouter un séparateur au-dessus de "Ajouter un engin" (etc pour les espèces)
- Pour les infractions,
  - Il y a un seul bouton d'ajout d'infractions, en bas du formulaire : "Ajouter une infraction" qui ouvre le box d'ajout dans laquelle on sélectionne la "thématique" d'infraction (Oblig. Décl. et autorisation de pêche, Engins, Espèces & Autres)

**Comment by AdelineCelier** [comment]
Retouches : 
- mettre le menu déroulant "groupe" en-dessous des "types d'infraction"
- renommer les deux champs : "type d'infraction" => "résultat de l'infraction" / "groupe" => "catégorie d'infraction"
- agrandir le menu déroulant "catégorie d'infraction" pour que les valeurs ne soient pas tronquées
- classer les valeurs du menu déroulant "catégorie d'infraction" dans l'ordre dans lequel les catégories apparaissent dans le formulaire : od et licences, engins, espèces, autre.

![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/cf07112a-5a55-4c94-bcd4-edf5b1cb958c)
