### ISSUE TITLE
[Missions] Quand on recherche un port pour un contrôle débarque, ne pas prendre en compte les majuscules/minuscules

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#2565]

**Comment by AdelineCelier** [comment]
Est-ce que pour ce genre de ticket ça ne vaudrait pas le coup de reprendre le boulot fait par Ivan sur la recherche ?

**Comment by louptheron** [comment]
Les majuscules ne sont déjà pas prises en compte, je ferme
