### ISSUE TITLE
Ajouter le pavillon Grenade (`GD`) aux navires à avaries

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#2614]
Car les débarquements sont en Martinique (voir pôle SIP).

Dans ce fichier : https://github.com/MTES-MCT/monitorfish/blob/master/datascience/src/pipeline/queries/monitorfish/vessels_that_should_emit.sql#L18

**Comment by VincentAntoine** [comment]
A priori on n'a plus du tout besoin du filtre sur le pavillon, j'ai soumis l'idée au SIP, en attente de leur retour.
