### ISSUE TITLE
[Fiche navire] Prendre en compte la prorogation des permis de navigation

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#2620]
"MonitorFish ne prend pas  la date de prorogation de permis de navigation." Jean-Laurent - ULAM 50

**Comment by AdelineCelier** [comment]
en attente du fix de Vincent pour faire la revue

**Comment by louptheron** [comment]
à corriger :
- [ ] Quand il n'y a pas de "Date d'expiration", le rond vert vert s'affiche
