### ISSUE TITLE
Missions - Ouvrir la fiche navire depuis la barre de recherche navire dans le formulaire de contrôle

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#2658]
Pour voir les infos du navire (ex. taille pour l'AIS) et éviter de copier/coller son CFR

**Comment by louptheron** [comment]
Ecran : 
![image(4)](https://github.com/MTES-MCT/monitorfish/assets/14853556/650b673e-790c-4966-9a00-c845d334ee4a)

**Comment by AdelineCelier** [comment]
L'écran ci-dessus ne fonctionne pas quand on ajoute aussi la taille du navire aux identifiants (cf. ticket #2692). 
Après discussion avec Loup, il a été convenu qu'on pouvait mettre le renvoi vers la fiche navire directement au sein de la barre de recherche. Un lien "voir la fiche" serait le plus clair, je propose qu'on le teste et qu'on vérifie qu'il ne tronque pas les noms de navires. 
Marge entre le lien "voir la fiche" et la croix pour effacer le navire : 16 px.

![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/875fc449-9b66-4a0f-aee9-57c678037292)

**Comment by AdelineCelier** [comment]
c'est bon, ça fonctionne bien !
