### ISSUE TITLE
Missions – La popup d'une mission sur la carto ne se fige plus quand on clique dessus

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#2663]
Ce qui empêche d'accéder au bouton "éditer la mission" de la popup.

**Comment by louptheron** [comment]
@AdelineCelier Je n'arrive pas à reproduire, tu as toujours ce bug ?

**Comment by AdelineCelier** [comment]
Hey @louptheron 
Ah bah non super bizarre ça ne me le fait plus non plus ! Bon bah je ferme le ticket 😅
