### ISSUE TITLE
Rajouter les infos manquantes dans la liste des navires

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#269]
Rajouter dans le tableau : Engins, segments et quartier du navire, taille, espèces §§

---

Puis, quand on les aura : date du dernier contrôle et résultat du contrôle (reprendre écrans)

**Comment by AdelineCelier** [comment]
Petites rectifs UI : 
- ajuster la largeur du tableau à la modale
- rectifier l'alignement du menu déroulant "2 heures"
- revoir le style des checkbox quand elles ne sont pas cochées (répercuter le changement dans les autres instances)
- rajouter un bouton de tri pour les colonnes des critères supplémentaires (quartier, taille du navire)

**Comment by AdelineCelier** [comment]
### Liste navires : ###
- le scroll qui apparaît quand il y a beaucoup de critères n'est pas très lisible, je serais pour le retirer. 
- espèces : régler les doublons
- regarder si on peut faire des colonnes redimensionnables
- petits bugs UI 
- - pb d'affichage du tag "zone libre"
- - disparition des lignes du tableau quand on rajoute un n° de priorisation dans la colonne de priorité de ciblage

**Comment by AdelineCelier** [comment]
@louptheron juste Loup je vois que tu as écarté le premier bullet point, la question du scroll sur les critères...c'est volontaire ou bien c'est un oubli ? 
Haha sorryyy je ne te lâche pas 👀 😈 🙀

**Comment by louptheron** [comment]
Si on ajoute beaucoup de critères, ça agrandit la page en hauteur et je trouvais ça bizarre... Mais c'est vrai que c'est mieux sans, c'est retiré !
