### ISSUE TITLE
Missions - Afficher la taille du navire en dessous de ses informations dans le formulaire de contrôle

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#2692]

**Comment by AdelineCelier** [comment]
Taille à afficher à la suite des identifiants du navire.
Pour que ça rentre bien dans un écran de 1680, il faut abréger différemment "Marq. ext." => devient "Mq. ext."

![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/bb3ccbb1-e53d-4c86-9536-729593efd8e4)
