### ISSUE TITLE
Missions - Enregistrement automatique

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#2698]
- Enregistrement à chaque modification du formulaire (mission & actions)
- Affichage de la date de création de la mission dans le bandeau du bas

**Comment by AdelineCelier** [comment]
### Retours UX

- [ ] J'ai créé une mission en saisissant une admin et une unité, puis suis retournée sur la vue liste : la mission apparaît 2 fois dans la liste.
![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/4d1f9f6a-f174-415f-a4a4-0f179eab627e)
- [ ] La mission semble créée mais la phrase d'enregistrement dans le bandeau du bas mentionne "**Mission non enregistrée**.Dernière modification enregistrée il y a 5 minutes."

### Retours UI
- [ ] Il y a un problème d'affichage des champs date + la phrase d'erreur s'affiche en anglais et non en français
- [ ] Problème de marge entr le tag "Enregistrement auto" et les 2 boutons dans le bandeau du bas
![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/7f897ee9-628f-4a1b-a0a4-9892db2f5781)
- [ ] Il n'y a plus hover ni de focus au clic sur les boutons du formulaire. Du coup quand on clique notamment sur "ajouter une zone de mission", on a l'impression qu'il ne se passe rien
- [ ] Le point de contrôle ne s'affiche plus quand on le définit sur la carte
https://github.com/MTES-MCT/monitorfish/assets/71878648/4f626f0a-0727-49d9-bbdd-c37600ec3542
- [ ] Deux des icônes du menu d'ajout d'une zone sur la carte ne sont pas les bonnes
![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/78d40c99-5ff3-4953-adec-137d517af239)
