### ISSUE TITLE
Missions - Fermer la modale d'ajout de zone de mission lorsqu'on quitte le formulaire de mission

### ISSUE THREAD

**Issue by VincentAntoine** [MTES-MCT/monitorfish#2712]
Reproduction :
- ouvrir une nouvelle mission
- tracer une zone de mission en clôturant le tracé en DOUBLE CLIQUANT (et non en cliquant sur "Valider sur la zone de mission")
- la zone de mission s'enregistre dans la mission mais la fenêtre "Vous êtes en train d'ajouter une zone de mission" reste ouverte
![image](https://github.com/MTES-MCT/monitorfish/assets/27647971/d38b7251-393f-41e1-bc3e-bdb7a1a72813)

- Cliquer sur "Enregistrer et quitter"
- La zone tracée et la fenêtre "Vous êtes en train d'ajouter une zone de mission" restent visible alors que l'on a quitté la vue de la mission
![image](https://github.com/MTES-MCT/monitorfish/assets/27647971/2f6bb01d-ddac-4720-b756-90e9e75fb63b)
- Ouvrir une nouvelle mission : la zone tracée de la mission précédente est directement attribuée à cette nouvelle mission !
![image](https://github.com/MTES-MCT/monitorfish/assets/27647971/071df240-b18b-44c8-958b-15125978c704)

**Comment by AdelineCelier** [comment]
Je me permets un commentaire sur ce ticket : 
- double-cliquer n'est pas considéré comme suffisant pour valider la zone de mission, car les utilisateurs tracent parfois plusieurs polygones pour une seule zone. Il faut donc quoi qu'il arrive cliquer sur "valider la zone de mission". 
- le bug est donc plutôt sur le fait que le menu pour ajouter une zone de mission reste ouvert quand bien même on enregistre et quitte la mission. Côté Env il me semble que le fait d'enregistrer et quitter valide automatiquement la zone de mission et ferme le menu. On peut faire pareil côté Fish, cela évitera le bug de l'attribution de la zone en cours à une nouvelle mission.
