### ISSUE TITLE
Afficher les étiquettes des navires sans overlap

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#273]
Cf. https://stackoverflow.com/questions/67259379/openlayers-move-vector-label-with-mouse

**Comment by AdelineCelier** [comment]
En métropole c'est très chargé, contrairement en métropole.
Je dois dessiner un petit réglage à rajouter dans la carte "gérer l'affichage des étiquettes des navires"

**Comment by AdelineCelier** [comment]
Ecran dans le XD, classé number one 🎹 🎵 🎙️ 
![image](https://user-images.githubusercontent.com/71878648/124300473-e88e9800-db5e-11eb-8afb-886bfdddf90a.png)

**Comment by AdelineCelier** [comment]
Revoir légèrement le temps d'ajustement des étiquettes et du trait qui les relie au navire (les étiquettes bougent plus vite que les traits)
