### ISSUE TITLE
[Tech] Refacto des styles de l'application

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#2739]
Suppression de `mini.css`

**Comment by AdelineCelier** [comment]
## Problèmes UI détectés

**Sur la carto**
- [ ] On ne voit plus les icônes navires quand il y a une alerte
- [ ] La note de risque n'est plus centrée dans le carré de couleur
- [ ] Rémanence des pointillés quand on masque les navires au port
![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/e6c65e9c-554a-4ca3-a084-3e5c0d8cf560)

**Dans la fiche navire**
- [ ] le champ de recherche pour la marée est tronqué
![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/1ebf00fd-1e7a-4b12-bf30-406da12d634e)

- [ ] On pourrait ptet en profiter pour revoir les tags dans le résumé du navire sur les appréhensions ? 😇 Là c'est vraiment très serré, au final j'abrévierais bien les "appréhension" en "appréhens.", et remettre la place gagnée à gauche et à droite des tags
![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/566e5ec0-c855-4919-91e5-95bb3497beae)

- [ ] A décliner aussi dans l'onglet contrôle de la fiche navire
![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/153ad5b0-9a91-4b14-8a43-5c3de5c4fdc1)

- [ ] Problème de marges dans le détail du message FAR : 
![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/b21a9792-c4c9-4e90-adec-beff2ea7979f)

- [ ] Formulaire dans la vue liste des signalements : j'ai l'impression que les champs libres sont trop petits en hauteur, ils devraient faire 30 px de haut de mémoire.
![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/d0e0b8d0-d37b-458c-937d-f790e3906565)

**Vue kanban VMS**
- [ ] Le "voir l'historique" doit être à la ligne
![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/7e25b2dd-50df-414f-be10-337b1a2522fd)

**Autres sujets vus à l'occasion de la revue UI**

- [ ] Dans le cas de message non acquittés, revoir la formulation dans le résumé reg : au lieu de "1 message – aucune capture acquittée", mettre "1 message non acquitté – aucune capture". Décliner cette logique sur tous les types de messages.

**Comment by AdelineCelier** [comment]
@louptheron il y a un problème d'affichage des tags d'appréhension maintenant que tu les as réduit en "appréhens. ..." : le texte s'affiche sur deux lignes. 

NB : à part ce point que j'ai vu au passage, je n'ai pas fait la revue des autres points que tu avais cochés, il faudra le faire quand on reprendra ce ticket.

**Comment by AdelineCelier** [comment]
J'ai passé en revue les points que tu avais cochés @louptheron, c'est bon sauf là où il y a une croix rouge 
+ je n'ai pas réussi à faire la revue des deux derniers points (section "Autres sujets vus à l'occasion de la revue UI" : je n'ai pas trouvé d'ex de message non acquitté en prod, et quand j'ai voulu tester en inté l'ouverture d'un signalement, je ne l'ai pas retrouv dans la liste des signalements (ouvert sur le Cintharth le 04/01/24 à 18h20).

J'ai aussi noté un autre point UI à régler : les pastilles des statuts de mission dans a vue liste sont trop grosses : 
![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/748f192a-143b-45c6-8b37-aa8f1e7fc30e)

**Comment by AdelineCelier** [comment]
@louptheron j'ai rebasculé tout ce qui devait l'être dans le ticket #2872, je ferme celui-ci et le passe en Done
