### ISSUE TITLE
Unités - Ajout des bases sur la carte

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#2746]
cf. https://github.com/MTES-MCT/monitorenv/issues/698

**Comment by AdelineCelier** [comment]
# Revue en cours

## Retours UX

- [ ] Formulaire d'ajout d'un contact : quand je sélectionne un type de contact, puis que dans la foulée je sélectionne "nom de contact personnalisé", le nom du type de contact précédemment sélectionné apparaît en anglais dans le champ


## Retours UI

- [ ] Il manque le fond gris quand on fait "ajouter un contact" (cf. écrans XD), ainsi que pour "ajouter un moyen"
![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/e51c0788-8a8e-45fe-97c8-410098f9b951)
![Uploading image.png…]()

- [ ] Dans l'en-tête de la fiche unité, le titre de l'unité me semble trop petit (différence de taille entre le nom de l'unité et l'admin de l'unité)
![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/9f59eae2-df7d-4d53-b8a2-a01ddf650653)

- [ ] Ce serait possible d'adapter la taille de la fiche unité à son contenu, comme pour la fiche navire ?
![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/c0d8b70f-188d-4b7c-977a-6ec5f4859f75)

**Comment by AdelineCelier** [comment]
@ivangabriele quasi tout est bon sauf : 

- [ ] le même pb que côté Env avec les titres des fiches unités trop longs 
![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/65989987-6679-4b54-9e0c-14ccba8f517d)

- [ ] le même pb avec la carte du moyen plus longue quand il y a plusieurs lignes de description : faire la même chose que côté Env, en agrandissant le fond gris et en centrant l'icône en hauteur
![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/1530b894-3cf5-4138-8047-1f00130ef053)

**Comment by ivangabriele** [comment]
> @ivangabriele quasi tout est bon sauf :
> 
>     * [ ]  le même pb que côté Env avec les titres des fiches unités trop longs
>       ![image](https://private-user-images.githubusercontent.com/71878648/297344852-65989987-6679-4b54-9e0c-14ccba8f517d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5OTQyMzMsIm5iZiI6MTcwNTk5MzkzMywicGF0aCI6Ii83MTg3ODY0OC8yOTczNDQ4NTItNjU5ODk5ODctNjY3OS00YjU0LTllMGMtMTRjY2JhOGY1MTdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDA3MTIxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzNTQ4ZjZjNDczNTRiNDc5YmM5ZGNhZDgwMDYyZDY1YzFmNjYyNjY3M2Y5NzI1ODFmNTViMTlhZGM1YzI2OWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aGhrkNsez0qk7yBlfmBaeNeDesApwraliG37Ot_rnTA)
> 
>     * [ ]  le même pb avec la carte du moyen plus longue quand il y a plusieurs lignes de description : faire la même chose que côté Env, en agrandissant le fond gris et en centrant l'icône en hauteur
>       ![image](https://private-user-images.githubusercontent.com/71878648/297344706-1530b894-3cf5-4138-8047-1f00130ef053.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5OTQyMzMsIm5iZiI6MTcwNTk5MzkzMywicGF0aCI6Ii83MTg3ODY0OC8yOTczNDQ3MDYtMTUzMGI4OTQtM2NmNS00MTM4LTgwNDctMWYwMDEzMGVmMDUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDA3MTIxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyZDY4ZmQ3NGQ2YTM2ZjBkMTA3ZDNkMjdlYTkwNTRiZDZiY2IxNTQzMDMyZWJmZjA3YTQ2MDJiOWYyMzg1ZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U8Ri9a2Sz62KxNgNM7xxxVkqxLTze_4zbA6Cast8Lfg)

Déplacé dans #2833.
