### ISSUE TITLE
Parser les messages CPS (captures d'espèces protégées)

### ISSUE THREAD

**Issue by VincentAntoine** [MTES-MCT/monitorfish#2765]

**Comment by louptheron** [comment]
@AdelineCelier On définit un écran pour ce message (selon le modèle du FAR) ?

Champs rajoutés (d'après le code de @VincentAntoine) :
```
        "sex": edci.get("SE"),
        "health_state": edci.get("HE"),
        "care_minutes": try_int(edci.get("CA")),
        "ring": edci.get("RI"),
        "fate": edci.get("FT"),
        "comment": edci.get("CO"),
```

**Comment by AdelineCelier** [comment]
Voilà la mise en forme pour afficher le message dans le détail du JPE : 
![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/9b9df011-a4d9-4606-8529-b4180be6f5d6)

Reste à faire : le message dans la vue résumée du JPE.

**Comment by louptheron** [comment]
@AdelineCelier As-tu pu faire la vue "Résumé" pour les messages CPS ?

**Comment by AdelineCelier** [comment]
@louptheron c'est bon j'ai décliné les deux écrans dans XD, le 1er c'est le résumé, le 2nd c'est le détail : 
https://xd.adobe.com/view/5def1e65-5f68-43df-b866-ecf5c4c57d9b-08bc/
