### ISSUE TITLE
Couches REG - Zoom auto. lors de la recherche

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#2772]
Proposition : 
- Ne pas recentrer sur la couche REG quand on utilise "Définir une zone sur la carte" 

Retour du CNSP :
> J'ai sondé les différents pôles du CNSP et l'autre bordée d'opérateur la semaine dernière au sujet d'une fonctionnalité de Monitor Fish.
Lors d'une recherche de zone réglementaire via "Définir une zone sur la carte" on obtient une ou plusieurs zone(s) incluant notre recherche dessinée. Pour un ces derniers résultats on peut cliquer sur "l'icone résumé" donnant : Ensemble Reg., Thématique, Zone, Région, Engins etc... Et lors du clic, l'écran se recentre sur ce qui semble être une position moyenne de la zone réglementaire concernée. C'est de ce recentrage dont je voudrais parlé. Après échange avec d'autres utilisateurs, **il s'avèrerait que l'on utilise majoritairement cet outil de recherche sur une zone très spécifique ou sur une piste de navire précise, donc un affichage très zoomé. Le recentrage nous amène souvent loin de l'endroit de travail initial** (au "centre théorique" de la zone reg.) nous faisant "click and drag" vers notre point de départ.

**Comment by AdelineCelier** [comment]
ça me va !

**Comment by AdelineCelier** [comment]
@louptheron c'est bon, la carte ne zoome plus quand on utilise l'outil "définir une zone sur la carte". 
En revanche j'ai repéré un truc bizarre, le décompte des zones d'un groupe ne se fait plus : elles s'affichent toutes avec x/0. 
Je laisse ça dans ce ticket ou bien j'ouvre un nouveau ticket sur ce pb ?

![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/f6fb8e80-f561-4034-afb8-868d430ba1ae)

**Comment by AdelineCelier** [comment]
C'est good !
