### ISSUE TITLE
Epingler un point d'intérêt, soit manuellement sur la carte, soit en rentrant des coordonnées

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#278]
US: Epingler un point d'interêt et le stocker dans le `localStorage`

---

**Retour des superviseurs métropole (Michaël et Xavier) :** 
- intérêt pour positionnement d'un navire avec coordonnées données par une unité sur le terrain, afin de voir dans quelles zones se situe le navire (3 Nq, zone fermée, etc.). A priori pas besoin de conserver cette position ou de la partager. Usage ponctuel.
- intérêt pour positionner les moyens de contrôle mais seulement si c'est une info partagée sur tous les postes (un superviseur est censé savoir où sont ses moyens, ce qui peut l'intéresser c'est de voir où sont les moyens des autres façades). 
=>Plutôt un outil spécifique, lié au planning et au suivi des unités dans MF

**Retour du superviseur outre-mer (Yves) :** 
- Idem que pour métropole, intérêt de rentrer des positions que lui donnent les unités (notamment pour des navire INN qui n'émettent rien). Vont jusqu'à retracer manuellement une piste de navire, pas juste un point. Yves me dit les garder pendant 24-48h puis les supprime. N'a pas besoin a priori de les partager. 
- Dans l'autre sens, il positionne un moyen sur le SEG (ex. l'Osiris II) puis définit un rayon d'action autour, afin de lui donner des indications sur les navires à proximité. Idem, pas besoin de partager ce point.

**Comment by AdelineCelier** [comment]
**Retour des superviseurs métropole (Michaël et Xavier) :** 
- intérêt pour positionnement d'un navire avec coordonnées données par une unité sur le terrain, afin de voir dans quelles zones se situe le navire (3 Nq, zone fermée, etc.). A priori pas besoin de conserver cette position ou de la partager. Usage ponctuel.
- intérêt pour positionner les moyens de contrôle mais seulement si c'est une info partagée sur tous les postes (un superviseur est censé savoir où sont ses moyens, ce qui peut l'intéresser c'est de voir où sont les moyens des autres façades). Plutôt un outil spécifique, lié au planning et au suivi des unités dans MF

**Retour du superviseur outre-mer (Yves) :** 
- Idem que pour métropole, intérêt de rentrer des positions que lui donnent les unités (notamment pour des navire INN qui n'émettent rien). Vont jusqu'à retracer manuellement une piste de navire, pas juste un point. Yves me dit les garder pendant 24-48h puis les supprime. N'a pas besoin a priori de les partager. 
- Dans l'autre sens, il positionne un moyen sur le SEG (ex. l'Osiris II) puis définit un rayon d'action autour, afin de lui donner des indications sur les navires à proximité.

**Comment by AdelineCelier** [comment]
@louptheron Écran fait et ajouté au XD, il faut juste qu'on discute de la manière de valider la création du point. 

![image](https://user-images.githubusercontent.com/71878648/124307699-79b63c80-db68-11eb-9ff7-e6ebc16b8562.png)

**Comment by AdelineCelier** [comment]
- [ ]  Lorsque je place le point d'intérêt sur la carte, c'est toujours l'icône du navire de pêche qui apparaît, quel que soit le type de point que j'ai sélectionné dans le menu
- [ ] Lorsque je clique sur la poubelle pour supprimer un point d'intérêt qui est en cours d'édition, il faut fermer le menu en même temps
- [ ] Il me semble que la "tige" de l'icône du point d'intérêt sur la carte n'est pas en Slate Gray
![image](https://user-images.githubusercontent.com/71878648/132323871-e3df8a2b-0a8c-4cd5-ae0b-73d275a95100.png)

**Comment by louptheron** [comment]
>     * [ ]  Il me semble que la "tige" de l'icône du point d'intérêt sur la carte n'est pas en Slate Gray

J'ai seulement le .png, tu peux me le renvoyer avec la bonne couleur ?

**Comment by AdelineCelier** [comment]
@louptheron tu en as toujours besoin ou bien le ticket est closed ? Tu veux que je te les envoie en .png ou en .svg ?

**Comment by AdelineCelier** [comment]
@louptheron j'ai mis à jour les .svg "Point d'intérêt" dans le dossier Assets, avec la couleur Slate Gray pour le pin. A toi de jouer pour les passer en .png :)

**Comment by AdelineCelier** [comment]
C'est bon pour moi
