### ISSUE TITLE
Unités – Affichage des bases sur la carte

### ISSUE THREAD

**Issue by ivangabriele** [MTES-MCT/monitorfish#2793]
- [x] Sur le fait de donner plus de marge aux numéros dans les pastilles, je ne vois pas la différence...est-ce que parce que c'est trop léger ou bien est-ce que tes changements ne s'affichent pas chez moi ?
![image](https://github.com/MTES-MCT/monitorenv/assets/71878648/4461dcfc-5724-4d34-b2f2-c0b13bb37532)

- [x] Je n'avais pas repéré avant, mais le titre dans la fiche d'une unité n'est pas tronqué non plus, il faut faire comme pour le titre des bases
![image](https://github.com/MTES-MCT/monitorenv/assets/71878648/cf739a78-e653-46b9-a9da-e7113f9e9f7d)

- [ ] Autre truc que je n'avais pas repéré : quand je filtre la liste des unités avec le moyen "drône", il y en a 3 qui remontent, mais seul 1 unité sur les 3 a effectivement un drône dans sa liste des moyens. 
![image](https://github.com/MTES-MCT/monitorenv/assets/71878648/d1c091a6-291f-485a-ab9c-a83d31eabe15)

_Originally posted by @AdelineCelier in https://github.com/MTES-MCT/monitorenv/issues/698#issuecomment-1816813298_

**Comment by ivangabriele** [comment]
> Autre truc que je n'avais pas repéré : quand je filtre la liste des unités avec le moyen "drône", il y en a 3 qui remontent, mais seul 1 unité sur les 3 a effectivement un drône dans sa liste des moyens.

@AdelineCelier Même chose côté Fish, je ne reproduis pas en local et en prod mais c'est peut-être un edge cas auquel je n'ai pas pensé ?

**Comment by AdelineCelier** [comment]
@ivangabriele idem côté Fish, ça marche bien, donc on peut dire que ce point est réglé.

**Comment by AdelineCelier** [comment]
Tout est bon
