### ISSUE TITLE
[Synchro des missions] Ajouter des actions dans la notification "mission en cours avec cette unité"

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#2804]
Formulation de la notification :
"Attention : une mission est en cours avec cette unité.
Voulez-vous tout de même conserver cette mission ?"

Ajouter 2 boutons d'actions :
- "Oui, conserver la mission"
- "Non, anbandonner la mission"

Si l'utilisateur clique sur "non", cela ferme la mission en cours sans l'enregistrer et revient à la vue liste filtrée sur l'unité sélectionnée. 

Écran XD ici : https://xd.adobe.com/view/fd2a8442-19aa-48a8-a7b2-af325f8712cc-a879/

**Comment by louptheron** [comment]
Done.
