### ISSUE TITLE
Définir une gamme colorée pour MonitorFish

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#282]
Pour l'interface 👍🏻 
~~Pour les zones reg~~
~~Pour les zones admin~~
=> à voir dans d'autres tickets

**Comment by AdelineCelier** [comment]
Retoucher la version anthracite de MonitorFish et faire la correspondances des couleurs pour Loup

**Comment by AdelineCelier** [comment]
Correspondances couleurs pour les éléments d'interface (à gauche l'ancienne, à droite la nouvelle) :
- #515151 => #3B4559
- #969696 => #707785, excepté pour tout ce qui est survol et sélection, qui devient #6B839E (couleur d'accentuation)
- #D6D6D6 => #CCCFD6
- #EDEDED => #E5E5EB
- #FFFFFF ne change pas

Correspondances couleurs pour les styles de typo : 
- #515151 => #282F3E
- #969696 => #707785

Ajustements couleur : 
- tous les bandeaux de titres de fenêtres changent de couleur, ils sont de la couleur la plus foncée

**Comment by AdelineCelier** [comment]
@louptheron Revue de ce ticket

**Couleurs**
- [ ] Petite subtilité : lorsque les icônes sont sélectionnées, le fond passe en Shadow Blue, et **les icônes passent en Blanc**. Si c'est pas trop long à faire, c'est cool, ça fait mieux ressortir les éléments sélectionnés/actifs. Après si c'est trop long je mets ce point-là dans le backlog. 
- [ ] Petite retouche à faire sur l'icône de la liste des navires (rond intérieur de la loupe)
![image](https://user-images.githubusercontent.com/71878648/132233476-cc7e7a1d-6f62-451f-b0a7-513b41117ed5.png)
- [ ] Dans le menu "Gérer l'affichage des dernières positions", les deux gris du curseur ne sont pas en Slate Gray et en Gainsboro
- [ ] Dans le menu "Point d'intérêt", le fond des champs n'est pas en Gainsboro
- [ ] Dans le menu "Point d'intérêt", l'icône "autre point" n'a pas l'air dans la bonne couleur. Est-ce que tu as besoin que je te redonne l'icône en .svg ?
- [ ] Dans l'onglet "Contrôles", le fond des tags "déroutement"/"reconduite à quai"/"appréhension" n'est pas en Gainsboro
- [ ] Harmoniser la couleur du survol : Shadow Blue à 15% (comme ce qu'on a fait pour les thématiques de la recherche reg. 2) dans tous les tableaux, not. la liste des navires et la liste des positions VMS d'un navire. 

**Typo**
- [ ] bien vérifier que les contenus des champs sont en Marianne medium, et les libellés en regular, j'ai eu un doute en regardant les écrans (il semble y avoir un léger contraste mais ça me paraît un peu faible).
- [ ] je crois que le titre de la modale "liste des navires" est encore en 23px au lieu de 22px (si j'ai bien lu l'inspecteur)

**Comment by louptheron** [comment]
> Petite subtilité : lorsque les icônes sont sélectionnées, le fond passe en Shadow Blue, et les icônes passent en Blanc. Si c'est pas trop long à faire, c'est cool, ça fait mieux ressortir les éléments sélectionnés/actifs. Après si c'est trop long je mets ce point-là dans le backlog.
Oui je veux bien, car je dois du coup manipuler les svg depuis le code

**Comment by AdelineCelier** [comment]
- [ ] Oupsy, autre petit problème de couleur d'icône, dans la loupe du header de la modale "Liste des navires VMS"
![image](https://user-images.githubusercontent.com/71878648/132370660-0e71dce5-50b7-423a-86a6-5a5bfa42b336.png)
- [ ] Je te redonne aussi l'icône "Autre point", que j'ai légèrement épaissie, elle semble plus fine que les autres et elle s'affiche mal dans Firefox (très légèrement tronquée). C'est aussi pour ça qu'elle me semblait étrange je me rends compte. 
Je l'ai mise dans les Assets, au nom de "Icone menu_Autre point d'interet"

> Oui je veux bien, car je dois du coup manipuler les svg depuis le code
Ticket #558 créé sur le sujet

> [ ] Petite subtilité : lorsque les icônes sont sélectionnées, le fond passe en Shadow Blue, et **les icônes passent en Blanc**. Si c'est pas trop long à faire, c'est cool, ça fait mieux ressortir les éléments sélectionnés/actifs. Après si c'est trop long je mets ce point-là dans le backlog.
Ticket #555 créé sur le sujet. Je ne lâcherai pas l'affaire 😈
