### ISSUE TITLE
Synchro missions – Revue avec enregistrement auto inactif

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#2820]
### Points UX

- [x] Lorsque je crée une mission et que j'ajoute une zone, la zone de mission n'apparait pas sur la carte (et le point de contrôle non plus)
https://github.com/MTES-MCT/monitorfish/assets/71878648/a8b5bbd0-7927-4dc2-a3f6-b56a0e5a0276

- [ ] J'ai créé une mission et saisi un contrôle. J'ai enregistré la mission, le contrôle s'est bien affiché dans le tableau. En revanche quand je suis retournée dans la mission, le contrôle n'apparaissait plus. 
![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/329961ee-ca93-4e6a-b7ef-f1e8221a7d7f)
![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/01e09f17-a04d-4fd4-8344-5cf9093fa350)
J'ai ensuite saisi un contrôle dans une mission déjà enregistrée, celui-ci s'est bien affiché partout. Et en revenant sur la mission qui posait pb, le contrôle s'affichait cette fois.

- [x] Quand je clique sur "ajouter une note libre", ça crée une note libre dans la colonne du milieu, mais ça ne l'ouvre pas, je reste sur le contrôle qui était affiché au moment où j'ai créé la note libre. Quand je clique sur la note libre pour l'afficher, ça ne fonctionne pas, il faut que je clique sur le contrôle puis à nouveau sur la note libre. 

- [ ] Bon ce n'est pas gravissime, mais je crois que lorsqu'on clique sur "enregistrer", la phrase qui mentionne l'enregistrement affiche brièvement "mission non enregistrée". Mais bon comme on sort de la mission, ça ne s'affiche que très rapidement.

### Points UI

- [ ] Les barres bleues à gauche (pour indiquer un contrôle "non clôturé") des cartes de contrôle dans la colonne du milieu ne s'affichent qu'à partir du moment où l'on clique sur l'une des cartes de contrôle...c'était déjà comme ça avant ? 
- [x] #2831
![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/78d40c99-5ff3-4953-adec-137d517af239)
- [ ] Les contenus des menus déroulants ne prennent pas toute la largeur, ça fait un affichage un peu bizarre
![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/b5ac4a13-c5a6-41dd-9a11-809f429c72ec)

**Comment by AdelineCelier** [comment]
@louptheron j'ai mis les points UI dans un nouveau ticket UI pour centraliser des points disséminés entre différents tickets. 

Concernant la synchro des missions à proprement parler : 

**Points UX**

- [ ] Quand j'ouvre un contrôle dans une mission que je viens juste de créer (donc que je n'ai pas encore enregistrée) et que je l'enregistre, d'autres contrôles ou des notes libres viennent s'y ajouter toutes seules, toujours avec la date du 4 janvier j'ai l'impression. J'ai l'impression que ça ne le fait pas quand ne le fait pas quand j'enregistre la mission avant d'y ajouter un contrôle.
![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/9ddec461-b059-4c6b-9ac5-2c7400bb70ee)
![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/a86062de-c1e5-4a9a-8e8d-f3ecdf5b6ea6)

- [ ] Les unités historiques sont réapparues dans le menu déroulant des unités

- [ ] Quand j'ajoute une infraction, le type d'infraction est pré-rempli avec "Infractions engins" (j'ai l'impression que ça ne l'a pas fait pour la première infraction que j'ai ajouté pendant le test, et depuis ça me le fait à chaque fois). 

- [ ] Dans la surveillance aérienne, il n'y a plus rien dans le menu déroulant "segments ciblés"

**Points UI**

- [ ] Possible de centrer dans le bandeau inférieur la phrase "Mission créée...Dernière modification enregistrée il y a..." (cf. écrans)
- [ ] Idem dans cette phrase, ce serait possible de mettre "aujourd'hui" et "hier" pour les dates de la mission créée ? Et de mettre l'année en 4 chiffres, ça me semble plus lisible.

**Comment by AdelineCelier** [comment]
@louptheron je n'avais pas vu tes réponses sur les points UI.
- pour le centrage du texte dans le bandeau, je ne me souvenais pas qu'on en avait parlé, désolée. On n'avait jamais centré un texte dans un bandeau avant ? Genre la phrase "veuillez corriger les éléments en rouge" il me semble qu'elle était centrée non ?
- pour la date oui c'était l'idée, pour rendre la date plus immédiatement lisible. Il me semblait qu'on avait déjà fait ça ailleurs dans l'interface mais peut-être que je me trompe

**Comment by louptheron** [comment]
Le dernier point "modifier l'ordre des items dans le menu déroulant des infractions, pour suivre l'ordre du formulaire et mettre le autre à la fin" a été rajouté dans la PR #3019
