### ISSUE TITLE
Unités - Copie des fixs et améliorations Env

### ISSUE THREAD

**Issue by ivangabriele** [MTES-MCT/monitorfish#2833]
## Bases

- [x] Taille, police et centrage des compteurs de badge. 👍🏻 
- [x] Re-rendre les unités lorsqu'elles sont modifiées (via la mise à jour du cache). 👍🏻 

## Liste des unités

- [x] Ne pas inclure les moyens archivés dans les données de recherche. 👍🏻 
- [x] Ajouter le filtre par catégorie : terrestre, maritime, aérien. 👍🏻 

## Fiche unité

- [x] Vérifier les titres longs et l'infobulle. [1895506811](https://github.com/MTES-MCT/monitorfish/issues/2746#issuecomment-1895506811) 👍🏻 
- [x] Vérifier l'édition des textarea modalités / secteur (contenu lors de la ré-édition au click). 👍🏻 
- [x] Vérifier le switch nom de contact personnalisé <> prédéfini. 👍🏻 
- [x] Taille et centrage interne du placeholder des moyens. [1895506811](https://github.com/MTES-MCT/monitorfish/issues/2746#issuecomment-1895506811) 👍🏻 

## Missions

- Déplacé => #2835

**Comment by AdelineCelier** [comment]
@ivangabriele 
Pour moi dans ce qui a été fait tout est bon, il reste juste ces petits points dont on a parlé côté Env : 
- la graisse des chiffres dans les pastilles des bases à passer en 700
- les 2 points manquants sur la recherche unité qui sont mentionnés dans le [ticket 1048](https://github.com/MTES-MCT/monitorenv/issues/1048) du kanban partagé

**Comment by ivangabriele** [comment]
@AdelineCelier Yes ça sera plus facile dans un nouveau ticket :).

**Comment by louptheron** [comment]
Duplicate of https://github.com/MTES-MCT/monitorenv/issues/1048
