### ISSUE TITLE
Missions - Impossible d'éditer une autre mission à partir de la carte lorsqu'une mission est déjà en cours d'édition

### ISSUE THREAD

**Issue by ivangabriele** [MTES-MCT/monitorfish#2837]
1. Clic mission sur la carte
2. Clic "Editer la mission"
3. Clic une autre mission sur la carte

=> L'overlay de l'autre ne reste pas ouvert, il se referme tout de suite.

Du coup impossible d'éditer une autre mission à partir de la carte dans ce cas.

**Comment by AdelineCelier** [comment]
Le problème est bien réglé !
