### ISSUE TITLE
Préavis – Consulter la liste des préavis

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#2843]
En tant qu'unité, au bureau, je veux pouvoir consulter la liste des préavis pour :
- Identifier le meilleur port et le meilleur moment pour la sortie
- Identifier un ou plusieurs navires à contrôler 

[![image](https://github.com/MTES-MCT/monitorfish/assets/5957876/cb87c36e-0d48-403c-861d-4686049d3433)](https://xd.adobe.com/view/e5dc3e34-ae1f-4a6d-be9a-5d2a70e54eff-b08f/screen/928b47ec-c5b4-47a3-a1ea-8d5e3039c516/)

**Comment by ivangabriele** [comment]
- [ ] Traduction FR des segments

**Comment by AdelineCelier** [comment]
## Revue de la vue liste des préavis

- [ ] Je me rends compte que je n'avais pas fait l'écran correctement, mais il faut rajouter un bouton sur la carte pour accéder directement à la vue préavis de la side window. Et tant qu'on est sur ces boutons raccourcis sur la carte, est-ce qu'il serait possible de :
  - faire correspondre l'ordre des boutons entre le menu de la carte et celui de la side window : 1. couches carto / 2. navires favoris / 3. missions / 4. alertes / 5. préavis / 6. VMS
  - revoir l'espacement entre les icônes sur la carte : 16 px entre les couches cartos et les navires favoris, puis entre les navires favs et le groupe d'icônes suivantes, puis 4 px entre chaque icône du groupe missions/alertes/préavis/VMS
  - mettre la bonne icône pour les couches cartos, et mettre plutôt l'étoile en filaire qu'en plein : 
![Map layers](https://github.com/MTES-MCT/monitorfish/assets/71878648/1a514fc6-505e-4861-95bf-10858b50327b)
![Favorite](https://github.com/MTES-MCT/monitorfish/assets/71878648/e3cd8a2e-fc82-401d-af94-c7f2ccf9710b)

**Comment by ivangabriele** [comment]
> Je rajoute un point :
> 
> * [ ]  Quand j'ouvre le date picker ("Arrivée estimée du navire entre deux dates"), je ne peux pas le fermer en cliquant autre part dans la fenêtre

@louptheron Normalement c'est fixé sur ma PR préavis en cours ça  (tout comme sur les missions d'ailleurs)

**Comment by AdelineCelier** [comment]
## Revue n°2 

=> bien noté pour l'enrichissement des préavis en prod. 
=> on peut s'atteler à la traduction des segments avant la mise en prod finale, ce sera fait ! 

### Vue générale

- [ ] J'ai l'impression que l'icône des préavis (le poisson) est un peu petite : dans les large buttons sur la carte, les icônes doivent faire 26x26 px
- [ ] L'emplacement pour les icônes de drapeaux est bien là, mais elles ne s'affichent pas
![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/57b58bdc-9470-4856-a46a-27848b793ee5)

- [ ] Je n'avais pas remarqué ça à la dernière revue, mais je pense qu'il faudrait renommer le type de préavis "espèces soumises à préavis" en "espèces démersales", ou alors en "autres espèces soumises à préavis".  Sinon je trouve que ça prête un peu à confusion, en soi toutes les espèces des types de préavis sont soumises à préavis.
- [ ] Possible d'élargir un peu le bloc de texte du détail des 5 principales espèces à bord, pour limiter le nb de retours à la ligne ? Passer de 206 à 224 px par exemple. 
- [ ] Pour le "pas de segment", possible de le mettre en forme comme dans les maquettes ? En Slate gray et en italique, pour qu'il se différencie plus visuellement des segments.
- [ ] De mon côté j'ai toujours l'impression que les libellés des champs en Slate Gray ne sont pas en regular (mais ptet que je vois mal ??) : 
![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/e31dcf83-1ec4-440e-a8d7-08a98958ebbe)

- [ ] Concernant le point sur le fait d'intégrer la ligne dépliée à la première ligne du tableau (pas d'espace entre les deux) : si c'est un challenge UI, on le dépriorise ce n'est pas archi important. Est-ce que c'est possible à minima de retirer le hover sur la ligne dépliée ? Comme elle n'est pas cliquable c'est un peu étrange qu'elle passe en Blue Yonder quand on la survole.

**Comment by AdelineCelier** [comment]
@ivangabriele 
Globalement je pense qu'on peut retirer le feature flag, même si le scroll horizontal n'est vraiment pas ergonomique (à régler vraiment pour la V1)

- [ ] Retirer le scroll horizontal qui empêche de voir les lignes du tableau en entier
- [ ]  renommer les types "espèces soumises à préavis" en "**autres** espèces soumises à préavis" => @VincentAntoine je crois que c'est une tâche pour toi ! 
- [ ] l'icône des préavis (le poisson) sur la carte est un peu petite : dans les large buttons sur la carte, les icônes doivent faire 26x26 px
- [ ] Mettre un espace de 8 px entre le bas du tableau et le bouton "charger les 10 préavis suivants"
- [ ] Les lignes de détail des préavis doivent se refermer en cas de tri ou de filtrage du tableau
- [ ] Dans le détail de la ligne d'un préavis, pour les principales espèces à bord : si le nom de l'espèce et sa quantité est plus longue que 224 px, possible de le couper avec trois pointillés et mettre un title ?

**Comment by AdelineCelier** [comment]
@VincentAntoine 

- [ ] les préavis "espèces soumises à préavis" n'ont pas été renommées en "autres espèces soumises à préavis" 

@louptheron 

- [ ] quand je clique sur "voir plus de détail", cela charge indéfiniment le formulaire sans l'afficher
- [ ] ce sont encore des icônes "œil" en fin de ligne pour les préavis auto dans MF pour le CNSP
- [ ] l'icône sur la carte est à la bonne taille, en revanche je ne suis pas certaine mais elle ne me semble pas en Gainsboro mais en White...il faut qu'elle soit en Gainsboro quand le bouton n'est pas sélectionné et en White quand il l'est (bon c'est un petit détail je reconnais)

Et je remets juste ici les 2 points encore non traités, histoire de tout centraliser dans un même commentaire : 
- [ ] Ajouter le tag "préavis zéro" dans la colonne "type de préavis" du tableau TODO @louptheron 
- [ ] Les lignes de détail des préavis doivent se refermer en cas de tri ou de filtrage du tableau TODO @louptheron

**Comment by AdelineCelier** [comment]
Je vois encore un petit souci sur le nommage des types de préavis : Vincent a fait tourner son flow pour changer le nom `espèces soumises à préavis` en `autres espèces soumises à préavis`, mais quand je crée un nouveau préavis, le type de préavis continue de s'afficher comme `espèces soumises à préavis`.

**Comment by AdelineCelier** [comment]
Les derniers points me semblent réglés !
