### ISSUE TITLE
Préavis – Génération des pdf de préavis

### ISSUE THREAD

**Issue by VincentAntoine** [MTES-MCT/monitorfish#2845]

**Comment by AdelineCelier** [comment]
@VincentAntoine je te fais mes retours sur les pdf ici : 
- ajouter un accent à "PRÉAVIS" dans le titre
- quand il n'y a pas de données pour les identifiants du navire, noter "aucun" plutôt que "none", et mettre ce "aucun" en couleur Slate Gray
- possible de faire 2 blocs plus distincts entre les 3 dates du préavis d'un côté et le port + le type de préavis de l'autre, en mettant 16 px entre les 2 groupes ? 
- les intitulés des colonnes du tableau des espèces doivent être en Slate Gray également
- quand on n'a pas le nom en toutes lettres du poisson (ça arrive ça ?), je serais pour mettre le code FAO seul, sans tiret ni parenthèses
- j'ai l'impression que l'image que je t'avais donnée pour le cartouche du secrétariat d'Etat a un léger cadre, voici un nouveau jpg où je l'ai viré : 
![Image](https://github.com/MTES-MCT/monitorfish/assets/71878648/bf192c26-cb81-46d1-9754-05c2920b5855)

**Comment by VincentAntoine** [comment]
@AdelineCelier  All good ! je t'envoie les pdfs mis à jour.

>  - quand on n'a pas le nom en toutes lettres du poisson (ça arrive ça ?), je serais pour mettre le code FAO seul, sans tiret ni parenthèses

Je viens de vérifier dans les données logbook, ça n'arrive pas.
