### ISSUE TITLE
La recherche de signalements sur un navire n'est pas fiable

### ISSUE THREAD

**Issue by VincentAntoine** [MTES-MCT/monitorfish#2849]
Remontée de salle : un signalement créé sur un navire brésilien se retrouve dans les signalements de tous les navires brésiliens !

Explication - à l'OM les navires qui n'existent pas dans la base et qui doivent faire l'objet d'un contrôle ou d'un signalement sont créés dans Navpro avec leur nom et avec comme seul identifiant `-` en guide de marquage extérieur.

Ces navires sont ensuite bien importés dans Monitorfish et comportent un `vessel_id`.

Il est possible de renseigner un signalement dessus, qui s'enregistre avec le `vessel_id`.

Seulement, la recherche de signalement, contrairement à la recherche de contrôles qui se base sur le `vessel_id`, se base sur les identifiants CFR, marquage extérieur et IRCS. Tout navire ainsi créé avec comme seul identifiant `-` en guise de marquage extérieur va donc afficher dans ses signalements l'ensemble des signalements créés sur un navire ayant également comme seul identifiant un `-` en guise de marquage extérieur.

Il faudrait donc modifier le use case `GetVesselReportings` pour qu'il adopte la même logique que `GetVesselControls`.

A creuser cependant : tous les signalements n'ont pas de `vessel_id`, contrairement aux `mission_actions`.

Je dirais qu'il faut soit faire en sorte que tous les signalements aient un `vessel_id` et adopter la même logique que sur les contrôles, soit au moins prioriser la recherche par `vessel_id` sur les autres identifiants.

**Comment by louptheron** [comment]
@VincentAntoine Merci pour les infos.
Pour avoir la même logique que `GetVesselControls` on devra ajouter le `vessel_id` dans toutes les alertes automatiques (il y a **2 954** alertes sans `vessel_id` ajourd'hui),  et donc ajouter une alerte seulement quand nous avons le navire dans `vessels`, ce qui n'est pas toujours le cas...

Je propose donc de partir sur ta deuxième proposition : prioriser la recherche par `vessel_id`, ok pour toi ?
