### ISSUE TITLE
Préavis – Consulter le détail d'un préavis

### ISSUE THREAD

**Issue by ivangabriele** [MTES-MCT/monitorfish#2867]
[![image](https://github.com/MTES-MCT/monitorfish/assets/5957876/baeb6d93-bdd4-4765-8ff6-177f0ad28938)](https://xd.adobe.com/view/e5dc3e34-ae1f-4a6d-be9a-5d2a70e54eff-b08f/screen/ff0cab16-9ec3-42f7-8cf4-f3d3bf9ad8e4/)

**Comment by ivangabriele** [comment]
- [ ] Si affiché dans la liste et supprimé au moment de l'ouverture, afficher une message pour indiquer qu'il a été supprimé

**Comment by AdelineCelier** [comment]
Pour l'info "acquitté/non acquitté", je propose de la mettre en 2è intention, au clic sur la ligne de préavis, dans la colonne "arrivée estimée". 

Cas du message acquitté
![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/a118de9d-a830-430e-9465-bfbd08c8d7d2)

Cas du message non acquitté
![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/00d0a0d5-e80d-4ec1-81a9-5d81a40f58b0)

**Comment by AdelineCelier** [comment]
## Revue vue de détail des préavis

- [ ] La fiche ne se scrolle pas 
- [ ] Comme dans la vue liste, l'icône de la nationalité ne s'affiche pas 
- [ ] Dans l'encart avec les dates, le port d'arrivée, la raison du préavis, etc., les libellés ne sont pas justifiés à gauche.
![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/a9a2855d-6fa4-4944-87e6-c7bd3c4f13ca)

- [ ] Pareil pour les libellés dans l'encart de détail des espèces

- [ ] Quand le n° de marée est trop long, il est tronqué. Mettre des pointillés et un title. 
![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/25bd5184-69b7-4761-9bb1-94b263dc1990)

**Comment by AdelineCelier** [comment]
Allleeez c'est bon !
