### ISSUE TITLE
Préavis – Ajouter et éditer un préavis pour une navire de moins de 12 mètres

### ISSUE THREAD

**Issue by ivangabriele** [MTES-MCT/monitorfish#2869]
- Formulaire UI
- Endpoint API d'enregistrement (mocké) 
- Toute modification reset le champ `isSent` à `false`
- Si quantité = 0, on affiche le tag `Préavis 0` 

Ecran :
[![image](https://github.com/MTES-MCT/monitorfish/assets/5957876/e664374e-1a0a-43f7-8433-c5c1e0894427)](https://xd.adobe.com/view/e5dc3e34-ae1f-4a6d-be9a-5d2a70e54eff-b08f/screen/a36d4e89-23e1-4965-95d8-607e91f61664/)

**Comment by AdelineCelier** [comment]
Remarque du pôle outre-mer : il peut arriver qu'un préavis soit long à remplir et que l'utilisateur soit interrompu en cours de route et doive par ex. saisir un rapport de mission. Il ne faut pas qu'il perde les infos saisies entre-temps. 

**Solution pour la V1** 
Faire en sorte que si l'on change de vue sans fermer le formulaire, celui-ci soit toujours ouvert (et les infos saisies dedans toujours là) quand on revient sur la vue préavis. 

**Solution à plus long terme**
A voir s'il faut une solution plus robuste, type possibilité d'enregistrer un brouillon, ou mettre en place un enregistrement auto, ou une possibilité de "ranger" temporairement le préavis, comme on le fait pour les signalements dans Env. Etudier la solution la plus proportionnée par rapport au besoin.

**Comment by AdelineCelier** [comment]
## Revue du formulaire de préavis -12 m

### Bugs
- [ ] J'étais en train de remplir un formulaire quand soudain il a disparu. 
- [ ] La sélection dans les différents menus déroulants est capricieuse...j'ai l'impression qu'il y a toujours ce problème de temps de chargement, qui fait que quand on scrolle ou quand on recherche, les résultats s'affichent mais mettent du temps à charger, temps pendant lequel on ne peut pas cliquer dessus
- [ ] Quand je cherche l'espèce "cabillaud" (ou "COD"), je ne la trouve pas, c'est normal ?

### Revue UX
- [ ] Le tag "préavis zéro" ne doit s'afficher qu'à partir du moment où des espèces ont été renseignées et que leurs quantités sont égales à 0. Là il s'affiche dès qu'on ouvre le formulaire
- [ ] Ajouter la mention "(UTC)" dans les champs heure, en Marianne Regular Slate gray (cf. maquettes)
- [ ] S'il n'y a pas de changement dans le formulaire, possible de griser le bouton "enregistrer" ?
- [ ] Afin de permettre de changer de vue sans perdre le formulaire en cours de saisie (cf. mon dernier commentaire ci-dessous), il faut que le "voile" sombre qui recouvre la vue liste ne recouvre pas la barre de menu de gauche 

![Image](https://github.com/MTES-MCT/monitorfish/assets/71878648/c2fbdd9b-6a7a-4dbf-a78a-75278c950a38)


### Revue UI
- [ ] Le champ des quantités est trop grand, il doit avoir une taille fixe de 96 px (notamment pour prévoir le cas où il faudra afficher sur la même ligne un sélecteur pour la zone de capture)
- [ ] Je ne suis pas sûre que les flèches pour ajuster la quantité soient nécessaires, est-ce qu'on peut les retirer ? 
- [ ] La champ du trigramme est trop long, il doit faire 120 px
- [ ] L'icône dans le bouton "ajouter un préavis" de la vue liste a une drôle de tête, on dirait qu'elle n'est pas totalement opaque ^^
![Image](https://github.com/MTES-MCT/monitorfish/assets/71878648/573675d8-b15f-4a75-9130-6ed89b21fd96)
- [ ] Il n'y a pas assez d'espace entre le texte et les icônes des champs date et heure : mettre 16 px

**Comment by louptheron** [comment]
>  Ajouter la mention "(UTC)" dans les champs heure, en Marianne Regular Slate gray (cf. maquettes)

Il faut changer le composant monitor-ui, en attendant j'ai ajouté (UTC) à la fin de la ligne.

---

Pour info, j'ai modifié la recherche dans les espèces pour qu'elle soit aussi simple que dans le CR de contrôle.

**Comment by louptheron** [comment]
>  /!\ La sélection dans les différents menus déroulants est capricieuse...j'ai l'impression qu'il y a toujours ce problème de temps de chargement, qui fait que quand on scrolle ou quand on recherche, les résultats s'affichent mais mettent du temps à charger, temps pendant lequel on ne peut pas cliquer dessus

Je n'ai pas réussi à reproduire le souci rencontré lors du scroll sur monitor-ui.
J'ai essayé :
- Rajouter le cacheKey sur monitor-ui
- Rajouter un `searchable`
- Mettre 10 `<Select/>`

J'ai testé à chaque fois sur Storybook dans la machine Windows le scrolling, aucun souci.

@ivangabriele Tu aurais une idée ?

**Comment by AdelineCelier** [comment]
@louptheron j'ai vérifié les points cochés à date, et cela me semble good. Juste une petite remarque sur la pop-up de confirmation de fermeture du formulaire : le bouton "quitter sans enregistrer" est tronqué, possible de l'afficher en entier (quitte à élargir un peu la pop-up pour respecter les marges) ? 

![Image](https://github.com/MTES-MCT/monitorfish/assets/71878648/86e81f9e-1a1f-40cd-bdbb-fb85a31491c8)

**Comment by AdelineCelier** [comment]
C'est good
