### ISSUE TITLE
Zones administratives - Impossible de masquer certaines zones admin

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#2934]
En ouvrant l'app, j'ai déjà ces zones affichées : 
- Zones ZEE
- 3 milles
- 6 milles
- 12 milles
- CGPM (dans les zones ORGP)

Je ne peux pas les masquer : je clique sur l'œil et rien ne se passe. En revanche je peux afficher/masquer sans pb les autres zones.

**Comment by louptheron** [comment]
Corrigé avec un reset du localstorage, je ferme le ticket
