### ISSUE TITLE
Recherche reg – Lorsqu'on recherche un code engin, les couches reg dans lesquelles une catégorie d'engins est renseignée ne remontent pas dans la recherche

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#2952]
Ex. dans un résumé reg c'est "chaluts" qui est mentionné dans les engins réglementés ou les engins interdits et que je tape OTB dans la barre de recherche, la reg ne remonte pas

La reg en question
![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/572bb952-e9d0-403a-9b7e-10c8e7475c55)

Et quand on tape "OTB" dans la barre de recherche
![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/387d59ec-e274-4859-9283-5afe2e07150e)

=> on ne stocke pas tous les engins dans la couche REG directement (on stocke juste "Chaluts"), donc il faut récupérer les engins de cette catégorie.

**Comment by louptheron** [comment]
Je ferme ce ticket car complexifie la recherche, en attendant de creuser les vérifications à faire sur un navire dans le cadre des préavis.

> @AdelineCelier : Dans le cadre des vérifications à faire sur un préavis, il peut être intéressant de proposer à l'opérateur une liste de zones reg qui pourraient concerner la marée du navire, en se basant notamment sur son engin.
