### ISSUE TITLE
Missions - Modifier les styles des champs en erreurs en rouge allégé

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#2969]
Dans le formulaire des missions :
- Ne pas mettre en rouge le `label`
- Ne pas afficher la phrase d'erreur
- Ajouter le rouge sur les composants custom (non `rsuite`)

cf. Miro : https://miro.com/app/board/uXjVNY_Ur84=/
cf. écrans XD : https://xd.adobe.com/view/bcb50441-8561-431e-9ce7-1a78965b60e4-e9e6/

**Comment by AdelineCelier** [comment]
C'est bon pour moi !
