### ISSUE TITLE
Synchro missions – Divers ajustements côté Fish

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#2985]
### Sur les champs bloquants

- [x] Le champ "Date de fin de mission" doit être bloquant dans Fish 👍🏻 

### Sur le bandeau du bas et la pop-up de confirmation

- [x] Revoir formulation de la pop-up qui s'affiche quand on veut quitter le formulaire alors que l'enregistrement auto n'était pas actif : 
   - dans le bandeau de titre mettre "enregistrement impossible" 👍🏻 
   - texte de la pop-up : mettre "de la mission" plutôt que "d'une mission" et retirer le "s" à erreur 👍🏻 
   - mettre le "retourner à l'édition" secondary button et "quitter sans enregistrer" en teriary
   - revoir les marges de la pop-up (cf. [cet écran](https://xd.adobe.com/view/bcb50441-8561-431e-9ce7-1a78965b60e4-e9e6/screen/d4f7bab6-bffe-4d6e-8238-cf35a1ac3282)) : 48 px de blanc tournant autour du texte et des boutons, 32 px de marge entre le bloc de texte et les boutons, 8 px d'écart entre les deux boutons (modifiable dans monitor-ui)
![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/6200a85e-1581-4b8c-b307-e76c14583016)

**Comment by AdelineCelier** [comment]
@louptheron tin désolée j'ai dû aller un peu vite sur le dessin de la pop-up et la rédaction du ticket : le bouton "quitter sans enregistrer" doit être en primary button, comme sur la capture, et pas en tertiary comme je l'ai écrit
Autrement le texte de la pop-up doit être en Gunmetal, pas en gris. 
Et je crois que Claire avait revu les marges internes de la pop-up dans monitor-ui : 48 px tout autour de la pop-up et 32 px de marge entre le texte et les boutons. Possible de récupérer ce qu'elle a fait ?

**Comment by louptheron** [comment]
@AdelineCelier Ah zut, mais le bouton principal ne devrait pas être "Retourner à l'édition" ? Je me dis que si l'utilisateur clique vite sur le bouton mis en avant, il peut perdre sa saisie ? 

Ok pour les éléments de syles.

**Comment by AdelineCelier** [comment]
Arf j'avoue c'est peut-être risqué...pfff je suis pas attentive aux détails ça va pas là désolée. 
On peut en effet mettre "retourner à l'édition" en primary et "quitter sans enregistrer" en secondary, et dans ce cas inverser les deux boutons ? Que le "retouner à l'édition" soit à droite - c'est celui sur lequel on a le réflexe de cliquer non ?
