### ISSUE TITLE
La messagerie (Smallchat) n'est plus disponible en production

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#3015]
Changer la var d'env : `FRONTEND_SMALL_CHAT_SNIPPET=https://embed.small.chat/T0176BBUCEQC01SV3W4464.js`

Passer de `VITE_SMALL_CHAT_SNIPPET` à `FRONTEND_SMALL_CHAT_SNIPPET`

**Comment by louptheron** [comment]
Ne fonctionne pas lorsque le script est dans `App.tsx`

**Comment by louptheron** [comment]
Done

**Comment by AdelineCelier** [comment]
le chat est revenuuu !
