### ISSUE TITLE
[Mission] Mise en place de l'état de complétion des données des actions

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#3037]
### Liste 

- Ajout d'un filtre sur statut & complétion des données 👍🏻 
- Ajouter deux colonnes statut et complétion des données 👍🏻 
  - Si un état est non-complété parmi la mission et les actions, on passe à "à compléter" 👍🏻 
- Rajouter les filtre "Missions avec actions Fish" (voir ticket #3008) 👍🏻 
- Supprimer le filtre "Ouvert par" (voir ticket #3008) 👍🏻 

#### Mission
- Afficher les tags de complétion 👍🏻 
- A chaque enregistrement, calculer l'état de complétion de la mission et de l'action pour l'enregistrer en BDD 👍🏻 
- Afficher le bandeau quand on revient sur une mission terminée mais non-complétée

#### Action

- A chaque enregistrement, calculer l'état de complétion de la mission et de l'action pour l'enregistrer en BDD 👍🏻 
- En dessous du titre de l'action, afficher les champs à compléter, ex. "12 champs à compléter pour la stat" 👍🏻 

### Données

- Rajouter le champ `completion` dans les actions
- Si le trigramme de clôture est présent dans les actions, on migre les `isClosed` en `COMPLETED`

**Comment by AdelineCelier** [comment]
@louptheron ça me semble bon globalement ! Qques remarques non bloquantes pour une mep : 

- [ ] Est-ce qu'il serait possible de rajouter une latence (par ex. 1h) pour passer de l'enregistrement auto à l'enregistrement manuel ? Ça me semble un peu abrupt d'y passer direct quand la mission passe à terminée. 
- [ ] Je n'avais pas vu à la dernière revue, j'ai repéré qu'il y a une astérisque pour le 1er champ "ajouter un engin", mais aussi pour les suivants, alors que ce n'est que le 1er qui est obligatoire...y'aurait moyen de virer l'astérisque pour les suivants ?
- [ ] Ce n'est pas vraiment le sujet du ticket (sorry), mais possible de remettre dans l'ordre alphabétique les ports de débarquement dans le menu déroulant ?

**Comment by AdelineCelier** [comment]
@louptheron comme vu ensemble à l'instant, tout est bon sauf la petite rectif UI du dernier point : trait blanc à mettre à droite du sous-menu, pas à gauche ;)
