### ISSUE TITLE
[Mission] Ajout du bandeau Toast

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#3038]
## Liste des actions

- Afficher "Des données ont été ajoutées par l'unité dans la mission." en récupérant les actions de rapportNav

## Formulaire 
- Afficher le nouveau bandeau "Toast" lors de la création d'une mission
- Afficher le bandeau quand on revient sur une mission terminée mais non-complétée

**Comment by AdelineCelier** [comment]
@louptheron je me suis permise de regarder même si tu ne m'avais pas assignée dessus 😇 

- [ ] Le bandeau vert de création de mission apparaît bien, juste il me semble disparaître assez vite. Ca pourrait être pas mal de définir une durée d'apparition standard qui serait reprise partout dans les 2 apps. Je dirais 10 secondes par ex ? (à voir côté Env combien de temps il apparaît)
- [ ] Le bandeau vert n'a pas de croix pour le fermer avant la fin des 10 secondes
- [ ] Le bandeau rouge n'a pas le bouton "masquer" pour le rétracter avant qu'il se rétracte tout seul (idem, au bout de 10 secondes)

**Comment by louptheron** [comment]
> Je dirais 10 secondes par ex ? (à voir côté Env combien de temps il apparaît)

C'est bien à 10 secondes sur Env

**Comment by AdelineCelier** [comment]
C'est bon pour les bandeaux !
