### ISSUE TITLE
[Mission] Mise à jour des pop-up de missions et d'actions sur la carte + Nouvelles couleurs de statut

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#3039]
- Changer les tags de la popup mission et action - cf. [cet écran](https://xd.adobe.com/view/bcb50441-8561-431e-9ce7-1a78965b60e4-e9e6/screen/39666b04-6f1f-4e33-b91a-17aff4a18eb3/)
 - Changer les couleurs des missions - cf. [cet écran ](https://xd.adobe.com/view/bcb50441-8561-431e-9ce7-1a78965b60e4-e9e6/). La pastille rouge sur les étiquettes de missions terminées indique une mission encore à compléter.

**Comment by AdelineCelier** [comment]
@louptheron qques retours
- les icônes de mission semblent en mauvaise résolution, plus que pour les icônes d'avant – dis-moi si le pb vient de mes png, je peux te les renvoyer en plus grand
- il manque la petite pastille rouge sur l'étiquette qui indique une mission terminée à compléter (cf. [écran](https://xd.adobe.com/view/bcb50441-8561-431e-9ce7-1a78965b60e4-e9e6/) en bas à droite, désolée c'était un peu discret ;) )
- je viens de voir que c'est l'icône "edit" et pas l'icône "editunbordered" qui est dans le bouton "éditer la mission" : possible de mettre le "editunbordered" plutôt ?

**Comment by AdelineCelier** [comment]
@louptheron comme vu à l'instant, je remets le ticket en todo pour la question de la pixellisation des icônes de mission.

**Comment by louptheron** [comment]
Après quelques essais infructueux, on clôture ce ticket.
La pixellisation semble être arrivée depuis la MAJ d'OpenLayers avec les styles WebGL.
