### ISSUE TITLE
Fiche navire - L'UI du paramétrage de l'affichage de la piste VMS est cassé

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#3050]
![Screenshot from 2024-03-27 16-34-42](https://github.com/MTES-MCT/monitorfish/assets/14853556/3a06bef9-3bc0-4a8a-ab93-cbb087542b59)

**Comment by AdelineCelier** [comment]
@louptheron Est-ce que tu peux aligner à gauche la phrase et le picker ? (l'aligner sur le date picker)
![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/367cdbdd-eae5-4c0f-a16e-592778c09925)
