### ISSUE TITLE
Missions - Problème lié à la validation des champs

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#3054]
Après avoir rempli un champ bloquant (ex. trigramme) je clique vite sur "fermer", ça me met la pop-up "enregistrement impossible". 
Ensuite j'ai beau revenir et recliquer sur fermer, ça bloque avec la même pop-up – alors qu'il n'y a plus de champ en erreur.
Et il faut que je change le contenu du champ (ici que je mette un autre trigramme) pour que ça réactualise et que je puisse fermer le formulaire sans être bloqué par la pop-up.

**Comment by louptheron** [comment]
Bug plus d'actualité ?

**Comment by AdelineCelier** [comment]
Mmh je ne sais pas, je n'ai pas retesté les missions depuis longtemps...tu as fait quelque chose qui est censé le régler ?

**Comment by AdelineCelier** [comment]
J'ai retesté ce ticket, je n'ai pas rencontré de problème. Je le ferme.
