### ISSUE TITLE
Unités – Ajouter ou modifier un contact de diffusion dans la fiche unité

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#3083]
Dans le cadre de la diffusion des CR de contrôle et des préavis, il a été décidé d'utiliser les contacts des unités saisis dans MonitorFish pour déterminer les adresses mail et les n° de téléphone de diffusion. 

### Diffusion par mail
- Les adresses de diffusion sont signalées dans la fiche contact par une petite icône
- Une adresse de diffusion unique par unité, les équipes se chargent ensuite des redirections
- Si une adresse de diffusion est déjà définie au niveau de l'unité, un message de confirmation apparaîtra lorsque l'utilisateur sélectionnera une autre adresse mail de diffusion. 
[Ecrans XD ici](https://xd.adobe.com/view/e419eaed-c054-4382-b1bb-fdf429fddeb9-b14a/screen/c409c0fb-4200-4252-8044-485069b0c541/), 13 à 16

### Diffusion par sms
Encore à déterminer : 
- est-ce qu'il y aurait un intérêt à remplacer cette diffusion par des salons Tchap ?
- si l'on reste sur une diffusion par sms, comment administre-t-on les numéros via Monitor ? Règles à respecter (pas de n° perso...)

**Comment by louptheron** [comment]
Je prends ce ticket

**Comment by AdelineCelier** [comment]
@louptheron ça fonctionne bien, il y a juste un pb d'alignement du n° de tel quand le nom de l'unité est sur 2 lignes :

**Comment by AdelineCelier** [comment]
ça me semble bon !
