### ISSUE TITLE
Quand on a ajoute un contrôle , il y a "à jour" d'affiché en haut du formulaire pour quelques secondes

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#3136]
Lors de l'ajout d'une nouvelle action, sa valeur par défaut ne contenait pas `completion: TO_COMPLETE`. C'est seulement lors de l'update de callback `updateEditedActionFormValues()` que sa `completion` se mettait à jour, après 1 ou 2 secondes.

**Comment by AdelineCelier** [comment]
@louptheron j'ai l'impression que c'est toujours le cas, ça apparaît parfois très rapidement, parfois plus longtemps. 

https://github.com/MTES-MCT/monitorfish/assets/71878648/abace7d6-b2e7-4602-b318-b5b4a6ad1428
