### ISSUE TITLE
Cerbère - Li'cône du profil Cerbère s'affiche au-dessus de la liste des navires et devrait être caché dans `displayedComponents`

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#3141]
![Screenshot from 2024-04-25 16-20-56](https://github.com/MTES-MCT/monitorfish/assets/14853556/03530abd-8f55-474b-a99d-8fe5c4bef119)

- Affichage avec trop de z-index
- Cacher le bouton avec `displayedComponents` lors de dessins de polygones sur la carte par exemple

**Comment by AdelineCelier** [comment]
C'est bon aussi !
