### ISSUE TITLE
Missions – Problème dans le calcul de la zone de mission à partir d'une action

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#3149]
@louptheron je remets ici les éléments que je t'ai écrit dans Mattermost suite à notre tour en prod avec Vincent aujourd'hui

Vincent a ouvert la mission de l'ULAM 29 à terre (du 26/04 09h44 au 26/04 16h - ID 12624) depuis la carte, donc elle avait bien une zone de mission calculée à partir du contrôle saisi (ID 4875). Mais au moment où Vincent a cliqué sur "éditer" dans la pop-up de mission, la zone a disparu de la carte. Et dans le formulaire, l'encart bleu n'est plus visible dans la colonne 1, alors qu'un port est bien renseigné. J'ai essayé de supprimer le port et de le resaisir, ou de le remplacer par un autre port puis de remettre le bon, mais ça ne marche pas, la géométrie ne se calcule pas.
![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/fe419a9b-028a-4888-bdbf-bbf6ab1b17e0)

En regardant la vue liste il y a le même problème sur d'autres missions, qui ont des contrôles mais pas de zone calculée. A noter que ce sont à chaque fois des contrôles terre (donc des ports), coïncidence ?
![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/354eadc9-3ef1-4d9c-b7bc-6df829a501bf)

**Comment by louptheron** [comment]
Il semblerait que `isGeometryComputed` soit passé à `false`, à creuser.

**Comment by louptheron** [comment]
Done, cf. https://github.com/MTES-MCT/monitorenv/pull/1358

**Comment by AdelineCelier** [comment]
@louptheron retours suite à la revue : 

- [ ] Vérifier la mise à jour de la zone de mission quand elle a été modifiée dans Env, pour que les zones autour des contrôles plus anciens s'affichent bien (icône de contrôle doit apparaître + l'étiquette ne doit pas se centrer sur l'ancienne zone de mission)
https://github.com/MTES-MCT/monitorfish/assets/71878648/b5541be0-e685-4c8d-b6f0-c9ed6895cc71

- [ ] Prendre en compte un changement de date d'action (au sein de Fish) pour recalculer une zone de mission
- [ ] Revoir la taille de la zone de mission calculée à partir d'un point de contrôle pour l'aligner avec Env : faire un cercle de 2000 px (à valider) de rayon en mer comme à quai.

**Comment by AdelineCelier** [comment]
@louptheron rien de bloquant pour la mep mais 2 points à revoir, l'un rapidement et l'autre peut attendre : 

1/ A faire rapidement : il ne faut pas enregistrer une zone de mission si l'action créée ou éditée n'est pas la dernière en date

2/ A faire plus tard : toujours le pb de l'étiquette qui ne se met pas tout de suite à jour au niveau de la bonne zone de mission
