### ISSUE TITLE
Avaries VMS - Rajouter des zones manquantes

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#3156]
Certains pêcheurs se plaignent de recevoir des avaries en mer alors qu'ils ne sont pas en pêche.

Il semblerait qu'il manque des zones d'exclusion.

Ex: à Port Navalo pour le DAME DE POISSON

## TODO

Récupérer les navires -12 ayant le plus d'avaries en mer et vérifier les zones de mouillage ou de stockage ?

**Comment by VincentAntoine** [comment]
Administrable via QGIS.
