### ISSUE TITLE
Rajouter une navigation dans les marées depuis l'onglet pêche, dans vue résumée et vue détaillée du JPE

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#317]

**Comment by AdelineCelier** [comment]
Ecrans màj dans le XD (https://xd.adobe.com/view/7fb378f2-2d2b-437d-a0ef-3b7001d56c62-2ae0/) : écran n°53 pour le résumé du JPE, et écran n°55 ou 56 pour la vue détaillée des messages. 

A noter que le bouton de refresh du JPE n'apparaît selon moi que lorsque l'utilisateur consulte la marée en cours, pas lorsqu'il est sur les marées précédentes.

**Comment by AdelineCelier** [comment]
La marée peut mettre un peu de temps à charger. Est-ce qu'on pourrait rajouter un loader ?

**Comment by louptheron** [comment]
Done, wdyt ?

**Comment by AdelineCelier** [comment]
Mettre le loader même quand la souris est au-dessus d'un bouton

**Comment by louptheron** [comment]
C'est assez compliqué à mettre en place malheureusement, à la limite une autre solution ?
Ou alors on se dit que l'utilisateur bouge sa souris ? :D

**Comment by AdelineCelier** [comment]
Autre solution : mettre un petit loader juste avant le texte "marée xxx" ?

**Comment by AdelineCelier** [comment]
Au final, un scroll global s'affiche et prend toute la fenêtre : au moins il n'y a pas d'ambigüité
