### ISSUE TITLE
Signalements - Retouches UI

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#3183]
Ce ticket regroupe plusieurs tickets UI sur les signalements : tickets #3022, #1757, #1684 

**Utilisation des composants de monitor-ui**
- [x] Composants radio du formulaire : prendre les radio buttons de monitor-ui (cf. [cet écran](https://xd.adobe.com/view/b31dea96-3e28-44f4-912c-32424d831d7c-e64e/screen/ab3693af-f3ec-44c9-af0d-a020c891a802))
- [x] Utiliser les icônes de monitor-ui : alerte (cloche) / observation (jumelles) / edit simple (juste le crayon) / archiver / supprimer

**Autres points**
- [x] La marge à droite du formulaire n'est plus bonne : 
![image](https://user-images.githubusercontent.com/71878648/220149064-705366db-c562-4301-8c4b-b308bd2d3372.png)

- [x] Quand il n'y a pas de signalement, mettre la phrase "pas de signalement ouvert sur ce navire" au-dessus du bouton et justifié à gauche (cf. [cet écran](https://xd.adobe.com/view/b31dea96-3e28-44f4-912c-32424d831d7c-e64e/))
- [x] Les 2 bandeaux rouges superposés ne sont pas très lisibles (bandeau alerte + bandeau signalement) : je propose de mettre le bandeau de suspicion d'infraction en MaximumRed 15%, et l'icône + le texte en MaximumRed. 
![image](https://user-images.githubusercontent.com/71878648/214116670-337f069a-fd98-4d6f-8753-bd08ee096868.png)

**Comment by louptheron** [comment]
Bugs identifiés :
- [ ] Le bouton "Afficher plus de signalements" ne fonctionne plus
- [ ] Il est possible d'éditer un signalement de type Alerte, alors qu'il faudrait cacher l'icône d'édition

**Comment by AdelineCelier** [comment]
@louptheron je me permets 2 mini points supplémentaires, puisqu'on est proches de la perfection maintenant sur les signalements 😇 

- [ ] Possible de mettre le bandeau "ouvrir/éditer un signalement" en rouge 15% comme le reste du formulaire, quand le signalement est une infraction ?
![Image](https://github.com/user-attachments/assets/86697183-b167-4aa1-9fc4-f5a035c1f722)

- [ ] Il semble que la marge blanche inférieure est un peu plus petite que les autres
![Image](https://github.com/user-attachments/assets/29de64e8-00f9-4060-bd2d-4848fe9aae22)

**Comment by louptheron** [comment]
Un autre retour : 
- [ ] On affiche "Dernière alerte le ..." sur les observations
 
![Screenshot from 2024-08-30 17-32-48](https://github.com/user-attachments/assets/f5cb0afe-ffb7-4df5-a4e0-f731c6caa323)

**Comment by AdelineCelier** [comment]
Les derniers points remontés sont bons, désolée je me permets d'en remonter un dernier : possible d'augmenter les marges entre les icônes à droite de la carte (pastille avec nb de signalements, éditer, supprimer, archiver) ? 
Il faut à minima 8 px de marge entre le haut de la carte et la 1ère icône + entre chaque icône. 
Voire je me demande s'il n'en faut pas 12 ou 16...tu crois qu'on peut faire un test en live ensemble ? Merci ! 

![Image](https://github.com/user-attachments/assets/ef336c6f-294e-437e-8378-d4fe0351bb1a)

**Comment by AdelineCelier** [comment]
C'est good !
