### ISSUE TITLE
Signalements – Ajouter un résumé à l'historique des signalements et revoir la manière d'empiler les signalements similaires

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#3188]
- [x] Ajouter un résumé en tête de l'onglet "Historique des signalements" (cf. [cet écran](https://xd.adobe.com/view/b31dea96-3e28-44f4-912c-32424d831d7c-e64e/screen/b097d12c-d68c-4f56-8715-081bafad1cef/))
- [x] Regrouper les alertes similaires dans l'historique comme c'est fait dans les signalements actifs 👍🏻 
- [x] Dans les deux onglets, ajouter un moyen de voir les différentes dates des signalements empilés (cf. écrans [21](https://xd.adobe.com/view/b31dea96-3e28-44f4-912c-32424d831d7c-e64e/screen/e0e1a444-2c99-468e-9065-16677310c32e/) et [22](https://xd.adobe.com/view/b31dea96-3e28-44f4-912c-32424d831d7c-e64e/screen/c2e8a0e7-6225-4ecc-bd4d-a228015873d6/))

**Comment by AdelineCelier** [comment]
@louptheron quelques retours : 
- pour moi il n'est pas nécessaire de mettre la pastille en haut à droite de la carte du signalement ou de l'observation s'il n'y en a qu'un seul. Elles n'y sont pas dans l'onglet "signalements en cours", je pense qu'on peut faire de même dans les signalements archivés. 

![Image](https://github.com/user-attachments/assets/f3ce6eae-1155-4f44-b915-ee8846290772)

- dans le résumé des signalements archivés, pour les signalements manuels, je me demande s'il ne faut pas faire figurer le n° du NATINF en plus de son intitulé – mais c'est aussi vrai que ça coupe un peu la lecture. Je te laisse me dire ce que tu en penses. 
- enfin, dans l'historique des signalements archivés, je ne pense pas qu'il soit nécessaire de mentionner 2 fois la dernière alerte d'une pile de plusieurs alertes. Cf. dans la capture ci-dessous, la 2è alerte et la dernière sont les mêmes. 

![Image](https://github.com/user-attachments/assets/123bd313-5e25-4587-be95-2270fbb0c1d2)

**Comment by AdelineCelier** [comment]
@louptheron c'est bon, je vois juste un souci de décalage dans le résumé de l'historique quand il y a plusieurs types de signalement, cf. cette capture : 
![image](https://github.com/user-attachments/assets/3784ba14-c08a-4e6a-981f-b5ab6ef48bc5)

**Comment by louptheron** [comment]
Ok en inté
