### ISSUE TITLE
Signalements – Archiver automatiquement les signalements issus d'alertes

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#3189]
Après discussion avec les équipes du CNSP, il s'avère fastidieux d'archiver manuellement les signalements, notamment les signalements issus d'alertes automatiques, qui sont toujours les mêmes. 
Il a donc été convenu que ces signalements s'archiveraient automatiquement au bout d'un temps donné. 

=> reste à définir avec les équipes le délai avant archivage pour toutes les alertes actuellement en place.

**Comment by AdelineCelier** [comment]
Proposition après discussion avec Xavier Goron, à faire valider par Célia et Katell : 
- pour l'alerte **incursion en ZEE FR** : c'est systématiquement vérifié et traité rapidement, c'est bien que le process reste manuel
- idem pour l'alerte **incursion sans droits historiques**
- pour l'alerte **absence de messages FAR en 48h**, Xavier propose de ne l'archiver qu'une fois qu'on est sûrs que la marée du navire est finie, à savoir au moment du DEP suivant => @VincentAntoine @louptheron qu'en pensez-vous ?
- pour l'alerte **3 milles - Chaluts**, Xavier propose un archivage après 24h (vu qu'on est généralement sur de la pêche côtière) mais à valider avec les officiers.

**Comment by louptheron** [comment]
à tester en prod.
