### ISSUE TITLE
JPE - L'affichage des espèces du JPE est cassé

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#3193]
Cas: Marée 20240009 du CFR FRA000911288

> Concernant l'espèce ANF, le poids total affiché présenté en GUT est de 10977,20kg pour un détail de 8385,87 +2060,35=10 446,22kg, soit un différentiel de 530,98kg.
> Cet écart correspond au poids d'ANF présenté en "LVR-C"  (soit 145,89+385,11), avec un CF de 0 s'agissant de foies.

![njooajpoeelagcol](https://github.com/MTES-MCT/monitorfish/assets/14853556/2427d753-aad2-43a0-b10f-ce4d27f16e30)

---

Analyse de Vincent :
> Le total des LAN est en poids nets, donc en sommant des poids nets on doit obtenir des poids nets, quel que soit le coefficient de conversion.

**Comment by AdelineCelier** [comment]
@louptheron ce ticket n'est pas déjà passé dans la dernière mep ? 
je n'ai pas souvenir de l'avoir vérifié avant...là j'ai été regarder en prod si le message du navire s'affichait pareil, et en l'occurrence le message s'affiche toujours pareil, mais le navire a ensuite fait un message corrigé 3 jours plus tard. Je sais pas trop quoi vérifier, comment checker le fix j'avoue 😅 

![Image](https://github.com/MTES-MCT/monitorfish/assets/71878648/79aa6c95-235d-46ca-be54-65e284d52da5)

![Image](https://github.com/MTES-MCT/monitorfish/assets/71878648/a15f9c37-2e12-4fa6-8aba-88c8a75d6f5c)
