### ISSUE TITLE
Act-rep – Retirer des act-rep les contrôles faits par les unités AECP

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#3194]
L'AECP faisant déjà son propre rapportage pour ses unités (Ocean Guardian, Sentinel, Protector), il n'est pas nécessaire d'inclure les contrôles faits par elles dans les act-rep du CNSP.

**Comment by louptheron** [comment]
Le filtre ne fonctionne pas Car il est appliqué sur les contrôles qui a le champ `controlUnit` vide
