### ISSUE TITLE
Fiche navire - Afficher l'indication mer/port de la position VMS dans la liste des positions VMS

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#3204]
Et également dans l'export des positions VMS.

## Tech

Utiliser `is_at_port` dans la table `positions`.
Vérifier si NOAA_LAND est utilisé ou seulement la zone des ports ?

**Comment by VincentAntoine** [comment]
La zone NOAA_LAND n'est pas utilisée, seulement les ports. C'est peut-être acceptable ? Je dirais qu'on peut commencer comme ça et au retour de Fabien si ce n'est pas OK je ferai évoluer le job `enrich_positions` pour prendre en compte NOAA_LAND.
