### ISSUE TITLE
JPE - Trier les messages par date d'activité

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#3205]
Cas d'usage: Pour les FAC sous VisioCaptures

## To Do

- Utiliser le composant de navigation dans les marées de l'écran "Résumé", avec les icônes en "secondary"
- Ajouter un tri, cf. [cet écran ](https://xd.adobe.com/view/00caf47d-fabc-4ade-9849-cddf93012cd9-5599/screen/d399846f-2e3d-4f2f-982d-75a752f8c625/)
- Passer en composant monitor-ui :
  - Le filtre des types de messages 
  - Le bouton téléchargement
  - Les icônes des flèches de la vue résumé (cf. [cet écran](https://xd.adobe.com/view/00caf47d-fabc-4ade-9849-cddf93012cd9-5599/))

**Comment by AdelineCelier** [comment]
@louptheron wow je ne me souvenais pas de ces écrans haha

Ca m'a l'air de bien fonctionner, juste deux mini points : 
- [ ] pour le champ de tri par date d'activité ou date d'envoi : je noterais "**trier par** date d'activité" ou "**trier par** date d'envoi". En effet, comme le champ est par défaut rempli, il n'y a aucun moment où tu vois un "trier par", donc tu ne sais pas forcément à quoi ça correspond. 
- [ ] au survol sur l'icône permettant de changer l'ordre de tri, remplacer "antichronologique" par "antéchronologique".
