### ISSUE TITLE
Fiche navire - Afficher plus d'informations balises

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#3208]
![image](https://github.com/MTES-MCT/monitorfish/assets/14853556/d09b784d-e9a5-4e90-ab2d-a9ea5bca1ed2)

Afficher :
- Si le navire est équipé e-Sacapt
  - Prendre l'information dans Poseidon
- La version du logiciel JPE
  - Prendre la version reçue dans le dernier message JPE
- Le statut du logiciel JPE (exempté/non-soumis/non-équipé/etc)
  - Prendre l'information dans Poseidon
- Si le navire est sous VisioCaptures

Dans le cas où le navire est déclaré avec FranceAgriMer, ne pas afficher la version du logiciel (VisioCaptures) pour ne pas induire en erreur l'utilisateur ?

**Comment by louptheron** [comment]
@VincentAntoine J'ai fait tourner le flow Vessels en intégration et j'ai cette erreur :
```
: Error during execution of task: NotNullViolation('null value in column "has_esacapt" of relation "vessels" violates not-null constraint\nDETAIL: Failing row contains (-1, null, UNKNOWN, UNKNOWN, null, UNKNOWN, UNKNOWN, null, null, null, null, null, null, null, null, null, null, null, {}, null, {}, {}, null, {}, {}, null, {}, null, null, null, null, null, null, null, null, null).\nCONTEXT: COPY vessels, line 124261: "-1,,UNKNOWN,UNKNOWN,,UNKNOWN,UNKNOWN,,,,,,,,,,,,{},,,{},{},,{},,,,{},,{},,,,,"\n') 
```

**Comment by louptheron** [comment]
Comme vu ensemble après discussion, il manque la version du logiciel dans les infos du JPE.
Il faut l'ajouter dans les écrans. Je remets ce ticket en todo

**Comment by AdelineCelier** [comment]
Et j'ajoute qu'il faut finir de fixer le statut du préavis (qui s'affiche encore la plupart du temps avec juste un tiret).

**Comment by VincentAntoine** [comment]
@louptheron Ll'import de `has_esacapt` est fixé en inté.

**Comment by louptheron** [comment]
Déployé

**Comment by AdelineCelier** [comment]
@louptheron je me suis permise d'aller faire un tour sur ce ticket 😇 
Je te propose de remanier légèrement les marges et les wordings afin d'être à la fois plus lisible 👓 et plus harmonieux 🧘🏻 
Cf. l'écran ci-dessous, qu'en penses-tu ? 
![image](https://github.com/user-attachments/assets/c9a13329-7008-40e6-bfe4-22895e64b9aa)

**Comment by AdelineCelier** [comment]
@louptheron c'est presque bon, pour la date de loggage, elle peut maintenant être affichée sur deux lignes, ce qui la rend plus lisible ! 
Et puisqu'on est sur des points UI, je pense qu'il manque une marge d'au moins 8 px sur le bord droit du bloc de droite
![Image](https://github.com/user-attachments/assets/9fd565c8-0f06-4330-aced-536616f7bb14)

**Comment by louptheron** [comment]
ok en inté
