### ISSUE TITLE
JPE - Analyser plus facilement les messages JPE triés par date d'activité dans Metabase

### ISSUE THREAD

**Issue by VincentAntoine** [MTES-MCT/monitorfish#3209]
Demande SIP pour pouvoir analyser plus facilement les messages JPE triés par date d'activité, et qui est sans doute plus clean de manière générale.
Il s'agirait de passer tous les champs de date d'activité actuellement renseignés dans un champ du `value` spécifique à chaque type de message (`effortZoneExitDatetimeUtc`, `farDatetimeUtc`) vers une nouvelle colonne `activity_datetime_utc`.

Tu en penses quoi @louptheron côté appli ?

Autre option, moins clean mais plus simple, rajouter cette colonne mais sans rien changer et sans supprimer les champs spécifiques à chaque type de message du champ `value`.

**Comment by louptheron** [comment]
Requête SQL exécutée en intégration, OK.
