### ISSUE TITLE
Recherche menu déroulants – Problème de chargement des valeurs au scroll

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#3211]
Il y a le même bug sur les menus déroulants que sur le menu déroulant des espèces dans les missions : quand je scrolle dans le menu, je ne peux pas cliquer sur les valeurs. En revanche quand je fais une recherche cela fonctionne

**Comment by VincentAntoine** [comment]
Même problème dans le formulaire de préavis manuels sur les sélections de ports, d'espèces...

Discuté ensemble avec Loup et Ivan, Loup et moi n'avons pas le problème sur Linux, Ivan le reproduit sur Mac. Cause non identifiée à ce stade.

**Comment by AdelineCelier** [comment]
A noter que certains utilisateurs du CNSP ont trouvé une parade des plus étonnantes pour contourner le problème : quand ils n'arrivent pas à cliquer sur un item du menu déroulant après avoir scrollé, ils font glisser la fenêtre du navigateur sur un autre écran et là ça marche, ils peuvent cliquer ! 
...je ne sais pas si cela peut aider à comprendre d'où vient le problème :-/

**Comment by ivangabriele** [comment]
## Reproduction

1. Être sous macOS
2. Lancer le Storybook de monitor-ui en local
3. Aller sur la story "Fields > Select (variations)" (car elle utilise `virtualized`)
4. Cliquer sur le bouton "Open in new window" pour émuler l'ouverture en mode `window.open()`
5. Scroller un peu dans la liste

=> Impossible de cliquer pour sélectionner une option.

## Investigation

### Tentative n°1 : Utilisez le composant `SelectPicker` directement

Même bug.

### Tentative n°2 : Upgrader Rsuite à la dernière version `v5.70.2`

Même bug (y compris sur le composant "nu").

### Tentative n°3 : Utiliser `react-select`

__Note : Je prends la liberté d'utilise [la deuxième paquet la plus populaire](https://www.npmjs.com/package/@radix-ui/react-select) plutôt que [le paquet historique](https://github.com/JedWatson/react-select) car son auteur principal a l'air d'avoir abandonné son compte Github.__

En cours...

**Comment by AdelineCelier** [comment]
Je viens de tester sur le formulaire d'un préavis manuel, ça marche nickel ! Peut-être que c'est un peu un hack côté tech, mais côté utilisateur c'est parfait 😅

**Comment by ivangabriele** [comment]
@AdelineCelier Ah non ça me paraîtrait très étrange qu'il puisse y avoir un lien. C'est un nouveau bug ça pour moi !

**Comment by AdelineCelier** [comment]
Ok je valide ce ticket-ci alors, et je crée un ticket à part pour l'ordre alphabétique.
