### ISSUE TITLE
Fiche navire - Afficher date ancienneté balise VMS (date de loggage)

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#3223]
Permet de savoir la version du logiciel de la balise et donc si la balise est ancienne.

Afficher le type de balise : satellitaire/côtier (disponible dans la table `beacons`)

**Comment by VincentAntoine** [comment]
- La version du logiciel n'est pas forcément liée à l'ancienneté de la balise, elle sera à prendre dans le dernier message JPE de chaque navire (dans #3208)
- On a bien un champ `is_coastal` dans la table `beacons` qui est issu des Poséidon, mais je vois qu'il n'y a que des `NULL` dedans, il y a un souci de conversion lors de l'import, je le fix ici. Reste à faire back et front pour afficher cette info.

**Comment by AdelineCelier** [comment]
@VincentAntoine et @louptheron 2 questions : 
- en lisant le commentaire de Vincent : au final, la date de loggage de la balise est-elle utile ou non ? Est-ce qu'il faut la remplacer par (ou alors ajouter) l'info de version du logiciel ?
- sur le statut du JPE : quelles sont les valeurs possibles ? Soumis / Non soumis / Exempté ? Pour l'instant dans l'inté tous les navires sur lesquels j'ai cliqué n'ont pas d'info dans le champ (juste un tiret).

**Comment by VincentAntoine** [comment]
@AdelineCelier 
- oui la date de loggage est utile au SIP, en plus de la version logiciel
- La partie data n'a pas été déployée, c'est pour ça qu'il n'y a pas de données, je fais la maj

**Comment by AdelineCelier** [comment]
Ok, donc comme vu ensemble après discussion, il manque la version du logiciel dans les infos du JPE.
Il faut l'ajouter dans les écrans. Je remets ce ticket en todo

**Comment by AdelineCelier** [comment]
Ok, on peut passer ce ticket, vu que la date de loggage de la balise est bien là, et finir de traiter les points restants via le ticket #3208.

**Comment by louptheron** [comment]
Deux bugs :
- L'appli crash quand on clique sur un navire qui n'a pas de balise (`beacon`)
- Dans l'onglet Identité ça affiche toujours - même si une balise est bien associée au navire
