### ISSUE TITLE
Un navire est en alerte FAR 48h alors qu'il n'a pas de JPE

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#3229]
> Le TERRE-NEUVAS de Saint pierre et miquelon sort en alerte FAR 48h. Il n'apparait pas dans le tableau des alertes et il n'a pas de JPE.

V. P.

**Comment by AdelineCelier** [comment]
Est-ce que ce ne serait pas lié au ticket #1946 ?

**Comment by VincentAntoine** [comment]
> Est-ce que ce ne serait pas lié au ticket [#1946](https://github.com/MTES-MCT/monitorfish/issues/1946) ?

ouitoutafè

**Comment by VincentAntoine** [comment]
Duplicate of #1946
