### ISSUE TITLE
Act-Rep - Ajouter le JDP OI

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#3231]
Du 8 au 19 juin prochains, aux Seychelles

Voir Décision EFCA.

**Comment by emmasutherland-cnsp** [comment]
L'EFCA se charge des ACTREPs pour ce JDP. Pour le moment pas de besoin de pouvoir l'exporter automatiquement depuis MF.

**Comment by louptheron** [comment]
Ok, je ferme le ticket
