### ISSUE TITLE
Préavis - Calculer le type de PNO, les segments et la note de risque pour les préavis manuels

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#3240]
Rajouter les fonctions qui calculent :
- `segments`
  - Voir `ComputeFleetSegments.kt`
- `pnoTypes`
  - Voir `ComputePnoTypes.kt`
- `riskFactor` (cf. https://monitorfish.readthedocs.io/en/latest/risk-factor.html)

Calcul :
> risk_factor = 
    impact_risk_factor^0.2 * 
    probability_risk_factor^0.3 * 
    control_rate_risk_factor^0.25 * 
    control_priority_level^0.25

  -  `impact_risk_factor` : aller chercher la colonne `impact_risk_factor` de la table `fleet_segments` en prenant l'année de débarquement et la note la plus élevées parmi les segments du PNO
  -  `probability_risk_factor` : aller chercher la colonne `probability_risk_factor` dans la table `risk_factors`
  - `detectability_score` :
    - `control_rate_risk_factor` : correspond à Vessel control level de la doc --> colonne `control_rate_risk_factor` de `risk_factors` à prendre
    - `control_priority_level` : correspond à Fleet segment control level de la doc --> à aller chercher dans la table `control_objectives` en cherchant le locode du PNO et la facade du port du PNO

Valeurs par défaut :
    "impact_risk_factor": 1,
    "probability_risk_factor": 2,
    "control_rate_risk_factor": 4,
    "control_priority_level": 1,

Rappel de l'architecture :
![Screenshot from 2024-05-29 16-40-33](https://github.com/MTES-MCT/monitorfish/assets/14853556/91335654-5808-49de-b9cd-8a9e43b0c9a3)

**Comment by AdelineCelier** [comment]
@louptheron encore qques petits points : 

- [ ] `la mention "le navire doit respecter un délai d'envoi" doit s'afficher dans tous les cas` : elle doit s'afficher dans tous les cas, mais seulement à partir du moment où le type de préavis a été calculé
- [ ] idem, le tag `aucun segment` s'affiche dès l'ouverture du formulaire vide, c'est un peu bizarre : dans l'idéal, il ne faudrait l'afficher qu'à partir du moment où les données nécessaires pour le calcul du segment ont été remplies.
- [ ] Il y a trop d'espace entre les deux phrases `le préavis doit être vérifié par le CNSP` et `Le navire doit respecter...` : 2px suffisent.
