### ISSUE TITLE
Préavis - Afficher les statuts de diffusion et demander la diffusion pour les préavis manuel

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#3241]
Dans la vue liste et la vue détail

**Comment by ivangabriele** [comment]
<img width="452" alt="image" src="https://github.com/MTES-MCT/monitorfish/assets/5957876/fb02bb5b-742a-40b8-8e14-a6e7f7bea4ec">

**Comment by AdelineCelier** [comment]
@louptheron le comportement des boutons et des statuts me semble bon, en revanche je ne sais pas comment vérifier si la diffusion a effectivement fonctionné...tu as mis une adresse de test ?

**Comment by louptheron** [comment]
>  quand je clique sur "diffuser", il ne se passe rien pendant qques secondes avant que le bandeau jaune "en cours de diffusion" apparaisse. On a l'impression pendant un moment que ça ne fonctionne pas.

J'ai augmenté le temps de chargement (icône qui tourne) pour ne pas avoir l'impression que le clic n'a eu aucun effet

**Comment by AdelineCelier** [comment]
Ok ça me semble bon !
