### ISSUE TITLE
Préavis - Afficher un PNO -12m en lecture seule pour les unités

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#3242]
- Retirer le bouton "Ajouter un préavis"
- Retirer le bouton "Diffuser le préavis"

**Comment by AdelineCelier** [comment]
@louptheron petit bug repéré + petit point UI: 
- [ ] certains préavis saisis manuellement ne s'affichent pas comme des préavis manuels (cf. captures ci-dessous)
- [ ] les deux boutons "fermer" et "télécharger les docs" sont collés, il faut 8 px d'écart entre les deux

Ex. 1 sur le Prospector
![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/87b5f912-2249-4a91-802c-1c5bcf9b35c8)

Ex. 2 sur le Talion
![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/cd59b791-087a-4a23-a047-bc130a6d134a)

**Comment by AdelineCelier** [comment]
@louptheron dans la side window, les menus pour accéder aux missions, aux alertes et aux avaries VMS s'affichent, c'est pas normal si ?

**Comment by AdelineCelier** [comment]
C'est bon, les menus sont bien retirés.
