### ISSUE TITLE
Préavis - Téléchargement d'un préavis

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#3243]
Ecran : https://xd.adobe.com/view/e5dc3e34-ae1f-4a6d-be9a-5d2a70e54eff-b08f/screen/56cc42e4-2d93-4eac-8b30-7886a9fef6c0/

**Comment by ivangabriele** [comment]
<img width="452" alt="image" src="https://github.com/MTES-MCT/monitorfish/assets/5957876/9bd15ac3-7010-4331-9ba9-b25a06020ebb">

**Comment by AdelineCelier** [comment]
@louptheron 

- [ ] le téléchargement des préavis auto ne fonctionne pas (j'imagine que c'est lié à la diffusion qui ne marche pas ?), quand je clique sur le bouton télécharger, cela m'ouvre un onglet avec ça : 
![Image](https://github.com/MTES-MCT/monitorfish/assets/71878648/a5755ea9-242e-4891-82ff-b336b4e63cbd)

- [ ] quand il n'y a pas d'autres docs à télécharger, il n'y a pas besoin de faire apparaitre un sous-bouton avec juste "préavis de débarquement", on peut direct appeler le bouton "télécharger le préavis", ça évite un clic supplémentaire.

**Comment by louptheron** [comment]
>  le téléchargement des préavis auto ne fonctionne pas, quand je clique sur le bouton télécharger, cela m'ouvre un onglet avec ça

Tu peux tester le préavis du 02/02/2024, le VALJUMY

**Comment by AdelineCelier** [comment]
Ok, sur le Valjumy ça fonctionne bien en effet !

**Comment by AdelineCelier** [comment]
les téléchargements semblent bien fonctionner.
