### ISSUE TITLE
Liste navires : rajouter la traduction du code FAO des engins et des espèces dans l'étiquette de survol

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#326]

**Comment by VincentAntoine** [comment]
@AdelineCelier C'est à quel endroit dans l'app ?

**Comment by AdelineCelier** [comment]
@VincentAntoine @louptheron 
C'est dans la colonne "espèces" du tableau de la liste de toutes les positions. Après il y a déjà un survol avec une étiquette qui affiche tous les trigrammes des espèces, la ligne du tableau étant souvent rognée. 
J'ai l'impression qu'on n'a jamais affiché la traduction des trigrammes des espèces en fin de compte...est-ce qu'on supprime cette idée ou pas ?

**Comment by VincentAntoine** [comment]
Condamné par un vote à l'unanimité, ce ticket est renvoyé aux calendes grecques sans sommation.
