### ISSUE TITLE
Le détail des captures s'affiche mal quand il y a plusieurs déclarations de la même espèce dans le même message

### ISSUE THREAD

**Issue by VincentAntoine** [MTES-MCT/monitorfish#3296]
Exemple sur un FAR comportant 2 déclarations portant sur la même espèce, même zone, même présentation, ... avec une déclaration de 3.12kg et une déclaration de 4.89 kg : le total s'affiche correctement mais le détail ne montre que la première déclaration sans somme par zone / présentation / préservation / ...

![Image](https://github.com/MTES-MCT/monitorfish/assets/27647971/291a23a6-e546-4b33-83ae-6d77116c2f54)

Le message "plusieurs zones de pêche et / ou présentation pour cette espèce" est aussi incorrect, il y a plusieurs déclarations mais elles concernent la même zone / présentation / préservation...

**Comment by louptheron** [comment]
Le souci d'affichage est fixé en production :
![Screenshot from 2024-07-12 10-47-49](https://github.com/user-attachments/assets/38c11d98-6965-421d-9884-64c65ba68056)
