### ISSUE TITLE
Définir une palette de couleurs pour les filtres (fond clair/fond sombre) et la décliner sur l'icône des navires (png)

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#331]

**Comment by louptheron** [comment]
![boat_mf](https://user-images.githubusercontent.com/14853556/119159681-c7169880-ba57-11eb-95bd-26eacef725c9.png)

**Comment by AdelineCelier** [comment]
@louptheron j'ai exporté les icônes colorées des navires dans Assets et typos, dossier "Navires_couleurs_filtres", en 72 px
