### ISSUE TITLE
Préavis - Demander la diffusion des préavis auto

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#3317]
Modifier `isVerified` et `isBeingSent` à `true`

**Comment by ivangabriele** [comment]
Normalement la route back fonctionne déjà est est accessible via la route RTK `priorNotificationApi > verifyAndSendPriorNotification`, il suffit de l'appeler avec le `reportId` et `isManuallyCreated=true`.

**Comment by ivangabriele** [comment]
<img width="452" alt="image" src="https://github.com/MTES-MCT/monitorfish/assets/5957876/f1fb6ffd-4fbd-4c38-a25d-19a879e8e6e5">

**Comment by AdelineCelier** [comment]
@louptheron la diffusion n'a pas l'air de fonctionner : 

- [ ] quand je clique sur "diffuser", cela charge brièvement, puis revient sur le préavis sans que le statut se soit mis à jour et sans que le bouton "diffuser" se soit grisé. Quand je retourne sur la liste, le statut s'est mis à jour à "en cours de diffusion", et ça mouline sans fin. 
- [ ] le tag "en cours de diffusion" déborde du tableau
![Image](https://github.com/MTES-MCT/monitorfish/assets/71878648/88f18e61-163c-4073-835d-50b3b3c54739)

**Comment by AdelineCelier** [comment]
@ivangabriele petit point restant mais pas bloquant pour la mep : le tag "en cours de diffusion" déborde toujours du tableau. 
On avait convenu avec Loup qu'on pouvait tronquer le texte dans le tag, car de toutes façons c'est un tag très temporaire. Il faut qu'il y ait au moins 16 px à droite du tag. 

![Image](https://github.com/user-attachments/assets/00648df9-f58e-468c-b033-382216d0174c)

**Comment by AdelineCelier** [comment]
@ivangabriele pour le tag c'est bon ! 
En revanche je me suis rendu compte de quelque chose que je n'avais pas vu : côté préavis manuels, Loup a mis en place un bandeau jaune disant "le préavis est en cours de diffusion", pour bien expliciter ce qui se passe pendant la +/- minute de la pipeline. 
Or ce bandeau jaune n'apparaît pas sur les préavis auto, il faudrait l'ajouter de la même manière que sur les préavis manuels.
