### ISSUE TITLE
Préavis - Ajouter la note d'un préavis auto

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#3318]
Ajouter le champ `note` dans le champ `value` du préavis de `logbook_reports`.

Ecran : https://xd.adobe.com/view/e5dc3e34-ae1f-4a6d-be9a-5d2a70e54eff-b08f/screen/56cc42e4-2d93-4eac-8b30-7886a9fef6c0/specs/

**Comment by AdelineCelier** [comment]
Les préavis auto m'ont l'air de bien avoir une note de risque !
