### ISSUE TITLE
BUG : les pistes des navires Brocéliande (FRA000642955) et Kanaven ar mor (	FRA000442565) ne remontent pas

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#332]
A priori ce sont des navires en avarie VMS, qui n'émettent plus depuis 2-3 jours. Or, quand on demande d'afficher la piste du navire sur 1 mois par ex, rien n'apparaît. 
Les points VMS précédant l'avarie remontent bien dans Poséidon.

Piste: Le bug survient quand nous n'avons pas la dernière position d'un navire dans la table `last_positions` et que l'on souhaite afficher des positions plus anciennes

**Comment by AdelineCelier** [comment]
@louptheron De mon côté j'ai bien les données du Brocéliande, mais rien ne remonte pour le Kanaouen Ar Mor

**Comment by louptheron** [comment]
Oui c'est normal !
En fait le ticket c'était plus pour afficher des positions de navires en avarie VMS (qui n'ont pas émis depuis plus de 48h)

**Comment by AdelineCelier** [comment]
On dit plutôt qu'on grise le champ "filtrer avec une zone existante" quand il n'y a pas d'accès aux zones
