### ISSUE TITLE
Préavis - Ajouter dans le formulaire de préavis la possibilité de joindre des fichiers (certificats de capture, formulaires 2B, 3A...) et de les supprimer

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#3320]
Dans une nouvelle table `prior_notification_uploads`.

UI :
![Screenshot from 2024-07-10 11-48-17](https://github.com/MTES-MCT/monitorfish/assets/14853556/9f522e0d-8b19-42b3-8fca-f51689c98b77)

**Comment by AdelineCelier** [comment]
@ivangabriele je ne vois pas le composant pour ajouter des fichiers dans les préavis manuels. Je ne le vois pas non plus dans les préavis auto, 
Je vois dans le titre du ticket qu'on n'avait parlé que des formulaires -12 m, mais j'ai un doute, je me demande si le pôle outre-mer/INN avait besoin d'ajouter des docs également dans les préavis auto... je leur demande confirmation.

**Comment by AdelineCelier** [comment]
Après demande auprès de l'outre-mer la réponse à la question "faut-il pouvoir ajouter des docs dans les préavis auto **et** manuels ?" est : 
> ce serait pour les deux ! Pour l'instant, c'est principalement pour les manuels, mais cela pourrait arriver sur des préavis autos. 

Donc si c'est long de l'ajouter côté préavis auto on peut le faire dans un 2nd temps, mais ce sera à faire aussi

**Comment by ivangabriele** [comment]
Pour répondre ici aussi donc, je vais regarder où est le soucis et ce sera facile d'intégrer aussi les préavis auto.

**Comment by ivangabriele** [comment]
@AdelineCelier @VincentAntoine Tout est prêt côté app, reste maintenant à envoyer les documents de la table `prior_notification_uploads` par emails côté pipelin.
