### ISSUE TITLE
Afficher la date du dernier contrôle et son résultat lors d'une extraction VMS

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#333]
- [x] vérifier avec équipes s'il faut différencier contrôle débarque et en mer pour la date de dernier contrôle
**=> la charte des 1 mois s'applique quel que soit le type de contrôle, donc a priori pas besoin de différencier.**
- [x] Ajouter le dernier contrôle et son résultat dans la table `last_positions`
- [x] Ajouter le dernier contrôle et son résultat dans le tableau d'extraction VMS

Dernier contrôle il y a:
- Plus d'1, 2, 3, 6, 12 mois
-

**Comment by ferchaudfabien** [comment]
Hello.
Concernant cet item, Xavier Goron estime qu’il serait nécessaire de faire remonter également la colonne « Commentaire » afin de mieux identifier la nature de l’infraction.
La colonne NATINF et son libellé ne serait pas forcément nécessaire par contre.

**Comment by AdelineCelier** [comment]
- La colonne "observations" est peu lisible en l'état. Le redimensionnement de la colonne est compliqué, vu que c'est la dernière du tableau : est-ce qu'on peut y remédier ? Peut-être à minima rajouter le texte complet de la case au survol.
- Il y a des navires qui ont été contrôlés il y a "51 ans". Peut-être vérifier que c'est bien une erreur de saisie des agents, et non un problème de notre côté ?
