### ISSUE TITLE
Préavis – Permettre d'entrer une zone par espèce capturée dans le formulaire

### ISSUE THREAD

**Issue by ivangabriele** [MTES-MCT/monitorfish#3335]
Ecrans XD : https://xd.adobe.com/view/e5dc3e34-ae1f-4a6d-be9a-5d2a70e54eff-b08f/screen/a36d4e89-23e1-4965-95d8-607e91f61664/

Saisie d'une seule zone de capture
![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/d3cb7370-a232-4104-ba72-74600738be28)

Saisie de plusieurs zones de capture
![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/f11399fe-7979-42be-8cff-96619aefa34a)

**Comment by AdelineCelier** [comment]
@ivangabriele cela fonctionne bien, juste 2 points : 
- [ ]  il manque juste la phrase en Slate Gray italique qui apparaît sous le champ de sélection des zones disabled quand on a sélectionné "Différentes zones de capture" (cf. cet écran) : "Veuillez saisir les zones de capture lors de l'ajout des espèces à débarquer."
- [ ] Possible de raccourcir un peu le champ "choisir une zone" ? Le mettre en 144 px de long plutôt que 156, afin de laisser plus de place au nom de l'espèce

**Comment by AdelineCelier** [comment]
c'est bon pour moi !
