### ISSUE TITLE
Préavis - Générer les pdf et diffuser les préavis manuels

### ISSUE THREAD

**Issue by VincentAntoine** [MTES-MCT/monitorfish#3350]

**Comment by AdelineCelier** [comment]
@VincentAntoine les pdf semblent bien générés pour les préavis manuels, en revanche je ne sais pas comment vérifier la diffusion : il y a une adresse de test ?

**Comment by VincentAntoine** [comment]
@AdelineCelier oui c'est diffusé sur l'adresse AIS. Le préavis que tu as créé hier aprem est bien arrivé, Anne-So vient de nous transféré l'email à toi et moi.

**Comment by AdelineCelier** [comment]
Ok je passe le ticket
