### ISSUE TITLE
Préavis - Aller chercher toutes les x secondes le nouvel état du préavis (pour mettre à jour l'envoi)

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#3366]
le préavis reste indéfiniment "En cours de diffusion" même après que la pipeline a diffusé le préavis et passé value->'isBeingSent' à false

**Comment by AdelineCelier** [comment]
@louptheron j'ai l'impression que c'est toujours le cas pour les préavis auto :-/

**Comment by louptheron** [comment]
> @louptheron j'ai l'impression que c'est toujours le cas pour les préavis auto :-/

La pipeline ne tourne pas sur les vieux préavis, à tester en production pendant la prédiode de test.

**Comment by AdelineCelier** [comment]
Ok, je propose qu'on passe ça dans "To deploy in prod", ce point-là sera forcément vérifié pendant les tests en prod la semaine prochaine en salle !

**Comment by AdelineCelier** [comment]
C'est bon !
