### ISSUE TITLE
Préavis - Il faut pouvoir télécharger un préavis non-diffusé

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#3374]
- Préavis non vérifié par le CNSP (hors-scope ou non)
- Préavis non diffusé à l'unité

**Comment by AdelineCelier** [comment]
@louptheron ça marche pour les préavis manuels, mais pas pour les préavis auto. Je vois que dans le cas des préavis auto, il est marqué "document non généré" tant qu'on n'a pas diffusé le préavis. Est-ce que ça veut dire que ce ne sera pas possible du coup ?

**Comment by louptheron** [comment]
Tu peux tester le préavis du 02/02/2024, le VALJUMY

**Comment by AdelineCelier** [comment]
Ok c'est bon, j'ai pu télécharger le préavis sans avoir diffusé avant. 
Idem, à valider en prod pendant les tests en salle.
