### ISSUE TITLE
Préavis - Il faut pouvoir enregistrer et diffuser un préavis déjà diffusé

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#3375]
- Après un premier enregistrement, il faut pouvoir re-modifier et enregistrer le préavis
- La diffusion est possible lorsque un nouvel enregistrement a été fait
  - Le bouton "Diffusé" passe à "Diffuser" lorsque l'enregistrement est fait

**Comment by AdelineCelier** [comment]
@louptheron ça marche pour les manuels, mais pas pour les autos (puisque la diffusion des autos ne fonctionne pas)...enfin je peux recliquer autant de fois que je veux sur "diffuser", mai ça reste en "en cours de diffusion".

**Comment by louptheron** [comment]
à vérifier en production

**Comment by AdelineCelier** [comment]
Hello, je viens de retester ce ticket pour voir si on pouvait le passer en done. 

En testant sur un préavis issu d'un JPE, je me rends compte que l'enregistrement auto rend un peu moins clair le processus de rediffusion : 
- je saisis un commentaire dans le champ "points d'attention"
- au départ il ne se passe rien (il semble y avoir encore des latences...)
- puis au bout de quelques secondes, le préavis s'affiche à nouveau comme "à diffuser"
- si j'efface le commentaire, le préavis reste en "à diffuser".
Je me demande au final si c'est pertinent de laisser l'enregistrement auto sur les préavis de JPE...si l'utilisateur tape quelque chose par mégarde dans le champ commentaire et qu'il l'efface, il faudra tout de même qu'il rediffuse le préavis qui sera repassé en "à vérifier". En plus, cela fait un fonctionnement différent entre préavis auto et préavis manuels, ce n'est peut-être pas très "consistant". 

@louptheron @ivangabriele qu'en pensez-vous ?

**Comment by AdelineCelier** [comment]
Après discussion avec Loup, on choisit de passer les préavis auto en enregistrement manuel. Ticket #3589 créé.
