### ISSUE TITLE
Préavis - Ajouter un cache pour accélerer le "Charger plus" de la liste des préavis

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#3389]
Ajouter un cache de ~3 minutes sur findAllPriorNotifications pour rendre le "charger 10 de plus" instantanné

> Avec une durée pas trop longue genre 3 minutes, histoire de ne pas afficher de la donnée obsolète
> Mais au moins quand on clique 5 fois de suite ce serait rapide
> Vincent

**Comment by ivangabriele** [comment]
Je clos ce ticket car ça fait déjà partie des propositions dans #3237 ^^.
