### ISSUE TITLE
Préavis – Revoir l'aspect du bouton "télécharger"

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#3401]
**Fonctionnement du téléchargement d'un préavis**
- le pdf d'un préavis est généré dans la foulée de la création du préavis, cette étape peut prendre jusqu'à 1 min.
- dans le cas d'un navire de +12 m qui fait un PNO, c'est invisible pour l'utilisateur, à moins que celui-ci ouvre le préavis immédiatement après son apparition dans MonitorFish
- dans le cas d'un préavis d'un navire de - 12 m saisi par le CNSP dans Fish, cette latence est visible puisque la minute court à partir du moment où l'utilisateur clique sur "créer le préavis".
- dans le cas d'un navire tiers, le bouton "télécharger" propose 2 options : le téléchargement du pdf du préavis ou le téléchargement de l'autorisation d'entrée au port et de débarquement

**A modifier sur le bouton "télécharger"**
- renommer dans tous les cas le bouton en "télécharger" (et non plus "télécharger les documents" ou encore "télécharger (document non généré"), car sinon il n'y a pas assez d'espace dans le bandeau du bas, cf captures ci-dessous : 
![Image](https://github.com/user-attachments/assets/3a13d17a-8291-4651-a983-e848742237fb)
![Image](https://github.com/user-attachments/assets/208aa9e5-03c9-4a78-bdcc-cbd460bcfbcf)

- dans le cas où le pdf n'a pas encore été généré, griser le bouton "télécharger" et au survol, afficher cette phrase : "le pdf du préavis est en cours de création, cela peut prendre jusqu'à 1 min".

**Comment by AdelineCelier** [comment]
@ivangabriele je viens de tester et je vois deux retours : 
- dans le cas des préavis de navires tiers et communautaires, le bouton s'appelle toujours "télécharger les documents", il faudrait le raccourcir en "télécharger"
- dans l'intervalle où le préavis n'est pas dispo au téléchargement, j'ai l'impression que le bouton disparaît au lieu de se griser.

**Comment by ivangabriele** [comment]
- [ ] Corriger ça :

<img width="531" alt="image" src="https://github.com/user-attachments/assets/51c5d945-1a1e-4976-991c-18c35f7feccc">
