### ISSUE TITLE
Préavis – Les préavis qui ont une note < 2.3 et qui n'ont pas été demandés par les unités ne doivent pas être diffusés

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#3403]
Après la mise en prod de ce matin, on constate que tous les préavis ayant une note en-dessous de 2.3 s'affichent comme "diffusés".
Or ces préavis devrait s'afficher comme "hors diffusion" et ne pas faire l'objet d'un envoi, étant donné que pour l'instant aucun paramètre n'a été réglé pour l'envoi de préavis supplémentaires aux unités.

**Comment by VincentAntoine** [comment]
@AdelineCelier vérifié en prod c'est bon depuis la MEP de ce matin, les préavis JPE restent en statut "Hors diffusion" si note de risque < 2.3
