### ISSUE TITLE
Préavis – Demander la diffusion des préavis manuels au moment de leur création s'ils ne sont pas dans le périmètre de vérification

### ISSUE THREAD

**Issue by VincentAntoine** [MTES-MCT/monitorfish#3407]
Actuellement les préavis hors scope de vérification (c'est-à-dire `isInVerificationScope` = `false`) ne sont pas diffusés du tout (ils restent 'Hors diffusion') alors qu'ils devraient être diffusés aux unités ayant paramétré de recevoir ces préavis spécifiquement. Il faut donc les passer à `isBeingSent` = `true`.

Pour résumer il y a deux cas possibles à la création d'un préavis manuel :
- soit il est dans le scope de vérification et doit être vérifié avant diffusion, dans ce cas :
  - `isInVerificationScope` = `true`
  - `isBeingSent` = `false`
- soit il est hors scope de vérification et doit être diffusé directement en diffusion restreinte aux unités en ayant fait la demande, donc :
  - `isInVerificationScope` = `false`
  - `isBeingSent` = `true`

**Comment by ivangabriele** [comment]
@AdelineCelier Passé en prod mais je le laisse en review.
