### ISSUE TITLE
Préavis – Il manque la zone FAO 31 dans le menu déroulant des zones d'un préavis manuel

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#3409]
C'est Vincent de l'outre-mer qui l'a repéré, et c'est problématique parce que c'est la zone d'un paquet de préavis faits à l'outre-mer.

**Comment by ivangabriele** [comment]
+ Me donner accès au Metabase de production.

**Comment by VincentAntoine** [comment]
Je viens de regarder, le problème ne vient pas des données, c'est le back qui ne remonte que les zones ayant une `f_subarea` (37.7, 34.1, ...) ou une `f_division` (27.7.a, 34.1.1, ...), les zones n'ayant aucune division mais présentant une seule zone non subdivisée (18, 31, 61, 67, 77 et 81) ne sont donc pas remontées.
