### ISSUE TITLE
Préavis – Lorsque le chargement de la liste est long, en délai ou en erreur, la dernière liste chargée est ré-affichée alors qu'elle ne devrait pas

### ISSUE THREAD

**Issue by ivangabriele** [MTES-MCT/monitorfish#3415]

**Comment by AdelineCelier** [comment]
Des quelques tests que j'ai fait, j'ai l'impression que ça ne me l'a pas refait...peut-être garder un œil sur ce point quand vous referez des tests @ivangabriele et @louptheron ? 
En attendant je pense qu'on peut le passer en done.
