### ISSUE TITLE
Préavis – La recherche de navires par les identifiants ne fonctionne pas

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#3456]
Dans la barre de recherches, quand je tape le CFR ou le MMSI d'un navire, celui-ci ne remonte pas.

**Comment by louptheron** [comment]
cf. https://github.com/MTES-MCT/monitorfish/blob/a2c7b24698ee35738ab8771e3004790cc5b3487d/backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/interfaces/DBManualPriorNotificationRepository.kt#L40C19-L40C137

**Comment by AdelineCelier** [comment]
Après avoir vérifié en salle, la recherche par nom et celle par CFR (que ce soit le CFR complet ou seulement les derniers chiffres) serait suffisante !
