### ISSUE TITLE
Préavis – Rajouter un filtre sur les préavis zéro

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#3457]

**Comment by louptheron** [comment]
@AdelineCelier Est-ce prio, vu le nombre peu important de préavis affiché dans la liste ? Le marqueur "Préavis 0" dans la liste semblait être satisfaisant pour eux.

**Comment by AdelineCelier** [comment]
@ivangabriele j'ai dessiné le filtre sur [cet écran](https://xd.adobe.com/view/e5dc3e34-ae1f-4a6d-be9a-5d2a70e54eff-b08f/screen/6b484776-b592-4694-a9ca-1f9ec06cf20e).
Je sais que je t'ai demandé de trier par ordre alphabétique les statuts de diffusion, mais après réflexion je me demande s'il ne vaudrait pas mieux les trier par pertinence (les plus utilisés/les plus clairs pour l'utilisateur en premier)...désolée ça te fait retoucher, mais pourrais-tu les mettre dans l'ordre de l'écran ci-dessus ?

**Comment by AdelineCelier** [comment]
C'est top, pour le filtre et pour l'ordre !
