### ISSUE TITLE
Préavis – Ajouter un raccourci pour ouvrir un signalement depuis un préavis

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#3460]
Dans le cas où une anomalie est détectée pendant les vérifications faites sur le préavis, il a été acté qu'il était important d'en garder une trace dans un signalement. 
Pour faciliter l'ouverture d'un signalement dans la foulée de la vérification du préavis, ajouter un raccourci permettant d'accéder rapidement au formulaire de signalement sur le navire (formulaire qui remplace la vue détaillée du préavis ?)

**Comment by AdelineCelier** [comment]
@ivangabriele j'ai mis à jour les écrans (cf. n°[53](https://xd.adobe.com/view/e5dc3e34-ae1f-4a6d-be9a-5d2a70e54eff-b08f/screen/baaa6692-e9d4-475c-a8c6-40d313516c3f/) et [54](https://xd.adobe.com/view/e5dc3e34-ae1f-4a6d-be9a-5d2a70e54eff-b08f/screen/a82f3da7-9e37-44f4-9558-04efb21224af/)), je propose qu'on :
- rajoute un bouton-lien sous le champ "points d'attention", 
- ce lien ouvre un volet avec les signalements du navire, et ouvre le formulaire de création de signalement. On reprend les composants de la fiche navire, c'est ce qui me semble le plus simple. 
- à la fermeture de ce volet de signalement, on retombe sur le formulaire du préavis. 
- même comportement entre préavis auto et préavis manuel. 
- 
Cela te semble ok comme manière de faire ?

**Comment by AdelineCelier** [comment]
@ivangabriele il y a un lag de plusieurs secondes avant que le signalement n'apparaisse dans la liste :-/ 
Cf. capture vidéo ci-dessous, le signalement met 14 secondes à apparaître dans la liste
https://github.com/user-attachments/assets/abad6fd4-627d-411b-8386-6555c1708a00

**Comment by louptheron** [comment]
cf. https://github.com/MTES-MCT/monitorfish/issues/3807
