### ISSUE TITLE
Afficher la liste des positions dans un encart à partir de la fiche navire

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#348]
Et afficher en subrillance le point de position quand la souris passe sur une ligne de position

Données à afficher : GDH, Vitesse, cap, latitude, longitude

**Comment by louptheron** [comment]
![Capture](https://user-images.githubusercontent.com/14853556/120206901-0c8f4e80-c22c-11eb-8797-d7bdd574c68c.PNG)

**Comment by AdelineCelier** [comment]
Les écrans sont faits dans le XD "Fiche navire et zone reg OK" : n° 39 à 45

Les assets sont dans le dossier partagé : 
- oeil : bouton_masquer piste, actif et inactif (il n'y a pas que la couleur qui change)
- navire : bouton_piste navire
- point de position plus gros, pour la surbrillance

**Comment by AdelineCelier** [comment]
@louptheron 
- bug du scroll, qui remonte tout seul
- ligne blanche tout en bas du tableau
- est-ce qu'il y a moyen de rendre le survol plus réactif ? Peut-être en supprimant la mini animation d'apparition ?
- est-ce qu'il y aurait aussi moyen de cliquer sur la ligne et que ça centre la carto sur le point VMS ?

**Comment by louptheron** [comment]
Done (sauf pour la ligne blanche tout en bas du tableau, ça vient du tableau c'est bizarre...)
wdyt ?

**Comment by AdelineCelier** [comment]
C'est cool ! Faudrait juste changer l'icône quand tu survoles une ligne : là c'est un curseur de texte, il faudrait plutôt un main clic-clic

**Comment by louptheron** [comment]
Done, wdyt ?

**Comment by AdelineCelier** [comment]
C'est VALIDEYYY
