### ISSUE TITLE
Couches REG - Le flow de MAJ en open data est en erreur

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#3489]
La dernière MAJ est le 4 juillet, cf sur https://www.data.gouv.fr/fr/datasets/reglementation-des-peches-cartographiee/#/resources

Erreur ([logs prefect](http://prefect.csam.e2.rie.gouv.fr/default/flow-run/45f57b91-29ac-47c0-ba76-28b897cab867?logs)) : 
```
HTTPError: 401 Client Error: UNAUTHORIZED for url: https://www.data.gouv.fr/api/1/datasets/60c0ad5b8d17ba18c7b17bd0/resources/12d32a68-e245-4e19-9215-7d07c699b6c0/upload/
```

**Comment by VincentAntoine** [comment]
Il faut mettre à jour l'API key lors de la prochaine MEP.
