### ISSUE TITLE
Dans la recherche de positions entre deux date, prendre la date avec la journée incluse

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#349]
Ex: si on choisit le 31/01, ça va remonter le 31/01 à 00h alors qu'il faut plutôt rendre le 31/01 à 23h59

**Comment by AdelineCelier** [comment]
La piste s'affiche bien, mais dans le calendrier la date de fin de période s'affiche à j+1, ce qui est en contradiction avec la fiche navire et l'infobulle de survol. Je ne sais pas si tu peux régler le composant React ? C'est d'autant plus étrange que tu sélectionnes une date dans le calendrier et qu'automatiquement ça la met à J+1.

![image](https://user-images.githubusercontent.com/71878648/120517485-caebd880-c3d0-11eb-8119-0943829a2b8d.png)
