### ISSUE TITLE
Préavis - calculer automatiquement le poids total de BFT

### ISSUE THREAD

**Issue by VincentAntoine** [MTES-MCT/monitorfish#3508]
Retour ops, le poids total de BFT pourrait se calculer à partir des poids par calibre BF1 / BF2 / BF3.
A creuser : le renseignement du détail par calibre BF1, BF2 et BF3 est-il obligatoire ? 
- Si oui, le poids total pourrait ne plus être remplissable par l'utilisateur mais être uniquement calculé en sommant les poids de BF1, BF2 et BF3
- Si non, comment gérer le fait de pouvoir remplir manuellement le poids total et qu'il soit par ailleurs calculé à partir des poids des calibres BF1, BF2 et BF3 ?

**Comment by AdelineCelier** [comment]
J'ai redemandé au pôle OPS métropole : ils remplissent systématiquement les calibres (BF1, BF2, BF3).
Au pôle outre-mer/INN, il n'y a pas de préavis avec du thon rouge. 

Donc on peut partir du principe que la case "BFT" avec le poids total est grisée, avec une infobulle au survol disant "le poids total est calculé à partir des poids saisis dans les cases BF1, BF2, BF3."

@ivangabriele cela te semble bon comme ça ?

**Comment by AdelineCelier** [comment]
c'est good !
