### ISSUE TITLE
Préparer 2 kepler d'export VMS (tracé et situation) et prendre les retours des superviseurs et unités

### ISSUE THREAD

**Issue by VincentAntoine** [MTES-MCT/monitorfish#351]

**Comment by AdelineCelier** [comment]
J'ai été montrer en salle les deux Kepler, il y avait Yves, Olivier, Xavier, ainsi que David, réserviste qui est venu prêter main-forte pendant la semaine, mais qui sinon travaille à l'ULAM 22.

**Yves et Olivier**: soulignent que s'il faut internet pour consulter la carte, ce sera compliqué pour pas mal d'unités, notamment certaines unités aériennes. Mais cela vaut surtout dans le cas où les unités sont loin des côtes, et doivent basculer sur une connexion satellitaire...à voir s'il serait possible d'activer un mode hors ligne, avec une carte très légère ?

**Xavier** : trouve que c'est intéressant, et se dit prêt à tenter de le partager la semaine prochaine aux unités. A un petit doute sur le fait que toutes les unités sauront manipuler l'ensemble. 

**David** : s'est dit intéressé en ULAM, puisque depuis le confinement, ils ont des tablettes sur lesquelles il fait un partage de connexion + met un VPN, et consulte donc la mini carto VMS de Trident quand il est en mer (il a du mérite !). Du coup, se dit prêt à tenter aussi cette carte. 

Du coup, on peut organiser des tests en salle la semaine prochaine, en envoyant des extractions à différents types d'unités : 
- une ULAM
- un PAM (Iris ou Themis)
- un moyen aéro

Il reste à voir l'autre cas d'usage de ces Kepler, plutôt à destination de personnes de l'administration, hors procédure directe de ciblage. J'avoue qu'à part les réquisitions judiciaires et les situations VMS (à qui servent-elles d'ailleurs ?), je n'ai pas encore bien compris qui d'autre demandait des situ VMS : à creuser, et présenter les Kepler aux personnes concernées.

**Comment by VincentAntoine** [comment]
Tests à faire avec les unités : 

[] ULAM 22 (Adeline)
[] Moyen aéro (Vincent)
[] Patrouilleur (Vincent)

Autre :
[] Test kepler sur tablette

**Comment by VincentAntoine** [comment]
Retours de JB : ces exports de situation VMS sont utilisés constamment (plusieurs fois par jour), c'est un moyen de communiquer avec les unités, ça peut être dans le cadre d'un ordre de mission, d'une orientation en live, d'un contrôle a posteri envoyé en DML (par exemple, screenshot de trajet + zone reg pour caractériser une pêche sur zone fermée)...

- pour le contrôle croisé et dans de nombreux autres cas, l'export kepler sera peu / pas utile s'il n'est pas possible d'inclure des zones reg en plus des tracés
- pour les moyens Marine, le besoin de connexion internet risque de poser problème, mais à tester
- il faut que l'export permette un sélection assez souple (avec / sans les noms, les cfr, ...)

**Comment by AdelineCelier** [comment]
**Après itw de David Nivanen**
Dans le 22 il y a surtout des pêcheurs de CSJ, essentiellement des -12m. Du coup en ce moment il y a très peu de navires avec VMS sur l'eau. Il vaudrait mieux trouver un département avec une flotte plus grosse pour faire le test.

**Comment by louptheron** [comment]
Conclusion:
Le Kepler sans zone REG n'a pas assez de valeur ajoutée (donc on ne fait que rendre plus lisible les etiquettes : #273 )
L'ouverture de MF n'est pas une priorité pour le moment.
