### ISSUE TITLE
Préavis – Exclure les préavis de navires étrangers débarquant à l'étranger

### ISSUE THREAD

**Issue by VincentAntoine** [MTES-MCT/monitorfish#3539]
On reçoit parfois des PNO logbook de navires étrangers débarquant à l'étranger, par exemple des navires anglais pêchant dans les eaux françaises et retournant débarquer au UK. Ces préavis n'ont pas à être vérifiés ni diffusés et ne devraient pas apparaître dans le module préavis.

Il faut donc ajouter une condition pour ne remonter que les préavis qui remplissent au moins une des conditions suivantes :
- le `flag_state` du navire tel que renseigné dans le préavis est un pavillon FRA ou un des pavillons des collectivités territoriales françaises (ATF, MTQ, GUF, MYT, GLP, REU, NCL, PYF, BLM, MAF, SPM, WLF)
- le `country_code_iso2` du port du préavis est FR ou un des codes pays des collectivités territoriales françaises (TF, MQ, GF, YT, GP, RE, NC, PF, BL, MF, PM, WF)

**Comment by AdelineCelier** [comment]
@VincentAntoine est-ce que ces préavis ont vocation à être dans MonitorFish tout court ? Ne faudrait-il pas les exclure complètement de l'app ?

**Comment by AdelineCelier** [comment]
@ivangabriele pour tester ce ticket, j'ai créé un préavis d'un navire anglais ("Calvados") débarquant à Alicante... et c'est bon, il ne s'affiche pas dans la liste.
Mais je ne sais pas si c'est la bonne manière de tester, et quid des préavis auto ?
Autre action à faire pour tester avant de le passer en prod ?

**Comment by AdelineCelier** [comment]
Bon j'imagine que c'est passé en prod et que c'est ok, je passe le ticket en done.
