### ISSUE TITLE
Préavis - Permettre la création d'un préavis manuel à partir d'un préavis logbook

### ISSUE THREAD

**Issue by VincentAntoine** [MTES-MCT/monitorfish#3564]
Pour faciliter notamment le traitement des préavis logbook mal remplis qui doivent être invalidés avant d'être recréés et corrigés en tant que préavis manuels.

![image](https://github.com/user-attachments/assets/c1ef76c4-3f99-4261-a9fc-dd990c676ef3)
![image](https://github.com/user-attachments/assets/be877f00-c67c-4749-b47d-ed2736c02f7e)

**Comment by AdelineCelier** [comment]
@ivangabriele je viens de tester, deux retours : 

- [ ] le préavis nouvellement créé n'apparait pas dans la liste, même après plusieurs minutes
- [ ] le bouton `invalider le signalement` disparaît une fois que le préavis est invalidé. Je trouve toujours un peu bizarre de faire disparaître un bouton, je serais plutôt pour le griser si ça te semble ok.

**Comment by AdelineCelier** [comment]
@ivangabriele c'est bon pour les préavis auto, il faudrait le même comportement avec les préavis manuels ! Dans les préavis manuels le bouton disparaît encore.

**Comment by AdelineCelier** [comment]
c'est good !
