### ISSUE TITLE
Préavis – Certaines unités ont dit qu'elles ne recevaient pas les préavis

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#3580]
A l'outre-mer, l'ULAM Martinique a dit ne pas avoir reçu un préavis alors que l'adresse de diffusion semble être la bonne. 
En métropole, c'est la BSN Hendaye qui a appelé le CNSP pour dire qu'elle ne recevait plus les préavis depuis un certain temps (probablement depuis la bascule ?).

A voir si ce souci est lié au ticket #3573 ouvert par Vincent.

**Comment by louptheron** [comment]
Pour l'ULAM Martinique :
- Il y a 6 envois par emails aux destinataires e-mails en succès (tous les envois SMS sont en échec), ce qui correspond aux prévis envoyés à Fort-De-France
  - Rien d'anormal vu sur les données, à creuser avec Ronan

Pour la BSN Hendaye :
- Cette unité a souscrit seulement au port Capbreton (FRCBT), hors il n'y a pas eu de préavis dans ce prot depuis la bascule
![Screenshot from 2024-08-28 16-09-03](https://github.com/user-attachments/assets/4b64ee82-3f2f-40c7-91d2-e36542eef7c5)
  - Il manque peut-être un port pour cette unité ?

**Comment by ivangabriele** [comment]
@VincentAntoine J'ai hésité à le faire dans les migrations mais c'est vraiment cracra parce qu'on aurait des données liées à rien en dev. Du coup je préfère attendre ton retour pour ajouter les ports manquants sur les données de prod.

**Comment by ivangabriele** [comment]
Bon au final j'ai quand même fait un insert en prod côté Fish lors de la MEP pour ajouter `FRZJZ` et `FRHEN` à la BSN Hendaye (`10374`). Je n'ai pas ajouté Anglet car il n'est pas dans la liste des ports (`FRALT`).

Il semble que le besoin soit plus compliqué que prévu, je laisse Adeline compléter.

**Comment by VincentAntoine** [comment]
Anglet n'existe pas dans le référentiel ports officiel implémenté dans les systèmes JPE donc aucun préavis JPE ne peut arriver sur ce port.
Il ne figure pas non plus dans l'arrêté de ports désignés, ce qui veut dire que les éventuels préavis manuels qui seraient faits dans ce port ne sont pas obligatoires (de même qu'un préavis manuel fait dans n'importe quelle autre commune de France).
Il n'existait pas dans Trident ni dans Poséidon.
Il n'y a jamais eu de contrôle enregistré à Anglet...
Vu que tout le reste a été traité je pense qu'on peut clôturer.

**Comment by AdelineCelier** [comment]
@VincentAntoine ok merci de la vérification. En relisant le mail de la BSN Hendaye, il dit effectivement que "[leurs] ports de contrôle de débarque sont principalement  CAPBRETON, ST JEAN DE LUZ et accessoirement ANGLET et HENDAYE." Ce qui ne veut en effet pas forcément dire qu'il recevait des préavis d'Anglet, juste qu'ils vont parfois y faire des contrôles.
Donc je suis d'accord pour clôturer, si ça marche bien pour les autres ports !
