### ISSUE TITLE
Préavis – Augmenter le filtre sur la date de création des préavis manuels qui permet d'optimiser les appels sql

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#3590]
Le fonctionnement actuel fait que les préavis créés dans le passé ou le futur ne s'affichent pas dans le tableau.

**Comment by louptheron** [comment]
Ce n'est pas possible de changer la colonne de l'hypertable `operation_datetime_utc` de `logbook_reports`.

Par contre, on peut peut-être augmenter le filtre :
```
                    lr.operation_datetime_utc
                        BETWEEN CAST(:willArriveAfter AS TIMESTAMP) - INTERVAL '48 hours'
                        AND CAST(:willArriveBefore AS TIMESTAMP) + INTERVAL '48 hours'
```
Pour prendre en compte plus de jours sans impact de performances.

En salle, 1 semaine dans le futur et 48h dans le passé semble OK.

**Comment by AdelineCelier** [comment]
Ok j'ai modifié le titre du ticket. Ce n'est pas vraiment un bug au final, j'ai retiré le tag.

**Comment by AdelineCelier** [comment]
ça me semble bon, j'arrive bien à voir des préavis qui ont été créés 48h avant et une semaine après la date du jour.
