### ISSUE TITLE
Signalements – Problème d'affichage des signalements dans la fiche du Cornelis g. J.

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#3595]
[En intégration] Il y a un cercle rouge autour du navire et une pastille sur l'onglet signalements, mais quand on l'ouvre il indique "pas de signalement ouvert sur ce navire". Même chose après avoir rechargé la page. 
CFR du navire : GBR000B13544

![Image](https://github.com/user-attachments/assets/ddab8e5b-6c42-4e89-9c40-1fb3e2e11d10)

**Comment by louptheron** [comment]
L'alerte date du 16/9/2022, date à laquelle il n'y avait pas de `vessel_id` sur les signalements.
Je n'ai pas rencontré ce souci en production, où les alertes sont plus récentes.
