### ISSUE TITLE
Préavis – Afficher la liste de diffusion (unités et leurs contacts) dans les préavis et si la diffusion a réussi ou non

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#3598]
Afficher dans le préavis un encart récapitulant la liste de diffusion des préavis avec : 
- le nom de l'unité
- son adresse mail
- (ses n° de tel ?)
- si le préavis a bien été reçu ou non

**Comment by AdelineCelier** [comment]
@ivangabriele j'ai mis à jour les écrans pour l'affichage de la liste de diffusion et l'historique des diffusions faites : 
- pour l'afficher, on clique sur le lien "Voir les détails de la diffusion du préavis" (cf. [cet écran](https://xd.adobe.com/view/e5dc3e34-ae1f-4a6d-be9a-5d2a70e54eff-b08f/screen/a7e22add-5395-42c1-b082-f356fd8a26dd) par ex., lien en-dessous des tags en tête de formulaire)
- au clic, ça affiche d'abord la liste de diffusion, puis l'historique des diffusions, et s'il y a eu des échecs de distribution sur des contacts (sachant qu'à ce stade on ne peut pas détecter certains échecs sur les sms). Cf. [écran n°21](https://xd.adobe.com/view/e5dc3e34-ae1f-4a6d-be9a-5d2a70e54eff-b08f/screen/543975c7-0079-4940-a790-fab07ec42ba4/).

**Comment by ivangabriele** [comment]
@AdelineCelier Les cas non gérés :

- La liste des inscrits est générée à partir de l'historique des messages envoyés, cela veut donc dire qu'elle est vide tant qu'un message n'a pas encore été envoyé.
- Une même unité ayant eu plusieurs emails ou téléphones n'en aura qu'un d'affiché dans la liste (non géré car dépend de la décision de créer un appel dédié ou non pour obtenir la liste des inscrits).

**Comment by louptheron** [comment]
Cas testé en intégration :
- Lorsqu'une diffusion était en "échec" puis qu'elle réussie, le statut reste en "échec" (alors que la liste de diffusion s'affiche bien et `isSent: true` & `state: VERIFIED_AND_SENT`)
![Screenshot from 2024-10-02 11-17-52](https://github.com/user-attachments/assets/5799056e-0cdf-432a-9717-e5aaddbb1aaa)
- Lorsqu'un envoie échoue, la liste s'affiche comme tel :
![Screenshot from 2024-10-01 15-29-36](https://github.com/user-attachments/assets/70efba45-61ad-4bb2-ae1e-a03a914753bb)

**Comment by AdelineCelier** [comment]
@ivangabriele en complément des points remontés par Loup : 

**Points UX**
- Les infos des 2 sections mettent parfois plusieurs secondes à s'afficher, je le note ici au cas où cela n'est pas lié au problème plus global des perfs. Si c'est lié à ce pb plus global, pas la peine de prendre en compte ma remarque. 
- J'ai l'impression qu'en cas de diffusion multiples sur un préavis, seule la première s'affiche dans l'historique, pas les suivantes : j'ai fait une première diffusion sur le navire Loira, puis je l'ai modifié et l'ai re-diffusé. Cette 2è diffusion n'apparaît pas dans l'historique. 
- La mention "chargement en cours..." apparaît en cas d'échec de la diffusion, mais également si la diffusion n'a pas été faite. Peut-être qu'on peut mettre une phrase à la place disant "La liste s'affichera suite à une première diffusion du préavis." 

**Points UI**
- Mettre en Marianne Italic Slate Gray les textes qui s'affichent avant que le contenu ne s'affiche : 
  - "Chargement en cours" 
  - "La liste s'affichera suite..."
  - "Aucun message n'a été envoyé..."
- Quand il n'y a pas encore eu de diffusion, une barre grise s'affiche sous la phrase "Aucun message n'a été envoyé pour ce préavis", il faudrait la retirer. 
![image](https://github.com/user-attachments/assets/994751e2-3e9f-43d1-991f-9cbb0fdbd6c0)

**Comment by AdelineCelier** [comment]
- [ ] Lors d'un premier test sur le Scuderia, j'ai diffusé le préavis qui est bien passé en "vérifié et diffusé", mais son historique de diffusion ne s'est pas mis à jour, cf. capture : 

![Image](https://github.com/user-attachments/assets/3bc3672a-d84d-4b84-a629-f6c98bdc23ce)

Je n'ai pas réussi à reproduire, mais peut-être essayer de creuser ce qui s'est passé ?

- [ ] Mini point UI restant : il manque 8 px d'écart entre le trait d'union qui relie les deux icônes de validation dans l'historique des signalements
![Image](https://github.com/user-attachments/assets/72cb7008-9a45-4ba5-bd72-65791138c14a)
