### ISSUE TITLE
Organiser des ateliers facteur de risque

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#362]
**Points à aborder**
- Quels scénarios d'usage ?
- Quelle formule pour le facteur de risque ?
- Quel niveau de paramétrage, par qui ?
- Quelle prise en compte de l'avancée des objectifs ?

**Comment by VincentAntoine** [comment]
- [ ] Adapter la pondération des dates de contrôle dans la note de taux de contrôle en pondérant plus fortement la date du dernier contrôle (Vincent)
- [ ] Ajouter une pondération des infractions en fonction de leur gravité selon la réglementation afférentes (annexe 30 du réglement 404, infractions graves INN) (Vincent)
- [ ] Valider la liste des segments de flotte avec S. et les notes de risque associées (Vincent)
- [ ] Revoir la conception de la note de risque sur le critère "captures" en séparant en deux notes distinctes (Vincent) : 
  1) le risque lié à l'appartenance à un segment de flotte (note de risque DIRM / PIRC) 
  2) le niveau d'avancement des objectifs de contrôle sur un segment de flotte
- [ ] Tester l'idée que le CNSP pilotera la priorisation des segments à contrôler en ajustant les poids des segments dans la note d'avancement des objectifs de contrôle (Adeline)
- [ ] Tester l'idée de permettre au CNSP de créer des segments de flotte pour cibler des espèces et / ou engins et / ou zones qui  ne font pas partie d'un segment de flotte (espèces soumises à plan...) (Adeline)
