### ISSUE TITLE
Préavis – Dans le cas de zones de capture différentes, permettre d'ajouter plusieurs fois la même espèce

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#3621]
Un superviseur outre-mer me signale que dans certains cas (par ex. pêche de légine), les pêcheurs déclarent avoir pêché la même espèce dans des zones différentes. 
Or le fonctionnement actuel ne permet pas de saisir plusieurs fois la même espèce, pour spécifier les différentes zones de pêche. Est-ce possible de changer cela ?
Si cela n'est pas souhaitable de sélectionner plusieurs fois la même espèce, peut-être peut-on envisager de saisir plusieurs couples poids/zones pour une même espèce ?

**Comment by ivangabriele** [comment]
@VincentAntoine :

- La solution la plus simple et naîve serait de répêter les même espèces avec à chaque fois une zone différente dans `catchOnboard/catchToLand`. 
- La solution la plus propre mais plus longue serait de transformer la prop `faoZone` en un array `fasZones` dans `catchOnboard/catchToLand`.

Au-delà du choix, quid de l'impact côté pipeline et stats ?

**Comment by AdelineCelier** [comment]
@ivangabriele je ne suis pas sure de comprendre ? Quand tu dis "quantités", c'est pour les espèces où il faut renseigner un nombre de pièces ?
Si c'est bien ça dont tu parles, on peut envisager de faire comme pour le poids, à savoir ajouter un champ "pc" pour chaque ligne d'espèce ?

**Comment by ivangabriele** [comment]
@AdelineCelier Pardon si je n'ai pas été assez clair, je parlais simplement du fait qu'il faudra qu'il fassent attention à bien s'assurer que la quantité et le poids additionnés des différentes zones d'une même espèce soient bien égale aux poids/quantité total pour cette espèce.

![image](https://github.com/user-attachments/assets/a48f7746-d07d-439c-bb9f-36fe321c51a8)

**Comment by AdelineCelier** [comment]
Ah yes ok compris ! Ma foi, c'est aux utilisateurs d'être attentifs en effet, s'ils ne le sont pas, ce ne sera pas de la faute de MonitorFish ;)

**Comment by AdelineCelier** [comment]
C'est bon pour moi !
