### ISSUE TITLE
Alertes – Ecran blanc dans la liste des alertes et signalements à l'ouverture par le menu et par la fiche navire

### ISSUE THREAD

**Issue by ivangabriele** [MTES-MCT/monitorfish#3625]

**Comment by AdelineCelier** [comment]
@ivangabriele cela ne fait plus un écran blanc, en revanche cela ne se met pas automatiquement sur la bonne façade selon le navire. 

Je remets ce ticket en todo, après s'il demande du temps pour être réglé (plus d'1h) je serais pour le déprioriser par rapport aux tickets de la V2 préavis. Les utilisateurs n'ont pas l'air d'utiliser souvent cette fonctionnalité.

**Comment by AdelineCelier** [comment]
c'est bon !
