### ISSUE TITLE
Alerte - Sous-déclaration de pêche

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#3647]
Algo possible :
- Effort de pêche incohérent avec ce qui est déclaré dans les FARs

Aussi :
- Prendre en compte les exemptions
- Archiver automatiquement après la marée

**Comment by louptheron** [comment]
L'alerte apparait en "Alerte inconnue" sur la carto et n'apparait ps dans la liste des alertes

**Comment by VincentAntoine** [comment]
> L'alerte apparait en "Alerte inconnue" sur la carto et n'apparait ps dans la liste des alertes. Il manque le `ALERT` à la fin ?

Ca a été traité dans #3865
