### ISSUE TITLE
CR de contrôle: lors d'une infraction laissez le libellé apparent à la suite du code NATINF.

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#3673]

**Comment by AdelineCelier** [comment]
Hello @CNSP-Etel, est-ce que vous pouvez nous donner des précisions sur ce sujet ? Dans quelle vue exactement avez-vous besoin de voir le libellé complet du code NATINF ?

**Comment by louptheron** [comment]
Le CNSP n'a pas retrouvé l'endroit, je clos le ticket.
Ils nous feront une demande si le sujet revient.
