### ISSUE TITLE
Préavis - La saisie des poids d'espadon sur les préavis 0 plante

### ISSUE THREAD

**Issue by VincentAntoine** [MTES-MCT/monitorfish#3683]
Remontée de salle

> Quand on saisit les poids capturés sur les préavis 0 de SWO, ça fait apparaître une ligne undefined et ça plante

@louptheron @ivangabriele

**Comment by louptheron** [comment]
je prends

**Comment by VincentAntoine** [comment]
Pour reproduire :

- Création de préavis 0 avec BFT et SWO
- Réouverture du préavis
  - Suppression du BFT
  - Saisie du poids de SWO --> crash

**Comment by AdelineCelier** [comment]
@ivangabriele je viens de retester en suivant la procédure donnée par Vincent, et il semblerait que le préavis crashe toujours :-/ 
![Image](https://github.com/user-attachments/assets/8bfdba64-ca65-48bd-ac1c-10c5182a6b25)

**Comment by AdelineCelier** [comment]
C'est bon, plus de plantage !
