### ISSUE TITLE
Prévenir quand la session Cerbère expire

### ISSUE THREAD

**Issue by VincentAntoine** [MTES-MCT/monitorfish#3684]
Remontée de salle

> Quand la session Cerbère expire, ça bloque et on ne comprend pas forcément pourquoi. Quand on finit par revenir à l'écran de connexion, on perd ce qu'on a fait entre temps et qui n'a pas été sauvegardé. Ce serait bien d'être prévenu.

@louptheron

**Comment by louptheron** [comment]
J'ai merge une PR qui essaie de résoudre le souci de non-renouvellement du token : https://github.com/MTES-MCT/monitorfish/pull/3665

J'attends la prochaine MEP pour vérifier si le problème est résolu ou non.

**Comment by louptheron** [comment]
Ok
