### ISSUE TITLE
Préavis - Un préavis envoyé reste "En cours de diffusion"

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#3689]
Dans la vue fiche :
1. Je clique sur diffuser un préavis
2. Le préavis diffusés est toujours en cours de diffusion
3. Alors que dans la liste il est bien diffusé

Il faut fermer la fenêtre de préavis et rafraîchir l'appli pour que ça apparaisse diffusé 
 
Ecrans :
![Image](https://github.com/user-attachments/assets/317ee713-a33d-4ca8-96dc-660136fbb4c9)
![Image](https://github.com/user-attachments/assets/43005918-5068-4556-b80a-67998a977c3f)

**Comment by AdelineCelier** [comment]
@louptheron est-ce que la diffusion fonctionne en inté ? j'ai testé sur 2 préavis manuels, et ça mouline indéfiniment, dans la vue liste comme dans le formulaire.

**Comment by AdelineCelier** [comment]
Ok donc quand j'ai testé hier l'inté n'était pas à jour. En retestant aujourd'hui sur des préavis manuels, cela semble bien fonctionner. Je n'ai pas pu tester sur des préavis auto mais partons du principe que ça marche bien aussi pour eux !
