### ISSUE TITLE
BUG: Quand un filtre est appliqué est que les aures navires (hors-filtre) sont masqués, quand je veux afficher la piste d'un navire filtré, l'icône du navire ne s'affiche pas 

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#369]
... alors que sa piste s'affiche bien

**Comment by AdelineCelier** [comment]
Les icônes des navires s'affichent bien, en revanche elles reprennent leur couleur d'origine, et ce même quand on quitte la fiche navire (mais j'ai l'impression qu'elles retrouvent leur couleur de filtre au moment du refresh des positions) : 
![image](https://user-images.githubusercontent.com/71878648/120720170-ebe52400-c4cb-11eb-986b-096886d9154d.png)

**Comment by louptheron** [comment]
Done!
