### ISSUE TITLE
BUG : incohérence d'affichage sur l'historique des contrôles du Mar de Flores 

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#370]
Dans le résumé, il est indiqué "0 infraction", avec une pastille rouge (idem en intégration et en prod).

![image](https://user-images.githubusercontent.com/71878648/120519650-261eca80-c3d3-11eb-86d2-d92f3a0cbf3e.png)

**Comment by louptheron** [comment]
En cours sur la branche `fix_controls_infraction_number`.

à faire : 
Pour la somme des infractions:
- Quand il y a le booleen `infraction` à true mais pas de NATINF, on incrémente de 1
- Sinon on fait la somme des `infractions`

**Comment by AdelineCelier** [comment]
Cela semble fonctionner, en tous cas sur Mar de Flores ! Il y a juste un petit souci de pluriel : 

![image](https://user-images.githubusercontent.com/71878648/121907238-281a4f00-cd2c-11eb-8752-f3abece9329a.png)
