### ISSUE TITLE
BUG: Quand je selectionne un navire sur une date range donnée puis que je ferme la sidebar, la "cible" apparait sur sa dernière position (`last_position`) alors que le navire devrait être deselectionné

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#371]

**Comment by AdelineCelier** [comment]
@louptheron j'ai l'impression que c'est bon, mais je ne suis pas tout à fait sure d'avoir compris ce que tu décrivais, donc je te laisse double-checker (qu'est-ce que tu appelles la sidebar ?? ^^)

**Comment by louptheron** [comment]
Oui, un peu jargonneux ce ticket :) 
La "sidebar" c'est la fiche navire sur la droite. Le bug semble résolu

**Comment by AdelineCelier** [comment]
Oui ça a l'air bon !
