### ISSUE TITLE
Préavis – Régression sur l'affichage de la liste suite à un changement de filtre de période

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#3749]
J'ai à nouveau par moments le pb de persistance des anciens résultats suite à un changement de filtres : 
- j'applique un 1er filtre de période, les préavis correspondants s'affichent.
- je change le filtre de période, cela semble charger puis cela réaffiche les résultats de l'ancien filtre pendant plusieurs secondes avant d'afficher les bons résultats. 

Cf. capture ci-dessous, où le filtre va du 30/01 au 01/02, mais où les résultats affichés concernent le 28/01
![Image](https://github.com/user-attachments/assets/0b102f5c-802e-4224-8715-3699c1965dff)

**Comment by AdelineCelier** [comment]
Avant d'essayer de trouver une nouvelle solution, creuser les raisons des pb de rendering dans la side window.

**Comment by ivangabriele** [comment]
A priori poas de soucis React côté perf donc on peut revenir à une version simplifié du useLoadingState()..

**Comment by louptheron** [comment]
Ce souci n'est plus actif en PROD. Par contre je rajoute un suivi des temps de chargements car ils semblent toujours lents.
