### ISSUE TITLE
SSO - Ajouter un encart bloquant de notification de déconnexion lorsque l'utilisateur n'est plus connecté

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#3759]
Il arrive qu'un utilisateur laisse MonitorFish en background, le token expire et rend inutilisable l'interface, avec des erreurs 401 en réponse aux APIs.
Il faut rediriger sur `/login` dans ce cas.

**Comment by louptheron** [comment]
@AdelineCelier Je vais faire quelques tests de mon côté. Tu peux aussi tester que la connexion/déconnexion fonctionne bien ?

**Comment by louptheron** [comment]
PR revert

**Comment by AdelineCelier** [comment]
@louptheron comme convenu, qques retours UI sur la page de connexion : 
- retirer le logo EIG et centrer le texte "MonitorFish" au-dessus du bouton "Se connecter avec Cerbère"
- Pour qu'il soit plus lisible 
- mettre en Regular et un peu plus gros le texte "Vous accédez à une application réservée aux services de l'Etat"

**Comment by AdelineCelier** [comment]
C'est bon pour moi !
