### ISSUE TITLE
Préavis et fiche navire – Problème UI sur les chevrons de la liste des espèces

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#3762]
Vu dans les préavis mais il me semble qu'il y a le même pb côté fiche navire – à vérifier. 

![Image](https://github.com/user-attachments/assets/766440d8-e7aa-4515-8ad8-a9d1a8f91319)

**Comment by AdelineCelier** [comment]
@ivangabriele le décalage m'a l'air réglé, en revanche j'ai l'impression que tous les chevrons sont à l'envers maintenant (dans les préavis et dans la fiche navire) : 
![Image](https://github.com/user-attachments/assets/98a046b2-4e0b-405c-9fe4-4a86c1f5311d)
![Image](https://github.com/user-attachments/assets/2227e2d7-857e-449f-885d-b343e76014c4)

**Comment by louptheron** [comment]
OK
