### ISSUE TITLE
Paramétrage diffusion préavis – Créer la liste des unités recevant des préavis

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#3767]
Dans le backoffice Fish, créer une vue liste des unités recevant des préavis. 
[Ecran ici](https://xd.adobe.com/view/bb960410-7180-46fe-9ee5-3f7d155d99b4-eec5/).

**Comment by ivangabriele** [comment]
Duplication de #3768 ?

**Comment by AdelineCelier** [comment]
@ivangabriele globalement ça marche bien, qques retours : 

- [ ] problème d'affichage quand il y a de nombreux ports : tronquer la liste et mettre un title
![Image](https://github.com/user-attachments/assets/30fcc34d-6b2e-40b0-bdef-1e5cf27f6857)

- [ ] pour donner plus de place à la liste des ports, on peut réduire la colonne avec le nom des unités (à 400 px max par ex) et donner l'espace gagné aux colonnes sur les ports

- [ ] en testant la vue, je me dis qu'on peut rajouter un filtre pour ne voir que les unités recevant des préavis, si pas trop compliqué. Parce que là il y a un paquet d'unités qui ne sont pas du tout concernées par les préavis à ce stade (même si c'est bien de quand même les avoir dans la liste, au cas où justement il faut les inclure dans la diffusion). Je propose de rajouter sur la ligne des filtres une case à cocher "unités recevant des préavis" (avec comme critère "l'unité doit être abonnée à au moins un port").

**Comment by ivangabriele** [comment]
@AdelineCelier Un petit bonus à connaître que j'avais ajouté sans que ce soit dans les specs : on peut taper un nom d'un port dans le champ de recherche ^^.

**Comment by AdelineCelier** [comment]
@ivangabriele ah ok bien noté pour la recherche dans le nom des ports ! Comme il y avait un filtre sur les ports je ne l'avais pas forcément envisagé, mais c'est en effet pas mal qu'on puisse rechercher ce qu'on veut dans la barre de recherche. Si on pousse la logique je serais pour rajouter la possibilité de chercher aussi dans les administrations dans ce cas. Je le mets dans la liste des qques retours qu'il reste.

- [ ] pouvoir taper le nom d'une administration dans la barre de recherche
- [ ] il y a en effet un problème sur le tableau, qui s'affiche trop en longueur et dépasse de l'écran
- [ ] pour la case à cocher permettant de filtrer les unités ayant des diffusions paramétrées, je trouverais plus clair qu'on l'appelle "unités recevant des préavis". A moins que cela te semble faux ? mais "au moins une diffusion" ne me paraît pas très clair.

**Comment by louptheron** [comment]
@AdelineCelier je reprends ce ticket, tu tranches quoi pour le 3ème point ?

**Comment by AdelineCelier** [comment]
@louptheron on part sur "unités recevant des préavis" !

**Comment by louptheron** [comment]
OK
