### ISSUE TITLE
Paramétrage diffusion préavis – Créer la vue par unités permettant de paramétrer les préavis qui lui sont diffusés

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#3768]
Paramétrages pouvant être faits à l'échelle d'une unité : 
- modifier les ports auxquels elle est abonnée par défaut
- ajouter une diffusion suppl. de préavis par port
- ajouter une diffusion suppl. de préavis par segments
- ajouter une diffusion suppl. de préavis par navire
Ecrans [2](https://xd.adobe.com/view/bb960410-7180-46fe-9ee5-3f7d155d99b4-eec5/screen/c9cfe37f-5e01-4e76-ba4c-49e3a2da6444/) à [4](https://xd.adobe.com/view/bb960410-7180-46fe-9ee5-3f7d155d99b4-eec5/screen/41c4463e-ac3e-4392-8a7c-d31c7c0644ab/).

**Comment by AdelineCelier** [comment]
@ivangabriele il reste qques points à revoir, on peut en discuter de vive voix si besoin : 

- [ ] quand j'ajoute un port de diffusion supplémentaire (hors diffusion de base, 2è tableau), il ne doit pas s'ajouter à la liste des ports de diffusion de base. Ce sont deux listes différentes et indépendantes, puisque quand j'ajoute un port supplémentaire et qu'il n'est pas dans la liste de diffusion de base, tous les préavis de ce port seront envoyés à l'unité **sans vérification par le CNSP** 
**=> donc ces préavis ne doivent pas être taggués comme "à vérifier" dans l'app, quand bien même ils ont une note > 2,3. C'est pareil pour les segments et les navires supplémentaires. Si besoin on peut en reparler de vive voix.**

- [ ] la recherche des navires ne fonctionne pas : quand je tape qqch dedans, rien ne remonte.

- [ ] il n'y a pas de pop-up de confirmation quand je supprime un des ports de diffusion de base de l'unité (1er tableau), en rajputer une. 

- [ ] il n'y en a pas non plus quand je supprime un segment supplémentaire. En description de la pop-up de confirmation de suppression :  "l'unité ne recevra plus les préavis de ce segment qui sont hors de la diffusion de base."

- [ ] le wording de la pop-up de confirmation de suppression d'un port supplémentaire n'est pas bon (c'est celui pour le 1er tableau). En description, mettre : "l'unité ne recevra plus les préavis de ce port qui sont hors de la diffusion de base."
![Image](https://github.com/user-attachments/assets/7992a153-80e0-4acf-930b-26e7157f00b0)

- [ ] ajouter la possibilité de chercher dans les menus déroulants des ports et des segments de flotte

- [ ] comme pour l'icône édition dans la vue liste, mettre l'icône "delete" en tertiary 20x20 px, sans fond bleu. 
![Image](https://github.com/user-attachments/assets/68a4e094-61b6-4a5b-814b-5c021ae5bc62)

- [ ] Remplacer les mots "aucune donnée" par "aucun port/segment/navire ajouté" et la mettre en Slate Gray
![Image](https://github.com/user-attachments/assets/64c640b2-a2b5-48ea-ba08-67385dd0104c)

- [ ] Mettre plus d'espace (16 px) entre "aucun navire ajouté" et la barre de recherche de navire
![Image](https://github.com/user-attachments/assets/86efa583-6038-4c88-8038-67582fbd4b03)

- [ ] Mettre 40 px d'écart entre le titre "[Nom de l'unité] - Paramétrage..." et "Ports de diffusion de base..."
![Image](https://github.com/user-attachments/assets/5c25a03d-193e-49cd-805f-d1b130f4368c)

**Comment by AdelineCelier** [comment]
@ivangabriele il reste encore qques trucs : 

- [ ] il manque la recherche dans le menu déroulant des ports
- [ ] concernant la pop-up de confirmation de suppression des ports : il faut ajuster le wording dans le cas où l'on supprime un port pour lequel la case "tous les préavis" a été cochée : "Êtes-vous sûr de vouloir supprimer ce port de diffusion ? L’unité ne recevra plus les tous les préavis des navires débarquant dans ce port."
- [ ] sur l'UI de la pop-up de confirmation : 
  - agrandir les boutons pour éviter que le "confirmer la suppression" soit tronquée 
  - passer le texte en Gunmetal
- [ ] mini retouche de marge : 
![Image](https://github.com/user-attachments/assets/a547598c-faef-4133-a9e0-2acab3947de6)

**Comment by louptheron** [comment]
OK en inté
