### ISSUE TITLE
Zones REG - Ajouter le Règlement (UE) 2024/2594

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#3770]
Un nouveau réglement européen a été publié avec des zones de gestion de ressources (interdictions d'engins suivant les zones). C'est le Règlement (UE) 2024/2594

**Comment by AdelineCelier** [comment]
C'est bon, ce nouveau règlement apparait bien dans le menu déroulant "ensemble réglementaire".
