### ISSUE TITLE
Afficher les acquittements sur les opérations multiples en ERS

### ISSUE THREAD

**Issue by VincentAntoine** [MTES-MCT/monitorfish#3774]
Dans le cas d'opérations multiples (plusieurs déclarations au sein d'un même message ERS, avec donc un seul `report_id`), l'acquittement ne s'affiche que sur la première opération.

Cf les 3 opérations de captures ayant le `report_id` `OOF20241015066000`.

![Image](https://github.com/user-attachments/assets/e7dc3d64-ef1a-4fe1-9eb0-361700a271ee)

**Comment by louptheron** [comment]
à vérifier en PROD
