### ISSUE TITLE
Signalements – Pouvoir supprimer un signalement archivé

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#3784]
Aujourd'hui, une fois qu'un signalement est archivé on ne peut plus le supprimer, alors que c'est parfois nécessaire
A faire : 
- reprendre la même UI que pour le signalement actif pour ajouter l'icône de suppression sur les signalements archivés.
- comme pour les signalements actifs, ajouter une modale de confirmation de la suppression

NB : une fois la fonctionnalité faite, il faudra supprimer le signalement test archivé que j'ai bêtement fait en prod sur le navire "Ptit Mumu (CFR FRA000787593).

**Comment by louptheron** [comment]
Bug identifié : lorsqu'on clique sur "archiver" dans la fiche navire : `vesselReportingWithoutFirstFoundReportingType is undefined`
