### ISSUE TITLE
Fiche navire - Afficher les permis illimités

### ISSUE THREAD

**Issue by emmasutherland-cnsp** [MTES-MCT/monitorfish#3795]
Lorsque le permis de nav est illimité, il s'affiche avec un - .
Possible d'afficher permis illimité à la place ?

**Comment by louptheron** [comment]
@VincentAntoine L'information "illimité" est disponible ?

**Comment by VincentAntoine** [comment]
Vu avec le CSN de Lorient, c'est un poil plus sioux que ça car un permis de navigation peut être délivré sans date de fin (permis illimité) mais suspendu après sa délivrance. Les infos sont saisies et mises à jour par les CSN dans Gina (qui est la donnée source pour les permis de nav, qui est reportée dans Poséidon et Navpro), et il y a donc à la fois une date d'expiration et un statut. Pour savoir si un permis est valable il faut à la fois son statut (qui ne doit pas être suspensu) et sa date d'expiration (qui ne doit pas être passée).
Donc il va falloir qu'on ajoute un champ "Etat du permis de navigation" en plus de la date d'expiration.
