### ISSUE TITLE
Navires - Ajouter les  `supply` dans la base `vessels`

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#3799]
Il est impossible de rentrer le contrôle du navire KERSAINT (935546), ce navire n'est pas dans la table `vessels`.

Le navire existe bien sur NAVPRO mais en activité "commerce" avec statut "armé". En réalité il s'agit d'un navire supply, il est donc assimilé à la pêche au regard du droit UE.

Sur la fiche NAVPRO du navire, dans la case "Modèle" il est indiqué "Assistance thonier". On peut utiliser cette information pour l'ajouter si on ne veut pas ajouter tous les navires de commerce.

**Comment by VincentAntoine** [comment]
Je comprends qu'il y a deux champs qui permettent d'identifier les navires supplémentaires à importer :
- Le champ `Modèle` de NAVPRO : le KERSAINT est le seul navire de modèle "Assistance thonier". On peut donc ajouter un critère sur ce champ pour spécifier que l'on souhaite importer les navires ayant Modèle = Assistance thonier, mais en pratique ça revient à spécifier qu'il faut importer le KERSAINT puisque c'est le seul navire de ce type
- le champ `Type de navire` de NAVPRO : il y a dans NAVPRO 63 navires ayant Type de navire = "RAVITAILLEUR / SUPPLY / OFFSHORE" --> si d'autres navires sont pertinents pour le contrôle pêche alors on peut utiliser plutôt ce critère, mais si le KERSAINT est le seul, à nouveau il vaut mieux spécifier que l'on souhaite importer le KERSAINT plutôt que d'importer 62 navires de ravitaillements inutiles.

**Comment by VincentAntoine** [comment]
Suite au retour du CNSP, seul le KERSAINT est concerné.
