### ISSUE TITLE
Ajouter le port Pérols dans la liste des ports pour CR Mission contrôle débarque

### ISSUE THREAD

**Issue by emmasutherland-cnsp** [MTES-MCT/monitorfish#3857]

**Comment by ferchaudfabien** [comment]
Pour le port de Perols:

Country_code_iso2: FR
region: 34
Locode: FRPOS
Latitude: 43.553333
Longitude: 3.969833
Facade: MED
faoçareas: 37.1.2
is_active: true

**Comment by louptheron** [comment]
@VincentAntoine

**Comment by VincentAntoine** [comment]
La donnée source est dans une table du cross, administrable via QGIS.
Après avoir fait les modifs, me prévenir pour que je fasse une synchornisation pour mettre à jour le référentiel de Monitorfish.
