### ISSUE TITLE
Permis de navigation

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#3860]
Bonjour,

Nous avons vu qu'un navire avait vu son permis de navigation suspendu provisoirement, pourtant sur monitor il apparait toujours en "illimité" avec le tiret. Serait il possible de faire une modification pour que ce genre de situation soit plus facilement lisible ?

![Image](https://github.com/user-attachments/assets/a3c7b52a-825e-4482-9a42-1bb9b36dbb43)

**Comment by louptheron** [comment]
Bonjour,
Nous avons actuellement un souci de synchronisation sur les données navires, nous regardons ça.

**Comment by AdelineCelier** [comment]
Ce ticket n'est-il pas en doublon avec le #3795 ?

**Comment by louptheron** [comment]
Si, je clôture
