### ISSUE TITLE
Migrer le Geoserver et les tables des zones à DAM-SI

### ISSUE THREAD

**Issue by VincentAntoine** [MTES-MCT/monitorfish#389]
## Reste à faire
- [x] Copier les zones du CROSS à DAM-SI toutes les X minutes (ou avec un check des diff)
- [x] Faire tourner un Geoserver à DAM-SI
- [ ] Rajouter une deuxième variable d'env pour faire les tests de performances abec le Geoserver localisé chez DAM-SI
- [ ] Mettre en place un DNS & certificat HTTPS sur le Geoserver du CROSS-A
  - Si les tests de performances sont concluants, pointer le traffic des couches sur DAM-SI
  - Si les tests de performances ne sont pas concluants, pointer le traffic des couches sur le CROSS-A

**Comment by louptheron** [comment]
## Reste à faire
- [ ] Rajouter une deuxième variable d'env pour faire les tests de performances abec le Geoserver localisé chez DAM-SI
- [ ] Mettre en place un DNS & certificat HTTPS sur le Geoserver du CROSS-A
  - Si les tests de performances sont concluants, pointer le traffic des couches sur DAM-SI
  - Si les tests de performances ne sont pas concluants, pointer le traffic des couches sur le CROSS-A

**Comment by louptheron** [comment]
à faire en prod:

- Mettre à jour le repo git pour télécharger le nouveau `docker-compose`
- Mettre à jour l'application en utilisant `cd infra/remote && docker-compose pull && docker-compose up -d` (sans le `--build app` pour également créer le conteneur `geoserver`)
