### ISSUE TITLE
Fiche navire – L'info du contact navire n'est souvent pas à jour

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#3891]
Info remontée par Kevin lors de l'atelier de ce matin : l'info de contact du navire n'est souvent pas à jour. 
Deux questions : 
- @VincentAntoine, où récupère-t-on cette donnée ? Sait-on si cette source est fiable ?
- Si on se rend compte que le n° n'est pas le bon, peut-on envisager de le corriger manuellement ? Si oui, sous quelles conditions ?

**Comment by VincentAntoine** [comment]
Hello,
Les données de contact navire (téléphone(s) et email(s)) sont pris dans la base Navpro. Les données sont visibles dans l'appli Navpro, onglet "Intervenants". Je ne peux pas les modifier, mais peut-être qu'avec les bons droits c'est modifiable depuis Navpro, il faudrait demander à Fabien ou à DSI.

**Comment by AdelineCelier** [comment]
@emmasutherland-cnsp tu crois que tu peux voir avec le pôle SIP s'ils ont la main dans Navpro sur ces données ?

**Comment by VincentAntoine** [comment]
Vu avec le SIP, ils ont la main dessus pour corriger les infos dans Navpro. J'ai fait un mail à cnsp france pour répondre à la question et partager l'info à tous.
