### ISSUE TITLE
La description de la note de probabilité est incorrecte quand la priorité est 1

### ISSUE THREAD

**Issue by VincentAntoine** [MTES-MCT/monitorfish#3926]
Quand la note de priorité de contrôle du segment le plus prioritaire d'un navire est de 1, la description est "pas de segment" :

![Image](https://github.com/user-attachments/assets/b1d8c094-9853-42a1-b34e-a914ffc35099)

1 est aussi le niveau de priorité par défaut en l'absence de segment, auquel cas cette mention est correcte, mais il faut la retirer quand la note est de 1 alors que le navire a un / des segment(s).

@louptheron

**Comment by louptheron** [comment]
à vérifier en PROD

**Comment by AdelineCelier** [comment]
Ok super !
