### ISSUE TITLE
Afficher le détail des sous-sommes pour une espèce du JPE

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#397]
Utile pour les personnes traitant les certificats de capture : voir le détail de présentation des poids et % des captures.

**Comment by AdelineCelier** [comment]
Écrans faits et ajoutés au XD, quelques petites spécifications UI : 
- typo pour les poids et pourcentages à l'intérieur des cases : 11 px partout (à voir ensemble si ça fait trop petit)
- typo pour les poids et pourcentages principaux : medium, poids en #515151 et pourcentage en #969696
- typo pour les sous-poids et sous-pourcentages : regular, tout en #969696
- couleur des cases principales : bordure en #969696, fond en #EDEDED
- couleur des sous-cases : bordure en #D6D6D6, fond blanc
- toujours laisser une marge d'au moins 10 px dans les cases et entre le texte et le chevron (cf. capture ci-dessous)
![image](https://user-images.githubusercontent.com/71878648/124455621-1572c300-dd8a-11eb-9d8b-2f74d8d10f55.png)

**Comment by AdelineCelier** [comment]
Très chouette, les Brexiteurs nous remercieront ;)

Qques petits ajustements : 
- le 11 px c'était pour l'intérieur des cases, en revanche je laisserais bien les noms des espèces en 13 px. Qu'en penses-tu ?
- après réflexion je me rends compte qu'il serait plus cohérent de garder le même système de couleur de typo pour les sous-cases que pour les cases principales (poids en #515151 et pourcentage en #969696), et de mettre les sous-cases en light, pour créer un contraste suffisant avec les principales.  
- idem, finalement je pense qu'il vaut mieux laisser la bordure des sous-cases de la même couleur que les cases principales (#969696)...sorry pour le revirement 
- rajouter un espace de 4 px entre le bas de la sous-case ouverte, et la case principale suivante : 
- 
![image](https://user-images.githubusercontent.com/71878648/126483741-2c1079dd-db27-4877-8c83-bcc7698d5f47.png)

**Comment by AdelineCelier** [comment]
@louptheron je ne vois pas de changements liés aux derniers retours, est-ce que c'est un bug de mon côté, ou est-ce que tu n'as pas pu tout traiter ? 
- les noms des espèces à côté des cases sont toujours en 11px
- le texte des sous-sommes n'est pas en light et le pourcentage n'est pas en slate gray (c'est vrai que ça ne se voyait pas trop sur la capture d'écran)
- la bordure des sous-cases doit être de la même couleur que la bordure des cases principales (en Slate Gray)
- espacement de 4 px (cf. ci-dessus)

S'il y a des choses qui ne vont pas, dis-moi on en discute

**Comment by AdelineCelier** [comment]
C'est top, ça rend nickel comme ça !
