### ISSUE TITLE
Préavis – Le tag "x signalements" n'apparaît pas dans la vue liste des préavis quand le signalement est issu d'une alerte

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#3978]

**Comment by louptheron** [comment]
Done, cf https://github.com/MTES-MCT/monitorfish/pull/3977/files#diff-6734acf3bc5a4fe21af0fdf1d178eb37be7c197224f618a770aad2cebd7e2871L163
