### ISSUE TITLE
Rajouter un flag "position manuelle" dans l'affichage de la liste des positions VMS d'un navire

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#402]
Dans le cas d'un 4h-report pour cause d'avarie VMS, le service SIP rentre manuellement les positions du navire dans Poséidon. Il faut les différencier dans MonitorFish des positions "normales" des navires.

**Comment by AdelineCelier** [comment]
Deux versions pour l'instant : 

1/ une pastille avec un point d'exclamation sur chaque ligne de position, avec en survol l'explication. Pour ne pas augmenter la largeur du menu j'ai dû réduire la colonne "Vitesse" en abréviant "Vit.", ce qui est un peu moche
![image](https://user-images.githubusercontent.com/71878648/124478518-8ecbdf00-dda5-11eb-8e05-2ba83a592487.png)

2/ une pastille jaune avec un point d'exclamation au niveau du titre du menu + des bandes jaunes face à chaque position manuelle. 
![image](https://user-images.githubusercontent.com/71878648/124478551-97241a00-dda5-11eb-866a-2c5370ca9184.png)

@louptheron wdyt ?

**Comment by louptheron** [comment]
@AdelineCelier La 1ère version est cool je trouve avec la bulle !

On peut pas mettre une icône plus spécifique ? Genre https://thenounproject.com/search/?q=handwriting
Un truc qui montre que c'est fait "à la main" ?

**Comment by AdelineCelier** [comment]
Mmmh je pense que la pastille est trop petite (14x14 px) pour accueillir une icône trop complexe. On est dans un espace assez contraint, c'est pour ça que je m'en tiendrais à un simple indicateur visuel qui attire l'attention. 
Après si tu penses que c'est une info vraiment nécessaire, je peux tenter, mais faudra augmenter la pastille (au moins 18x18, voire 20x20).

**Comment by AdelineCelier** [comment]
Laisser la pastille mais remplacer le ! par un m comme manuel

**Comment by AdelineCelier** [comment]
Pastille avec le M faite, exportée dans le dossier "Assets et typos"
Écran XD mis à jour (n° 41)

**Comment by louptheron** [comment]
@AdelineCelier 
![Screenshot from 2021-09-09 08-47-21](https://user-images.githubusercontent.com/14853556/132636675-65ac16e8-8d4b-4811-be20-380ddca43045.png)

**Comment by AdelineCelier** [comment]
Allez c'est validey 👍🏻
