### ISSUE TITLE
Paramétrer les coordonnées de la carto : en Degrés Minutes Secondes, mais aussi en Degrés Minutes Décimales

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#403]

**Comment by AdelineCelier** [comment]
@louptheron 
Est-ce que tu pourrais juste rajouter un peu de marge à droite et à gauche des coordonnées ? Dans les maquettes j'avais mis 8px, j'ai l'impression que c'est un peu moins ici : 
![image](https://user-images.githubusercontent.com/71878648/123999762-23fc5b80-d9d3-11eb-831a-081c37872bba.png)

**Comment by louptheron** [comment]
Done, wdyt ?

**Comment by AdelineCelier** [comment]
Top ! Juste rajouter le fait que cliquer n'importe où ailleurs referme l'encart de paramétrage des coordonnées (qu'il n'y ait pas besoin de recliquer sur les coordonnées pour le refermer)

**Comment by louptheron** [comment]
Done, wdyt ?
