### ISSUE TITLE
Utiliser l'outil mesure en même temps qu'afficher une piste navire

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#426]

**Comment by louptheron** [comment]
@AdelineCelier Comment faire ? Aujourd'hui, l'affichage de la piste navire se fait quand les informations navire sont affichées.
Il faudrait revoir cela ; on peut se pencher dessus dans le cadre de l'affichage de plusieurs pistes navires en même temps également.

**Comment by AdelineCelier** [comment]
Résolu avec les évolutions du ticket #118 :
Le ctrl+clic ou le clic droit sur un navire permet de voir sa piste, tout en interagissant avec tous les outils (mesure, mais aussi affichage de la piste navire - quand on clique une 2è fois sur le bateau par ex, sans ctrl)
