### ISSUE TITLE
Alerte marge de 10%

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#427]
S'assurer que nos alertes sont conformes avec les calculs de l'UE.

Cf. discussion avec Anne-So

**Comment by louptheron** [comment]
On regarde PNO/LAN alors qu'il faudrait faire FAR/PNO selon l'UE

**Comment by AdelineCelier** [comment]
Conclusion : notre formule avec le PNO est plus cohérente que celle avec le FAR, on reste donc comme ça, sauf si objection nous est remontée. On archive le ticket.
