### ISSUE TITLE
Filtrage de la liste des réglementations de l'interface REG

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#437]
Description

```
En tant qu'administratrice des couches réglementaires
Je veux filtrer les couches réglementaires
Afin d'afficher seulement celles qui m'interressent
```

Elements:
- Faire une requête WFS-T pour mettre à jour une REG: https://gist.github.com/SKalt/0f4b757209687331c8a1d40aecbf69f9

**Comment by AdelineCelier** [comment]
Comme vu avec @louptheron, j'ai aussi modifié le bouton "loupe" sur la barre de recherche : ce n'est plus un bouton pour lancer la recherche, c'est juste une icône pour indiquer la barre de recherche. La recherche se lance et s'actualise au fur et à mesure que l'on tape dans la barre de recherche.

Cf. écrans : https://xd.adobe.com/view/b1ea0a09-9296-419d-84cb-f72afc2931eb-e4b9/

**Comment by AdelineCelier** [comment]
Top, le filtrage me semble fonctionner nickel.
Juste petit point concernant le cas où il n'y a pas de reg qui remonte dans "RÉGLEMENTATION FRANCE" ou "RÉGLEMENTATION UE". Très bonne idée d'avoir mis une phrase disant "aucune zone pour ce territoire", juste la passer en #969696, et augmenter la marge entre le titre et la phrase : 25 px, qu'elle soit alignée avec le texte de la colonne d'à côté.

![image](https://user-images.githubusercontent.com/71878648/126497386-70b6b7b1-85e1-4add-b94e-76e0145f2695.png)
