### ISSUE TITLE
Créer une nouvelle reglementation

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#452]
Cf. https://dbauszus.medium.com/wfs-t-with-openlayers-3-16-6fb6a820ac58

**Comment by AdelineCelier** [comment]
### Retours UX ###

- [ ] le bouton "revenir à la liste complète des zones ne fonctionne pas
- [ ] 

### Retours UI ###
- [ ] Marges globales de la page : au minimum 40 px à gauche et à droite, 30 px au-dessus du titre "saisir une nouvelle réglementation"
- [ ] le bouton "revenir à la liste..." doit être sur la même ligne que le titre, le texte est aligné verticalement avec le reste de l'interface (40 px), c'est le chevron qui "déborde" (cf. capture ci-dessous)
![image](https://user-images.githubusercontent.com/71878648/130786705-3b3a212f-b652-4806-886d-87ec345a605f.png)
- [ ] marge de 8px entre le texte du titre "identification de la zone reg" et le filet juste en-dessous
- [ ] petite coquille d'accent : "ensemble r**é**glementaire" (libellé à gauche du menu déroulant + texte dans le champ libre qui apparaît quand on veut ajouter un nouvel ensemble)
- [ ] longueur des menus déroulants : je ne sais pas si c'est un composant facilement modifiable, mais si possible allonger tous les menus déroulants afin que le texte "choisir une thématique" ne soit pas tronqué (pi ils font 180 px de longueur dans les maquettes)
- [ ] marge de 20 px entre le libellé le plus long de la colonne et les menus déroulants (cf. ci-dessous)

**Comment by AudreyBramy** [comment]
Note pour moi : 
Dans les variables, les composants, etc, remplacer : 
- [ ] remplacer zoneName par layerZone 
- [ ] zoneTheme par Topic 
- [ ] RegulationBloc par LawType

**Comment by AudreyBramy** [comment]
Note pour moi : 
refaire une passe sur les couleurs
