### ISSUE TITLE
Piste depuis le dernier DEP : requêter 4h avant la date du DEP pour bien avoir la piste depuis le port.

### ISSUE THREAD

**Issue by VincentAntoine** [MTES-MCT/monitorfish#457]

**Comment by VincentAntoine** [comment]
En profiter pour changer la date prise en compte : prendre la date de départ (value -> departureDatetimeUtc) et non la date de réception du message de départ.

**Comment by louptheron** [comment]
@VincentAntoine 
4h avant la date ça suffit non ?
Prendre la date de départ ne m'arrange pas, car j'utilise aussi cette fonction pour naviguer entre les marées...
