### ISSUE TITLE
Enlever les navires détruits dans la table `vessels` (champs présent dans ASTERIE)

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#459]

**Comment by VincentAntoine** [comment]
Ci-dessous les nombres de flotteurs par `situation` et par `statut` :

![image](https://user-images.githubusercontent.com/27647971/127154370-8644b0e4-1484-4481-a3d1-7ac811dbd83e.png)

Il y avait déjà un filtre sur la `situation` pour exclure les navires de plaisance et de commerce. et je rajoute maintenant un filtre sur le `statut` pour exclure les navires "Hors Service". On garde donc les navires encadré en blanc dans l'image ci-dessus.
