### ISSUE TITLE
SIP : étudier les données VMS pour avoir plus d'informations sur les avaries.

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#46]
Exemples:
- Représenter sur carte / sur la journée les coupures de messages
- Afficher les messages d'intrusions

Message d'intrusions:
Il s'agit d'un message formaté comme pour une information batterie (BA1, BA2,NOR) mais avec le code INT.
Nous n'avons pas connaissance d'autres cas que l'ouverture du capot de la balise où se message se déclenche.

**Comment by AdelineCelier** [comment]
Traité dans d'autres tickets sur les avaries VMS
