### ISSUE TITLE
BUG : l'onglet pêche ne se met pas à jour quand on change de navire

### ISSUE THREAD

**Issue by VincentAntoine** [MTES-MCT/monitorfish#465]
**Environnement**
Prod et intégration

**Comportement attendu**
Depuis l'onglet "pêche" d'un navire, si je clique sur un autre navire, les données JPE se mettent à jour et affichent les données du navire sur lequel j'ai cliqué

**Comportement observé**
Depuis l'onglet "pêche" d'un navire, si je clique sur un autre navire, les données JPE ne se mettent pas à jour et affichent toujours les données du même navire

**Comment by AdelineCelier** [comment]
Cela me semble ok, à surveiller en prod. 
Il peut y avoir 2 secondes de latence si on clique au moment où l'appli refresh, à surveiller donc mais pour l'instant non bloquant.
