### ISSUE TITLE
Fonctionnalité facteur de risque

### ISSUE THREAD

**Issue by VincentAntoine** [MTES-MCT/monitorfish#467]
- [x] Présentation de restitution atelier (Vincent)
- [x] Data engineering (Vincent)
- [x] Écrans (Adeline) : 
  - [x] Administration des segments
    - [x] Définition des segments avec une liste d'engins, d'espèces et de zones
    - [x] Pilotage du niveau de priorité de contrôle des segments
  - [x] Opérationnel
    - [x] Détail des notes dans l'onglet résumé
    - [x] Notes sur la carte
    - [x] Paramétrage de l'affichage sur la carte (avec les étiquettes)
  - [x] Écran explicatif résumé + renvoi vers la documentation
- [x] Dev (Loup):
  - [x] Ecrans admin
  - [x] Ecrans ops

**Comment by AdelineCelier** [comment]
Les écrans pour le pilotage du facteur de risque seront faits après ceux des avaries VMS.

Notes pour la reprise du ticket : 

**Fonction principale de l'écran : piloter les priorités de contrôle des segments**
- fréquence : 1 fois/semaine, ou au moins 2 fois/mois
- le pilotage des segments se fait par façade, ce qui veut dire qu'un même segment peut se retrouver dans plusieurs façades, avec des priorités différentes
- mode d'édition : juste la note de priorité à modifier, avec menu déroulant au clic
- affichage du détail des segments au second clic, si par hasard Stéphane a un doute

**Fonction secondaire : ajouter, supprimer et mettre à jour les segments**
- fréquence : 1 fois/an, et peut-être ponctuellement dans l'année
- mode d'édition : il faut éviter les erreurs de saisie, et donc éditer les segments via un formulaire comme pour l'interface reg, avec menus déroulants quand c'est possible. 
- à voir comment formaliser la vue liste de tous les segments (liste avec chevrons et filets, ou bien tableau ?) et comment renvoyer vers le mode édition

**Comment by VincentAntoine** [comment]
@louptheron J'ai déterré ce ticket du backlog, que tu viens / es en train de traiter :)
