### ISSUE TITLE
Mettre à jour les fonds de carte Mapbox

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#497]
Deux fonds de carte sont publiés sur Mapbox :
- MonitorFish Antracithe clair (par défaut)
- MonitorFish Antracithe sombre

**Comment by louptheron** [comment]
Email envoyé à Mapbox

**Comment by AdelineCelier** [comment]
Le fond clair a bien été mis à jour, et et bien paramétré par défaut à l'ouverture de MF.

**Comment by AdelineCelier** [comment]
Top que tu aies réorganisé les fonds de carte, c'est plus logique que celui par défaut arrive en premier :)

En revanche le fond de carte sombre a oublié son filet derrière lui ;)
![image](https://user-images.githubusercontent.com/71878648/132516884-ac0e9e22-5616-4804-bf8d-039d9c042f46.png)

**Comment by louptheron** [comment]
![Screenshot from 2021-09-08 17-32-02](https://user-images.githubusercontent.com/14853556/132539621-34a457a3-e120-4176-9202-e2c91812a014.png)

Pas chez moi...

**Comment by AdelineCelier** [comment]
@louptheron j'ai l'impression que si, c'est juste qu'il est collé au bas et qu'on le voit moins du coup...t'es sur Chrome toi c'est ça ?

**Comment by louptheron** [comment]
Avec un fond blanc ?
Je suis sur Firefox.

![Screenshot from 2021-09-09 08-49-27](https://user-images.githubusercontent.com/14853556/132636832-fd1c0dd2-26af-4cee-905c-5d16e7cbb1ca.png)

**Comment by AdelineCelier** [comment]
ah oui zut j'avais oublié le fond de carte marine...en fait il faudrait plutôt mettre une légère ombre peut-être. 
Bon laisse comme ça du coup pour l'instant, je me fais un ticket "ombre des menus".
