### ISSUE TITLE
Créer un filtre même s'il n'y a pas de navires dans le tableau

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#505]

**Comment by AdelineCelier** [comment]
@louptheron Cela fonctionne, après je me demande s'il ne faut pas signaler par un petit encart quelque part que c'est normal que rien ne s'affiche sur la carte, du genre : "Il n'y a pas de navire dans ce filtre"
wdyt ?

**Comment by louptheron** [comment]
Done!

**Comment by AdelineCelier** [comment]
ok pour moi
