### ISSUE TITLE
Re-ordonner les colonnes de l'extraction VMS pour être iso-QGIS

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#510]
Les moyens aéro ont besoin d'un tableau dans un format précis.
Il faudrait donc que les tableaux de situation VMS présentent automatiquement ces colonnes, dans cet ordre : 
- quartier
- CFR
- call sign
- nom du navire
- GDH
- latitude 
- longitude
- cap
- vitesse

Au moment de l'export du tableau, il faudrait que le réglage par défaut soit : les colonnes ci-dessus sont cochées, et le reste est décoché, libre aux agents de rajouter les infos qui les intéressent.

**Comment by AdelineCelier** [comment]
@louptheron c'est good pour le tableau extrait à partir de la liste des navires.
Question : faut-il faire la même chose pour le tableau extrait à partir d'une fiche navire ? Est-ce que c'est une demande qui t'est remontée ou non (de la part de Fabien ou autre) ?

**Comment by louptheron** [comment]
@AdelineCelier Non, j'ai pas de remontée sur ce tableau, c'était vraiment pour les situations VMS pour les aéros.
