### ISSUE TITLE
Trouver un moyen de stabiliser WikiFish

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#530]
*Constat*
WikiFish saute souvent, comme le Geoserver. Cela m'arrive régulièrement de ne plus avoir accès au site.
Les documents contenus dans WikiFish sont des données de documentation, au même titre que le reste, et ce serait intéressant de les partager plus largement au sein de la DAM.

*Suggestions*
- laisser WikiFish à Étel mais trouver une solution au fait que le serveur saute régulièrement
- déplacer WikiFish à Saint-Malo ? (mais le risque est que le SI nous demande de tout mettre dans le Redmine)
- déplacer la doc de WikiFish dans une autre doc, comme notre Git ? En notant que cette doc doit avoir une diffusion restreinte, les interviews ayant des passages "sensibles".

**Comment by louptheron** [comment]
Regarder la mem utilisée par WikiFish

**Comment by AdelineCelier** [comment]
Je vois que tu as bougé ce ticket, est-ce que c'est parce que vous allez virer WikiFish ? 
En vrai je me rends compte que je ne l'utilise plus, on pourrait le virer mais il faudrait juste que je récupère ce qu'il y a dessus avant !
