### ISSUE TITLE
[BUG] Le label est affiché même quand la position est caché à cause de la visibilité

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#545]

**Comment by AdelineCelier** [comment]
Lorsque je change les paramètres d'affichage des pistes, les étiquettes des navires qui disparaissent s'en vont bien, mais seulement lorsque je bouge le zoom ou la carte.
Pour moi ce n'est pas un gros problème, mais si c'est rapide à régler c'est mieux. 
@louptheron wdyt ?

**Comment by louptheron** [comment]
@AdelineCelier Je modifie les étiquettes avec le zoom/mouvements et les paramètres d'affichage des pistes avec un cadencement pour des raisons de performance, il se peut donc qu'il y ait un petit délai. Je ne peux pas vraiment changer ça...
C'est ok niveau UX ?
