### ISSUE TITLE
Rajouter un raccourci dans le box Filtres pour ajouter un nouveau filtre

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#547]
Qui ouvre le tableau des navires

Cf. https://xd.adobe.com/view/64f60826-e259-414d-a9c1-0dedddd742e8-31a5/screen/11e83280-343e-4724-8f40-aa4257161441/

**Comment by louptheron** [comment]
![Screenshot from 2021-09-03 09-48-39](https://user-images.githubusercontent.com/14853556/131970247-aad14311-1ba4-4182-8228-25635fccc1f7.png)

**Comment by AdelineCelier** [comment]
@louptheron je propose une version ci-dessous, où j'ai rajouté un bouton "+" qui renvoie vers le tableau, et où j'ai aussi changé la case à cocher "masquer les autres navires" en reprenant l'icône de la fiche navire (c'est plus lisible et ça harmonise l'ensemble je trouve : 
![image](https://user-images.githubusercontent.com/71878648/132231053-81ba21d2-e4c4-4a36-8607-97fa7951d6b9.png)

C'est ok pour toi ?
