### ISSUE TITLE
Affichage des sous-sous-zones FAO à revoir

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#57]
Les noms des zones FAO/CIEM s'affichent en double, voire en triple.
![{7E4B3AE5-4449-4E36-ADAB-BB3106EDA9CF} png](https://user-images.githubusercontent.com/71878648/103672038-01393f00-4f7c-11eb-874a-655b34812838.jpg)

**Comment by AdelineCelier** [comment]
Et j'ai aussi l'impression que la couche FAO affiche aussi les ZEE, mais un peu dégueu...ça brouille pas mal la couche ZEE je trouve, s'il y a moyen de ne conserver que la plus précise ce serait 🔝 
![image](https://user-images.githubusercontent.com/71878648/103914419-1643d880-510a-11eb-937d-53c6cd34f6c5.png)

**Comment by AdelineCelier** [comment]
Il y a aussi un problème d'accents dans les noms des ZEE : 
![image](https://user-images.githubusercontent.com/71878648/104914685-ced20d80-598f-11eb-8062-eb259b753c56.png)

**Comment by louptheron** [comment]
Afficher les noms complets des zones

**Comment by AdelineCelier** [comment]
A demander en salle s'ils ont besoin des noms de sous-sous-zones 
- Si oui : on met en gras les sous-zones
- Si non : on masque les sous-sous-zones

**Comment by AdelineCelier** [comment]
Après demande en salle (à Xavier, Yves et Anaïs), a priori pas de besoin de connaître les dernières subdivisions des zones CIEM, on peut s'arrêter au 27.7.e.
Pour info, Xavier m'expliquait que le 4è numéro correspond au découpage de la subdivision CIEM entre une ZEE et la haute mer (genre 27.7.e.1 = morceau en ZEE française, 27.7.e.2 = morceau en eaux internationales). Donc vu qu'ils ont aussi les limites des ZEE, ils ne perdent pas l'info. 

@louptheron, tu peux donc masquer les noms de ces sous-sous zones.

**Comment by louptheron** [comment]
Vérifier avec les TAAFs froides, il me semblait que c'est sous-sous zones (27.7.e.2) étaient nécessaires
