### ISSUE TITLE
Afficher les étiquettes de notes des navires

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#577]
- [x] Affichage de l'étiquette et déplacement du menu des étiquettes (https://xd.adobe.com/view/64f60826-e259-414d-a9c1-0dedddd742e8-31a5/screen/6e4efe67-82ec-4423-ac9b-8ebdf73af65b/)
- [x] Affichage du détail de la note au clic sur la note afichée sur l'étiquette (https://xd.adobe.com/view/64f60826-e259-414d-a9c1-0dedddd742e8-31a5/screen/815956b6-ce54-46ef-8f79-b99a59046536/)
- [x] Tests E2E

**Comment by AdelineCelier** [comment]
**Retours sur les étiquettes**
- [ ] les chiffres des étiquettes ne semblent pas centrés (un peu trop hauts)
- [ ] comme dit dans le ticket sur le facteur de risque dans la fiche navire, rajouter des congés de 1px à tous les carrés contenant les chiffres + à la petite fenêtre contenant les 3 sous-chiffres du facteur. 
- [ ] Problème de marge en-dessous du dernier sou-chiffre de la fenêtre : 
![image](https://user-images.githubusercontent.com/71878648/134474243-d7e33f1a-25e4-4cb9-9d35-a0033fedcf2e.png)
- [ ] Le libellé "absence d'antériorité de contrôle" ne doit pas être affiché s'il y a eu 1 contrôle ou plus dans les 5 dernières années : 
`number_controls_last_5_years`
- [ ] Les libellés sont différents entre la carte et la fiche navire : 
![image](https://user-images.githubusercontent.com/71878648/134474481-a492cb4d-7884-4cf8-8ff5-004771c6428c.png)

**Comment by AdelineCelier** [comment]
- Retirer l'histoire du chevauchement des étiquettes, qui empêche de cliquer sur les éléments en-dessous
- On peut peut-être uniformiser les arrondis, et mettre du 1px à tous les coins des étiquettes, avec ou sans facteur de risque

**Comment by AdelineCelier** [comment]
Ok pour moi !
