### ISSUE TITLE
Ajouter le résumé du facteur de risque du navire

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#593]
- [x] Ecran résumé 1 : la note de risque globale et les 3 sous-notes sont dans la table risk_factors
- [x] Ecran résumé 2 :
  - les segments de flotte actuels, les engins à bord et les espèces à bord sont dans la table current_segments
  - le segment dont la note de risque est la plus élevée : pas dispo en l'état
  - pour les zones de la marée, j'ai vu que tu le fais dans le front à partir des espèces à bord, dis moi si c'est OK comme ça, sinon je peux ajouter une colonne dans current_segments
- [x] Ecran résumé 3 : nombre de contrôles en 5 ans, nombre d'infractions, de déroutements, de reconduites à quai et d'appréhension : on n'a rien pour le moment
- [x] Ecran résumé 4 :
  - priorité du segment : dans current_segments colonne control_priority_level  :c'est la note de priorité de contrôle la plus élevée parmi les segments du navire
  - le segment dont la priorité est la plus élevée : pas dispo en l'état
  - priorité du navire : dans la table control_anteriority colonne control_rate_risk_factor
  - nombre de contrôles sur les 3 dernières années : pas dispo en l'état
  - date de dernier contrôle : dans control_anteriority colonne last_control_datetime_utc

**Comment by AdelineCelier** [comment]
**Retours fiche navire**
- [ ] Petit décalage sur la jauge principale : 
![image](https://user-images.githubusercontent.com/71878648/134160336-faa476bf-76fe-4948-9b87-41f50412de78.png)
- [ ] Petit problème avec les espèces à bord. Peut-être faudrait-il ne prendre que les espèces qui concernent le segment ? Et quoi qu'il arrive lorsqu'il y a plus de deux lignes d'espèces, mettre des pointillés et une infobulle au survol avec la liste complète
![image](https://user-images.githubusercontent.com/71878648/134163615-06d4f598-c0f8-4650-b2ca-3218caef3d81.png)


**Retours modale d'explication du facteur de risque**
- [ ] tu as interverti les icônes entre probabilité d'infraction et score de détectabilité
- [ ] dans la "formule" du facteur à la fin de la première partie, il y a un léger décalage vers le haut de l'icône de probabilité d'infraction : 
![image](https://user-images.githubusercontent.com/71878648/134163147-8e37e1a5-52b7-4dc8-8b53-d493db15d457.png)

**Comment by AdelineCelier** [comment]
- [ ] Pour la note "Priorité de contrôle", il faut mettre un libellé qui correspond à la moyenne des deux sous-notes, même quand il n'y a pas de priorité de segment, et que cette sous-note équivaut à 1, et ce à la fois dans l'onglet résumé et dans la fenêtre avec les trois sous-notes sur la carte
![image](https://user-images.githubusercontent.com/71878648/134641633-b107a580-9840-4ef8-bc7f-dcdf8835b888.png)
- [ ] Retirer le petit tiret devant le libellé "Priorité du segment" quand il n'y a pas de segment
![image](https://user-images.githubusercontent.com/71878648/134641729-56a41390-a1d5-4eaf-af9a-de0e164eed8b.png)

**Comment by AdelineCelier** [comment]
Seul point qui est à régler : libellé de la (sous) sous-note "Priorité du segment" qui n'est pas encore bon ("priorité faible" s'affiche au lieu de "pas de segment"). 
Comme convenu, rectification à faire dans la prochaine mise en production.
