### ISSUE TITLE
Pour les situations VMS, faire en sorte d'exclure les navires qui sont à quai dans les zones

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#608]
- Soit on demande à Charlotte de retracer les zones
- Soit on le fait de notre côté

**Comment by VincentAntoine** [comment]
Depuis #721 ça doit répondre au besoin je pense ? @AdelineCelier

**Comment by AdelineCelier** [comment]
@VincentAntoine yes tu as raison, je ferme le ticket !
