### ISSUE TITLE
Affichage des champs texte de la reg en markdown

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#63]
Aller à la ligne quand il y a un tiret ou une puce dans les champs de la colonne "mesures techniques".
Pour tous les champs du résumé reg, limiter l'affichage à 4 lignes max, et mettre un lien "voir tout", qui déroule le reste du texte.
Cf. écrans : 
![Capture](https://user-images.githubusercontent.com/71878648/108710102-df881d00-7513-11eb-9a81-94744d030727.PNG)

**Comment by AdelineCelier** [comment]
Sur les écrans dans XD, j'ai mis un bouton/lien "voir toutes les mesures techniques" à la suite du texte. Tu te souviens on s'était dit que ça éviterait de trop gros pavés. 
Mais ce n'est pas prioritaire. 

![image](https://user-images.githubusercontent.com/71878648/103915252-4344bb00-510b-11eb-862f-29c8ed0b201e.png)

**Comment by AdelineCelier** [comment]
Faire une première passe sur les champs textes de la reg pour les mettre en markdown.

**Comment by louptheron** [comment]
Les textes sont déjà en markdown.
Afficher le markdown avec une lib JS.

**Comment by AdelineCelier** [comment]
Le champ "mesures techniques" n'apparaît plus.
