### ISSUE TITLE
Améliorer l'affichage des étiquettes

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#658]
- [ ] Afficher un mode "dégradé" des étiquettes (avec seulement le text en petit)
- [x] Cacher les étiquettes des navires qui sont dans les ports

**Comment by louptheron** [comment]
![Screenshot from 2021-10-05 11-23-28](https://user-images.githubusercontent.com/14853556/136000985-10c59a2c-7eee-43e2-8c13-4ba40c8ed897.png)

**Comment by VincentAntoine** [comment]
Masquage des navires au port fait dans #721.
Reste à faire le mode dégradé avec des étiquettes plus petites.

**Comment by AdelineCelier** [comment]
@louptheron je ferme ce ticket, je ne sais pas pourquoi il est dans le backlog alors qu'il est fait !
