### ISSUE TITLE
Ajustement UX/UI interface reg

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#672]
**Ecran d'accueil**
- [x] le bandeau de titre du résumé reg a disparu 👍🏻 
![image](https://user-images.githubusercontent.com/71878648/136759209-492793cc-c2a0-48cf-acc6-22a164dfa4fe.png)

**Formulaire**
- [x] dans le champ "géométrie", remplacer la mention en anglais "no results found" par "pas de tracé à associer". 👍🏻 
- [x] la pastille d'info pour la thématique de zone est un peu décentrée vers le bas + un peu trop éloignée vers la droite 👍🏻 
![image](https://user-images.githubusercontent.com/71878648/136759702-839a7869-66b6-4076-be85-31611286f1ee.png)
- [x] L'icône œil pour voir un tracé sur la carte et toute pitite :) 👍🏻 
![image](https://user-images.githubusercontent.com/71878648/136759915-8bc3c89a-5d94-44e1-a5dd-a8c0114667bc.png)
- [x] Style des typos dans les champs "nom" et "url" de la ligne "texte réglementaire" : Marianne 11px Light, en Slate Gray
- [x] #678 👍🏻 
- [x] Dans la modale "ajouter une réglementation à venir", il y a une barre de scroll même quand il n'y a rien à scroller
![image](https://user-images.githubusercontent.com/71878648/136760122-e7b94214-be62-42ff-9812-1697d0216391.png)

**Comment by louptheron** [comment]
@AdelineCelier, it's on you :)

**Comment by AdelineCelier** [comment]
Bon du coup il reste quelques points UI qui traînent, que je récapitule ici : 

- [ ] les barres de scroll de la modale "référence reg. à venir"
- [ ] petit problème de marge droite de la box jaune "réglementation à venir" (cf. commentaire juste au-dessus)
- [ ] il me semble que le style de la typo des champs Nom et URL de "texte reg." n'est pas encore tout à fait le même que dans les autres champs (font weight 500 pour Nom et URL, et 400 pour les autres)

Comme ce sont des points vraiment mineurs, je propose qu'on les mette dans un nouveau ticket qu'on remette dans le backlog. @AudreyBramy OK pour toi ?

**Comment by AudreyBramy** [comment]
Yep c'est ok pour moi

**Comment by AdelineCelier** [comment]
Ok, c'est bon, les problèmes restants sont référencés dans ce ticket #756 
Je ferme donc celui-ci.
