### ISSUE TITLE
[Backoffice] Ajout des périodes de pêches dans l'interface reg.

### ISSUE THREAD

**Issue by AudreyBramy** [MTES-MCT/monitorfish#673]

**Comment by AdelineCelier** [comment]
## Revue section période de pêche
**Revue UX**
- [ ] Dans l'idéal ne faudrait pas que deux plages de dates puissent se superposer. Aujourd'hui, je peux remplir une plage du 7 au 13 décembre, et une autre du 10 au 20 décembre par ex. 
- [ ] Idem pour les horaires. Mais bon c'est seulement si c'est pas trop long à faire. Cela permettrait de limiter les erreurs de saisie

**Revue UI**
- [ ] le filet en-dessous de "périodes / autorisées / interdites" doit arriver au même endroit que celui en-dessous de "horaires"
![image](https://user-images.githubusercontent.com/71878648/145041046-e8bbf3ff-ca34-4078-b958-4b91f7f7a932.png)
- [ ] problème de marge trop importante au-dessus du champ "plages de dates"
- [ ] l'intitulé "plages de dates" n'est pas aligné avec les champs des dates, et il n'est pas ancré en haut : il descend au fur et à mesure qu'on rajoute des champs de plages de dates 
![image](https://user-images.githubusercontent.com/71878648/145037864-1de616eb-393a-4d84-aa74-2ed364f747b1.png)
![image](https://user-images.githubusercontent.com/71878648/145037977-b7f9a567-b57d-4a58-a977-aa74819d0da8.png)
- [ ] Idem pour le champ "dates précises"
- [ ] les + et - me paraissent vraiment énormes...via l'inspecteur je vois qu'ils font 35 de haut, contre 34,5 pour les champs des dates. Est-ce qu'on pourrait tout mettre à 34 ? Et d'autre part tu peux les faire carrés (34x34), en réduisant les signes + et -

**Comment by AudreyBramy** [comment]
@AdelineCelier pour "Pour définir des horaires, faire un seul champ qui permet de choisir juste les heures, rondes ou demi (17h00 / 17h30 / 18h / 18h30, etc.)"
L'idée est de faire une liste déroulante avec les heures de 00:00 à 23:30 ?

**Comment by AdelineCelier** [comment]
Oui, qu'est-ce que tu en penses ? Je me dis que c'est peut-être encore le plus simple

**Comment by AudreyBramy** [comment]
Yep tout à fait.
Je suis en train de réfléchir sur les questions des chevauchements de dates.

**Comment by AdelineCelier** [comment]
>     * [x]  Cela me semblerait plus intuitif d'inverser les + et - : j'ai l'impression que la plupart du temps on commence par le + et pas par le moins...plusieurs fois je me suis trompée en faisant des tests et je me demande si ce n'est pas lié à ça.

Tu l'as fait pour les plages de dates mais pas pour les dates ;)

**Comment by AudreyBramy** [comment]
Pour le chevauchement on avait dit que ce n'était pas prioritaire et qu'on verrait à l'usage.

**Comment by AdelineCelier** [comment]
Etant donné qu'on va revoir le formulaire reg du backoffice avec les nouveaux composants, les dernières remarques UI de ce ticket ne sont plus pertinents, je le ferme.
