### ISSUE TITLE
[Backoffice] Agrandir les champs "nom" et "url" dans la section "réf. reg. en vigueur"

### ISSUE THREAD

**Issue by AudreyBramy** [MTES-MCT/monitorfish#678]

**Comment by AdelineCelier** [comment]
Haha d'acc ! Alors en y repensant je pense que le plus simple est d'agrandir les champs "Nom" et "URL", comme sur la maquette, sur laquelle ils font 250 px de long. Cela permet de mieux voir ce qu'on écrit/colle dedans : 
![image](https://user-images.githubusercontent.com/71878648/136928774-008cfb02-b74d-41dc-81f5-07ea931c8dfc.png)
![image](https://user-images.githubusercontent.com/71878648/136928819-8e1b57ca-19ab-4679-8c5d-3138af882cfa.png)

**Comment by AdelineCelier** [comment]
Cette fois c'est bon il est ok ;)
