### ISSUE TITLE
[Backoffice] Revoir la gestion des façades et des ensembles règlementaires.

### ISSUE THREAD

**Issue by AudreyBramy** [MTES-MCT/monitorfish#685]

**Comment by AudreyBramy** [comment]
Le script doit supprimer la colonne seafront et remplacer la valeur de law_type, comme suit :

law_type + seafront => nouveau law_type et on supprime seafront : 

Reg locale + Méditerranée, MED => Reg. MED
Reg locale + NAMO => Reg. NAMO
Reg locale + MEMN => Reg. MEMN
Reg locale + Outre-mer => Reg. Outre-Mer
Reg locale + Sud Athlantique, SA => Reg. NAMO
Reg locale + MED => Reg. Med
Reg Locale + NULL => 
R(UE) 2019/1241 + ... => R(UE) 2019/1241
R(UE) 1380/2013 + ... => R(UE) 1380/2013
Reg 494 - Merlu + ... => R(CE) 494/2002

**Comment by AudreyBramy** [comment]
- [ ] côté code : supprimer la notion de façade 
- [ ] on applique le script en dev
- [ ] si test ok, merge en intégration
- [ ] MEP 
- [ ] puis on passe le script sur la prod

**Comment by AudreyBramy** [comment]
Extrait des données en PROD 

              facade               |    law_type
-----------------------------------+-----------------
                                   |
 Mer du Nord                       | R(UE) 2019/1241
 NAMO                              | Reg locale
 Sud-Atlantique, SA                | Reg locale
 Mer Baltique                      | R(UE) 2019/1241
 MÃ©diterranÃ©e, MED               | R(UE) 1380/2013
 Outre-mer                         | Reg locale
 Eaux occidentales septentrionales | R(UE) 2019/1241
 Eaux occidentales australes       | R(UE) 2019/1241
 CPANE                             | R(UE) 2019/1241
 MED                               | Reg locale
 Golfe de Gascogne                 | Reg 494 - Merlu
 MÃ©diterranÃ©e, MED               | Reg locale
 SA                                | R(UE) 1380/2013
 MEMN                              | Reg Locale
 MEMN                              | Reg locale
 Sud Irlande                       | Reg 494 - Merlu
 MEMN                              | R(UE) 1380/2013

**Comment by louptheron** [comment]
Ah zut il y a eu un pb d'encodage.
MÃ©diterranÃ©e -> Méditerranée

**Comment by AudreyBramy** [comment]
Ça a été stocké comme ça en base ou c'est dans l'extraction @louptheron ?

**Comment by louptheron** [comment]
> Ça a été stocké comme ça en base ou c'est dans l'extraction @louptheron ?

C'est seulement dans l'extraction

**Comment by AudreyBramy** [comment]
Pour vérifier après les update

`SELECT DISTINCT(law_type), facade FROM public.reglementation_peche;`

**Comment by AudreyBramy** [comment]
`UPDATE public.reglementation_peche SET law_type='Reg locale' 
WHERE law_type='Reg Locale';

UPDATE public.reglementation_peche SET law_type='Reg. SA' 
WHERE law_type='Reg locale' AND facade='Sud-Atlantique, SA';

UPDATE public.reglementation_peche SET law_type='Reg. Outre-mer' 
WHERE law_type='Reg locale' AND facade='Outre-mer';

UPDATE public.reglementation_peche SET law_type='Reg. MED' 
WHERE law_type='Reg locale' AND (facade='MED' OR facade='Méditerranée, MED');

UPDATE public.reglementation_peche SET law_type='Reg. MEMN' 
WHERE law_type='Reg locale' AND facade='MEMN';

UPDATE public.reglementation_peche SET law_type='Reg. NAMO' 
WHERE law_type='Reg locale' AND facade='NAMO';

UPDATE public.reglementation_peche SET law_type='R(CE) 494/2002' 
WHERE law_type='Reg 494 - Merlu';`

**Comment by louptheron** [comment]
Script appliqué en PROD
