### ISSUE TITLE
Quand je passe la souris sur la zone remontée lors d'une recherche, la zone s'affiche sur la carte, pour qu'on puisse la visualiser avant de l'ajouter à Mes Zones

### ISSUE THREAD

**Issue by VincentAntoine** [MTES-MCT/monitorfish#698]

**Comment by AdelineCelier** [comment]
@thoomasbro en discutant de cette fonctionnalité avec Diane, on s'est rendu compte que ce serait bien que cela marche dès le survol de la thématique d'une zone. En effet, quand on fait une recherche, le résultat apparaît sous forme de thématiques repliées, donc pour survoler les zones il faut nécessairement déplier la thématique. 
Afficher toutes les zones de la thématique au survol sur cette dernière permet de se faire une première idée, quitte à ensuite la déplier et à regarder chaque zone plus en détail.

**Comment by AdelineCelier** [comment]
Super cette fonctionnalité, ça apporte vraiment une meilleure visibilité à la recherche !

Je viens de tester sur l'intégration en étant en VPN, voic mes questions/remarques :
- j'ai l'impression qu'il y a parfois des problèmes dans le centrage de la carte sur les zones qui s'affichent au survol. Je crois que c'est quand on est à un certain niveau de zoom (assez zoomé), la carte se centre mal sur la zone, qui n'apparaît pas dans le champ, voire la carte bouge à l'endroit où était la zone précédemment survolée
- j'avais mal anticipé le fait qu'afficher les zones au survol des thématiques ferait que la carte se promène en même temps que l'on navigue/scrolle dans la liste...cela donne un peu le mal de mer ^^' je suis désolée, je me demande s'il ne vaut pas mieux revenir à l'affichage des zones seulement. Ou alors, on peut dire que toutes les zones de la thématique s'affichent au clic pour déplier cette dernière ? Et qu'ensuite, au survol des zones, celles-ci s'affichent une à une, comme aujourd'hui ? Qu'en pensez-vous ? Est-ce possible de tester ce mode-là et voir ce que ça donne ?
- est-ce possible de récupérer les couleurs de zones existantes ? Si cela demande un développement complexe en plus, on peut laisser cette question de couleurs de côté le temps que je refasse le point dessus (j'attends pour cela que Diane ait fini de renseigner toutes les infos des couches dans le back). Si c'est rapide à faire, c'est cool, cela permettra de mieux s'y retrouver.

**Comment by AdelineCelier** [comment]
**EDIT après discussion avec Loup**
Le fait de charger toutes les géométries ralentit beaucoup la recherche reg et le backoffice. De plus, comme vu ci-dessus, le comportement d'affichage au survol n'est pas optimal. 
Nouveau comportement souhaité : on n'affiche plus les zones au survol, on ne les affiche qu'au moment où l'on affiche le résumé reg. Le couple résumé reg. et zone se masquent à partir du moment où l'on referme la thématique, ou qu'on sort de la recherche reg. (clic ailleurs dans l'interface).

**Comment by AdelineCelier** [comment]
C'est parfait, ça marche très bien comme ça ! Je valide.
