### ISSUE TITLE
[Backoffice] Rajouter la possibilité de supprimer des réglementations

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#707]
A rajouter à l'intérieur du formulaire, avec une modale de confirmation avant suppression définitive (cf. écrans 27 et 28 dans le XD) : 
![image](https://user-images.githubusercontent.com/71878648/139037400-b1015dbb-d425-4dc9-bd10-53cb91a8edc7.png)
![image](https://user-images.githubusercontent.com/71878648/139037897-ac6d257d-6715-486b-9e01-832c1da21a31.png)

**Comment by louptheron** [comment]
@AudreyBramy PEtit décalage :
![Screenshot from 2021-11-24 13-16-05](https://user-images.githubusercontent.com/14853556/143236841-fcecb860-59da-443c-9911-7226432b20db.png)

**Comment by AudreyBramy** [comment]
Je ne reproduis pas ce comportement chez moi, mais j'ai tenté de le réparer avec 
https://github.com/MTES-MCT/monitorfish/pull/726/commits/ff2993d9ca7cb1cf1b7d7e44193453867d1b7162

**Comment by AdelineCelier** [comment]
ça ressemble au même problème que la double barre de scroll dans la modale "reg à venir", non ?
