### ISSUE TITLE
[Backoffice] Lorsqu'on recharge une page de reg en cours d'édition, cela efface toutes les données du formulaire

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#714]

**Comment by AudreyBramy** [comment]
C'est commencé dans cette PR => https://github.com/MTES-MCT/monitorfish/pull/877

Par contre, @AdelineCelier j'ai quelques questions que l'on pourra voir à mon retour.

Pour le moment j'ai juste commencé par stoker la zone au moment de la sélection.

Si je recharge ma page, le formulaire est complété avec les informations d'origine.
Est-ce qu'on souhaite, afficher le formulaire dans l'état où il était avant le rechargement (idem dans le cas d'une création) ?

**Comment by AdelineCelier** [comment]
Cela me semble good ! Je n'ai pas testé en essayant de remplir absolument tous les champs, @louptheron @AudreyBramy ce n'est pas nécessaire si ?
