### ISSUE TITLE
A faire sur la REG (métadonnées)

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#73]
Il y a des champs que je n'ai pas mis dans la maquette, pour différentes raisons.

    Il y a tous les champs des deux couches "Etang de Thau-Ingrill", qui leur sont spécifiques, et qui ne devront apparaître que pour ces couches-là :

    crocs
    dragues à main
    filets encerclants
    filets fixes
    filets maillants trémail
    nasses
    palangres
    pêche sous-marine
    petite drague coquillages
    senne de plage
    senne tournante

    Les colonnes "captures accessoires" et "prises accessoires" doivent être réunies en une seule
    La colonne valeur doit être supprimée
    La colonne "type" doit être supprimée, et pour cela il faut subdiviser la couche "Interdiction pêche ouest cotentin" en trois couches, 1 "étrilles", 1 "casiers pièges" et 1 "cantonnement"
    La colonne "dates" ne doit pas remonter dans l'interface utilisateur, elle sert à dire si certaines zones sont ouvertes ou fermées
    La colonne "interdits" ne doit pas remonter non plus, c'est pour créer

**Comment by AdelineCelier** [comment]
Encore plusieurs problèmes sur les données de reg :
- Revoir le nom des couches, pour y ajouter systématiquement une zone (façade, région ou sous-zone, selon les couches). Respecter une nomenclature [Zone]_[Engin]_[Espèces] (engin et espèce étant facultatifs, à voir selon les couches)
- Faire en sorte que les sous-zones (colonne "zones") aient toujours un nom, même quand il n'y a qu'une zone dans la couche
- Refaire une passe sur les engins, pour toujours mettre les codes FAO (cf. "filets Bretagne")

**Comment by AdelineCelier** [comment]
👍🏻

**Comment by VincentAntoine** [comment]
**Renommage des layer_names et des zones**
- [ ] Sortir la liste de tous les couples (layer_names, zones) dans un fichier Excel **(Vincent)**
- [ ] Définir le nouveau nom souhaité pour chaque layer_name et chaque zone **(Adeline / Marine / Vincent / Diane / major)**
- [ ] Mettre à jour la base de données et les vues (pour ne pas impacter Neptune) **(Vincent)**

---
**Corrections de valeurs dans la table**
- [ ] Remplacer les libellés d'engins par des codes FAO (cf Google doc pour la liste des modifs à faire) **(Marine)**
- [ ] Remplacer les libellés d'espèces par des codes FAO (cf Google doc pour la liste des modifs à faire) **(Marine)**

---
**Changements de colonnes**
- [ ] La colonne "type" doit être supprimée, et pour cela il faut subdiviser la couche "Interdiction pêche ouest cotentin" en plusieurs couches, en indiquant le type (étrilles, casiers pièges ou cantonnement) dans le nom de la zone.  **(Marine)**
- [ ] La colonne "valeur" doit être supprimée **(Vincent)**
- [ ] Les colonnes "captures accessoires" et "prises accessoires" doivent être réunies en une seule **(Vincent)**
- [ ] Pour la réglementation de l'Etang de Thau-Ingrill, créer une couche pour chacune des colonnes suivantes, en renseignant dans chaque couche la réglementation correspondant à l'engin dont il est question et en incluant l'engin dans le nom de la zone : peche_sous_marins, crocs, petite_drague_coquillage, drague_a_main, filets_fixes, filets_maillants_tremails, senne_tournante, senne_de_plage, nasses, palangres, filets_encerclants  **(Marine)**
- [ ] Renommer les colonnes engins et espèces en "engins_autorises" et "especes_autorisees" respectivement **(Vincent)**
- [ ] Créer les colonnes "autre_reglementation_especes" et "autre_reglementation" **(Vincent)**
- [ ] Dispatcher le contenu de la colonne "autorisations" dans les colonnes "engins_autorises" et "especes_autorisees" quand c'est possible. Ce qui ne peut pas être dispatché -> à copier-coller dans la colonne "autre_reglementation" ou "autre_reglementation_espece"
- [ ] Dispatcher le contenu de la colonne "interdiction" dans les colonnes "engins_interdits" et "especes_interdites" quand c'est possible. Ce qui ne peut pas être dispatché -> à copier-coller dans la colonne "autre_reglementation" ou "autre_reglementation_espece"

**Comment by AdelineCelier** [comment]
@VincentAntoine est-ce que tu peux attendre avant de supprimer la colonne "gisements" ? J'aimerais qu'on discute d'une manière d'afficher des zones plus pertinentes pour les CSJ, et les gisements pourraient nous y aider je pense.

**Comment by AdelineCelier** [comment]
+ ne faudrait-il pas rajouter une colonne "type de réglementation" : européenne / française / régionale / locale ? 
Cela aiderait probablement à trier l'affichage du résultat d'une recherche

**Comment by VincentAntoine** [comment]
> @VincentAntoine est-ce que tu peux attendre avant de supprimer la colonne "gisements" ? J'aimerais qu'on discute d'une manière d'afficher des zones plus pertinentes pour les CSJ, et les gisements pourraient nous y aider je pense.
> **=> on a dit qu'on mettait le nom du gisement au début du nom de la zone**

@AdelineCelier 
* J'ai un doute, tu veux encore réfléchir ou je peux faire la modif ? Il me semble qu'on a dit go mais juste pour être sûr.
* Pour les Laminaria, les gisements correspondent aux années : 2019, 2020, 2021. Pour ces zones, on peut peut-être inclure le gisement non pas dans le nom de nom mais dans le nom de thématique ?

**Comment by VincentAntoine** [comment]
@louptheron j'ai remis les colonnes type et gisement pour comme l'app grognait, dis moi quand je peux les renlever !

**Comment by AdelineCelier** [comment]
@VincentAntoine J'aurais aimé tester de rajouter un 3è niveau de classification de la reg, afin de ranger les thématiques par paquets dans la recherche reg : 
![image](https://user-images.githubusercontent.com/71878648/110635275-31cf6c00-81ab-11eb-900f-7c78fe11fdf2.png)

L'idée est tout simplement de spécifier de quelle reg on parle : 
- Reg locale (découpée par façade) : Reg locale / MEMN, Reg locale / NAMO, Reg locale / MED, etc. 
- R(UE) 1241
- R(UE) 1380 / Droits historiques
- R(UE) 494 / Merlu

Aujourd'hui il n'y a "que" ces reg-là, mais on pourra en rajouter au fur et à mesure. 
Je pense que ça pourrait aider à structurer les résultats de la recherche reg, mais c'est difficile de se projeter sans les vraies données. Et si on rajoute un champ, il faut que ça vaille le coup ! Bref, à discuter ensemble

**Comment by VincentAntoine** [comment]
@AdelineCelier j'ai ajouté une colonne "law_type" avec comme valeurs :
* "Reg locale" pour la reg locale
* "Reg 494 - Merlu" pour le box merlu

Les autres types de reg ne sont pas encore dans la base de données.

Ce ticket commence à être gros et il faut du dev donc pour que ça reste clair je crée un autre ticket.
