### ISSUE TITLE
[Backoffice] Ajout de la section des engins de pêches

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#762]

**Comment by AudreyBramy** [comment]
@AdelineCelier
Il me manque deux petites infos : 
- les textes pour les bulles d'information sur les checkbox
- est-ce qu'on encadre ou pas la section "Mesures dérogatoires"

**Comment by AdelineCelier** [comment]
@AudreyBramy Oups oui pardon je suis désolée j'ai complètement oublié de te répondre avant de partir en vacances.
- j'ai rajouté les textes pour les infobulles des "engins traînants" et "engins dormants" sur l'écran n°
- pour l'encadré "mesures dérogatoires", j'ai supprimé la pastille avec le point d'exclamation qui n'était pas très claire ni très bien placée, mais je propose de quand même garder l'encadré, qui rappelle l'affiche côté carto, et met en avant ce point un peu particulier, qui risque d'être oublié sinon. Et du coup si le "non" est coché, il reste gris, si le oui est coché, il devient jaune (#f6d012)

**Comment by AdelineCelier** [comment]
OK ici
