### ISSUE TITLE
Le résumé de marée affiche parfois "aucune capture" alors que la marée contient des messages FAR avec des captures

### ISSUE THREAD

**Issue by VincentAntoine** [MTES-MCT/monitorfish#785]

**Comment by VincentAntoine** [comment]
Cf la marée 21101812 du navire FRA000801709

**Comment by louptheron** [comment]
Quand les messages FAR ne sont pas acquittés, on affiche seulement "2 messages" dans le résumé, sans pouvir dérouler.
Fau p-e qu'on definisse ce qu'on affiche dans ce cas, @AdelineCelier on peut spécifier qu'ils ne sont pas acquittés ?
Pour le DEP on avait mis une croix rouge : https://xd.adobe.com/view/7fb378f2-2d2b-437d-a0ef-3b7001d56c62-2ae0/screen/1ce1a4d0-0655-41b3-b463-2eeb1a8541f5/

**Comment by AdelineCelier** [comment]
Pardon je me rends compte que je n'ai jamais répondu à ton message ! Oui très bonne idée, on peut les afficher de la même manière que les DEP non acquittés, en rouge avec une croix. 
D'ailleurs ça pourrait être une manière de montrer les messages Visiocapture aussi ?
