### ISSUE TITLE
[Backoffice] Accentuer la différence entre actif et inactif de l'icône "afficher le résumé reg"

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#787]
![image](https://user-images.githubusercontent.com/71878648/142428584-25573eff-f5ce-4fa6-a65d-ebed866a9538.png)

**Comment by AdelineCelier** [comment]
@AudreyBramy en revoyant mes maquettes, je me rends compte que j'avais déjà fait une différenciation entre l'icône inactive et l'icône active. J'ai légèrement rectifié les épaisseurs pour accentuer les effets.
- Icône inactive : en Light Gray, épaisseur des traits 1,5 px
- Icône active : en Slate Gray, épaisseur des traits 2 px

Ci-joint les deux versions de l'icône en .svg
[Icones svg_actif et inactif.zip](https://github.com/MTES-MCT/monitorfish/files/7853999/Icones.svg_actif.et.inactif.zip)

**Comment by AudreyBramy** [comment]
C'est ajouté dans la PR #910.

**Comment by AdelineCelier** [comment]
Good pour moi.
