### ISSUE TITLE
[Backoffice] Voir le problème du mail récap' des changements dans Légipêche

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#789]

**Comment by VincentAntoine** [comment]
Fix dans https://github.com/MTES-MCT/monitorfish/commit/245611e6f40359b80c8148d7d763b4003afc4e84
Les colonnes du csv de sortie du scraper sont définies par l'objet extrait de première page scrapée, qui contenait aléatoirement 2 ou 4 colonnes selon que la première page scrapée contenait ou non des documents téléchargeable. Avec ce fix, même les pages ne contenant pas de documents téléchargeables renvoient un objet avec 4 champs, et le csv de sortie comporte donc toujours 4 colonnes.
