### ISSUE TITLE
[Backoffice] Ajouter la possibilité de modifier ou supprimer de thématiques

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#792]
On n'avait pas laissé cette possibilité au départ parce que les vues des zones dans QGIS reposaient sur le "layer_name" (= la thématique). 

On acte le fait que l'on s'affranchit de QGIS, et qu'on peut donc modifier le nom des thématiques via le backoffice.

**Comment by AudreyBramy** [comment]
Sur la maquette je remarque que "Avant de créer une nouvelle thématique, vérifiez bien qu'il n'en existe pas déjà une qui pourrait correspondre." est plus d'être en gras, le texte est en GunMetal alors que le reste est en SlateGray, est-ce normal ?

**Comment by AdelineCelier** [comment]
Ah oui bien vu ! Effectivement j'ai fait ça sans trop réfléchir, pour mettre un peu plus en valeur encore la première phrase de la bulle. Je pense qu'on peut bien partir sur le GunMetal, le SlateGray ne ressort pas assez je trouve.

**Comment by AudreyBramy** [comment]
Vu avec Adeline le 30 nov.

Pour plus de cohérence lors de la modification d'une thématique (layername) : 
1/ en cas de création :
La liste des thématique est accessible que si un ensemble (lawtype) est sélectionné
Une fois qu'un ensemble est sélectionné, on affiche dans la liste des thématique seul les thématique liées à cet ensemble

2/ En cas d'édition (à réfléchir et confirmer avec Diane)
Si on modifie un ensemble alors la thématique sélectionnée n'est plus cohérente : 
- soit on modifie les ensembles des toutes les zones de cette thématique (après demande de confirmation par une popup)
- soit on reset la valeur de la thématique pour forcer à sélectionner une thématique dans la liste disponible
- ou ?

**Comment by AudreyBramy** [comment]
Finalement on peut modifier le nom d'une thématique que dans la liste des zone.
Au survol d'une thématique on ajoute un icône d'édition, au clique sur l'icône le nom est éditable.

**Comment by AdelineCelier** [comment]
@AudreyBramy Cela me semble good ! 
Il faudrait juste modifier le texte de l'infobulle au survol de l'icône : plutôt que "éditer la thématique", on pourrait dire "modifier le nom de la thématique".

**Comment by AudreyBramy** [comment]
C'est fait dans #841

**Comment by AdelineCelier** [comment]
C'est bon pour moi
