### ISSUE TITLE
Afficher les dernières alertes chalutage sur la cartographie

### ISSUE THREAD

**Issue by VincentAntoine** [MTES-MCT/monitorfish#799]

**Comment by AdelineCelier** [comment]
Écrans pour la carte faits, dans ce XD : 

**Règles et explications**

- l'icône "alerte" en haut à gauche permet d'ouvrir une nouvelle fenêtre à placer sur un autre écran, avec la vue liste des alertes, triées par façades. Lorsque des alertes remontent, une pastille apparaît, avec le nombre d'alertes en cours. A voir s'il ne faut pas prévoir une animation avec une notification disant "nouvelle alerte : chalutage dans les 3 milles" (selon volumétrie des alertes).
![image](https://user-images.githubusercontent.com/71878648/143273773-3fa61efa-8c12-4e99-8a20-aabcc8829b6e.png)


- lorsqu'une alerte remonte sur un navire, un cercle rouge apparaît autour de l'icône de sa dernière position – avec une petite animation "halo" mouf-mouf en prime si t'as le temps Loup, je te montrerai ce que j'ai en tête c'est assez simple. Ce cercle rouge ne disparaît pas tant que le navire est dans la liste des alertes
![image](https://user-images.githubusercontent.com/71878648/143272413-5ea9ff97-9851-4618-928a-b7b9c802f37d.png)

- au survol, un bandeau apparaît dans la fiche résumé du navire, qui spécifie la nature de l'alerte. Idem, il ne disparaît pas tant que le navire est dans la liste des alertes.
![image](https://user-images.githubusercontent.com/71878648/143273321-fc6a32cc-b15d-4761-afa1-932991be8b1b.png)

- dans la fiche navire, un bandeau apparaît également, avec un lien renvoyant vers la liste. Il faut que la liste s'ouvre direct centrée sur l'alerte du bateau (voire avec le détail du ticket ouvert, quand on en sera là) : 
![image](https://user-images.githubusercontent.com/71878648/143273402-df41caef-c1f1-4a11-bfb9-1a17568e22c1.png)
