### ISSUE TITLE
REG : rajouter un lien depuis le résumé reg vers Légipêche

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#80]
Changer la colonne référence réglementaire en tableau d'objets
De type :
```
[{
  reference: "ARRETE 1234",
  url: "http://legifrance"
}]
```

**Comment by VincentAntoine** [comment]
@louptheron C'est modifié dans la base, à toi de jouer pour l'affichage.

**Comment by AdelineCelier** [comment]
@louptheron @VincentAntoine  Aujourd'hui, il y a plusieurs zones sans références reg (ex. Bretagne Bolinche / Sud Bretagne). Est-ce que ça se joue côté Marine ou bien de notre côté ?

**Comment by AdelineCelier** [comment]
@VincentAntoine 
Remettre à jour les données de ref. reg. avec le "Kleanonslareg". 

Pour les nouvelles ref. reg. ajoutées, il faudra refaire une passe au moment de l'interface reg.

**Comment by VincentAntoine** [comment]
Point sur les liens Légipêche au 27/04/2021 : 
- en base de données, sur 873 zones
  - 633 ont pour value un json array vide {}
  - 57 sont NULL
  - 183 ont un json array bien formé de type [{url: "url_1.legipeche", reference: "Titre arrêté 1"}, {url: "url_2.legipeche", reference: "Titre arrêté 2"}]
- Un export du google sheet de nettoyage de données reg réalisé le 2 mars 2021 contient 766 références réglementaires
- Après ré-import des références réglementaires de ce fichier csv dans la base : 
  - 49 ont pour value un json array vide {}
  - 57 sont NULL
  - 767 ont un json array bien formé

Les thématiques dans lesquelles les références réglementaires sont soit NULL soit {}, avec le nombre de zones par thématique : 

Box_Merlu                                           2
Bretagne_Bivalves                                   1
Bretagne_Laminaria_Hyperborea_Scoubidous - 2019    48
Bretagne_Seiches_Chaluts                            5
Interdictions_Bretagne                              1
Interdictions_MEMN                                  2
MEMN_Soles_Nourriceries                             5
Mayotte_Poulpes                                     1
Méditerranée_Box_CGPM                               1
Méditerranée_Cantonnements                          2
Méditerranée_Oursins                                3
Méditerranée_Prudhomies                            33

A suivre si des valeurs disparaissent.

**Comment by louptheron** [comment]
TODO: UPDATE SITUATION §§

**Comment by VincentAntoine** [comment]
UPDATE SITUATION $$
Au 27/05/2021 : 
- 763 zones avec references_reglementaires json bien formé, vs 766 zones avec json bien formé le 27/04 (quelques zones ont été supprimées par Marine depuis le 27/04) -> pas de disparition de données
- mise à jour en cours via Gsheet

**Comment by VincentAntoine** [comment]
MàJ faite par Marine et intégrée à Monif \o/
