### ISSUE TITLE
Il semble y avoir des navires en double dans `last_positions`, cf. "GABIGEL"

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#816]

**Comment by louptheron** [comment]
![Screenshot from 2021-11-29 09-07-46](https://user-images.githubusercontent.com/14853556/143830631-017fe76b-dff2-4ab2-8726-aa0240ae4909.png)

**Comment by VincentAntoine** [comment]
Duplicate of #753
