### ISSUE TITLE
[Backoffice] Ajout des espèces dans l'interface REG

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#825]

**Comment by AdelineCelier** [comment]
## Revue UX
- [ ] Problème avec les menus déroulants qui débordent du cadre : les placer plutôt au-dessus du champ pour éviter qu'ils soient coupés par le bas de la page
- [ ] Est-ce qu'il serait possible de prendre en compte la casse (minuscules/majuscules) dans la recherche du menu déroulant des espèces ? cela permettrait de rechercher le trigramme autant que le nom commun.

## Revue UI
- [ ] agrandir la marge entre le menu déroulant espèces et les espèces ou catégories d'espèces sélectionnées : 20 px
![image](https://user-images.githubusercontent.com/71878648/145065158-0a0ba8b7-5c37-466b-b40c-4a50403262a9.png)
- [ ] idem, agrandir la marge entre les deux blocs de champs "espèces " : 15 px
![image](https://user-images.githubusercontent.com/71878648/145065661-3c8b9114-494d-471e-b5bf-0d800ccb550d.png)
- [ ] idem, agrandir la marge entre les catégories d'espèces ou les espèces quand elles sont seules (quand "espèces interdites" est coché) : 8 px
![image](https://user-images.githubusercontent.com/71878648/145066202-865be89c-b5ae-43b1-afc7-270ca6ca1e2e.png)
![image](https://user-images.githubusercontent.com/71878648/145066438-05603aaa-042d-4c52-b31c-27ae27d4b25b.png)
- [ ] Griser les champs libres (comme "taille", "quantité" et "autres points sur les espèces") une fois qu'ils sont remplis (cf. comportement du champ "zone" en début de formulaire)
