### ISSUE TITLE
[Backoffice] Le contour rouge autour des champs non remplis n'est peut-être pas assez visuel

### ISSUE THREAD

**Issue by AudreyBramy** [MTES-MCT/monitorfish#840]
il faudrait rajouter une phrase au niveau du bouton : "Veuillez vérifier les champs surlignés en rouge dans le formulaire" 
 (le message disparaît au bout de 10 secondes) :

**Comment by AudreyBramy** [comment]
![Uploading 138480452-2bfe1096-7d21-4411-a19c-56b04ec22ee3.png…]()

**Comment by AudreyBramy** [comment]
![138480452-2bfe1096-7d21-4411-a19c-56b04ec22ee3](https://user-images.githubusercontent.com/5551618/144835476-b09786bb-f8f8-4d27-a4cc-87eed73c22b3.png)

**Comment by AdelineCelier** [comment]
@AudreyBramy c'est top ça marche bien ! Je pense qu'il faut juste qu'une fois que l'erreur est corrigée (le champ libre rempli, le choix dans le menu déroulant fait), l'encadré rouge et le message disparaissent, pour bien montrer que c'est ok.

**Comment by ivangabriele** [comment]
@AdelineCelier On garde ce ticket ?

**Comment by AdelineCelier** [comment]
@ivangabriele ça fait mille ans que je n'ai pas été dans le backoffice...le système d'erreur y fonctionne de la même manière que dans le reste de l'app ou pas ? (je veux dire, c'est le même comportement des composants ?)
