### ISSUE TITLE
Affichage couches reg : centrage et zoom de la carte

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#85]
- Lorsqu'on clique sur l’œil pour afficher une zone ou un ensemble de zones, la carte se met à un niveau de zoom intermédiaire et se centre sur la zone/le groupe de zone
- Lorsqu'on double-clique sur le nom ou le carré de couleur d'une zone, la carte affiche la zone si elle n'est pas déjà visible et zoome dessus

**Comment by AdelineCelier** [comment]
@louptheron Il faut qu'on rediscute ensemble de la cinématique du zoom, aujourd'hui ça ne va pas. A voir si corréler le niveau de zoom et l'aire de la zone à afficher suffirait ou non. En tous cas c'est quand même cool de ne pas avoir à chercher la zone nous-même quand on l'affiche sur la carte.

**Comment by louptheron** [comment]
Nouvelle approche : si le niveau de zoom est plus bas que le zoom défini quand on clique sur une zone, alors on zoom sur cette zone, sinon on reste dans le niveau de zoom actuel (la zone devrait être visible).
