### ISSUE TITLE
Sélectionner l'année actuelle pour la priorité de contrôle dans le backoffice

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#864]
- [x] Sélectionner les objectifs par année
- [ ] Ajouter un bouton pour initialiser une nouvelle année d'objectifs depuis l'année en cours, i.e "Créer l'année 2023"
  - on copie les données de l'année en cours dans la nouvelle année
- [x] Permettre l'ajout et la suppression de segments de flotte dans le tableau des objectifs

**Comment by VincentAntoine** [comment]
@AdelineCelier comme discuté à l'instant, il faudrait dessiner qqch pour permettre de choisir l'année pour laquelle on renseigne les priorités de contrôle dans le backoffice
