### ISSUE TITLE
Afficher le nom de la zone au survol de la souris

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#87]

**Comment by AdelineCelier** [comment]
@louptheron Le texte n'est pas centré dans le rectangle, et je crois que j'avais mis le nom de la couche en gras, et celui de la zone en normal, pour bien les différencier.
Mais bon je crois que de toutes façons il va falloir revoir la manière d'afficher ces légendes, car ce matin Mickaël n'avait pas remarqué que ça s'affichait en bas (c'est vrai que c'est très discret), et hier quand il y avait les étiquettes au-dessus des zones, l'un des opérateurs m'a fait remarquer que c'était un peu relou de devoir survoler les zones une par une pour trouver celle que tu cherches...et c'est pas faux. Faudrait que je refasse des maquettes je pense.
Qu'est-ce qu'on fait avec ce ticket du coup ? Je le remets dans le backlog ?

![image](https://user-images.githubusercontent.com/71878648/104602637-e6ea1a00-567b-11eb-9138-4c0f74098f0f.png)

**Comment by louptheron** [comment]
Ok pour le centrage mais j'ai bien mis en gras, cf:
![Screenshot from 2021-01-14 15-39-22](https://user-images.githubusercontent.com/14853556/104605397-bbb4fa00-567e-11eb-9f1d-6ed26e44ccf0.png)

Oui je suis d'accord c'est pas hyper visible

**Comment by AdelineCelier** [comment]
Tiens c'est bizarre pourquoi ça ne s'affiche pas en gras chez moi ?

**Comment by louptheron** [comment]
Les navigateurs n'ont pas les mêmes gras :/
J'ai centré

**Comment by AdelineCelier** [comment]
Ticket faisant partie du grand ticket sur les légendes de la carte : #115
