### ISSUE TITLE
[Mail reg] Un texte abrogé ne remonte pas dans la liste des liens morts du mail quotidien pour la reg

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#870]
**Reg concernée dans MonitorFish**
Thématique : Seine Maritime crevettes grises
Nom de la zone : Bande côtière des 3 milles entre l'estuaire de la Seine et Ouistreham

**Références reg.**
Ancienne référence (qui est dans MF et qui renvoie donc aujourd'hui vers une page morte) : arrêté préfectoral du 20/2016
Nouvelle référence, mise en ligne le 7 décembre par Diane sur Légipêche : arrêté préfectoral 206/2021

Ce lien mort n'est donc a priori pas mentionné dans les mails quotidiens, en tous cas pas dans celui du 15/12/2021.

**Comment by VincentAntoine** [comment]
La ref reg n'a pas l'air d'être encore dans la base.. je ne vois pas trop ce qui a pu causer ça, je ferme et on avisera si ça se reproduit.
