### ISSUE TITLE
La simplification des zones fait que des features ne sont pas des polygones valides dans MF (message `invalid polygon` dans turj.js lors de la simplification)

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#874]
@VincentAntoine Tu pourras jêter un oeil ? Sinon quand je rentre je check ça !

En gros turf.js essaie de simplifier la zone (l. 80 de `use_cases/showRegulatoryLayers`) mais il retourne une erreur (tu peux voir dans la console) du navigateur

J'ai essayé de changer avec aça, sans succès : 
```
UPDATE prod.reglementation_peche SET geometry = ST_MakeValid(ST_CurveToLine(geometry));
UPDATE prod.reglementation_peche SET geometry_simplified = ST_SimplifyPreserveTopology(ST_CurveToLine(geometry), 0.0001);
ALTER TABLE reglementation_peche ADD CONSTRAINT geometry_is_valid_check CHECK (st_isvalid(geometry));

-- This trigger function
--   * is triggered whenever a row in the local regulation database is inserted or modified
--   * computes the simplified geometry (ST_Simplify) and store it in the geometry_simplified column
--   * convert the MULTISURFACE geometry to MULTYPOLYGON geometry type
--
-- The trigger is BEFORE insert of update, so values always have an up-to-date simplified geometry.

DROP FUNCTION IF EXISTS prod.simplify_geometry CASCADE;

CREATE FUNCTION prod.simplify_geometry() RETURNS trigger AS $$
    BEGIN
        NEW.geometry_simplified := ST_SimplifyPreserveTopology(ST_CurveToLine(NEW.geometry), 0.0001);
        NEW.geometry := ST_MakeValid(ST_CurveToLine(NEW.geometry));
        RETURN NEW;
    END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER simplify_geometry
    BEFORE INSERT OR UPDATE ON prod.reglementation_peche
    FOR EACH ROW
    EXECUTE PROCEDURE prod.simplify_geometry();

```

**Comment by VincentAntoine** [comment]
Hello! Je n'ai pas réussi à reproduire l'erreur. C'est en prod ? Dans la base je ne vois pas non plus de polygones non valides : 
 
| st_isvalid   | st_geometrytype       |   count |
|:-------------|:----------------------|--------:|
| True         | ST_Polygon            |      46 |
| True         | ST_MultiLineString    |       5 |
| True         | ST_GeometryCollection |      59 |
| True         | ST_MultiPolygon       |     803 |

Et les différents types de polygones s'affichent correctement dans l'app. On regarde ensemble lundi ?

**Comment by VincentAntoine** [comment]
Résolu en n'utilisant pas turf.js
