### ISSUE TITLE
Recherche REG par num. reg. ne fonctionne plus

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#889]
Il semblerait que la recherche par référence rég quand on est sur l'interface classique mais aussi sur le backoffice de Monitor Fish ne fonctionne plus. On a tapé 494/2002, 143-2021 et 58/2007 mais rien ne remonte...

**Comment by AdelineCelier** [comment]
@AudreyBramy
Des reg remontent alors que les numéros tapés dans la barre de recherche n'apparaissent nulle part dans le résumé réglementaire. Après investigation, on a vu que la recherche tapait dans l'url de la référence réglementaire, faisant remonter des reg. avec des numéros qui n'ont rien à voir. 
Comportement attendu : la recherche ne doit chercher dans le nom de la réglementation, et non dans son url.

**Comment by VincentAntoine** [comment]
Testé le 02/02/2022 : la recherche fonctionne mais remonte des couches qui ne devraient pas car la recherche est faite dans l'URL, il faudrait rechercher uniquement dans les titres des refs reg et non dans les URL.

**Comment by AdelineCelier** [comment]
Cela me semble fonctionner correctement maintenant !
