### ISSUE TITLE
Réajuster les tags "engins traînants" et "engins dormants" + revoir catéories "sennes tournantes coulissantes" et "filets tournants"

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#903]
Après une (énième) vérification auprès de Diane, je crois que nous touchons au but, et que la vérité sur les engins traînants et dormants est proche ! 😅  

## Ajustement des catégories d'engin

**SENNES TRAÎNANTES**
En plus des SDN, SSC et SX, il faut rajouter les SPR et les SV

**SENNES TOURNANTES COULISSANTES ET FILETS TOURNANTS**
Ces deux catégories peuvent être réunies sous le seul nom de "filets tournants", et regroupent donc les PS, PS1, PS2, LA, SUX et SB

## Ajustement des tags "traînants" et "dormants"

**ENGINS TRAÎNANTS**
- tous les chaluts
- toutes les dragues, à savoir DRB, DHB, DHS, DRH, DRM, HMD
- toutes les sennes traînantes, à savoir SDN, SSC, SPR, SX et SV 

**ENGINS DORMANTS**
- tous les filets maillants et emmêlants
- tous les filets soulevés 
- toutes les lignes et hameçons
- tous les pièges

**ENGINS NI TRAÎNANTS NI DORMANTS**
- tous les filets tournants (et sennes tournantes coulissantes) : PS, PS1, PS2, SB, LA, SUX
- engins divers
- engins de récolte
- engins de pêche récréative
- engins inconnus

Pour simplifier les choses,

**Comment by AudreyBramy** [comment]
Suite aux modifs dans #913 lorsque la catégorie "sennes tournantes coulissantes" sera intégrée dans "filets tournants", il faudra modifier la liste des catégories dans la fonction `prepareCategoriesAndGearsToDisplay` du fichier [regulatory.js](https://github.com/MTES-MCT/monitorfish/blob/master/frontend/src/domain/entities/regulatory.js)

**Comment by AudreyBramy** [comment]
<img width="325" alt="Capture d’écran 2022-01-14 à 11 52 48" src="https://user-images.githubusercontent.com/5551618/149504059-1e2d1b60-ed48-4a54-ae48-4373ae10f8ae.png">
@AdelineCelier est-ce que 250px pour le menu ça peut convenir aussi ?
