### ISSUE TITLE
[Backoffice / Reg] Il faudrait que le résumé rég. d'une zone affiché sur la carto se ferme automatiquement si on filtre la liste des zones et que la zone du résumé reg. disparaît

### ISSUE THREAD

**Issue by AudreyBramy** [MTES-MCT/monitorfish#907]

**Comment by AudreyBramy** [comment]
Dans le backoffice, si j'affiche le résumé je ne peux plus fermer la liste de la thématique.
Comportement attendu : 
- si je ferme la thématique, ça ferme le résumé
- si j'ouvre une autre thématique ça ferme le résumé

**Comment by AdelineCelier** [comment]
Nickel ! C'est beaucoup mieux comme ça :)
