### ISSUE TITLE
Mettre les dates en UTC

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#91]
Et mettre les dates au format "00/00/0000"

**Comment by AdelineCelier** [comment]
Good pour le format des dates, juste mettre UTC plutôt que Zulu ;)

**Comment by louptheron** [comment]
done

**Comment by AdelineCelier** [comment]
Oups, je vois à l'instant qu'il y a encore des dates qui ne sont pas au format 00/00/000 : 
![image](https://user-images.githubusercontent.com/71878648/105025190-4f0a7880-5a4d-11eb-8610-076f5601ab69.png)

**Comment by louptheron** [comment]
Done

**Comment by AdelineCelier** [comment]
Attention, j'ai vu passer un format horaire : 24h10, il faudrait passer minuit en 00h...non ?
