### ISSUE TITLE
[Backoffice] Problème d'affichage de l'icône œil

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#919]
@AudreyBramy 
Comme discuté, il y a par moments un problème avec l'affichage des zones via l'icône œil : l'icône reste sélectionnée même quand on clique dessus. 
Là tout de suite je n'arrive pas à reproduire, mais il me semble que l'icône est comme bloquée : elle ne se désélectionne pas, et les zones ne s'affichent/désaffichent pas. 
Diane m'avait déjà parlé de ce problème, je ne sais plus si je te l'avais remonté ou pas ?

**Comment by AudreyBramy** [comment]
Oui on en avait parlé.
J'ai crois avoir eu le problème et il me semblait que ça venait de la liste des zone affichées stockée dans le local storage.
Comme si, lorsqu'on déselectionne, dans une certaine situation (que je ne serai reproduire) la zone n'était pas supprimée de la liste. 
Et je ne suis pas certaine de ce que je raconte.

**Comment by AudreyBramy** [comment]
Je n'arrive pas à reproduire ce problème.
En revanche j'ai fixé quelques trucs en rapport avec l'affiche des géométries alors peut-être que ça l'aura résolu :s.
