### ISSUE TITLE
[Backoffice] Problème affichage tracé depuis le formulaire

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#922]
**Comportement observé**
- je suis dans le formulaire d'une reg, j'affiche sa zone en cliquant sur l'œil
- je quitte le formulaire
- la zone reste affichée sur la carte, et je ne peux plus la masquer en cliquant sur l'œil dans la liste. 
- je dois recharger la page pour faire disparaître la zone

**Comportement attendu**
- lorsque je reviens dans la liste, celle-ci se recadre sur la reg que je viens d'éditer et la zone est affichée sur la carto
- quand je clique sur l'œil de la liste, la zone disparaît de la carto

**Comment by AudreyBramy** [comment]
Du coup, ça peut avoir un lien avec #919 ?

**Comment by AdelineCelier** [comment]
A TESTER EN PROD

**Comment by AdelineCelier** [comment]
c'est good en prod !
