### ISSUE TITLE
[Recherche reg] Revoir le comportement de la recherche reg

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#934]
Il y a plusieurs points qui sont gênants aujourd'hui : 

- [x] si les zones recherchées sont déjà présentes dans notre espace "mes zones", il faut qu'elle soient déjà cochées, mais aussi que la checkbox soit grisée (contour + tick en Light Grey), afin de ne pas pouvoir les décocher. Rajouter un petite infobulle au survol de la checkbox disant "zones déjà ajoutées à mes zones réglementaires". Le résumé reg s'affiche toujours au clic sur le bouton en revanche. 

![image](https://user-images.githubusercontent.com/71878648/155180655-69812eac-7d05-4fb4-9a8c-8cd14246a605.png)

- [ ] lorsque l'on fait une recherche, puis qu'on ajoute des zones à son espace "mes zones", on ne retrouve pas le résultat de sa recherche quand on y revient (alors qu'en plus les mots et/ou la zone de recherche n'ont pas été effacés)
=> comportement attendu : retrouver le résultat de sa recherche, avec les zones déjà ajoutées cochées (cf ci.dessus)

- [x] il faut pouvoir du coup effacer sa recherche en un clic. Par exemple remplacer la loupe de la barre principale par une croix quand un champ de la recherche est rempli.

- [ ] point qui peut se débattre : quand on sélectionne une zone sur la carte, on aurait plus tendance à avoir un mouvement comme pour les captures d'écran, ou toute autre forme de sélection (clic et maintien du clic pour tirer la zone). Aujourd'hui il faut cliquer puis lâcher, tirer la zone et re-cliquer. Perso j'aurais tendance à faire la 1ère manip (et Diane aussi), mais à vérifier auprès de qques autres personnes. A moins que @louptheron tu me dises que c'est lié à une contrainte technique ? Ce point-là est moins crucial

**Comment by louptheron** [comment]
- 4ème point : Si on fait ça, on ne peut plus se déplacer sur la carte quand on trace la zone

**Comment by AdelineCelier** [comment]
Ah effectivement, bien vu. Restons comme ça alors. 
Juste en testant la fonctionnalité, j'ai voulu "sortir" du mode sélection en faisant échap, mais cela ne fonctionne pas. Si c'est rapide à implémenter, c'est un petit plus je trouve. Sinon ça t'oblige à tracer une zone au hasard, puis à cliquer sur "effacer la zone définie".

**Comment by AdelineCelier** [comment]
**Pour le point 1**
- Il faudrait si possible mettre le "tick" de la case à cocher en Light Grey aussi
- Au survol sur la case à cocher déjà sélectionnée, peux-tu mettre une infobulle disant "zones déjà ajoutées à mes zones réglementaires" plutôt que de changer le curseur de la souris en stop rouge ?

**Pour le point 2**
Coder le bail 😸

**Comment by louptheron** [comment]
>     * Au survol sur la case à cocher déjà sélectionnée, peux-tu mettre une infobulle disant "zones déjà ajoutées à mes zones réglementaires" plutôt que de changer le curseur de la souris en stop rouge ?

C'est affiché quand tu mets ton curseur dessus, mais une infobulle ne remplace pas le curseur

**Comment by AdelineCelier** [comment]
Ah je n'ai pas vu l'infobulle de mon côté, mais peut-être que je ne suis pas restée assez longtemps dessus.

**Comment by AdelineCelier** [comment]
Effectivement je n'étais pas restée assez longtemps dessus...et le point 2 fonctionne bien aussi, je valide !
