### ISSUE TITLE
Avaries VMS : existe-t-il une liste de balises censées émettre ? Peut-on se baser sur une telle liste plutôt que sur les seules interruptions d'émission ?

### ISSUE THREAD

**Issue by VincentAntoine** [MTES-MCT/monitorfish#937]

**Comment by VincentAntoine** [comment]
Cf discussion SIP du 24.01.2022 : idéalement c'est ce qu'il faut faire, il faut regarder la liste des balises en prenant éventuellement en compte certains filtres (navires détruits...) et faire un gros clean pour repartir d'une base propre et utiliser une logique basée sur une liste plutôt que sur les interruptions d'emission.

**Comment by AdelineCelier** [comment]
@VincentAntoine je dirais que la réponse est oui, et que du coup on peut fermer ce ticket ;)

**Comment by VincentAntoine** [comment]
ouitoutafait
