### ISSUE TITLE
Revue de la V1 des alertes

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#942]
## Revue UX

- [ ] J'ai ma fenêtre "vue liste" au-dessus de celle avec la vue carte, et quand je clique sur l'icône carte pour voir le navire sur la carto, ça ne me switche pas automatiquement de fenêtre. Et vice-versa
- [x] Quand je clique sur l'icône carte pour voir le navire en alerte sur la carto, il n'y a pas le bandeau rouge qui s'affiche dans la fiche navire
- [x] Il manque un scroll dans la vue liste, en effet ;)
- [x] Problème d'affichage du facteur de risque : au lieu de l'icône, il y a un "NaN" en lettres blanches (un message caché ? ;) : 
![image](https://user-images.githubusercontent.com/71878648/150956310-8115de02-2455-49a6-a078-036b38e623d5.png)

## Revue UI

- [x] Problème d'affichage du cadre de la recherche par navire dans la vue liste : 
![image](https://user-images.githubusercontent.com/71878648/150957139-49fd9953-23e4-4932-a80b-8e2c326cffbe.png)
- [x] Réduire la taille de base des cercles rouges autour des bateaux. Je l'avais dessiné pour que les deux tiennent dans le cercle en pointillés qui montre qu'un navire est sélectionné. Tu peux tester pour voir si ça marcherait comme ça et me faire une capture d'écran ? cf. maquette : 
![image](https://user-images.githubusercontent.com/71878648/150959023-9386c67d-c113-4c10-83bd-65243ba61b2e.png)
- [x] Question de designer reloue, mais c'est normal que le bord des cercles rouges (et du navire) apparaissent légèrement pixellisés ? L'ensemble cercles rouges + navire semble manquer un peu de définition...mais c'est peut-être des questions de performance ? 
- [x] Dans la vue liste, c'est pareil j'ai l'impression que le bord des lignes du tableau est comme doublé sur les bords longs – enfin en tous cas le contour de la carte n'est pas uniforme : 
![image](https://user-images.githubusercontent.com/71878648/150960671-0eb67f08-4044-4a22-8d41-4de36816c7e4.png)

**Comment by louptheron** [comment]
> ## Revue UX
> 
>     * [ ]  J'ai ma fenêtre "vue liste" au-dessus de celle avec la vue carte, et quand je clique sur l'icône carte pour voir le navire sur la carto, ça ne me switche pas automatiquement de fenêtre. Et vice-versa
Ce n'est pas possible de switcher de fenêtre malheureusement. Ni d'envoyer la nouvelle fenêtre sur un autre écran.

>     * [ ]  Quand je clique sur l'icône carte pour voir le navire en alerte sur la carto, il n'y a pas le bandeau rouge qui s'affiche dans la fiche navire
OK
>     * [ ]  Il manque un scroll dans la vue liste, en effet ;)
OK
>     * [ ]  Problème d'affichage du facteur de risque : au lieu de l'icône, il y a un "NaN" en lettres blanches (un message caché ? ;) :
>       ![image](https://user-images.githubusercontent.com/71878648/150956310-8115de02-2455-49a6-a078-036b38e623d5.png)
> 
> 
> ## Revue UI
> 
>     * [ ]  Problème d'affichage du cadre de la recherche par navire dans la vue liste :
OK
>     * [ ]  Réduire la taille de base des cercles rouges autour des bateaux. Je l'avais dessiné pour que les deux tiennent dans le cercle en pointillés qui montre qu'un navire est sélectionné. Tu peux tester pour voir si ça marcherait comme ça et me faire une capture d'écran ?
OK
>     * [ ]  Question de designer reloue, mais c'est normal que le bord des cercles rouges (et du navire) apparaissent légèrement pixellisés ? L'ensemble cercles rouges + navire semble manquer un peu de définition...mais c'est peut-être des questions de performance ?
Même pas, je trace directement un cercle dans le SIG, c'est ma lib de sig qui pixellise le cercle. J'ai essayé avec le png, c'est mieux ?
>     * [ ]  Dans la vue liste, c'est pareil j'ai l'impression que le bord des lignes du tableau est comme doublé sur les bords longs – enfin en tous cas le contour de la carte n'est pas uniforme :
OK

**Comment by AdelineCelier** [comment]
Petite remarque en plus sur les pastilles avec le nombre d'alertes dans le menu (même chose que dans ticket de revue avaries) : 
- il faut qu'elles aient un arrondi de 2 px constant 
- leur taille minimum est de 18x18 px, puis elles s'allongent vers l'intérieur du menu selon le nombre de chiffres
![image](https://user-images.githubusercontent.com/71878648/151391675-d2649226-b400-4133-825e-98487deed0b7.png)

**Comment by AdelineCelier** [comment]
Bon j'ai l'impression que le point que tu n'arrivais pas à reproduire ci-dessus est aujourd'hui résolu. Le reste est ok aussi. Je ferme donc le ticket.
