### ISSUE TITLE
Le décochage des zones ne fonctionne pas dans le recherche REG

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#979]
Lorsque j'affiche toutes les zones d'une thématique sur MF, il ne m'est pas possible de décocher une zone particulière. Je dois cliquer sur l'œil de la thématique pour recocher les zones que je veux voir.

**Comment by AdelineCelier** [comment]
Ce problème me semble résolu. N'était-ce pas le même ticket que le #980 ? En tous cas je n'ai pas rencontré de problème à l'affichage des zones, par thématique ou individuellement.
