### ISSUE TITLE
On ne peut pas masquer une zone reg si sa thématique est activée

### ISSUE THREAD

**Issue by VincentAntoine** [MTES-MCT/monitorfish#980]

**Comment by VincentAntoine** [comment]
Pour reproduire :
- ajouter une thématique à "mes zones"
- dans "mes zones", cliquer sur l'icône pour visualiser toute la thématique
- essayer de masquer une des zones de la thématique en cliquant sur l'icône correspondant : elle se masque brièvement et réapparait tout de suite

**Comment by AdelineCelier** [comment]
Ce problème me semble résolu.
