### ISSUE TITLE
Le refresh des avaries efface le champ input du commentaire en cours d'écriture sur la fiche de l'avarie

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#981]
Il faudrait ne pas refresh le composant du détail des avaries et demander à rafraichir manuellement les données, lorsqu'elles changent, selon le même principe que sur l'onglet du JPE.

**Comment by louptheron** [comment]
En fait il n'y a pas de bouton "nouveaux messages", mais ça ajoute les messages automatiquement

**Comment by AdelineCelier** [comment]
Ok très bien. Du coup je valide le ticket.
