### ISSUE TITLE
[Avarie VMS] Retirer les navires de Polynésie française du suivi des avaries.

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#987]
Ces navires ont des balises spécifiques, qui interrompent très souvent leurs émissions. Ce n'est pas le rôle du CNSP de les surveiller, donc leurs avaries n'ont pas à remonter dans le kanban.

**Comment by AdelineCelier** [comment]
Je vois encore des navires polynésiens dans le kanban. Ex : le Teiri Iri, dernière émission il y a 15h, en mer.
Est-ce que c'est parce que tu as désactivé le suivi des polynésiens il y a moins de 15h @VincentAntoine ? (on est le 21/02/2022, et il est 17h36). 

![image](https://user-images.githubusercontent.com/71878648/154995544-c853e0af-e5c0-4bde-95a4-040e75af93e8.png)

**Comment by VincentAntoine** [comment]
Hello Adeline, oui c'est ça, ce sont des tickets qui datent d'avant le dernier déploiement. Il faudra les fermer manuellement, mais il n'y en a pas de nouveaux qui se créeront (en intégration du moins, car on n'a pas encore déployé en prod).
