### ISSUE TITLE
[Avarie VMS] Rajouter un bouton pour réduire le sous-menu des avaries VMS vers la gauche

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#988]
Afin d'afficher une plus grande partie du kanban

**Comment by AdelineCelier** [comment]
J'ai copié un système vu dans Monday que je trouve pas mal.
Le menu a deux états, un déplié et un replié.
- état déplié : bouton avec la flèche vers la gauche, le menu est complètement visible et fixe. 
- était replié : bouton avec la flèche vers la droite, il ne laisse plus apparaître qu'une bande grise de 30 px. Au survol sur cette bande, il se déplie **par-dessus** le kanban (avec une petite ombre pour bien le faire ressortir) le temps que l'utilisateur le consulte/navigue avec. Hors survol, il se replie. 
Cf. ci-dessous les captures d'écran. @louptheron qu'en penses-tu ?

**Menu déplié**
![image](https://user-images.githubusercontent.com/71878648/153051129-0fa92ec4-baed-44fc-b909-21ebebe0e409.png)

**Menu replié**
![image](https://user-images.githubusercontent.com/71878648/153051215-dc559757-6e23-4310-93d0-330b14e356a8.png)

**Menu replié au survol**
![image](https://user-images.githubusercontent.com/71878648/153051272-bfb71734-f418-4e00-971c-1ffc9f186777.png)

**Comment by AdelineCelier** [comment]
Le principe est bon, il y a juste des problèmes d'animation : 
- quand on clique sur la flèche pour passer de l'état replié à l'état déplié, le kanban "saute" vers la gauche pour se recaler ensuite le long du menu
- au survol pendant l'état replié, l'animation n'est pas tout à fait coordonnée : le texte "vue d'ensemble" s'estompe et disparaît au lieu de suivre le tiroir et de se ranger avec lui, et le texte "Avaries VMS en cours" se réduit bizarrement au lieu de disparaître lui aussi vers la gauche avec le reste. 

Je sais pas si mes commentaires sont très clairs, on pourra regarder ensemble !

**Comment by louptheron** [comment]
@AdelineCelier C'est déployé en INT!

**Comment by AdelineCelier** [comment]
C'est quasi tout ok ! Juste deux petits points : 

- il y a un petit souci maintenant sur la taille du menu "avaries VMS" + le centrage de la pastille dans le menu + le centrage du chiffre du nb d'avaries dans la pastille : 
![image](https://user-images.githubusercontent.com/71878648/160590318-eb0a80e8-d104-4938-a8e8-dff3acfacfa3.png)

- j'ai l'impression que le sous-menu mange quelques pixels du menu principal quand il est en mode replié

**Comment by louptheron** [comment]
@AdelineCelier C'est déployé en INT!

**Comment by AdelineCelier** [comment]
La question des pixels "mangés" est réglée
En revanche je vois toujours un petit décentrage vertical du chiffre dans sa pastille : 
![image](https://user-images.githubusercontent.com/71878648/161563418-97590763-ed6b-46ae-b1dc-00a2a70a4c56.png)

**Comment by AdelineCelier** [comment]
@louptheron flûte de mon côté c'est toujours décentré... si c'est galère à régler tant pis, c'est clairement du détail. 
![image](https://user-images.githubusercontent.com/71878648/165122419-d51896e1-f9f8-459b-871c-406eb3e19772.png)

**Comment by louptheron** [comment]
Je peux encore baisser d'1px mais c'est en aveugle car je ne vois pas le résultat sur ton écran... Chez moi c'est nickel :/

**Comment by AdelineCelier** [comment]
Rah relou !! je ne comprends pas ces écarts de disposition...non bah écoute ça sert à rien, surtout que si tu avais déjà baissé avant ça veut dire que ça n'a déjà rien changé de mon côté.
