### ISSUE TITLE
[Avaries VMS] Ajouter dans les fiche navire la date exate de dernière émission + la date exacte de création du ticket

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#997]
Et vérifier le degré de précision des horaires de dernière émission indiqués sur les tickets : est-ce que "il y a 1h" suffit, ou plutôt "il y a 1h12" ?

**Comment by AdelineCelier** [comment]
@louptheron dans la fiche d'avarie, j'ai changé le titre "avarie en cours" pour "avarie #1234, ouverte il y a xxx".

En ce qui concerne les dates exactes de fin d'émission, je ne sais pas si c'est la peine de les afficher tout le temps, mais ça serait pas mal qu'au survol du texte "dernière émission il y a..." on donne la date exacte en infobulle. Autant sur le ticket que dans la fiche navire. J'ai du mal à évaluer si le service SIP aura besoin de ces dates exactes de façon plus systématique, auquel cas on pourra les mettre en avant de façon plus claire. 
Qu'en penses-tu ?

**Comment by AdelineCelier** [comment]
C'est good pour moi, il faut juste adapter les formules aux différentes situations : 
- lorsque le navire n'a jamais émis, et que l'on connaît la date d'activation de sa balise : "Balise activée le [date]" à la place de "Dernière émission il y a..."
- lorsque le navire n'a jamais émis, et que l'on ne connaît pas la date d'activation de sa balise : on ne met rien à la place de "Dernière émission il y a...". Il y aura toujours l'info au-dessus du moment d'ouverture de l'avarie, ou du moment de sa dernière modification.

**Comment by louptheron** [comment]
@AdelineCelier C'est déployé en INT!

**Comment by AdelineCelier** [comment]
@louptheron j'ai l'impression que pour la mention "balise activée le...", c'est toujours la date d'ouverture du ticket qui est notée. Est-ce que c'est parce que ça ne sert à rien de faire un développement pour quelque chose qui va s'arranger avec le temps ? 
Si oui, ça me va, c'était juste pour être sure :)
